<!-- app/design/frontend/schrack/schrackresponsive/template/checkout/total/subtotal.phtml (start) -->
<?php
    $_currency = Mage::getStoreConfig('currency/options/default');
?>

<style>
    .checkout_review_subtotal_left_container {
        width: 73% !important;
        float: left !important;
        height: 55px !important;
        padding-left: 16px !important;
        padding-top: 5px !important;
    }

    .checkout_review_subtotal_right_container {
        width: 27% !important;
        float: left !important;
        height: 55px !important;
        padding-left: 5px !important;
        padding-right: 5px !important;
        padding-top: 18px !important;
    }

    .checkout_review_subtotal_text {
        font-size: 1.3em !important;
        font-weight: bold !important;
    }

    .checkout_review_subtotal_price_currency {
        font-size: 0.8em !important;
        font-weight: bold !important;
        display: block !important;
        float: left !important;
        margin-top: 14px !important;
        width: 33% !important;
    }

    .checkout_review_subtotal_price {
        font-size: 0.9em !important;
        font-weight: bold !important;
        display: block !important;
        float: left !important;
        text-align: right !important;
        width: 67% !important;
        margin-top: 13px !important;
    }

    .onlinebonus {
        padding-left: 16px !important;
        padding-right: 16px !important;
        font-weight: bold !important;
        letter-spacing: 0.03em;
        color: #ffffdd;
        font-size: 1em;
    }

    .checkout_review_subtotal_review_subtotal_left_container_detail {
        font-size: 0.9em !important;
    }

    @media (min-width: 366px) and (max-width: 499px) {
        .checkout_review_subtotal_left_container {
            width: 73% !important;
        }
        .checkout_review_subtotal_right_container {
            width: 27% !important;
            padding-top: 18px !important;
        }
        .checkout_review_subtotal_text {
            font-size: 0.9em !important;
        }
        .annotation {
            font-size: 0.9em !important;
        }
        .checkout_review_subtotal_price_currency {
            font-size: 0.6em !important;
            margin-top: 6px !important;
            text-align: left !important;
            width: 33% !important;
        }
        .checkout_review_subtotal_price {
            font-size: 1.0em !important;
            text-align: left !important;
            width: 67% !important;
            margin-top: 0 !important;
        }
    }

    @media (min-width: 500px) and (max-width: 700px) {
        .checkout_review_subtotal_left_container {
            width: 76% !important;
        }
        .checkout_review_subtotal_right_container {
            width: 24% !important;
            padding-top: 26px !important;
        }
        .checkout_review_subtotal_price_currency {
            font-size: 0.9em !important;
            margin-top: 6px !important;
            width: 33% !important;
            text-align: left !important;
        }
        .checkout_review_subtotal_price {
            font-size: 1em !important;
            width: 67% !important;
            text-align: left !important;
            margin-top: 4px !important;
        }
    }

    @media (min-width: 701px) and (max-width: 991px) {
        .checkout_review_subtotal_left_container {
            width: 82% !important;
        }
        .checkout_review_subtotal_right_container {
            width: 18% !important;
            padding-top: 25px !important;
        }
        .checkout_review_subtotal_price_currency {
            font-size: 0.8em !important;
            margin-top: 9px !important;
            text-align: left !important;
            width: 33% !important;
        }
        .checkout_review_subtotal_price {
            font-size: 1.2em !important;
            text-align: left !important;
            width: 67% !important;
            margin-top: 3px !important;
        }
    }

    @media (min-width: 992px) and (max-width: 1240px) {
        .checkout_review_subtotal_left_container {
            width: 86% !important;
        }
        .checkout_review_subtotal_right_container {
            width: 14% !important;
            padding-top: 22px !important;
        }
        .checkout_review_subtotal_price_currency {
            font-size: 0.9em !important;
            margin-top: 10px !important;
            text-align: left !important;
            width: 33% !important;
        }
        .checkout_review_subtotal_price {
            font-size: 1.3em !important;
            text-align: left !important;
            width: 67% !important;
            margin-top: 3px !important;
        }
    }

    @media (min-width: 1241px) and (max-width: 3000px) {
        .checkout_review_subtotal_left_container {
            width: 86% !important;
        }
        .checkout_review_subtotal_right_container {
            width: 14% !important;
            margin-top: 9px !important;
        }
        .checkout_review_subtotal_price_currency {
            font-size: 0.9em !important;
            margin-top: 7px !important;
            text-align: left !important;
            width: 33% !important;
        }
        .checkout_review_subtotal_price {
            font-size: 1.3em !important;
            text-align: left !important;
            width: 67% !important;
            margin-top: 0 !important;
        }
    }
</style>

<div class="checkout_review_subtotal_left_container">
    <div class="large-fine-20 columns-fine">
        <div class="checkout_review_subtotal_text">
            <?php echo $this->getTotal()->getTitle() ?>
        </div>
        <div class="annotation checkout_review_subtotal_review_subtotal_left_container_detail"><?php echo $this->__('incl. surcharge excl. fees and VAT'); ?></div>
    </div>
</div>
<div class="checkout_review_subtotal_right_container">
    <div>
        <span class="checkout_review_subtotal_price_currency"><?php echo $_currency; ?></span>
        <span class="checkout_review_subtotal_price"><?php echo ' ' . $this->helper('checkout')->formatPrice($this->getTotal()->getValue()); ?></span>
    </div>
</div>
<div style="clear: both;"></div>

<?php if (Mage::getSingleton('customer/session')->isLoggedIn()) : ?>
    <?php $bonusUrl = Mage::getStoreConfig('schrack/general/onlinebonus_url'); $bonusMinValue = Mage::getStoreConfig('schrack/general/onlinebonus_minvalue');
        $diffValue = $bonusMinValue - $this->getTotal()->getValue();
        $onlinebonusActive = true;
        $onlineBonusStart  = strtotime(Mage::getStoreConfig('schrack/general/onlinebonus_datestart'));
        $onlineBonusStop   = strtotime(Mage::getStoreConfig('schrack/general/onlinebonus_datestop'));
        $nowDateTime       = strtotime(date('Y-m-d H:i:s'));
        if ($onlineBonusStart) {
            if ($onlineBonusStart <= $nowDateTime && $nowDateTime <= $onlineBonusStop) {
                $onlinebonusActive = true;
            } else {
                $onlinebonusActive = false;
            }
        }
        if ( $onlinebonusActive && isset($bonusUrl) && isset($bonusMinValue) && intval($bonusMinValue) > 0 && $diffValue > 0 ):?>
            <div class="onlinebonus">
                <div class="large-3 columns link">
                    <a href="<?php echo $bonusUrl?>"><?php echo $this->__('Online Bonus')?></a>
                </div>
                <div class="large-9 columns text">
                    <?php echo $this->__('You are still missing %s to reach your online bonus.', (Mage::getStoreConfig('currency/options/default') . ' ' . $this->helper('checkout')->formatPrice($diffValue)))?>
                </div>
            </div>
    <?php endif;?>
<?php endif;?>
<!-- app/design/frontend/schrack/schrackresponsive/template/checkout/total/subtotal.phtml (end) -->