<?php
/* @var $_stateHelper Schracklive_SchrackCatalog_Helper_Product */
$_stateHelper = Mage::helper('schrackcatalog/product');
$_textsDelivery = array();
$_imagesDelivery = array();
$_codesDelivery = Mage::getStoreConfig('schrack/availability_legend/delivery');
if ($_codesDelivery) {
	foreach(explode(',', $_codesDelivery) as $code) {
		if (strlen(trim($_stateHelper->getDeliveryStateTextFromCode($code)))) {
			$_textsDelivery[] = $_stateHelper->getDeliveryStateTextFromCode($code);
			$_imagesDelivery[] = $_stateHelper->getDeliveryStateImageFromCode($code);
		}
	}
}
$_textsPickup = array();
$_imagesPickup = array();
$_codesPickup = Mage::getStoreConfig('schrack/availability_legend/pickup');
if ($_codesPickup) {
	foreach(explode(',', $_codesPickup) as $code) {
		if (strlen(trim($_stateHelper->getPickupStateTextFromCode($code)))) {
			$_textsPickup[] = $_stateHelper->getPickupStateTextFromCode($code);
			$_imagesPickup[] = $_stateHelper->getPickupStateImageFromCode($code);
		}
	}
}
?>
<?php if (count($_textsDelivery)||count($_textsPickup)): ?>
<div class="block block-schrack-availability">
	<h2><span><?php echo __('Your availability'); ?></span></h2>
	<div class="block-content">
		<ul>
<?php foreach ($_textsDelivery as $key => $text): ?>
			<li><img src="<?php echo $this->getSkinUrl('images/'.$_imagesDelivery[$key]); ?>" width="36" height="20" /><span><?php echo $this->__($text); ?></span></li>
<?php endforeach; ?>
<?php foreach ($_textsPickup as $key => $text): ?>
			<li><img src="<?php echo $this->getSkinUrl('images/'.$_imagesPickup[$key]); ?>" width="36" height="20" /><span><?php echo $this->__($text); ?></span></li>
<?php endforeach; ?>
		</ul>
	</div>
</div>
<?php endif; ?>