<!-- app\design\frontend\schrack\schrackresponsive\template\customer\accountadministration\new.phtml (start) -->
<?php
    echo $this->getMessagesBlock()->getGroupedHtml();
    $customer = Mage::getModel("customer/customer");
    $customer->setData(Mage::getSingleton('customer/session')->getCustomerFormData());

    $_session = Mage::getSingleton('customer/session');
    $sessionCustomer  = $_session->getCustomer();
?>

<style>
    .initialHideToTopSymbol {
        display: none !important;
    }

    @media (min-width: 1px) and (max-width: 992px) {
        .my_account_settings_newuseraccount_content_wrapper {
            margin-right: 16px !important;
        }
    }

    @media (min-width: 60px) and (max-width: 320px) {
        #save_user_data_button {
            height: 30px !important;
        }
    }

    @media (min-width: 321px) and (max-width: 480px) {
        #save_user_data_button {
            height: 30px !important;
        }
    }

    @media (min-width: 481px) and (max-width: 767px) {
        #save_user_data_button {
            height: 30px !important;
        }
    }
</style>

<?php if ($sessionCustomer->isAllowed('accessRight','edit')) :?>
<div id="my_account_settings_newuseraccount_wrapper" class="my_account_settings_newuseraccount_content_wrapper">
    <form action="<?php echo $this->getUrl('customer/accountadministration/savenew') ?>" method="post" id="form-validate" onsubmit="return isValidForm()">
        <div class="row data">
            <div class="col-xs-12 info-box">
                <h1><?php echo $this->__('Add Account'); ?></h1>
                <p class="required"><?php echo $this->__('* Required Fields') ?></p>
                <div class="row content loginCont">
                    <div class="col-xs-12">
                        <div class="fieldset">
                            <?php echo $this->getBlockHtml('formkey') ?>
                            <div class="formContianer">
                                <ul class="form-list">
                                    <li>
                                        <div class="row">
                                            <?php $_gender = $this->getLayout()->createBlock('customer/widget_gender') ?>
                                            <?php if ($_gender->isEnabled()): ?>
                                            <div class="col-xs-3 col-sm-2"><?php echo $_gender->setGender($customer->getGender())->toHtml() ?></div>
                                            <?php endif ?>
                                                    <?php //echo $this->getLayout()->createBlock('schrackcustomer/widget_addressname')->setObject($customer)->toHtml() ?>
                                        </div>
                                    </li>
                                    <li>
                                        <div class="row">
                                            <?php echo $this->getLayout()->createBlock('schrackcustomer/widget_addressname')->setObject($customer)->toHtml() ?>
                                        </div>
                                    </li>
                                    <li>
                                        <h3><?php echo $this->__('Salutation') ?></h3>
                                        <div class="input-box">
                                                <input type="text" name="schrack_salutatory" value="<?php echo $customer->getSchrackSalutatory() ?>" placeholder="<?php echo $this->__('Salutation') ?>" title="<?php echo $this->__('Salutation') ?>" id="schrack_salutatory" class="form-control input-text" />
                                        </div>
                                    </li>
                                    <?php echo $this->getLayout()->createBlock('schrackcustomer/widget_phonenumber')->setObject($customer)->toHtml() ?>
                                    <li>
                                        <h3><?php echo $this->__('Email') ?> <span class="red">*</span></h3>
                                        <div class="input-box">
                                                <input type="text" name="email" value="<?php echo $customer->getEmail() ?>" title="<?php echo $this->__('Email') ?>" id="email" placeholder="<?php echo $this->__('Email') ?>*" class="form-control input-text" maxlength="255" />
                                        </div>
                                    </li>
                                    <li>
                                        <h3><?php echo $this->__('Permissions') ?></h3>
                                        <div class="input-box">
                                                <?php echo Mage::helper('schrack/acl')->getAclRoleSelectorBoxForCustomerId($customer->getId()) ?>
                                        </div>
                                        <h3>
                                                <?php if (Mage::getStoreConfig('schrack/typo3/aclrolesurl')): ?>
                                                        <a href="<?php echo Mage::getStoreConfig('schrack/typo3/aclrolesurl') ?>" target="_new"><?php echo $this->__('Explanation of different permissions:') ?></a>
                                                <?php else: ?>
                                                        <?php echo $this->__('Explanation of different permissions:') ?>
                                                <?php endif; ?>
                                        </h3>
                                                <p><?php echo $this->__('admin – is allowed to add new users, change data and set the user\'s rights. More than one (but minimum one) admin per customer is possible. This user is allowed to see purchase prices and send orders.') ?></p>
                                                <p><?php echo $this->__('customer – sees purchase prices, can send orders.') ?></p>
                                                <p><?php echo $this->__('staff – sees purchase prices, can not send orders.') ?></p>
                                                <p><?php echo $this->__('projectant – sees no prices, can not send orders.') ?></p>

                                    </li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="row content">
                    <div class="col-xs-6">
                        <button id="save_user_data_button" class="bttn-md" type="submit" title="<?php echo $this->__('Save') ?>" ><?php echo $this->__('Save') ?></button>
                    </div>
                    <div class="col-xs-6 text-right">
                        <a href="<?php echo $this->getUrl('*/accountadministration/'); ?>" class=""><?php echo $this->__('Back'); ?></a>
                    </div>
                </div>
            </div>
        </div>
    </form>
</div>
<?php endif; ?>

<script type="text/javascript">
	//<![CDATA[

    jQuery(document).ready(function() {

        Validation.add('password-check','<?php echo $this->__("The new password must have at least 8 characters and must contain at least one digit and one letter."); ?>',function(text) {
            if ( text.length < 8 )
                return false;
            if ( ! text.match(/[a-z]/i) )
                return false;
            if ( ! text.match(/[0-9]/) )
                return false;
            return true;
        });

        Validation.add('password-equal-check','<?php echo $this->__("Please make sure your passwords match."); ?>',function(text) {
            ref = jQuery('#password').val();
            return text == ref;
        });

        <?php if (!$sessionCustomer->isAllowed('accessRight','edit')) :?>
            console.log('Keine Berechtigung');
        <?php endif; ?>

		var s4y_salut_format = new Object();

		s4y_salut_format['de_DE_1'] = "Sehr geehrter Herr %title% %last_name%";
		s4y_salut_format['de_DE_2'] = "Sehr geehrte Frau %title% %last_name%";
        s4y_salut_format['de_AT_1'] = "Sehr geehrter Herr %title% %last_name%";
        s4y_salut_format['de_AT_2'] = "Sehr geehrte Frau %title% %last_name%";
		s4y_salut_format['en_EN_1'] = "Dear Mr. %last_name%";
		s4y_salut_format['en_EN_2'] = "Dear Ms. %last_name%";
		s4y_salut_format['hr_HR_1'] = "Poštovani gospodine %title% %last_name%";
		s4y_salut_format['hr_HR_2'] = "Poštovana gospodo %title% %last_name%";
		s4y_salut_format['fr_FR_1'] = "Monsieur %last_name%";
		s4y_salut_format['fr_FR_2'] = "Madame %last_name%";
		s4y_salut_format['nl_NL_1'] = "Geachte heer %last_name%";
		s4y_salut_format['nl_NL_2'] = "Geachte mevrouw %last_name%";
		s4y_salut_format['ro_RO_1'] = "Stimate domnule %last_name%";
		s4y_salut_format['ro_RO_2'] = "Stimata doamna %last_name%";
		s4y_salut_format['sr_SR_1'] = "Poštovani gospodine %title% %last_name%";
		s4y_salut_format['sr_SR_2'] = "Poštovana gospodo %title% %last_name%";
		s4y_salut_format['sl_SL_1'] = "Spoštovani gospod %title% %last_name%";
		s4y_salut_format['sl_SL_2'] = "Spoštovana gospa %title% %last_name%";
		s4y_salut_format['cs_CS_1'] = "Vážený Pane %title% %last_name%";
		s4y_salut_format['cs_CS_2'] = "Milá Paní %title% %last_name%";
		s4y_salut_format['hu_HU_1'] = "Tisztelt %title% %last_name% Úr!";
		s4y_salut_format['hu_HU_2'] = "Tisztelt %title% %last_name% Asszony!";
		s4y_salut_format['sk_SK_1'] = "Vážený pán %title% %last_name%";
		s4y_salut_format['sk_SK_2'] = "Vážená pani %title% %last_name%";
		s4y_salut_format['bg_BG_1'] = "Уважаеми господин %last_name%";
		s4y_salut_format['bg_BG_2'] = "Уважаема госпожо %last_name%";
 		s4y_salut_format['pl_PL_1'] = "Szanowny Panie %last_name%";
		s4y_salut_format['pl_PL_2'] = "Szanowna Pani %last_name%";       

		function s4y_gen_salutatory() {
			var language = "<?php echo Mage::app()->getLocale()->getLocaleCode();?>";

			// if (language == "pl_PL")
			// return true;

			var s4y_gender = jQuery("#gender").val();
			var s4y_salutatory;

            if (s4y_gender == "1") {
                s4y_salutatory = s4y_salut_format[language+"_1"];
            } else {
                s4y_salutatory = '';
            }

            if (s4y_gender == "2") {
                s4y_salutatory = s4y_salut_format[language+"_2"];
            }


            s4y_salutatory = s4y_salutatory.replace(/undefined/g, "");
			s4y_salutatory = s4y_salutatory.replace("%title%", jQuery("#prefix").val());
			s4y_salutatory = s4y_salutatory.replace("%first_name%", jQuery("#firstname").val());
			s4y_salutatory = s4y_salutatory.replace("%last_name%", jQuery("#lastname").val());
			s4y_salutatory = s4y_salutatory.replace("  ", " ");

			jQuery("#schrack_salutatory").val(s4y_salutatory);
			return true;
		}

		jQuery("#gender, #lastname, #firstname, #prefix").change(function() {
			s4y_gen_salutatory();
		});

        /* Back to Top */
        jQuery('body').append('<div id="toTop" class="btn btn-info print-hide-imp initialHideToTopSymbol"><span class="glyphicon glyphicon-chevron-up"></span> <?php echo $this->__('Back to Top'); ?></div>');
        jQuery(window).scroll(function () {
            if (jQuery(this).scrollTop() != 0) {
                jQuery('#toTop').fadeIn();
            } else {
                jQuery('#toTop').fadeOut();
            }
        });
        jQuery('#toTop').click(function(){
            jQuery("html, body").animate({ scrollTop: 0 }, 600);
            console.log('ScrollTop #81');
            return false;
        });
        jQuery('#toTop').removeClass('initialHideToTopSymbol');
        /* Back to Top */

        jQuery('#save_user_data_button').on('click', function() {
            checkMinimumPhoneExistent('<?php echo $this->__('Please enter a valid number in this field'); ?>');
            if (dataLayer) {
                dataLayer.push({
                    'event' : 'userSettingChange',
                    'eventLabel' : 'User Account New'
                });
            }
        });

        if (jQuery(window).width() < 993) {
            jQuery('#breadcrumb_block').removeClass('breadcrumb_custom');
            jQuery('#breadcrumb_block').addClass('breadcrumb_my_account');
        }

    });

	var dataFormNewCustomer = new VarienForm('form-validate', true);

	// Set tabindex to all element of forms
	jQuery('#firstname').focus();
	jQuery('#form-validate :input,select,button,a').each(function (ifv) { if (this.type != "hidden") { jQuery(this).attr('tabindex', ifv + 1); } });

	var emailChecked = false;

    function isValidForm () {
        if ( !emailChecked ) {
            var email = jQuery('#email').val();
            jQuery('#email-error').remove();
            vaildateEmail(email, vaildateEmailResponse);
            return false;
        } else {
            return true;
        }
    }

    function vaildateEmailResponse ( data ) {
        if ( data.validateEmailAddress.result.is_valid ) {
            var phoneNoOk = jQuery('#requiredWarningPhone').text() == '';
            if ( phoneNoOk && dataFormNewCustomer.validator && dataFormNewCustomer.validator.validate() ) {
                emailChecked = true;
                dataFormNewCustomer.submit();
                emailChecked = false;
            }
        } else {
            jQuery('#email').after('<div class="validation-advice" id="email-error">' + data.validateEmailAddress.result.message + '</div>');
        }
    }
	//]]>
</script>
<!-- app\design\frontend\schrack\schrackresponsive\template\customer\accountadministration\new.phtml (end) -->
