<form id="formular" method="post" action="<?php echo Mage::getUrl('customer/account/actAsUserPost'); ?>" >
    <input type="hidden" name="form_key" value="<?php echo Mage::getSingleton('core/session')->getFormKey(); ?>" />
    <div class="row">
        <div class="large-3 columns">
            <?php echo $this->__('Customer')?>:
        </div>
        <div class="large-9 columns">
            <input type="text" name="customer_id" /><input type="submit" class="button-red small" value="<?php echo $this->__('Login')?>"/>
        </div>
    </div>
</form>