<!-- customer\account\dashboard.phtml (start) -->

<?php
    $promotionBookHelper = Mage::helper('schrackcustomer/promotionbook');
    $promotionBookStuff = $promotionBookHelper->getPromotionbookLinksAndImages();

    $customerType = $this->getCustomer()->getSchrackCustomerType(); // ProspectTypes: 'light-prospect' / 'full-prospect'
?>
<style>

    .documentNumber, .documentNumber2, .documentNumber3{
        width: 19.53333% !important;
    }

    .schrackWwsStatus, .rowStatus2, .rowStatus3{
        width: 26.16667% !important;
    }

</style>

<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<?php if ( count($promotionBookStuff) > 0 ) : ?>
    <section class="slider">
        <div id="kab_slider" class="flexslider">
            <ul class="slides">
            <?php foreach ( $promotionBookStuff as $promotionBookPdfAndImage ) : ?>
                <li>
                    <a target="_blank" href="<?php echo $promotionBookPdfAndImage['pdf_link']; ?>">
                        <img border="0" src="<?php echo $promotionBookPdfAndImage['image_link']; ?>">
                    </a>
                </li>
            <?php endforeach; ?>
            </ul>
        </div>
    </section>
<?php else : ?>
    <div style="height: 47px;">
        <ul id="notice-message-container-overview" class="messages" style="display: none;"">
        <li class="notice-msg">
            <ul>
                <li id="notice-message-overview"></li>
            </ul>
        </li>
        </ul>
    </div>
<?php endif; ?>
<div class="dashboard-frame large-12 columns">
    <?php echo $this->getChildHtml('documents_newdocuments')?>
    <div class="headline b1"><?php echo $this->__('My Data 2') ?></div>
	<div class="row my-data">
        <?php //Customer Group ID = 12 (Prospect Light) ID = 11 (Full Register Prospect) ?>
        <?php if ( !in_array($customerType, array('light-prospect')) ) : ?>
            <div class="large-6 columns">
                <div class="info-box">
                    <?php echo $this->getChildHtml('mycompany') ?>
                </div>
            </div>
        <?php endif; ?>
        <div class="large-6 columns">
            <div class="info-box">
                <?php echo $this->getChildHtml('info') ?>
            </div>
        </div>	
    </div>
    <?php if ( !in_array($customerType, array('light-prospect')) ) : ?>
        <div class="row my-data">
            <div class="large-6 columns">
                <div class="info-box">
                    <?php echo $this->getChildHtml('address') ?>
                </div>
            </div>
            <?php if ( !in_array($customerType, array('full-prospect')) ) : ?>
                <div class="large-6 columns">
                    <div class="info-box">
                        <?php echo $this->getChildHtml('persons') ?>
                    </div>
                </div>
            <?php endif; ?>
        </div>
    <?php endif; ?>
</div>


<script type="text/javascript">//<![CDATA[

    jQuery(document).ready(function(){
        jQuery('#kab_slider').flexslider({
            animation: "slide"
        });
    });

    //]]>
</script>

<!-- customer\account\dashboard.phtml (end) -->