<?php echo $this->__('Hello,')?><br/><br/>
<?php echo $this->__('A customer with the following data has just signed up. The VAT identification number could not be checked via the server and has thus been checked only semantically.')?><br/><br/>

<table>
    <tr><th><?php echo $this->__('Email')?>:</th><td><?php echo $params['email']?></td></tr>
    <tr><th><?php echo $this->__('Name 1')?>:</th><td><?php echo $params['name1']?></td></tr>
    <tr><th><?php echo $this->__('Name 2')?>:</th><td><?php echo $params['name2']?></td></tr>
    <tr><th><?php echo $this->__('Name 3')?>:</th><td><?php echo $params['name3']?></td></tr>
    <tr><th><?php echo $this->__('First Name')?>:</th><td><?php echo $params['firstname']?></td></tr>
    <tr><th><?php echo $this->__('Last Name')?>:</th><td><?php echo $params['lastname']?></td></tr>
    <tr><th><?php echo $this->__('Telephone:')?>:</th><td><?php echo $params['schrack_telephone']?></td></tr>
    <tr><th><?php echo $this->__('VAT Identification Number')?>:</th><td><?php echo $params['vat_identification_number']?></td></tr>
</table>
<br/><br/>
<?php echo $this->__('Regards,')?><br/>
<?php echo $this->__('Webshop')?>