<!-- app/design/frontend/schrack/default/template/customer/accountadministration/overview.phtml (start) -->
<?php
/* @var $this Schracklive_SchrackCustomer_Block_Account_Administration */

    $_session = Mage::getSingleton('customer/session');
    $sessionCustomer  = $_session->getCustomer();
?>

<?php if ($sessionCustomer->isAllowed('accessRight','edit')) :?>
<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<div class="row data">
    <div class="large-12 columns info-box">
        <div class="row">
            <div class="large-12 columns">
                <div class="headline b1">&nbsp;<?php echo $this->__('Account Administration') ?></div>
            </div>
        </div>

        <div class="row content" style="border: 1px solid #d6d6d6; height: 52px; padding-bottom: 0px;">
            <div class="large-10 columns" style="margin-top: 20px;">
                <span style="margin-left: 1px; font-size: 1.2em; font-weight: bold; color: #00589D;"><?php echo $this->__('New account') ?></span>
            </div>
            <div class="large-2 columns" style="margin-top: 13px;">
                <button class="button-red small gray add-new-user" title="<?php echo $this->__('Add') ?>" >&plus; <?php echo $this->__('Add') ?></button>
            </div>
        </div>

        <?php $triggerColor = 2; ?>
        <?php foreach ($this->getVisibleContacts() as $_customer) : ?>
            <?php
                if ($triggerColor % 2 == 0) $panelInitialBackgroundColor = 'white'; else  $panelInitialBackgroundColor = '#f5f5f5';
                $_customer->load($_customer->getId()); // We need all attributes
                $triggerColor++;
            ?>

            <div class="row content" style="background-color: <?php echo $panelInitialBackgroundColor; ?>; height: 77px; padding-bottom: 0px;">
                <div class="large-10 columns" style="margin-top: 15px;">
                    <span style="font-weight: bold; font-size: 1.1em;"><?php echo $_customer->getName() ?></span>
                    <span style="margin-left: 5px; font-size: 1em;"><?php echo $_customer->getEmailAddress() ?></span><br/>
                    <?php
                    if ($_customer->isInactiveContact()) {
                        echo '<span style="margin-top: 5px; font-size: 1em; line-height: 26px;">' . $this->__('inactive') . '</span><br/>';
                    }
                    if ($_customer->isContact()) {
                        $aclRoleName = $_customer->getSchrackAclRole();
                        if ($aclRoleName == '') {
                            $aclRoleName = $this->__('No Role set');
                        }
                        echo '<span style="margin-top: 5px; font-size: 1em; line-height: 26px;">' . $this->__($aclRoleName) . '</span><br/>';
                     }
                     ?>

                <?php if (!$_customer->isProspect()) : ?>
                    <?php if ($_customer->isInactiveContact()) : ?>
                    <?php if ($_customer->getEmailAddress()) : ?>
                    <span style="margin-right: 10px; font-weight: bold;"><a href="<?php echo $this->getUrl('customer/accountadministration/activate/id/'.$_customer->getId()) ?>" ><?php echo $this->__('Activate') ?></a></span>
                    <?php endif ?>
                    <?php else : ?>
                    <span style="margin-right: 10px; font-weight: bold;"><a href="<?php echo $this->getUrl('customer/accountadministration/deactivate/id/'.$_customer->getId()) ?>" ><?php echo $this->__('Deactivate') ?></a></span>
                    <?php endif ?>
                <?php endif ?>
                    <span style="font-weight: bold;"><a href="<?php echo $this->getUrl('customer/accountadministration/delete/id/'.$_customer->getId()) ?>" onclick="return confirmDeleteCustomer();"><?php echo $this->__('Delete') ?></a></span>
                </div>
                <div class="large-2 columns" style="margin-top: 26px;">
                    <button class="button-red small gray" onclick="jQuery(location).attr('href', '<?php echo $this->getUrl('customer/accountadministration/edit/id/'.$_customer->getId()) ?>');return false;" title="<?php echo $this->__('Edit') ?>" ><?php echo $this->__('Edit') ?></button>
                </div>
            </div>
        <?php endforeach ?>
    </div>
</div>
<?php endif; ?>

<script type="text/javascript">
//<![CDATA[
function confirmDeleteCustomer() {
	return confirm('<?php echo $this->__('Are you sure you want to delete this account?') ?>');
}

jQuery(document).ready(function() {

    <?php if (!$sessionCustomer->isAllowed('accessRight','edit')) :?>
        console.log('Keine Berechtigung');
    <?php endif; ?>

    jQuery('.add-new-user').on('click', function() {
        jQuery(location).attr('href', '<?php echo $this->getUrl('customer/accountadministration/new') ?>');
        return false;
    });

});

//]]>
</script>
<!-- app/design/frontend/schrack/default/template/customer/accountadministration/overview.phtml (end) -->