<!-- default/template/checkout/onepage/payment.phtml (start) -->

<div class="box-content">
<script type="text/javascript">
//<![CDATA[
    var payment = new Payment('co-payment-form', '<?php echo $this->getUrl('checkout/onepage/savePayment') ?>');
//]]>
</script>
<form action="" id="co-payment-form">
    <?php echo $this->getBlockHtml('formkey') ?>
    <fieldset>
        <?php echo $this->getChildHtml('methods') ?>
    </fieldset>
	<br />
	<b><?php echo $this->__('Purchase Order Number'); ?>:</b>&nbsp;<input type="text" id="payment-schrack-custom-order-number" name="payment[schrack_custom_order_number]" maxlength="20" size="20" />
</form>
<div class="tool-tip" id="payment-tool-tip" style="display:none;">
    <div class="btn-close"><a href="#" id="payment-tool-tip-close" title="<?php echo $this->__('Close') ?>"><?php echo $this->__('Close') ?></a></div>
    <div class="tool-tip-content"><img src="<?php echo $this->getSkinUrl('images/cvv.gif') ?>" alt="<?php echo $this->__('Card Verification Number Visual Reference') ?>" title="<?php echo $this->__('Card Verification Number Visual Reference') ?>" /></div>
</div>
    <div class="checkout-back-link-container">
        <a class="back-link back-to-shipping-method-button" href="#"><small>&laquo; </small><?php echo $this->__('Back') ?></a>
    </div>
</div>
<div class="buttons-set" id="payment-buttons-container">
    <button type="button" class="button-red small savePaymentButton"><span id="payment-please-wait" class="please-wait" style="display:none;float:left;padding-left:20px;text-align:left;background:url('<?php echo $this->getSkinUrl('images/opc-ajax-loader.gif') ?>') left center no-repeat;"><?php echo $this->__('Loading next step...') ?></span><?php echo $this->__('Continue') ?></button>
</div>

<script type="text/javascript">
//<![CDATA[
    function toggleToolTip(event){
        if($('payment-tool-tip')){
            $('payment-tool-tip').setStyle({
                top: (Event.pointerY(event)-560)+'px'//,
                //left: (Event.pointerX(event)+100)+'px'
            })
            $('payment-tool-tip').toggle();
        }
        Event.stop(event);
    }

    if($('payment-tool-tip-close')){
        Event.observe($('payment-tool-tip-close'), 'click', toggleToolTip);
    }
    payment.currentMethod = "<?php echo $this->getChild('methods')->getSelectedMethodCode() ?>";

    jQuery('.savePaymentButton').on('click', function() {
        localStorage.newCheckoutProcessLastUpdateTime = Math.floor(Date.now() / 1000);

        payment.save();
    });

    jQuery('.back-to-shipping-method-button').on('click', function() {
        localStorage.newCheckoutProcessLastUpdateTime = Math.floor(Date.now() / 1000);
        localStorage.newCheckoutProcessCurrentStep = 'opc-shipping_method';
        jQuery('#change-back-to-edit-shipping-method').hide();
        jQuery('#change-back-to-edit-payment-method').hide();
        checkout.back();
        return false;
    });

    jQuery('#content-wrap').on('click', '#change-back-to-edit-shipping-method', function(event) {
        event.preventDefault();
        localStorage.newCheckoutProcessLastUpdateTime = Math.floor(Date.now() / 1000);
        localStorage.newCheckoutProcessCurrentStep = 'opc-shipping_method';
        checkout.accordion.openSection('opc-shipping_method');
        jQuery('#change-back-to-edit-shipping-method').hide();
        jQuery('#change-back-to-edit-payment-method').hide();
    });
//]]>
</script>

<!-- default/template/checkout/onepage/payment.phtml (end) -->