<!-- default/template/checkout/onepage/progress.phtml (end) -->

<?php
// @var $this Mage_Checkout_Block_Onepage_Progress
    $_geoipHelper = Mage::helper('geoip');
    $_mayPerformCheckout = $_geoipHelper->mayPerformCheckout();

    $customer = $this->getCustomer();
    if ($customer) {
        $customerType = $customer->getSchrackCustomerType(); // ProspectTypes: 'light-prospect' / 'full-prospect'
    }

    $prospectFull  = false;
    $prospectLight = false;

    if ($customerType == 'light-prospect') {
        $prospectLight = true;
    }

    if ($customerType == 'full-prospect') {
        $prospectFull = true;
    }

    $customerIsLoggedIn = $this->helper('customer')->isLoggedIn();

?>

<?php if ($_mayPerformCheckout):?>
<div class="block block-progress">
    <div class="block-title">
        <div class="headline c1"><?php echo $this->__('Your Checkout Progress') ?></div>
    </div>
    <div class="block-content">
        <dl>
        <?php if ($this->getCheckout()->getStepData('billing', 'is_show')): ?>
        <?php if($this->getCheckout()->getStepData('billing', 'complete')): ?>
            <dt class="complete">
                <strong><?php echo $this->__('Billing Address') ?>:</strong>
<?php /*
                <?php if (!$this->getCustomer()->hasSchrackWwsCustomerId()): ?>
                    <span class="separator">|</span> <a href="#billing" onclick="checkout.accordion.openSection('opc-billing'); return false;"><?php echo $this->__('Change') ?></a>
                <?php endif; ?>
 *
 */
?>
            </dt>
            <dd class="complete">
                <?php if ($prospectLight == false ) : ?>
                    <address><?php echo $this->getBilling()->format('html') ?></address>
                <?php endif; ?>
                <?php // Only show billing address data, if it is not a confusing dummy address : ?>
                <?php if ($prospectLight == true && $this->getBilling()->getCity() != 'PROSLI') : ?>
                    <address><?php echo $this->getBilling()->format('html') ?></address>
                <?php endif; ?>
            </dd>
        <?php else: ?>
            <dt>
                <?php echo $this->__('Billing Address') ?>
            </dt>
        <?php endif; ?>
        <?php endif; ?>

        <?php if ($this->getCheckout()->getStepData('shipping', 'is_show')): ?>
        <?php if($this->getCheckout()->getStepData('shipping', 'complete')): ?>
            <dt class="complete">
                <strong><?php echo $this->__('Shipping Address') ?>:</strong>
            </dt>
            <dd class="complete">
                <address><?php echo $this->getShipping()->format('html') ?></address>
                <?php if ($this->helper('customer')->isLoggedIn()) : ?>
				    <a href="#payment" id="change-back-to-edit-shipping"><?php echo $this->__('Change') ?></a>
                <?php endif; ?>
            </dd>
        <?php else: ?>
            <dt>
                <?php echo $this->__('Shipping Address') ?>
            </dt>
        <?php endif; ?>
        <?php endif; ?>

        <?php if ($this->getCheckout()->getStepData('shipping_method', 'is_show')): ?>
        <?php if($this->getCheckout()->getStepData('shipping_method', 'complete')): ?>
            <dt class="complete">
                <strong><?php echo $this->__('Shipping Method') ?>:</strong>
            </dt>
            <dd class="complete">
				<p>
                <?php if ($this->getShippingMethod()): ?>
                    <?php echo $this->getShippingDescription() ?>

                    <?php $_excl = $this->getShippingPriceExclTax(); ?>
                    <?php $_incl = $this->getShippingPriceInclTax(); ?>
                    <?php if ($this->helper('tax')->displayShippingPriceIncludingTax()): ?>
                        <?php echo $_incl; ?>
                    <?php else: ?>
                        <?php echo $_excl; ?>
                    <?php endif; ?>
                    <?php if ($this->helper('tax')->displayShippingBothPrices() && $_incl != $_excl): ?>
                        (<?php echo $this->__('Incl. Tax'); ?> <?php echo $_incl; ?>)
                    <?php endif; ?>

                <?php else: ?>
                    <?php echo $this->__('Shipping method has not been selected yet') ?>
                <?php endif; ?>
				</p>
				<a href="#shipping_method" id="change-back-to-edit-shipping-method"><?php echo $this->__('Change') ?></a>
			</dd>

        <?php else: ?>
            <dt>
                <?php echo $this->__('Shipping Method') ?>
            </dt>
        <?php endif; ?>
        <?php endif; ?>

        <?php if ($this->getCheckout()->getStepData('payment', 'is_show')): ?>
        <?php if($this->getCheckout()->getStepData('payment', 'complete')): ?>
            <dt class="complete">
                <strong><?php echo $this->__('Payment Method') ?>:</strong>
            </dt>
            <dd class="complete">
                <?php echo $this->getPaymentHtml() ?>
				<a href="#payment" id="change-back-to-edit-payment-method"><?php echo $this->__('Change') ?></a>
            </dd>
        <?php else: ?>
            <dt>
                <?php echo $this->__('Payment Method') ?>
            </dt>
        <?php endif; ?>
        <?php endif; ?>
        </dl>
    </div>
</div>
<?php endif?>
<button id="data-reset" style="display: none; margin-left: 20px;" class="button-arrow small"><?php echo $this->__('Empty Form') ?></button>
<input id="progressBlocker" type="hidden" value="2" />

<script type="text/javascript">
    //<![CDATA[

    jQuery(document).ready(function() {

        if (localStorage.newCheckoutProcessCurrentStep == 'opc-shipping') {
            jQuery('#change-back-to-edit-shipping').hide();
            jQuery('#change-back-to-edit-shipping-method').hide();
            jQuery('#change-back-to-edit-payment-method').hide();
        }

        if (localStorage.newCheckoutProcessCurrentStep == 'opc-shipping_method') {
            jQuery('#change-back-to-edit-shipping-method').hide();
            jQuery('#change-back-to-edit-payment-method').hide();
        }

        if (localStorage.newCheckoutProcessCurrentStep == 'opc-payment') {
            jQuery('#change-back-to-edit-payment-method').hide();
        }

        jQuery(window).keydown(function(event){
            if(event.keyCode == 13 &&
            localStorage.newCheckoutProcessCurrentStep == 'opc-login' &&
            localStorage.newCheckoutProcessCurrentRole == 'login-user' &&
            jQuery('#loginAsExistingCustomer').prop('checked')) {
                event.preventDefault();
                jQuery('#logmein').click();
            }

            if(event.keyCode == 13 &&
                localStorage.newCheckoutProcessCurrentStep == 'opc-login' &&
                localStorage.newCheckoutProcessCurrentRole == 'prospect-user' &&
                jQuery('#registerForNewCustomer').prop('checked')) {
                event.preventDefault();
                jQuery('#progressBlocker').val(2);
                var counter = setInterval(timer, 1000);
                jQuery('#nextRegisterForNewCustomer').click();
            }
            // guest = non-registering-user
            if(event.keyCode == 13 &&
            localStorage.newCheckoutProcessCurrentStep == 'opc-login' &&
            localStorage.newCheckoutProcessCurrentRole == 'guest' &&
            jQuery('#buyWithoutRegistration').prop('checked')) {
                event.preventDefault();
                jQuery('#nextBuyWithoutRegistration').click();
                jQuery('#progressBlocker').val(2);
                var counter = setInterval(timer, 1000);
            }

            if(event.keyCode == 13 &&
                localStorage.newCheckoutProcessCurrentStep == 'opc-billing' &&
                jQuery('#progressBlocker').val() == 0) {
                event.preventDefault();
                jQuery('.saveBillingButton').click();
            }

            if(event.keyCode == 13 &&
                localStorage.newCheckoutProcessCurrentStep == 'opc-shipping' &&
                jQuery('#progressBlocker').val() == 0) {
                event.preventDefault();
                jQuery('.saveShippingButton').click();
            }

            if(event.keyCode == 13 &&
                localStorage.newCheckoutProcessCurrentStep == 'opc-shipping_method' &&
                jQuery('#progressBlocker').val() == 0) {
                event.preventDefault();
                jQuery('.saveShippingMethodButton').click();
            }

            if(event.keyCode == 13 &&
                localStorage.newCheckoutProcessCurrentStep == 'opc-payment' &&
                jQuery('#progressBlocker').val() == 0) {
                event.preventDefault();
                jQuery('.savePaymentButton').click();
            }
            // guest = non-registering-user
            if (localStorage.newCheckoutProcessCurrentRole == 'prospect-user' || localStorage.newCheckoutProcessCurrentRole == 'guest') {
                jQuery('#alternate-delivery-address-choser').hide();
                jQuery('#change-back-to-edit-shipping').hide();
                jQuery('.checkout-back-link-container').hide();
            } else {
                jQuery('#alternate-delivery-address-choser').show();
                jQuery('#change-back-to-edit-shipping').show();
                jQuery('.checkout-back-link-container').show();
            }
        });

    localStorage.newCheckoutProspectRole = 'none';

<?php if ($customerIsLoggedIn) : ?>
    localStorage.newCheckoutProcessCurrentRole = 'login-user';
    localStorage.newCheckoutRunningProcess     = 'processCheckoutAsLoggedInUser';
    localStorage.customerNotLoggedIn = "0";
    <?php if ($prospectLight || $prospectFull) : ?>
        localStorage.newCheckoutProcessCurrentRole = 'prospect-user';
    <?php endif; ?>
    <?php if ($prospectLight) : ?>
        localStorage.newCheckoutProspectRole = 'prospect-light';
        jQuery('#opc-billing').removeClass('allow');
        jQuery('#opc-billing').removeClass('active');
        jQuery('#new_address_button').click();
        jQuery('#shipping-address-select').hide();
        jQuery("#shipping-address-select option[value='']").remove();
    <?php endif; ?>
    <?php if ($prospectFull) : ?>
        localStorage.newCheckoutProspectRole = 'prospect-full';
        jQuery('#new_address_button').hide();
        jQuery("#shipping-address-select option[value='']").remove();
    <?php endif; ?>
<?php else : ?>
    localStorage.newCheckoutRunningProcess = 'processCheckoutAsNonLoggedInUser';
    // guest = non-registering-user
    //localStorage.newCheckoutProcessCurrentRole = 'guest';
    localStorage.customerNotLoggedIn = "1";
<?php endif; ?>
    });

    if (localStorage.newCheckoutProspectRole == 'prospect-light' ||
        localStorage.newCheckoutProcessSpecialAction == 'full-register-prospect-application') {
        localStorage.newCheckoutProcessSpecialAction = 'full-register-prospect-application';
    } else {
        localStorage.newCheckoutProcessSpecialAction = 'none';
    }

    if (localStorage.newCheckoutProcessCurrentRole == "guest") {
        jQuery('.back-to-shipping-button').hide();
        jQuery('#data-reset').show();
    }

    jQuery('#data-reset').on('click', function(){
        location.reload();
    });

    // TODO -- make new required fields dependend from store-config (UID/Firembuchnummer)

    //]]>
</script>

<!-- default/template/checkout/onepage/progress.phtml (end) -->