<!-- template/customer/address/book.phtml (start) -->
<?php
/**
 * Template for Mage_Customer_Block_Address_Book block
 * @var $this Mage_Customer_Block_Address_Book
 */

    $sessionCustomer = Mage::getSingleton('customer/session')->getCustomer();
    $customerID = $sessionCustomer->getId();
    $defaultBillingAddressId = Mage::getSingleton('customer/session')->getCustomer()->getDefaultBilling();
    $defaultBillingAddressData = Mage::getModel('customer/address')->load($defaultBillingAddressId);
    $defaultBillingChangeAllowed = false;
    if ($customerID == $defaultBillingAddressData->getParentId()) {
        $defaultBillingChangeAllowed = true;
    }

    $defaultShippingAddressId = Mage::getSingleton('customer/session')->getCustomer()->getDefaultShipping();
    $defaultShippingAddressData = Mage::getModel('customer/address')->load($defaultShippingAddressId);

    $defaultShippingChangeAllowed = false;
    // Mysterious check??:
    if ($customerID == $defaultShippingAddressData->getParentId()) {
        $defaultShippingChangeAllowed = true;
    }
    // Set to true, until someone will complain:
    $defaultShippingChangeAllowed = true;
    $customerType = $sessionCustomer->getSchrackCustomerType(); // ProspectTypes: 'light-prospect' / 'full-prospect'

?>

<?php if ( !in_array($customerType, array('light-prospect', 'full-prospect')) ) : ?>
    <?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
    <div class="row data">
        <div class="large-12 columns">
            <div class="row">
                <div class="page-title large-12 columns">
                    <h1 class="headline a"><?php echo $this->__('Address Book') ?></h1>
                </div>
            </div>
            <div class="row">
                <div class="large-6 columns">
                    <div class="white-form">
                        <h1 class="headline b1"><?php echo $this->__('Default Addresses') ?></h1>
                        <div class="content padded">
                            <ul>
                                <?php if($defaultBillingAddressId): ?>
                                    <li class="item">
                                        <h3 class="headline b2"><?php echo $this->__('Default Billing Address') ?></h3>
                                        <address style="padding-left: 14px;">
                                            <?php echo $this->getAddressHtml($defaultBillingAddressData); ?>
                                        </address>
                                        <p>
                                            <?php //if($this->mayEditDefaultBilling()): ?>
                                            <?php if(false): ?>
                                        <div style="padding-left: 200px;">
                                            <a class="button-red small gray" style="width: 227px; margin-left: -16px; margin-top: 11px; margin-bottom: 31px;" href="<?php echo $this->getAddressEditUrl($defaultBillingAddressData) ?>addressaction/editdefaultbillingaddress"><?php echo $this->__('Change Billing Address') ?></a>
                                        </div>
                                        <?php else: ?>
                                            <div style="width: 391px; padding-left: 13px;">
                                                <div style="border: 1px solid #d6d6d6; padding: 2px 12px;">
                                                    <?php echo $this->__('To change the billing address please contact <a href=%s>Schrack customer service</a>.','"'.Mage::getUrl('account/account/edit/').'"') ?>
                                                </div>
                                            </div>
                                        <?php endif ?>
                                        </p>
                                    </li>
                                <?php else: ?>
                                    <li class="item">
                                        <h3 class="headline b2"><?php echo $this->__('Default Billing Address') ?></h3>
                                        <?php echo $this->__('You have no default billing address in your address book.') ?>
                                    </li>
                                <?php endif ?>

                                <?php if($defaultShippingAddressId): ?>
                                    <li class="item">
                                        <h3 class="headline b2"><?php echo $this->__('Default Shipping Address') ?></h3>
                                        <address style="padding-left: 14px;">
                                            <?php echo $this->getAddressHtml($defaultShippingAddressData); ?>
                                        </address>
                                        <?php if($defaultShippingChangeAllowed): ?>
                                            <div style="padding-left: 200px;">
                                                <a class="button-red small gray" style="width: 227px; margin-left: -16px; margin-top: 11px; margin-bottom: 6px;" href="<?php echo $this->getAddressEditUrl($defaultShippingAddressData) ?>addressaction/editdefaultshippingaddress"><?php echo $this->__('Change Shipping Address') ?></a>
                                            </div>
                                        <?php endif ?>
                                    </li>
                                <?php else: ?>
                                    <li class="item empty">
                                        <h3 class="headline b2"><?php echo $this->__('Default Shipping Address') ?></h3>
                                        <p><?php echo $this->__('You have no default shipping address in your address book.') ?></p>
                                    </li>
                                <?php endif ?>
                            </ul>
                        </div>
                    </div>
                </div>
                <div class="large-6 columns">
                    <div class="white-form">
                        <h1 class="headline b1"><?php echo $this->__('Additional Address Entries') ?></h1>
                        <div class="content padded">
                            <ul>
                                <?php if($_additionalAddresses = $this->getAdditionalAddresses()): ?>
                                    <?php foreach($_additionalAddresses as $_address): ?>
                                        <li class="item">
                                            <address>
                                                <?php echo $this->getAddressHtml($_address) ?>
                                            </address>
                                            <a id="deleteAddressRecord_<?php echo $_address->getId(); ?>" name="deleteAddressRecord" href="" style="color: #00589D; position: absolute; margin-left: 389px; margin-top: -49px; font-size: 22px; outline: none;" title="<?php echo $this->__('Delete Address') ?>"><i class="fa fa-trash-o" aria-hidden="true"></i></a>
                                            <div style="padding-left: 220px;">
                                                <a class="button-red small gray" href="<?php echo $this->getUrl('customer/address/edit', array('id'=>$_address->getId())) ?>"><?php echo $this->__('Edit Address') ?></a>
                                            </div>
                                        </li>
                                    <?php endforeach; ?>
                                <?php else: ?>
                                    <li class="item empty">
                                        <p><?php echo $this->__('You have no additional address entries in your address book.') ?></p>
                                    </li>
                                <?php endif ?>
                            </ul>
                        </div>
                    </div>
                    <div>
                        <button class="button-blue" title="<?php echo $this->__('Add New Address') ?>" onclick="window.location='<?php echo $this->getAddAddressUrl() ?>';"><?php echo $this->__('Add New Address') ?></button>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <p class="large-12 columns back-link"><a href="<?php echo $this->getBackUrl() ?>"><small>&laquo; </small><?php echo $this->__('Back') ?></a></p>
    </div>

    </div>

    <script type="text/javascript">
        //<![CDATA[

        jQuery(document).ready(function() {

            function deleteAddress(addressId) {
                if(confirm('<?php echo $this->__('Are you sure you want to delete this address?') ?>')) {
                    window.location='<?php echo $this->getDeleteUrl() ?>id/'+addressId;
                }
                return false;
            }

            jQuery('[name="deleteAddressRecord"]').on('click', function(event) {
                event.preventDefault();
                var deleteAddressId = jQuery(this).attr('id');
                deleteAddressId = deleteAddressId.replace('deleteAddressRecord_', '');
                deleteAddress(deleteAddressId);
            });

        });

        //]]>
    </script>
<?php endif; ?>

<!-- template/customer/address/book.phtml (end) -->