<?php
/**
 * Edit customer address template
 */
/* @var $this Schracklive_SchrackCustomer_Block_Address_Edit */
?>
<?php
    $customerHasDefaultBillingAddress = false;
    $customerHasDefaultShippingAddress = false;
    $addressMode = "";
//var_dump($this->getAddress());
    $addresaction = $this->getRequest()->getParam('addressaction');
    if ($addresaction == 'editdefaultbillingaddress') $addressMode = 'editdefaultbillingaddress';
    if ($addresaction == 'editdefaultshippingaddress') $addressMode = 'editdefaultshippingaddress';

    $session = Mage::getSingleton('customer/session');
    if ($session->getCustomer()->getPrimaryBillingAddress() && $session->getCustomer()->getPrimaryBillingAddress()->getId()) {
        $customerHasDefaultBillingAddress = true;
    }
    if ($session->getCustomer()->getPrimaryShippingAddress() && $session->getCustomer()->getPrimaryShippingAddress()->getId()) {
        $customerHasDefaultShippingAddress = true;
    }

	if ($this->getRequest()->getBeforeForwardInfo('action_name') == 'new') {
        $actionName = 'new';
		$valName1 = '';
		$valName2 = '';
		$valName3 = '';
	} else {
        $actionName = 'edit';
		$valName1 = $this->htmlEscape($this->getAddress()->getName1());
		$valName2 = $this->htmlEscape($this->getAddress()->getName2());
		$valName3 = $this->htmlEscape($this->getAddress()->getName3());
	}

?>
<!-- /customer/address/edit.phtml (start) -->
<style>
    .validate-select {
        width: 342px !important;
    }
</style>

<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<div class="row data">
    <div class="large-12 columns">
        <div class="row">
            <div class="large-12 columns">
                <?php if($this->getTitle()): ?>
                    <div class="headline b1">
                        <?php if($this->isDefaultBilling()): ?>
                            <?php echo $this->__('Default Billing Address'); ?>
                        <?php elseif($this->isDefaultShipping()): ?>
                            <?php echo $this->__('Default Shipping Address'); ?>
                        <?php else: ?>
                            <div>
                                <div>
                                    <?php echo $this->getTitle($actionName); ?>
                                </div>
                                <?php if ($actionName == 'edit') : ?>
                                    <div>
                                        <a id="deleteAddressRecord_<?php echo $this->getAddress()->getId(); ?>" name="deleteAddressRecord" href="" style="color: #00589D; position: absolute; margin-left: 89px; margin-top: 42px; font-size: 22px; z-index: 999; outline: none;" title="<?php echo $this->__('Delete Address') ?>"><i class="fa fa-trash-o" aria-hidden="true"></i></a>
                                    </div>
                                <?php endif; ?>
                                <div style="clear: both;"></div>
                            </div>
                        <?php endif; ?>
                    </div>
                <?php endif; ?>
            </div>
        </div>
        <form action="<?php echo $this->getSaveUrl() ?>" method="post" id="form-validate">
            <?php echo $this->getBlockHtml('formkey')?>
            <div class="row content">
                <div class="large-12 columns">
                    <input type="hidden" name="success_url" value="<?php echo $this->getSuccessUrl() ?>" />
                    <input type="hidden" name="error_url" value="<?php echo $this->getErrorUrl() ?>" />
                    <input type="hidden" name="schrack_wws_address_number" value="<?php echo $this->getAddress()->getSchrackWwsAddressNumber() ?>" />
                        <div class="headline c1"><?php echo $this->__('Address') ?></div>
                    <ul class="form-list">
                        <li>
                            <fieldset style="border: 1px solid #d6d6d6; color: black; width: 350px; float: left; margin-right: 25px; margin-bottom: 20px; margin-top: 14px; margin-left: 33px; height: 195px;">
                                <legend><em> *</em> <?php echo $this->__('Company') ?>&nbsp;&nbsp;</legend>
                                <div class="fields" style="margin-bottom: 15px;"">
                                    <div class="customHeightDistance"></div>
                                    <label for="name1" class="required"></label>
                                    <div class="input-box">
                                        <input style="width: 342px;" type="text" name="name1" id="name1" value="<?php echo $valName1 ?>" title="<?php echo $this->__('Company') ?>" class="input-text required-entry" maxlength="30" />
                                    </div>
                                </div>
                                <div class="fields">
                                    <div class="customHeightDistance"></div>
                                    <div class="input-box">
                                        <input style="width: 342px !important;" type="text" name="name2" id="name2" value="<?php echo $valName2 ?>" title="<?php echo $this->__('Company') ?>" class="input-text" maxlength="30" />
                                    </div>
                                </div>
                                <div class="fields">
                                    <div class="customHeightDistance"></div>
                                    <label for="name3"><?php echo $this->__('Contact') ?></label>
                                    <div class="input-box">
                                        <input style="width: 342px;" type="text" name="name3" id="name3" value="<?php echo $valName3 ?>" title="<?php echo $this->__('Contact') ?>" class="input-text" maxlength="30" />
                                    </div>
                                </div>
                            </fieldset>
                            <fieldset style="border: 1px solid #d6d6d6; color: black; width: 350px; float: left; margin-bottom: 21px; margin-top: 14px; height: 87px;">
                                <legend><em> *</em> <?php echo $this->__('Street Address') ?>&nbsp;&nbsp;</legend>
                                <div class="fields">
                                    <div class="customHeightDistance"></div>
                                    <label for="street_1" class="required"></label>
                                    <div class="input-box">
                                        <input style="width: 342px !important;" type="text" name="street[]" id="street_1" value="<?php echo $this->htmlEscape($this->getAddress()->getStreet(1)) ?>" title="<?php echo $this->__('Street Address') ?>" class="input-text required-entry" maxlength="30" />
                                    </div>
                                </div>
                                <?php for ($_i=2, $_n=$this->helper('customer/address')->getStreetLines(); $_i<=$_n; $_i++): ?>
                                    <div class="fields">
                                        <div class="customHeightDistance"></div>
                                        <label for="street_<?php echo $_i?>" class="required"></label>
                                        <div class="input-box">
                                            <input style="width: 342px !important;" type="text" name="street[]" id="street_<?php echo $_i?>" value="<?php echo $this->htmlEscape($this->getAddress()->getStreet($_i)) ?>" title="<?php echo $this->__('Street Address '.$_i) ?>" class="input-text required-entry" maxlength="30" />
                                        </div>
                                    </div>
                                <?php endfor ?>
                            </fieldset>
                            <fieldset style="border: 1px solid #d6d6d6; color: black; width: 350px; float: left;  margin-right: 25px; margin-bottom: 20px; height: 87px;">
                                <legend><em> *</em> <?php echo $this->__('Zip/Postal Code') ?>&nbsp;&nbsp;</legend>
                                <div class="fields">
                                    <div class="customHeightDistance"></div>
                                    <label for="postcode" class="required"></label>
                                    <div class="input-box">
                                        <input style="width: 342px !important;" type="text" name="postcode" id="zip" value="<?php echo $this->htmlEscape($this->getAddress()->getPostcode()) ?>" title="<?php echo $this->__('Zip/Postal Code') ?>" class="input-text validate-must-be-zip required-entry" maxlength="10" />
                                    </div>
                                </div>
                            </fieldset>
                            <div style="clear: both;">
                            <fieldset style="border: 1px solid #d6d6d6; color: black; width: 350px; float: left; margin-left: 33px; margin-right: 25px; height: 87px; margin-bottom: 20px;">
                                <legend><em> *</em> <?php echo $this->__('City') ?>&nbsp;&nbsp;</legend>
                                <div class="fields">
                                    <div class="customHeightDistance"></div>
                                    <label for="city" class="required"></label>
                                    <div class="input-box">
                                        <input style="width: 342px !important;" type="text" name="city" id="city" value="<?php echo $this->htmlEscape($this->getAddress()->getCity()) ?>" title="<?php echo $this->__('City') ?>" class="input-text required-entry" maxlength="30" />
                                    </div>
                                </div>
                            </fieldset>
                            <fieldset style="border: 1px solid #d6d6d6; color: black; width: 350px; float: left; height: 87px;">
                                <legend><em> *</em> <?php echo $this->__('Country') ?>&nbsp;&nbsp;</legend>
                                <div class="fields">
                                    <div class="customHeightDistance"></div>
                                    <label for="country" class="required"></label>
                                    <div class="input-box">
                                        <?php echo $this->getCountryHtmlSelect() ?>
                                    </div>
                                </div>
                            </fieldset>
                            <div style="clear: both;"></div>

                            <?php //Case: edit default billing address ?>
                            <?php if ($addressMode == 'editdefaultbillingaddress') : ?>
                                <input type="hidden" name="address_mode" value="editdefaultbillingaddress" />
                                    <?php if (!$customerHasDefaultShippingAddress) :?>
                                        <div class="control" style="float: left; width: 350px; margin-top: 19px; margin-left: 38px;">
                                            <p><input type="checkbox" id="primary_shipping" name="default_shipping" value="1" title="<?php echo $this->__('Use as my default shipping address') ?>" class="checkbox" /><label for="primary_shipping" style="display: inline;"><strong><?php echo $this->__('Use as my default shipping address') ?></strong></label></p>
                                        </div>
                                    <?php else:?>
                                        <input type="hidden" name="default_shipping" value="0" />
                                    <?php endif; ?>
                            <?php endif; ?>

                            <?php //Case: edit or create new (normal) address ?>
                            <?php if ($addressMode != 'editdefaultbillingaddress' && $addressMode != 'editdefaultshippingaddress') : ?>
                                <fieldset style="border: 1px solid #d6d6d6; color: black; width: 350px; float: left; height: 87px; margin-left: 33px;">
                                    <legend><em> *</em> <?php echo $this->__('Address Type') ?>&nbsp;&nbsp;</legend>
                                    <div class="fields">
                                        <div class="customHeightDistance"></div>
                                        <label for="schrack-type" class="required"></label>
                                        <div class="input-box">
                                            <?php echo $this->getTypeHtmlSelect() ?>
                                        </div>
                                    </div>
                                </fieldset>
                                <div class="control" style="float: left; width: 350px; margin-top: 69px; margin-left: 38px;">
                                    <p><input type="checkbox" id="primary_shipping" name="default_shipping" value="1" title="<?php echo $this->__('Use as my default shipping address') ?>" class="checkbox" /><label for="primary_shipping" style="display: inline;"><strong><?php echo $this->__('Use as my default shipping address') ?></strong></label></p>
                                </div>
                            <?php else: ?>
                                <?php if ($addressMode == 'editdefaultshippingaddress') : ?>
                                    <input type="hidden" name="default_shipping" value="1" />
                                <?php endif; ?>
                            <?php endif; ?>

                            <div style="clear: both;"></div>
                            <p style="float: left; width: 120px; margin-left: 33px; margin-top: 20px;" class="required"><b><?php echo $this->__('* Required Fields') ?></b></p>
                        </li>
                    </ul>
                </div>
            </div>
            <div class="row content">
                <div class="large-3 columns" style="margin-top: 5px;">
                    <a href="<?php echo $this->getBackUrl() ?>" class="button-blue" style="border: none;"><small>&laquo; </small><?php echo $this->__('Back') ?></a>
                </div>
                <div class="large-3 columns">
                    <button class="button-red small gray" title="<?php echo $this->__('Save Address') ?>"><?php echo $this->__('Save Address') ?></button>
                </div>
            </div>
        </form>
    </div>
</div>
<script type="text/javascript">
//<![CDATA[
    var dataForm = new VarienForm('form-validate', true);
    Validation.add('validate-must-be-zip', '<?php echo $this->__('Please enter the zip/postal code.')?>', function(text) {
        return validateZipCode(jQuery('select[name="country_id"]').val(), text);
    });

    function deleteAddress(addressId) {
        if(confirm('<?php echo $this->__('Are you sure you want to delete this address?') ?>')) {
            window.location='<?php echo $this->getUrl('customer/address/delete', array(Mage_Core_Model_Url::FORM_KEY => Mage::getSingleton('core/session')->getFormKey())) ?>id/'+addressId;
        }
        return false;
    }

    jQuery('[name="deleteAddressRecord"]').on('click', function(event) {
        event.preventDefault();
        var deleteAddressId = jQuery(this).attr('id');
        deleteAddressId = deleteAddressId.replace('deleteAddressRecord_', '');
        deleteAddress(deleteAddressId);
    });


//]]>
</script>
<!-- /customer/address/edit.phtml (end) -->