<!-- app/design/frontend/schrack/schrackresponsive/template/page/html/header.phtml (start) -->

<?php
/* @var $this Schracklive_SchrackPage_Block_Html_Header */
/* @see Schracklive_Typo3_Block_Page_Html_Header */
    $_session = Mage::getSingleton('customer/session');
    $_customer = $_session->getCustomer();
    $currentUrl = Mage::helper('core/url')->getCurrentUrl();

    $customerIsDSGVOConfirmed = false;
    $customerEmail = '';

    // Abfrage, ob ein Login vorliegt:
    if ($_session->isLoggedIn()) {
        $customerEmail = $_customer->getEmail();
        if ($_customer) {
            // Wenn ja, dann eine nächste Abfrage, ob die DSGVO bereits bestätigt wurde
            $customerIsDSGVOConfirmed = $_customer->getSchrackConfirmedDsgvo();
        }
    }

    if (Mage::getStoreConfig('ec/config/active')) $trackingEnabled = 'enabled'; else $trackingEnabled = 'disabled';

    if (Mage::getSingleton("customer/session")->isLoggedIn()) {
        $crmUserId = Mage::getSingleton('customer/session')->getCustomer()->getSchrackS4yId();
    } else {
        $crmUserId = 0;
    }

    if (Mage::getSingleton("customer/session")->isLoggedIn()) {
        $customerTypeGTM = 'normalCustomerType'; // = default

        // If customer is logged in, must be light-prospect, full-prospect or normal-customer (= default) :
        $customerTypeFromCustomer = Mage::getSingleton('customer/session')->getCustomer()->getSchrackCustomerType();
        if($customerTypeFromCustomer == 'light-prospect') {
            $customerTypeGTM = 'lightProspectCustomerType';
        }
        if($customerTypeFromCustomer == 'full-prospect') {
            $customerTypeGTM = 'fullProspectCustomerType';
        }
    } else {
        $customerTypeGTM = 'guestCustomerType';
    }

    if (Mage::getSingleton("customer/session")->isLoggedIn()) {
        $wwsId = Mage::getSingleton('customer/session')->getCustomer()->getSchrackWwsCustomerId();
        if (!$wwsId) {

            $accountCrmId = 0;
        } else {
            $resource       = Mage::getSingleton('core/resource');
            $readConnection = $resource->getConnection('core_read');

            $queryFindAccountData = "SELECT schrack_s4y_id FROM account WHERE wws_customer_id LIKE '" . $wwsId . "' ";
            $result = $readConnection->fetchAll($queryFindAccountData);

            if (is_array($result) && !empty($result)) {
                foreach ($result as $index => $recordset) {
                    $accountCrmId = $recordset['schrack_s4y_id'];
                }
            }
        }
    } else {
        $accountCrmId = 0;
    }

    $cartButtonImagePath = $this->getSkinUrl('schrackdesign/Public/Images/rwd/cartIconWht.png');

    if (strtoupper(Mage::getStoreConfig('schrack/general/country')) == 'SI') {
        $logo = 'schrack-SI-logo-30let.png';
    } else {
        $logo = 'schrack-logo.png';
    }

    $ajaxLoaderGifPath = $this->getSkinUrl('schrackdesign/Public/Images/download_ajax_loader.gif');


?>

<style>
    .poll_label {
        font-weight: normal !important;
    }
    #pollpopup_content {
        margin-left: 15px !important;
    }
    .poll_thanks_line {
        margin-left: 0;
    }
    .poll_thanks_line_content {
        float: left;
        width: 100%;
        color: #00589d !important;
        font-weight: bold;
    }
    .poll_answer_textarea {
        width: 75% !important;
        resize: vertical !important;
    }
    .poll_question {
        color: #00589d !important;
        font-size: 16px !important;
    }
    .poll_checkbox_label {
        font-weight: normal !important;
    }
    .container {
        display: block !important;
    }
    html, body {
        max-width: 100% !important;
        overflow-x: hidden !important;
        min-height: 100vh;
    }
    #page_layer_text_block_content {
        float: left;
        margin-left: 12px;
        margin-top: 7px;
        width: 90%;
        text-align: justify;
        color: black;
        font-size: 1.1em;
    }

    #page_layer_checkbox_block {
        color: black !important;
        font-size: 1em;
        font-weight: bold;
        padding-left: 4%;
        padding-top: 2%;
    }

    #page_layer_cancel_button_warning_text {
        display: none;
        margin-top: 20px;
        font-size: 1.2em;
        color: red;
        font-weight: bold;
        text-align: center;
    }
    #page_layer_user_terms_confirm_checkbox {
        float: left;
    }
    #page_layer_user_terms_confirm_checkbox_text {
        float: left;
        margin-left: 3px;
        margin-top: 2px;
    }

    button#close_poll_popup_right_lower_corner, button#close_poll_popup_right_lower_corner:after{
        background-color: #919191;
    }

    @media (min-width: 60px) and (max-width: 320px) {
        .modal-content {
            width: 99% !important;
        }
        #page_layer_container {
            margin-top: 3%;
            margin-left: 3%;
            width: 94%;
            height: auto;
            padding: 14px;
            background: #ffffff;
            border-radius: 12px;
            border: 2px solid #005b9f;
        }
        #page_layer_confirm_button {
            float: left;
            margin-left: 11%;
            height: 30px !important;

        }
        #page_layer_cancel_button {
            height: 30px !important;
        }
        #page_layer_cancel_warning_button_yes {
            float: left;
            margin-left: 24%;
        }
        #page_layer_text_block_content {
            font-size: 0.8em;
        }
        #page_layer_checkbox_block {
            font-size: 0.8em;
        }
        #page_layer_actions_block {
            margin-top: 16px !important;
        }
        #page_layer_cancel_button_warning_text {
            display: none;
            margin-top: -109px;
            font-size: 0.9em;
            color: red;
            font-weight: bold;
            text-align: center;
        }
        #page_layer_cancel_warning_button_yes {
            height: 30px !important;
        }

        #page_layer_cancel_warning_button_no {
            height: 30px !important;
        }
    }

    @media (min-width: 321px) and (max-width: 480px) {
        .modal-content {
            width: 99% !important;
        }
        #page_layer_container {
            margin-top: 3%;
            margin-left: 3%;
            width: 94%;
            height: auto;
            padding: 14px;
            background: #ffffff;
            border-radius: 12px;
            border: 2px solid #005b9f;
        }
        #page_layer_confirm_button {
            float: left;
            margin-left: 11%;
        }
        #page_layer_cancel_warning_button_yes {
            float: left;
            margin-left: 24%;
        }
    }

    @media (min-width: 481px) and (max-width: 768px) {
        .modal-content {
            width: 99% !important;
        }
        .inquiryPopup {
            width: 100% !important;
            margin-left: 0 !important;
        }
        #page_layer_container {
            margin-top: 3%;
            margin-left: 3%;
            width: 94%;
            height: auto;
            padding: 35px;
            background: #ffffff;
            border-radius: 12px;
            border: 2px solid #005b9f;
        }
        #page_layer_confirm_button {
            float: left;
            margin-left: 25%;
        }
        #page_layer_cancel_warning_button_yes {
            float: left;
            margin-left: 30%;
        }
    }

    @media (min-width: 769px) and (max-width: 1024px) {
        .modal-content {
            width: 99% !important;
        }
        #quickaddpopup .modal-dialog .modal-content {
            width: 600px !important;
        }
        .inquiryPopup {
            width: 120% !important;
            margin-left: -10% !important;
        }
        #page_layer_container {
            margin-top: 3%;
            margin-left: 3%;
            width: 94%;
            height: auto;
            padding: 35px;
            background: #ffffff;
            border-radius: 12px;
            border: 2px solid #005b9f;
        }
        #page_layer_confirm_button {
            float: left;
            margin-left: 25%;
        }
        #page_layer_cancel_warning_button_yes {
            float: left;
            margin-left: 32%;
        }
    }

    @media (min-width: 1025px) and (max-width: 1370px) {
        .modal-content {
            width: 100% !important;
        }
        #quickaddpopup .modal-dialog .modal-content {
            width: 600px !important;
        }
        .inquiryPopup {
            width: 140% !important;
            margin-left: -17% !important;
        }
        #page_layer_container {
            margin-top: 5%;
            margin-left: 24%;
            width: 52%;
            height: auto;
            padding: 35px;
            background: #ffffff;
            border-radius: 12px;
            border: 2px solid #005b9f;
        }
        #page_layer_confirm_button {
            float: left;
            margin-left: 25%;
        }
        #page_layer_cancel_warning_button_yes {
            float: left;
            margin-left: 30%;
        }
    }

    @media (min-width: 1371px) and (max-width: 3000px) {
        .modal-content {
            width: 100% !important;
        }
        #quickaddpopup .modal-dialog .modal-content {
            width: 600px !important;
        }
        .inquiryPopup {
            width: 140% !important;
            margin-left: -17% !important;
        }
        #page_layer_container {
            margin-top: 5%;
            margin-left: 24%;
            width: 52%;
            height: auto;
            padding: 35px;
            background: #ffffff;
            border-radius: 12px;
            border: 2px solid #005b9f;
        }
        #page_layer_confirm_button {
            float: left;
            margin-left: 25%;
        }
        #page_layer_cancel_warning_button_yes {
            float: left;
            margin-left: 30%;
        }
    }

    #page_layer {
        position: fixed;
        display: none;
        width: 100%;
        height: 100%;
        top: 0;
        left: 0;
        right: 0;
        bottom: 0;
        background-color: rgba(143, 143, 143, 0.95);
        z-index: 99999999;
    }

    #page_layer_text_block {
        height: auto;
    }

    .pageLayerAgbConfirmCheckbox {
        padding-left: 7px;
        padding-right: 7px;
        padding-top: 5px;
        padding-bottom: 2px;
        margin-bottom: 10px;
        width: 90%;
        border-radius: 4px;
    }

    .pageLayerAgbConfirmCheckboxWarning {
        padding-left: 7px;
        padding-right: 7px;
        padding-top: 5px;
        background: #ffb9af;
        padding-bottom: 2px;
        margin-bottom: 10px;
        width: 90%;
        border-radius: 4px;
    }

    .pageLayerAgbConfirmCheckboxConfirmed {
        padding-left: 7px;
        padding-right: 7px;
        padding-top: 5px;
        background: #afeeee;
        padding-bottom: 2px;
        margin-bottom: 10px;
        width: 90%;
        border-radius: 4px;
    }

    .pageLayerDataprotectionConfirmCheckbox {
        padding-left: 7px;
        padding-right: 7px;
        padding-top: 5px;
        padding-bottom: 2px;
        margin-bottom: 10px;
        width: 90%;
    }

    .pageLayerDataprotectionConfirmCheckboxWarning {
        padding-left: 7px;
        padding-right: 7px;
        padding-top: 5px;
        background: #ffb9af;
        padding-bottom: 2px;
        margin-bottom: 10px;
        width: 90%;
        border-radius: 4px;
    }

    .pageLayerDataprotectionConfirmCheckboxConfirmed {
        padding-left: 7px;
        padding-right: 7px;
        padding-top: 5px;
        background: #afeeee;
        padding-bottom: 2px;
        margin-bottom: 10px;
        width: 90%;
        border-radius: 4px;
    }

    .pageLayerDSGVOConfirmCheckbox {
        padding-left: 7px;
        padding-right: 7px;
        padding-top: 5px;
        padding-bottom: 2px;
        width: 90%;
    }

    .pageLayerDSGVOConfirmCheckboxWarning {
        padding-left: 7px;
        padding-right: 7px;
        padding-top: 5px;
        background: #ffb9af;
        padding-bottom: 2px;
        width: 90%;
        border-radius: 4px;
    }

    .pageLayerDSGVOConfirmCheckboxConfirmed {
        padding-left: 7px;
        padding-right: 7px;
        padding-top: 5px;
        background: #afeeee;
        padding-bottom: 2px;
        width: 90%;
        border-radius: 4px;
    }

    .pageLayerUserTermsConfirmCheckbox {
        padding-left: 7px;
        padding-right: 7px;
        padding-top: 5px;
        padding-bottom: 2px;
        width: 90%;
    }

    .pageLayerUserTermsConfirmCheckboxWarning {
        padding-left: 7px;
        padding-right: 7px;
        padding-top: 5px;
        background: #ffb9af;
        padding-bottom: 2px;
        width: 90%;
        border-radius: 4px;
    }

    .pageLayerUserTermsConfirmCheckboxConfirmed {
        padding-left: 7px;
        padding-right: 7px;
        padding-top: 5px;
        background: #afeeee;
        padding-bottom: 2px;
        width: 90%;
        border-radius: 4px;
    }

    #page_layer_actions_block {
        margin-top: 31px;
    }

    #page_layer_cancel_button {
        float: left;
        margin-left: 20%;
    }

    #page_layer_cancel_warning_button_no {
        float: left;
        margin-left: 20%;
    }

    .clearBoth {
        clear: both;
    }

    .not_visible {
        display: none;
    }

    #page_layer_logo {
        float: right;
        margin-bottom: 9px;
    }

    #page_layer_logo_default {
        margin-left: 0;
        float: none;
        margin-top: 5px;
        box-sizing: border-box;
        display: block;
        line-height: 1.42857143;
        z-index: 100;
        cursor: pointer;
        position: absolute;
    }

    #headerPLCaptionIcon {
        border: 1px solid #9f9f9f;
        border-radius: 25px;
        width: 41px;
        height: 41px;
        padding-top: 6px;
        padding-left: 9px;
        margin-top: 1px !important;
    }

    /* Mobile Mega Menu Redesign 2019 */
    @media (min-width: 1px) and (max-width: 320px) {
        .lower_main_content {
            padding-right: 27px !important;
            padding-left: 26px !important;

        }
        #crtRtAction {
            padding-left: 10px !important;
        }
        #headerLinks {
            margin-right: -44px !important;
            margin-top: -2px;
        }
        #page_layer_logo_default {
            margin-left: -11px !important;
            margin-top: 0 !important;
        }
        #page_layer_logo_default_image {
            width: 70%;
            margin-left: 8px;
        }
        .header_menu_logo_container_left {
            padding-left: 0 !important;
            width: 44% !important;
        }
        #headerPLCaptionIcon {
            margin-right: 0 !important;
            width: 38px;
            height: 38px;
            padding-top: 1px;
            padding-left: 6px;
        }
        .partlistBlueIcon {
            padding-top: 4px !important;
            padding-left: 8px !important;
        }
        #link_header_login_button {
            background: transparent !important;
            height: 40px !important;
            width: 40px !important;
            border: 1px solid #9f9f9f !important;
            border-radius: 20px !important;
            overflow: hidden !important;
            box-shadow: none !important;
            padding-top: 0 !important;
        }
        .header_menu_links_container_right {
            width: 54.333333% !important;
            margin-left: -33px !important;
        }
        #agentInfoHead {
            height: 40px !important;
            width: 40px !important;
            border-radius: 20px !important;
        }
        .partlistGrayIcon {
            font-size: 24px !important;
            margin-top: 3px!important;
        }
        #login_image_mobile {
            display: block !important;
            width: 21px !important;
            height: 28px !important;
            margin-left: 7px !important;
            margin-top: 5px !important;
        }
        #customerLogInContainer {
            border-radius: 20px !important;
            width: 40px !important;
            height: 40px !important;
        }
        .cart_icon_header {
            width: 40px !important;
        }
    }

    @media (min-width: 321px) and (max-width: 360px) {
        .lower_main_content {
            padding-right: 32px !important;
        }
        #headerLinks {
            margin-right: -18px !important;
            width: 121% !important;
        }
        #page_layer_logo_default {
            margin-left: -11px !important;
            margin-top: 4px !important;
        }
        #page_layer_logo_default_image {
            width: 70%;
            margin-left: 4px;
        }
        .header_menu_logo_container_left {
            padding-left: 0 !important;
            width: 44% !important;
        }
        #headerPLCaptionIcon {
            margin-right: 1px !important;
            width: 38px;
            height: 38px;
            padding-top: 2px;
            padding-left: 6px;
        }
        #link_header_login_button {
            background: transparent !important;
            height: 40px !important;
            width: 40px !important;
            border: 1px solid #9f9f9f !important;
            border-radius: 20px !important;
            overflow: hidden !important;
            box-shadow: none !important;
            padding-top: 0 !important;
            padding-left: 0 !important;
        }
        .header_menu_links_container_right {
            width: 54.333333% !important;
        }
        #agentInfoHead {
            height: 40px !important;
            width: 40px !important;
            border-radius: 20px !important;
        }
        .partlistGrayIcon {
            font-size: 24px !important;
            margin-top: 3px!important;
        }
        #login_image_mobile {
            display: block !important;
            width: 21px !important;
            height: 28px !important;
            margin-left: 9px !important;
            margin-top: 5px !important;
        }
        #customerLogInContainer {
            border-radius: 20px !important;
            width: 40px !important;
            height: 40px !important;
        }
        .cart_icon_header {
            width: 81% !important;
            margin-top: 3px !important;
        }
    }

    @media (min-width: 361px) and (max-width: 410px) {
        .lower_main_content {
            padding-right: 32px !important;
        }
        .my_account_image {
            float: left;
            padding: 0;
            width: 25px;
            margin-top: 5px;
            margin-left: 4px;
        }
        #my_account_text {
            float: left;
            color: #00589D;
            font-size: 13px;
            font-weight: bold;
            margin-left: 10px;
            margin-top: 10px;
        }
        .my_logout_link_image {
            float: left;
            padding: 0;
            width: 25px;
            margin-top: 9px;
            margin-left: 7px;
        }
        #my_logout_text {
            float: left;
            color: #00589D;
            font-size: 13px;
            font-weight: bold;
            margin-left: 12px;
            margin-top: 11px;
        }
        #headerLinks {
            margin-right: -12px !important;
            width: 118% !important;
        }
        #page_layer_logo_default {
            margin-left: 0 !important;
            margin-top: 0 !important;
        }
        .header_menu_logo_container_left {
            padding-left: 0 !important;
            width: 44% !important;
        }
        #page_layer_logo_default_image {
            width: 116px !important;
            margin-left: -8px;
            margin-top: 1px;
        }
        #headerPLCaptionIcon {
            margin-right: 1px !important;
            width: 40px;
            height: 40px;
            padding-top: 4px;
            padding-left: 9px;
        }
        #link_header_login_button {
            background: transparent !important;
            height: 40px !important;
            width: 40px !important;
            border: 1px solid #9f9f9f !important;
            border-radius: 20px !important;
            overflow: hidden !important;
            box-shadow: none !important;
            padding-top: 0 !important;
        }
        .header_menu_links_container_right {
            width: 55.333333% !important;
        }
        #agentInfoHead {
            height: 40px !important;
            width: 40px !important;
            border-radius: 20px !important;
        }
        .partlistGrayIcon {
            font-size: 24px !important;
            margin-top: 3px!important;
        }
        #login_image_mobile {
            display: block !important;
            width: 21px !important;
            height: 28px !important;
            margin-left: 7px !important;
            margin-top: 5px !important;
        }
        #customerLogInContainer {
            border-radius: 20px !important;
            width: 40px !important;
            height: 40px !important;
        }
        .cart_icon_header {
            width: 81% !important;
        }
    }

    @media (min-width: 411px) and (max-width: 460px) {
        .lower_main_content {
            padding-right: 32px !important;
        }
        #headerLinks {
            margin-right: -37px !important;
        }
        #page_layer_logo_default {
            margin-left: -11px !important;
            margin-top: 3px !important;
        }
        .header_menu_logo_container_left {
            padding-left: 0 !important;
            width: 44% !important;
        }
        #page_layer_logo_default_image {
            width: 70%;
            margin-left: 4px;
        }
        #headerPLCaptionIcon {
            margin-right: 0 !important;
            width: 39px;
            height: 39px;
            padding-top: 2px;
            padding-left: 7px;
        }
        #link_header_login_button {
            background: transparent !important;
            height: 40px !important;
            width: 40px !important;
            border: 1px solid #9f9f9f !important;
            border-radius: 20px !important;
            overflow: hidden !important;
            box-shadow: none !important;
            padding-top: 0 !important;
            padding-left: 0 !important;
        }
        .header_menu_links_container_right {
            /* width: 54.333333% !important; */
        }
        #agentInfoHead {
            height: 40px !important;
            width: 40px !important;
            border-radius: 20px !important;
        }
        .partlistGrayIcon {
            font-size: 24px !important;
            margin-top: 3px!important;
        }
        #login_image_mobile {
            display: block !important;
            width: 21px !important;
            height: 28px !important;
            margin-left: 9px !important;
            margin-top: 5px !important;
        }
        #customerLogInContainer {
            border-radius: 20px !important;
            width: 40px !important;
            height: 40px !important;
        }
        .cart_icon_header {
            width: 81% !important;
        }
    }

    @media (min-width: 461px) and (max-width: 480px) {
        .lower_main_content {
            padding-right: 32px !important;
        }
        #headerLinks {
            margin-right: -13px !important;
        }
        #page_layer_logo_default {
            margin-left: 0 !important;
            margin-top: 0 !important;
        }
        .header_menu_logo_container_left {
            padding-left: 0 !important;
            width: 44% !important;
        }
        #headerPLCaptionIcon {
            margin-right: 7px !important;
        }
        #link_header_login_button {
            background: transparent !important;
            height: 40px !important;
            width: 40px !important;
            border: 1px solid #9f9f9f !important;
            border-radius: 20px !important;
            overflow: hidden !important;
            box-shadow: none !important;
            padding-top: 0 !important;
        }
        .header_menu_links_container_right {
            width: 54.333333% !important;
        }
        #agentInfoHead {
            height: 40px !important;
            width: 40px !important;
            border-radius: 20px !important;
        }
        .partlistGrayIcon {
            font-size: 24px !important;
            margin-top: 3px!important;
        }
        #login_image_mobile {
            display: block !important;
            width: 21px !important;
            height: 28px !important;
            margin-left: 9px !important;
            margin-top: 5px !important;
        }
        #customerLogInContainer {
            border-radius: 20px !important;
            width: 40px !important;
            height: 40px !important;
        }
    }

    @media (min-width: 481px) and (max-width: 560px) {
        .lower_main_content {
            padding-right: 32px !important;
        }
        #headerLinks {
            margin-right: -13px !important;
        }
        #page_layer_logo_default {
            margin-left: 0 !important;
            margin-top: 0 !important;
        }
        .header_menu_logo_container_left {
            padding-left: 0 !important;
            width: 44% !important;
        }
        #headerPLCaptionIcon {
            margin-right: 7px !important;
        }
        #link_header_login_button {
            background: transparent !important;
            height: 40px !important;
            width: 40px !important;
            border: 1px solid #9f9f9f !important;
            border-radius: 20px !important;
            overflow: hidden !important;
            box-shadow: none !important;
            padding-top: 0 !important;
        }
        .header_menu_links_container_right {
            width: 54.333333% !important;
        }
        #agentInfoHead {
            height: 40px !important;
            width: 40px !important;
            border-radius: 20px !important;
        }
        .partlistGrayIcon {
            font-size: 24px !important;
            margin-top: 3px!important;
        }
        #login_image_mobile {
            display: block !important;
            width: 21px !important;
            height: 28px !important;
            margin-left: 9px !important;
            margin-top: 5px !important;
        }
        #customerLogInContainer {
            border-radius: 20px !important;
            width: 40px !important;
            height: 40px !important;
        }
    }

    @media (min-width: 561px) and (max-width: 639px) {
        .lower_main_content {
            padding-right: 32px !important;
        }
        #headerLinks {
            margin-right: -13px !important;
        }
        #page_layer_logo_default {
            margin-left: 0 !important;
            margin-top: 0 !important;
        }
        #page_layer_logo_default_image {
            width: 48%;
            margin-left: -9px;
            margin-top: 4px !important;
        }
        .header_menu_logo_container_left {
            padding-left: 0 !important;
            width: 44% !important;
        }
        #headerPLCaptionIcon {
            margin-right: 7px !important;
        }
        #link_header_login_button {
            background: transparent !important;
            height: 40px !important;
            width: 40px !important;
            border: 1px solid #9f9f9f !important;
            border-radius: 20px !important;
            overflow: hidden !important;
            box-shadow: none !important;
            padding-top: 0 !important;
        }
        .header_menu_links_container_right {
            width: 54.333333% !important;
        }
        #agentInfoHead {
            height: 40px !important;
            width: 40px !important;
            border-radius: 20px !important;
        }
        .partlistGrayIcon {
            font-size: 24px !important;
            margin-top: 3px!important;
        }
        #login_image_mobile {
            display: block !important;
            width: 21px !important;
            height: 28px !important;
            margin-left: 7px !important;
            margin-top: 5px !important;
        }
        #customerLogInContainer {
            border-radius: 20px !important;
            width: 40px !important;
            height: 40px !important;
        }
    }

    @media (min-width: 640px) and (max-width: 767px) {
        .lower_main_content {
            padding-right: 32px !important;
        }
        #headerLinks {
            margin-right: -13px !important;
        }
        #page_layer_logo_default {
            margin-left: 0 !important;
            margin-top: 0 !important;
        }
        #page_layer_logo_default_image {
            width: 47%;
            margin-left: -7px;
            margin-top: 2px;
        }
        .header_menu_logo_container_left {
            padding-left: 0 !important;
            width: 44% !important;
        }
        #headerPLCaptionIcon {
            margin-right: 0 !important;
            width: 40px;
            height: 40px;
            padding-top: 5px;
            padding-left: 9px;
        }
        #link_header_login_button {
            background: transparent !important;
            height: 40px !important;
            width: 40px !important;
            border: 1px solid #9f9f9f !important;
            border-radius: 20px !important;
            overflow: hidden !important;
            box-shadow: none !important;
            padding-top: 0 !important;
        }
        .header_menu_links_container_right {
            width: 54.333333% !important;
        }
        #agentInfoHead {
            height: 40px !important;
            width: 40px !important;
            border-radius: 20px !important;
        }
        .partlistGrayIcon {
            font-size: 24px !important;
            margin-top: 3px!important;
        }
        #login_image_mobile {
            display: block !important;
            width: 21px !important;
            height: 28px !important;
            margin-left: 7px !important;
            margin-top: 5px !important;
        }
        #customerLogInContainer {
            border-radius: 20px !important;
            width: 40px !important;
            height: 40px !important;
        }
    }

    @media (min-width: 768px) and (max-width: 768px) {
        .lower_main_content {
            padding-right: 32px !important;
        }
        #headerLinks {
            margin-right: 18px !important;
        }
        #page_layer_logo_default {
            margin-left: 16px !important;
            margin-top: 0 !important;
        }
        .header_menu_logo_container_left {
            padding-left: 0 !important;
            width: 44% !important;
        }
        #headerPLCaptionIcon {
            margin-right: 2px !important;
            padding-top: 3px !important;
            padding-left: 8px !important;
        }
        #link_header_login_button {
            background: transparent !important;
            height: 45px !important;
            width: 45px !important;
            border: 1px solid #9f9f9f !important;
            border-radius: 25px !important;
            overflow: hidden !important;
            box-shadow: none !important;
            padding-top: 2px !important;
            padding-left: 2px !important;
        }
        .header_menu_links_container_right {
            width: 54.333333% !important;
        }
        #agentInfoHead {
            height: 40px !important;
            width: 40px !important;
            border-radius: 20px !important;
        }
        .partlistGrayIcon {
            font-size: 24px !important;
            margin-top: 3px!important;
        }
        #login_image_mobile {
            display: block !important;
            width: 21px !important;
            height: 28px !important;
            margin-left: 9px !important;
            margin-top: 5px !important;
        }
        #customerLogInContainer {
            border-radius: 20px !important;
            width: 40px !important;
            height: 40px !important;
        }
        .cart_icon_header {
            width: 45px !important;
            margin-top: 3px !important;
        }
    }

    @media (min-width: 769px) and (max-width: 992px) {
        .lower_main_content {
            padding-right: 32px !important;
        }
        #headerLinks {
            margin-right: -13px !important;
        }
        #page_layer_logo_default {
            margin-left: 13px !important;
            margin-top: 0 !important;
        }
        .header_menu_logo_container_left {
            padding-left: 0 !important;
            width: 44% !important;
        }
        #headerPLCaptionIcon {
            margin-right: 2px !important;
            padding-top: 3px !important;
            padding-left: 7px !important;
        }
        #link_header_login_button {
            background: transparent !important;
            height: 43px !important;
            width: 43px !important;
            border: 1px solid #9f9f9f !important;
            border-radius: 20px !important;
            overflow: hidden !important;
            box-shadow: none !important;
            padding-top: 0 !important;
        }
        .header_menu_links_container_right {
            width: 54.333333% !important;
            margin-left: -8px !important;
        }
        #agentInfoHead {
            height: 40px !important;
            width: 40px !important;
            border-radius: 20px !important;
        }
        .partlistGrayIcon {
            font-size: 24px !important;
            margin-top: 3px!important;
        }
        #login_image_mobile {
            display: block !important;
            width: 21px !important;
            height: 28px !important;
            margin-left: 8px !important;
            margin-top: 6px !important;
        }
        #customerLogInContainer {
            border-radius: 20px !important;
            width: 40px !important;
            height: 40px !important;
        }
    }

    #testinfolayer {
        margin: 0;
        padding-left: 5px;
        padding-right: 5px;
        padding-bottom: 19px;
        position: absolute;
        top: 13px;
        left: 50%;
        transform: translate(-50%, -50%);
        border: 4px solid red;
        z-index: 1000000000000000000000000000;
        color: red;
        font-weight: bold;
        background: yellow;
        font-size: 16px;
        opacity: 0.2;
        height: 25px;
    }

    #dsgvoLayerHeadline {
        font-size: 1.5em;
        color: #005b9f;
        text-align: center;
        font-weight: bold;
        text-decoration: underline;
        letter-spacing: 0.06em;
    }

</style>

<?php if (Mage::getStoreConfig('schrack/general/platform') == 'TEST') : ?>
    <div id="testinfolayer">TEST-SYSTEM</div>
<?php endif; ?>

<?php if (intval(Mage::getStoreConfig('schrack/dsgvo/activateLayerForLogin')) == 1) : ?>
    <div id="page_layer">
        <div id="page_layer_container">
            <div id="dsgvoLayerHeadline"><?php echo $this->__('User Terms'); ?></div>
            <div id="page_layer_content">
                <div id="page_layer_text_block">
                    <div id="page_layer_text_block_content">
                        <?php echo $this->__('DSGVO Schrack Confirm Text'); ?>
                    </div>
                    <div class="clearBoth"></div>
                </div>
                <div id="page_layer_checkbox_block">
                    <?php if (intval(Mage::getStoreConfig('schrack/dsgvo/activateRegistrationCheckboxAGB')) == 1) : ?>
                        <div id="page_layer_agb_confirm_checkbox_block" class="pageLayerAgbConfirmCheckbox">
                            <input type="checkbox" id="page_layer_agb_confirm_checkbox">
                            <span id="page_layer_agb_confirm_checkbox_text"><?php echo $this->__("Schrack AGB Checkbox Confirm Text"); ?></span>
                        </div>
                    <?php endif; ?>

                    <div id="page_layer_dataprotection_confirm_checkbox_block" class="pageLayerDataprotectionConfirmCheckbox">
                        <input type="checkbox" id="page_layer_dataprotection_confirm_checkbox">
                        <span id="page_layer_dataprotection_confirm_checkbox_text"><?php echo $this->__("Schrack DataProtection Checkbox Confirm Text"); ?></span>
                    </div>
                    
                    <?php if (intval(Mage::getStoreConfig('schrack/dsgvo/activateRegistrationCheckboxDSGVO')) == 1) : ?>
                        <div id="page_layer_dsgvo_confirm_checkbox_block" class="pageLayerDSGVOConfirmCheckbox">
                            <input type="checkbox" id="page_layer_dsgvo_confirm_checkbox">
                            <span id="page_layer_dsgvo_confirm_checkbox_text"><?php echo $this->__("Schrack DSGVO Checkbox Confirm Text"); ?></span>
                        </div>
                    <?php endif; ?>

                    <?php if (intval(Mage::getStoreConfig('schrack/dsgvo/activateRegistrationCheckboxUserTerms')) == 1) : ?>
                        <?php
                            $typo_url = Mage::getStoreConfig('schrack/typo3/typo3url');
                            $typo_page_id_suffix = Mage::getStoreConfig('schrack/typo3/terms_of_use_service_url');
                            $use_of_terms_url = $typo_url . $typo_page_id_suffix;
                        ?>
                        <div id="page_layer_user_terms_confirm_checkbox_block" class="pageLayerUserTermsConfirmCheckbox">
                            <input type="checkbox" id="page_layer_user_terms_confirm_checkbox">
                            <div id="page_layer_user_terms_confirm_checkbox_text">
                                <?php echo $this->__("Schrack User Terms Checkbox Confirm Text"); ?>
                                <a href="<?php echo $use_of_terms_url; ?>" target="_blank">
                                    <?php echo $this->__('Schrack User Terms Link Text'); ?>
                                </a>
                            </div>
                            <div style="clear: both;"></div>
                        </div>
                    <?php endif; ?>
                </div>
                <div id="page_layer_cancel_button_warning_text" class=""><?php echo $this->__('Logout Question'); ?></div>
                <div id="page_layer_actions_block">
                    <button id="page_layer_confirm_button" class="bttn-md"><?php echo $this->__('Confirm'); ?></button>
                    <button id="page_layer_cancel_button" class="bttn-md"><?php echo $this->__('Cancel'); ?></button>
                    <button id="page_layer_cancel_warning_button_yes" class="bttn-md not_visible"><?php echo $this->__('Yes'); ?></button>
                    <button id="page_layer_cancel_warning_button_no" class="bttn-md not_visible"><?php echo $this->__('No'); ?></button>
                    <div class="clearBoth"></div>
                </div>
            </div>
        </div>
    </div>
<?php endif; ?>

<?php echo $this->breachProtection()?>
<!-- currentUrl = <?php echo $currentUrl; ?> -->
<div class="grayout"></div>
<div id="global_wrapper_header" class="headerHgt">
<header class="gradient main_header">
    <div id="global_wrapper" class="container">
        <div class="row">
            <div class="col-xs-6 col-sm-6 col-md-5 padR0 header_menu_logo_container_left">
                <div id="page_layer_logo_default">
                    <a href="<?php echo Mage::helper('schrackcore/url')->ensureCurrentProtocol($this->getUrl('')); ?>"
                       title="<?php echo $this->getLogoAlt() ?>">
                        <img id="page_layer_logo_default_image" src="<?php echo $this->getSkinUrl('schrackdesign/Public/Images/' . $logo)?>"/>
				    </a>
				<!--<a id="siteHeaderInfoIconLink" class="hidden-xs" href="javascript:void(0)" target="_blank" title="<?php echo $this->__('Schrack Technik'); ?>"><span id="siteHeaderInfoIcon" class="glyphicon glyphicon-info-sign info-icon blueTxt" style="display:none;"></span></a>
				-->
				</div>
            </div>
            <div class="col-xs-6 col-sm-6 col-md-7 header_menu_links_container_right print-hide">
                <?php echo $this->getChildHtml('topLinks')?>
            </div>

        </div>
    </div>
    <div id="messagebar_content"></div>
</header>

<style>
.top-navigation-container-hide {
    display: none;
}
</style>

<!-- Mega Menu load container (start) -->
<div class="top-navigation-container top-navigation-container-hide">
    <div class="top-navigation-wrapper">
        <div class="navbar navbar-megamenu" role="navigation">
            <!-- Mega Menu Container (start) -->
            <div class="mainNav bottom-header" id="mainNav">
                <!-- Content fetched by AJAX (header.phtml -> MenuController.php) -->
            </div>
            <!-- Mega Menu Container (end) -->
        </div>
    </div>
</div>

<!-- Mega Menu load container (end) -->


<!-- poll modal start -->
<?php $pollActive = false ?>
<?php if($pollActive) :?>
<div class="pollpopup modal fade" id="pollpopup" tabindex="-1" role="dialog" aria-labelledby="pollLabel">
    <div class="modal-dialog pollPopup" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button data-dismiss="modal"
                        aria-label="Close"
                        id="close_poll_popup_right_upper_corner"
                        class="close"
                        type="button">
                    <span aria-hidden="true">&times;</span>
                </button>
                <h4 class="modal-title" id="pollpopuplabel"><?php echo $this->__('POLL_SCHRACK') ?></h4>
                <br>
                <h5 class="poll_sub_title"><?php echo $this->__('POLL_1_TITLE') ?></h5>
            </div>
            <div class="modal-body">
                <div id="pollpopup_content" class="poll_content_container"></div>
                <br>
                <br>
                <div class="poll_thanks_line">
                    <div class="poll_thanks_line_content"><?php echo $this->__('POLL_THANK_YOU') ?></div>
                    <div class="poll_thanks_line_content"><?php echo $this->__('Your Schrack Team') ?></div>
                    <div style="clear: both;"></div>
                </div>
            </div>
            <div class="modal-footer">
                <button id="close_poll_popup_left_lower_corner" class="bttn-md"><?php echo $this->__('Save'); ?></button>
                <button data-dismiss="modal"
                        style="float: right; margin-right: 18px;"
                        type="button"
                        id="close_poll_popup_right_lower_corner"
                        class="bttn-md"><?php echo $this->__('Close'); ?>
                </button>
                <div style="clear: both;"></div>
            </div>
        </div>
    </div>
</div>
<?php endif; ?>
<!-- poll modal end -->

<div class="container">
    <?php echo $this->getChildHtml('topSearch') ?>
</div>

</div>
<?php echo $this->breachProtection()?>

<input type="hidden" id="header_phtml_uncached_timestamp" value="<?php echo date('Y-m-d H:i:s'); ?>">

<script type="text/javascript">
//<![CDATA[
    var checkDataprotectionAlternate = false;

// TODO : get current URL per AJAX:
    var currentUrl = window.location.href;
    if (currentUrl.indexOf('checkout/onepage') > 0) {
        // Do something here - Hooray, welcone to checkout !
    } else {
        jQuery('.top-navigation-container-hide').removeClass('top-navigation-container-hide');
    }
    //------------------------------------------- "Act as customer" translations



jQuery(document).ready(function() {

    //--------------------------------------------------------------------------
    if (localStorage.getItem("searchResultIsSingleProduct") === null) {
         localStorage.searchResultIsSingleProduct = '';
     }
    //--------------------------------------------------------------------------
     localStorage.darkBackground = 'false';
////////////////////////////////////////////////////////////////////////////////
///////////-----------------    DSGVO Module (start) ----------------///////////

     function getDSGVOConfirmation() {
         console.log('Fetching DSGVO Status From Customer');
         jQuery.ajax({
             url: '<?php echo $this->getUrl('customer/tools/getCustomerDSGVOConfirmed'); ?>',
             type: 'post',
             dataType: 'json',
             data: {
                 'form_key' : '<?php echo Mage::getSingleton('core/session')->getFormKey(); ?>',
             },
             success: function (data) {
                 console.log(data);
                 if (data.msg == 'okay') {
                     console.log('Customer has already confirmed DSGVO');
                     localStorage.setItem('DSGVO_Confirmed', "yes");
                     console.log('DSGVO Customer Layer Module Status: --- DSGVO Confirmed ---');
                     var txt = '<?php echo $this->__('Please Read And Confirm Our User Terms') ?>';
                     jQuery('#page_layer_text_block_content').html(txt);
                     getUserTermsConfirmation('dsgvo done');
                 } else if (data.msg == 'customer not logged in') {
                     console.log('Customer has NOT confirmed DSGVO (not logged in)');
                     localStorage.setItem('DSGVO_Confirmed', "no");
                     localStorage.setItem('customerNotLoggedIn', "1");
                 } else {
                     console.log('Customer has NOT confirmed DSGVO');
                     localStorage.setItem('customerNotLoggedIn', "0");
                     localStorage.setItem('DSGVO_Confirmed', "no");
                     console.log('DSGVO Customer Layer Module Status: --- DSGVO NOT Confirmed ---');
                     jQuery('#page_layer').show();
                 }
             },
             error: function (data) {
                 console.log('getDSGVOConfirmation : Some Network Error');
                 localStorage.setItem('DSGVO_Confirmed', "no");
                 jQuery('#page_layer').show();
                 console.log(data);
             }
         });
     }

     function getUserTermsConfirmation(status) {
         console.log('Fetching User Terms Status From Customer');
         jQuery.ajax({
             url: '<?php echo $this->getUrl('customer/tools/getCustomerUserTermsConfirmed'); ?>',
             type: 'post',
             dataType: 'json',
             data: {
                 'form_key' : '<?php echo Mage::getSingleton('core/session')->getFormKey(); ?>',
             },
             success: function (data) {
                 console.log(data);
                 if (data.msg == 'okay') {
                     console.log('Customer has already confirmed User Terms');
                     localStorage.setItem('User_Terms_Confirmed', "yes");
                     console.log('User Terms Customer Layer Module Status: --- User Terms Confirmed ---');
                 } else if (data.msg == 'customer not logged in') {
                     console.log('Customer has NOT confirmed User Terms (not logged in)');
                     localStorage.setItem('User_Terms_Confirmed', "no");
                     localStorage.setItem('customerNotLoggedIn', "1");
                 } else {
                     console.log('Customer has NOT confirmed User Terms');
                     localStorage.setItem('customerNotLoggedIn', "0");
                     localStorage.setItem('User_Terms_Confirmed', "no");
                     console.log('User Terms Customer Layer Module Status: --- User Terms NOT Confirmed ---');
                     if (status == 'dsgvo done') {
                        jQuery('#page_layer_dataprotection_confirm_checkbox_block').hide();
                        checkDataprotectionAlternate = true;
                     }
                     jQuery('#page_layer').show();
                 }
             },
             error: function (data) {
                 console.log("getUserTermsConfirmation : Some Network Error");
                 localStorage.setItem("User_Terms_Confirmed", "no");
                 jQuery('#page_layer').show();
                 console.log(data);
             }
         });
     }

     function getStatusIfCustomerLoggedIn () {
         if ( __suppressAjaxDispatcherCalls ) {
             return;
         }
         jQuery.ajax({
             url: '<?php echo $this->getUrl('customer/tools/getStatusIfCustomerLoggedIn'); ?>',
             type: 'post',
             dataType: 'json',
             data: {
                 'form_key' : '<?php echo Mage::getSingleton('core/session')->getFormKey(); ?>',
             },
             success: function (data) {
                 console.log(data);
                 if (data.msg.match(/okay/)) {
                     console.log('Customer is already Logged In');
                     var emailFromLoggedInUser = data.msg.replace('okay&', '');
                     console.log('Really Logged-In User = ' + emailFromLoggedInUser);
                     localStorage.setItem('customerLoggedInEmail', emailFromLoggedInUser);
                     localStorage.setItem('customerNotLoggedIn', "0");
<?php if (intval(Mage::getStoreConfig('schrack/dsgvo/activateLayerForLogin')) == 1) : ?>
                     console.log('DSGVO/AGB/User Terms Layer Module: ACTIVE');
                     console.log('DSGVO : Detected Customer Status: LOGGED IN');
                     getDSGVOConfirmation();
<?php else: ?>
                     console.log('DSGVO/AGB/User Terms Layer Module: --- NOT ACTIVE ---');
<?php endif; ?>
                 } else {
                     console.log('Customer --- NOT Logged In ---');
                     localStorage.setItem('customerNotLoggedIn', "1");
                     localStorage.setItem('DSGVO_Confirmed', "no");
                     localStorage.setItem('User_Terms_Confirmed', "no");
                 }
             },
             error: function (data) {
                 console.log('getStatusIfCustomerLoggedIn : Some Network Error');
                 console.log(data);
             }
         });
     }

     var customerIsLoggedIn = 0;
     getStatusIfCustomerLoggedIn();

     function confirmDSGVOLayer() {
         console.log('AJAX Call for save confirmation');
         jQuery.ajax({
             url: '<?php echo $this->getUrl('customer/tools/setCustomerDSGVOConfirmed'); ?>',
             type: 'post',
             dataType: 'json',
             data: {
                 'form_key' : '<?php echo Mage::getSingleton('core/session')->getFormKey(); ?>',
             },
             success: function (data) {
                 if (data.msg == 'okay') {
                     console.log('Customer set already confirmed DSGVO');
                     localStorage.setItem('DSGVO_Confirmed', "yes");
                     jQuery('#page_layer').hide();
                     confirmUserTerms();
                 }
                 console.log(data);
             },
             error: function (data) {
                 console.log(data);
             }
         });
     }

     function confirmUserTerms() {
         console.log('AJAX Call for save confirmation of user terms');
         jQuery.ajax({
             url: '<?php echo $this->getUrl('customer/tools/setCustomerUserTermsConfirmed'); ?>',
             type: 'post',
             dataType: 'json',
             data: {
                 'form_key' : '<?php echo Mage::getSingleton('core/session')->getFormKey(); ?>',
             },
             success: function (data) {
                 if (data.msg == 'okay') {
                     console.log('Customer set already confirmed User Terms');
                     localStorage.setItem('DSGVO_Confirmed', "yes");
                     jQuery('#page_layer').hide();
                 }
                 console.log(data);
             },
             error: function (data) {
                 console.log(data);
             }
         });
     }

     // Wenn DSGVO nicht bestätigt: AJAX Call einrichten
     jQuery('#page_layer_confirm_button').on('click', function () {
         var checkAGB            = false;
         var checkDataprotection = false;
         var checkDSGVO          = false;
         var checkUserTerms      = false;

         <?php if (intval(Mage::getStoreConfig('schrack/dsgvo/activateRegistrationCheckboxAGB')) == 1) : ?>
             if (jQuery('#page_layer_agb_confirm_checkbox').prop('checked') === true) {
                 // Checkbox AGB checked + set classes:
                 jQuery('#page_layer_agb_confirm_checkbox_block').addClass('pageLayerAgbConfirmCheckboxConfirmed');
                 jQuery('#page_layer_agb_confirm_checkbox_block').removeClass('pageLayerAgbConfirmCheckboxWarning');
                 checkAGB = true;
             } else {
                 // Set warnings (checkbox AGB must be set):
                 jQuery('#page_layer_agb_confirm_checkbox_block').removeClass('pageLayerAgbConfirmCheckboxConfirmed');
                 jQuery('#page_layer_agb_confirm_checkbox_block').removeClass('pageLayerAgbConfirmCheckbox');
                 jQuery('#page_layer_agb_confirm_checkbox_block').addClass('pageLayerAgbConfirmCheckboxWarning');
             }
         <?php endif; ?>

         if (jQuery('#page_layer_dataprotection_confirm_checkbox').prop('checked') === true || checkDataprotectionAlternate === true) {
             // Checkbox Dataprotection checked + set classes:
             jQuery('#page_layer_dataprotection_confirm_checkbox_block').addClass('pageLayerDataprotectionConfirmCheckboxConfirmed');
             jQuery('#page_layer_dataprotection_confirm_checkbox_block').removeClass('pageLayerDataprotectionConfirmCheckboxWarning');
             checkDataprotection = true;
         } else {
             // Set warnings (checkbox Dataprotection must be set)::
             jQuery('#page_layer_dataprotection_confirm_checkbox_block').removeClass('pageLayerDataprotectionConfirmCheckboxConfirmed');
             jQuery('#page_layer_dataprotection_confirm_checkbox_block').removeClass('pageLayerDataprotectionConfirmCheckbox');
             jQuery('#page_layer_dataprotection_confirm_checkbox_block').addClass('pageLayerDataprotectionConfirmCheckboxWarning');
         }

         <?php if (intval(Mage::getStoreConfig('schrack/dsgvo/activateRegistrationCheckboxDSGVO')) == 1) : ?>
             if (jQuery('#page_layer_dsgvo_confirm_checkbox').prop('checked') === true) {
                 // Checkbox DSGVO checked + set classes:
                 jQuery('#page_layer_dsgvo_confirm_checkbox_block').addClass('pageLayerDSGVOConfirmCheckboxConfirmed');
                 jQuery('#page_layer_dsgvo_confirm_checkbox_block').removeClass('pageLayerDSGVOConfirmCheckboxWarning');
                 checkDSGVO = true;
             } else {
                 // Set warnings (checkbox DSGVO must be set)::
                 jQuery('#page_layer_dsgvo_confirm_checkbox_block').removeClass('pageLayerDSGVOConfirmCheckboxConfirmed');
                 jQuery('#page_layer_dsgvo_confirm_checkbox_block').removeClass('pageLayerDSGVOConfirmCheckbox');
                 jQuery('#page_layer_dsgvo_confirm_checkbox_block').addClass('pageLayerDSGVOConfirmCheckboxWarning');
             }
         <?php endif; ?>

         <?php if (intval(Mage::getStoreConfig('schrack/dsgvo/activateRegistrationCheckboxUserTerms')) == 1) : ?>
             if (jQuery('#page_layer_user_terms_confirm_checkbox').prop('checked') === true) {
                 // Checkbox User Terms checked + set classes:
                 jQuery('#page_layer_user_terms_confirm_checkbox_block').addClass('pageLayerUserTermsConfirmCheckboxConfirmed');
                 jQuery('#page_layer_user_terms_confirm_checkbox_block').removeClass('pageLayerUserTermsConfirmCheckboxWarning');
                 checkUserTerms = true;
             } else {
                 // Set warnings (checkbox User Terms must be set)::
                 jQuery('#page_layer_user_terms_confirm_checkbox_block').removeClass('pageLayerUserTermsConfirmCheckboxConfirmed');
                 jQuery('#page_layer_user_terms_confirm_checkbox_block').removeClass('pageLayerUserTermsConfirmCheckbox');
                 jQuery('#page_layer_user_terms_confirm_checkbox_block').addClass('pageLayerUserTermsConfirmCheckboxWarning');
             }
         <?php endif; ?>

         // DSGVO + AGB + User Terms Confirmation required (dataprotection always required):
         <?php if (intval(Mage::getStoreConfig('schrack/dsgvo/activateRegistrationCheckboxDSGVO')) == 1
                && intval(Mage::getStoreConfig('schrack/dsgvo/activateRegistrationCheckboxUserTerms')) == 1
                && intval(Mage::getStoreConfig('schrack/dsgvo/activateRegistrationCheckboxAGB')) == 1) : ?>
             if (jQuery('#page_layer_text_block_content').html() != ''
                 && jQuery('#page_layer_text_block_content').html() != 'DSGVO Schrack Confirm Text') {
                 if (checkDataprotection && checkAGB  && checkDSGVO && checkUserTerms) {
                     confirmDSGVOLayer();
                 }
             }
         // DSGVO + AGB Confirmation required (dataprotection always required):
         <?php elseif (intval(Mage::getStoreConfig('schrack/dsgvo/activateRegistrationCheckboxDSGVO')) == 1
                   && intval(Mage::getStoreConfig('schrack/dsgvo/activateRegistrationCheckboxUserTerms')) == 0
                   && intval(Mage::getStoreConfig('schrack/dsgvo/activateRegistrationCheckboxAGB')) == 1) : ?>
             if (jQuery('#page_layer_text_block_content').html() != ''
                 && jQuery('#page_layer_text_block_content').html() != 'DSGVO Schrack Confirm Text') {
                 if (checkDataprotection && checkAGB  && checkDSGVO) {
                     confirmDSGVOLayer();
                 }
             }
         // Only AGB Confirmation required (dataprotection always required):
         <?php elseif (intval(Mage::getStoreConfig('schrack/dsgvo/activateRegistrationCheckboxAGB')) == 1
                && intval(Mage::getStoreConfig('schrack/dsgvo/activateRegistrationCheckboxDSGVO')) == 0
                && intval(Mage::getStoreConfig('schrack/dsgvo/activateRegistrationCheckboxUserTerms')) == 0) : ?>
             if (checkDataprotection && checkAGB) {
                 confirmDSGVOLayer();
             }
         // Only DSGVO Confirmation required (dataprotection always required):
         <?php elseif (intval(Mage::getStoreConfig('schrack/dsgvo/activateRegistrationCheckboxDSGVO')) == 1
             && intval(Mage::getStoreConfig('schrack/dsgvo/activateRegistrationCheckboxUserTerms')) == 0
             && intval(Mage::getStoreConfig('schrack/dsgvo/activateRegistrationCheckboxAGB')) == 0) : ?>
             if (jQuery('#page_layer_text_block_content').html() != ''
                 && jQuery('#page_layer_text_block_content').html() != 'DSGVO Schrack Confirm Text') {
                     if (checkDataprotection && checkDSGVO) {
                         confirmDSGVOLayer();
                     }
             }
         // Onl User Terms Confirmation required (dataprotection always required):
         <?php elseif (intval(Mage::getStoreConfig('schrack/dsgvo/activateRegistrationCheckboxUserTerms')) == 1
            && intval(Mage::getStoreConfig('schrack/dsgvo/activateRegistrationCheckboxDSGVO')) == 0
            && intval(Mage::getStoreConfig('schrack/dsgvo/activateRegistrationCheckboxAGB')) == 0) : ?>
         if (jQuery('#page_layer_text_block_content').html() != ''
             && jQuery('#page_layer_text_block_content').html() != 'User Terms Schrack Confirm Text') {
             if (checkDataprotection && checkUserTerms) {
                 confirmDSGVOLayer();
             }
         }
         // Only Dataprotection Confirmation required (minimum requirement):
         <?php else: ?>
            <?php if (intval(Mage::getStoreConfig('schrack/dsgvo/activateRegistrationCheckboxDataProtection')) == 1) : ?>
                 if (checkDataprotection) {
                     confirmDSGVOLayer();
                 }
            <?php endif; ?>
         <?php endif; ?>
     });

     jQuery('#page_layer_cancel_button').on('click', function () {
         jQuery('#page_layer_confirm_button').hide();
         jQuery('#page_layer_cancel_button').hide();
         jQuery('#page_layer_cancel_button_warning_text').show();
         jQuery('#page_layer_cancel_warning_button_yes').show();
         jQuery('#page_layer_cancel_warning_button_no').show();
         jQuery('#page_layer_text_block_content').css('opacity', '0.1');
         jQuery('#page_layer_checkbox_block').css('opacity', '0.1');
     });

     jQuery('#page_layer_cancel_warning_button_yes').on('click', function () {
         window.location = '<?php echo $this->getUrl('customer/account/logout'); ?>';
     });

     jQuery('#page_layer_cancel_warning_button_no').on('click', function () {
         jQuery('#page_layer_confirm_button').show();
         jQuery('#page_layer_cancel_button').show();
         jQuery('#page_layer_cancel_button_warning_text').hide();
         jQuery('#page_layer_cancel_warning_button_yes').hide();
         jQuery('#page_layer_cancel_warning_button_no').hide();
         jQuery('#page_layer_text_block_content').css('opacity', '1');
         jQuery('#page_layer_checkbox_block').css('opacity', '1');
     });

///////////////-----------------  DSGVO Module (end) ----------------///////////
////////////////////////////////////////////////////////////////////////////////


	 addDefaultText('search', '<?php echo $this->__('Search')?>');
     grayDefaultText('search');
     jQuery('#search').change(function() { grayDefaultText('search'); });
     localStorage.removeItem('checkoutShippingStep');
     localStorage.openedQuickAddPanel = 0;
     if (localStorage.flagForHeader && localStorage.flagForHeader == 1) {
         localStorage.openedQuickAddPanel = 1;
         localStorage.flagForHeader = 0;
     }

<?php if (!stristr($currentUrl, 'checkout/onepage/')): ?>

     // Remove localstorage-data, if not required any more (only useful in checkout process):
     if (localStorage.newCheckoutProcessInitialTime || localStorage.newCheckoutProcessLastUpdateTime) {
        // Delete all new checkout relevant data:
         localStorage.removeItem('newCheckoutProcessCurrentRole');
         localStorage.removeItem('newCheckoutProcessCurrentStep');
         localStorage.removeItem('newCheckoutProcessHumanReadableLastUpdateTime');
         localStorage.removeItem('newCheckoutProcessInitialHumanReadableTime');
         localStorage.removeItem('newCheckoutProcessInitialTime');
         localStorage.removeItem('newCheckoutProcessLastUpdateTime');
         localStorage.removeItem('newCheckoutProcessSpecialAction');
         localStorage.removeItem('newCheckoutProspectRole');
         localStorage.removeItem('newCheckoutRunningProcess');
         localStorage.removeItem('newCheckoutHomepage');
         localStorage.removeItem('newCheckoutProcessCity');
         localStorage.removeItem('newCheckoutProcessCompanyRegistrationNumber');
         localStorage.removeItem('newCheckoutProcessCountryId');
         localStorage.removeItem('newCheckoutProcessEmail');
         localStorage.removeItem('newCheckoutProcessGender');
         localStorage.removeItem('newCheckoutProcessName1');
         localStorage.removeItem('newCheckoutProcessName2');
         localStorage.removeItem('newCheckoutProcessName3');
         localStorage.removeItem('newCheckoutProcessPersonFirstname');
         localStorage.removeItem('newCheckoutProcessPersonLastname');
         localStorage.removeItem('newCheckoutProcessPostcode');
         localStorage.removeItem('newCheckoutProcessRegionId');
         localStorage.removeItem('newCheckoutProcessStreet1');
         localStorage.removeItem('newCheckoutProcessTelephone');
         localStorage.removeItem('newCheckoutProcessVATIdentificationNumber');
         localStorage.removeItem('newCheckoutHomepage');
         localStorage.removeItem('newCheckoutNewsletter');
         localStorage.removeItem('newCheckoutProcessTelephoneCompany');
         localStorage.removeItem('newCheckoutProcessFax');
         localStorage.removeItem('newCheckoutLocalVAT');
     }
<?php endif; ?>

    function fetchMegaMenu() {
        jQuery.ajax({
            url: '<?php echo Mage::helper('schrackcore/url')->getUrlWithCurrentProtocol('sd/menu/getMegaMenu'); ?>',
            type: 'post',
            data: {
                'form_key' : '<?php echo Mage::getSingleton('core/session')->getFormKey(); ?>',
                'responsive' : 'force_update', // Default = 'force_update'
            },
            success: function (data) {
                var datax = JSON.parse(data);
                if (datax && datax.responsive) {
                    var desktopWindow = jQuery(window);
                    jQuery('#mainNav').html(datax.responsive);
                }

                console.log('>>> Filling localstorage from AJAX data (header.phtml)');

                if (data && datax.responsive) {
                    localStorage.megamenuContentResponsive = datax.responsive;
                    console.log('>>> localstorage.megamenuContentResponsive success (header.phtml)');
                } else {
                    console.log('>>> data --> empty content for RESPONSIVE menu (header.phtml)');
                }
            },
            error: function (data) {
                console.log(data);
                console.log('Mega Menu not successfully fetched');
            }
        });
    }

    //set variable to request data from ajax dispacher
    if (getParameterByName('excludeAjaxCall') == null) {	// Added by Nagarro for exclude AJAX call for performance testing
        if (typeof isTypo3Page === 'undefined' || !isTypo3Page) {
            if (typeof(loadCachedMegaMenu) == 'function') {
                if (loadCachedMegaMenu() == false) {
                    // dataArray.getMegaMenu = '';
                    console.log('Fetching Mega Menu');
                    fetchMegaMenu();
                }
            } else {
                // dataArray.getMegaMenu = '';
                console.log('etching Mega Menu Alternat');
                fetchMegaMenu();
            }
        }

        if (typeof(loadCachedSearchBarCategories) == 'function') {
            if (loadCachedSearchBarCategories() == false) {
                dataArray.getSearchBarCategories = '';
            }
        } else {
            dataArray.getSearchBarCategories = '';
        }

        dataArray.getAdvisorData = '';
        dataArray.getCustomerInformation = '';
        dataArray.getCartItemCount = '';
        dataArray.getAllPartslists = '';
    }

    if (localStorage.flagPartlistCsvUploadPointer) {
        // AJAX Call for get items to track, from currently CSV-Uploaded Document:
        jQuery.ajax({
             url: '<?php echo Mage::getUrl("sd/Csv/getArticlesFromCsvPartlisUpload"); ?>',
             type: 'post',
             data: {
                 'form_key' : '<?php echo Mage::getSingleton('core/session')->getFormKey(); ?>',
                 'uuid' : localStorage.flagPartlistCsvUploadPointer
             },
             success: function (data) {
                 var datax = JSON.parse(data);
                 if (datax.result) {
                     localStorage.removeItem("flagPartlistCsvUploadPointer");
                     var skulist = datax.result;
                     skulist.forEach(trackCsvUploadedArticles);
                     function trackCsvUploadedArticles(sku) {
                         if (dataLayer) {
                             dataLayer.push({
                                 'event' : 'partlistModification',
                                 'eventAction' : 'Add',
                                 'eventLabel' : 'csv upload',
                                 'partlistModificationSource' : 'Standard',
                                 'productSku' : sku
                             });
                         }
                     }

                     if (dataLayer) {
                         dataLayer.push({
                             'event' : 'partlistCSVFile',
                             'eventAction' : 'Upload CSV',
                             'eventLabel' : '-'
                         });
                     }
                 }
             },
             error: function (data) {
             }
         });
     }

    if (localStorage.getItem("IDS_Transfer_Done") !== null && localStorage.getItem('IDS_Transfer_Done') == 'true') {
        localStorage.setItem('IDS_Transfer_Done', '');
        window.location = '<?php echo Mage::helper('schrackcore/url')->getUrlWithCurrentProtocol('checkout/cart'); ?>';
    }


<?php if (intval(Mage::getStoreConfig('schrack/shop/schrack_poll_active')) == 1) : ?>
    // Poll Logic:
    if (localStorage.getItem("lastViewedPoll") === null) {
        localStorage.setItem('lastViewedPoll', '');
    }
    if (localStorage.getItem("nextViewPoll") === null) {
        localStorage.setItem('nextViewPoll', '');
    }
    if (localStorage.getItem("completePollHTML") === null) {
        localStorage.setItem('completePollHTML', '');
    }

    var currentTimeStamp = Math.floor(Date.now() / 1000);
    if (localStorage.lastViewedPoll == '') {
        if (localStorage.itemCustomerNotLoggedIn != 1) {
            localStorage.lastViewedPoll = currentTimeStamp;
        }
    }

    if (localStorage.getItem("nextViewPoll" == '')) {
        // AJAX -> Fetch Questions and show popup:
        fetchPollData();
    } else {
        if (localStorage.getItem("nextViewPoll") > currentTimeStamp) {
            // Do Nothing!
            console_poll('Do Nothing');
        } else {
            // else fetch data
            fetchPollData();
        }
    }

    jQuery('#close_poll_popup_left_lower_corner').on('click', function() {
        var formdata = {};
        var key;
        jQuery('.poll_radio_answer').each( function(index) {
            if (jQuery(this).is(":checked")) {
                key = jQuery(this).attr("name");
                formdata[key] = jQuery(this).attr("value");
            }
        });
        jQuery('.poll_check').each( function(index) {
            if (jQuery(this).is(":checked")) {
                key = jQuery(this).attr("name");
                formdata[key] = jQuery(this).attr("value");
            }
        });
        jQuery('.poll_answer_text').each( function(index) {
            key = jQuery(this).attr("id");
            formdata[key] = jQuery(this).val();
        });
        jQuery('.poll_answer_textarea').each( function(index) {
            key = jQuery(this).attr("id");
            formdata[key] = jQuery(this).val();
        });

        jQuery.ajax({
            'url': '<?php echo Mage::getUrl("sd/Poll/setPollingData"); ?>',
            'dataType': 'json',
            'type': 'POST',
            'data': formdata,
            success: function (data) {
                // TODO
            },
            error: function (data) {
                // TODO
            }
        });
        jQuery('#pollpopup').hide();
        jQuery('.modal-backdrop').remove();
    });

    function showPollpopup() {
        if (localStorage.completePollHTML == '') {
            fetchPollData();
        } else {
            // Show popup poll window here:
            jQuery('#pollpopup_content').html(localStorage.completePollHTML);
            jQuery('#pollpopup').modal();
        }
    }


    function fetchPollData() {
        console_poll('fetchPollData()');
        if (localStorage.itemCustomerNotLoggedIn == 1) {
            // TODO
        } else {
            console_poll('Fetching Poll Data (Customer is already logged in)');
            jQuery.ajax({
                'url': '<?php echo Mage::getUrl("sd/Poll/getPollingInterval"); ?>',
                'type': 'POST',
                success: function (data) {
                    var datax = JSON.parse(data);
                    if (datax) {
                        if (datax.next_view && datax.next_view != 'undefined') {
                            localStorage.nextViewPoll = datax.next_view;
                            if (datax.next_view == 'none') {
                                localStorage.nextViewPoll = '';
                            }
                            if (datax.html_base64) {
                                // Decode base64 encoded HTML poll content:
                                localStorage.completePollHTML = b64DecodeUnicode(datax.html_base64);
                            }
                            if (datax.show_now == 'yes') {
                                showPollpopup();
                            }
                        }
                        if (datax.last_viewed && datax.last_viewed != 'undefined') {
                            if (datax.last_viewed == 'never_viewed_before') {
                                console_poll('Never Viewed Before');
                            } else {
                                localStorage.lastViewedPoll = datax.last_viewed;
                            }
                        }
                    }
                },
                error: function (data) {
                    // TODO
                }
            });
        }
    }

    function console_poll(message) {
        console.log("%c POLL %c " + message, "color: white; background: #000000;", "");
    }

    function b64DecodeUnicode(str) {
        // Going backwards: from bytestream, to percent-encoding, to original string.
        return decodeURIComponent(atob(str).split('').map(function(c) {
            return '%' + ('00' + c.charCodeAt(0).toString(16)).slice(-2);
        }).join(''));
    }

<?php endif;  ?>

});

    function getSkinUrl() { return '<?php echo $this->getSkinUrl()?>'; }
    var okButtonName = '<?php echo $this->__('Ok')?>';
    var cancelButtonName = '<?php echo $this->__('Cancel')?>';
    var pleaseSelectSomeRowsFirstText = '<?php echo $this->__('Please select an entry from the list, by selecting at least one checkbox first.')?>';


    var globalTRACKING_ENABLED             = '<?php echo $trackingEnabled; ?>';
    var globalCURRENCY_CODE                 = '<?php echo Mage::app()->getStore()->getCurrentCurrencyCode() ?>';
    var globalTYPO_URL                     = '<?php echo Mage::getStoreConfig('schrack/typo3/typo3url') ?>';
    var globalSHOP_CATEGORY_AJAX_URL       = '<?php echo Mage::getUrl("catalog/product/getCategoryId4googleTagManager"); ?>';
    var globalFORM_KEY                     = '<?php echo Mage::getSingleton('core/session')->getFormKey(); ?>';
    var globalCRM_USER_ID                  = '<?php echo $crmUserId; ?>';
    var globalCUSTOMER_TYPE                = '<?php echo $customerTypeGTM; ?>';
    var globalACCOUNT_CRM_ID               = '<?php echo $accountCrmId; ?>';
    var globalADD_TO_CART_BUTTON_IMAGE_SRC = '<?php echo $cartButtonImagePath; ?>';
    var globalSEARCH_RESULT_VIEW_MODE      = 'gridView';
    var globalFRESH_LOAD                   = true;
    var globalAJAX_LOADER_GIF_PATH         = '<?php echo $ajaxLoaderGifPath; ?>';
    console.log('Status 1 -> ' + globalFRESH_LOAD);

//]]>
</script>
<!-- app/design/frontend/schrack/schrackresponsive/template/page/html/header.phtml (end) -->
