<!-- app/design/frontend/schrack/schrackresponsive/template/customer/account/dashboard/persons.phtml (start) -->
<?php if ($this->getCustomer()->isAllowed('accessRight', 'edit')) : ?>
    <div class="userAccountCont">
        <div class="row">
            <div class="col-xs-12 col-sm-6">
                <h2><?php echo $this->__('User Accounts'); ?>(<?php echo $this->getVisibleContacts()->count() ?>)</h2>
            </div>
            <div class="col-xs-12 col-sm-6 hidden-xs text-right"><h2 class="paddingR15"><a class="blue" href="<?php echo Mage::getUrl('customer/accountadministration'); ?>" class=""><?php echo $this->__('Manage User Accounts'); ?></a></h2></div>
        </div>

        <div class="contentArea">
            <div class="row">
                <?php
                $i = 0;
                foreach ($this->getVisibleContacts() as $_customer) :
                    $_customer->load($_customer->getId());
                    $i++;
                    ?>
                    <div class="col-xs-12 col-sm-6">
                        <div class="box">
                            <div class="row">
                                <div class="col-md-3"><?php echo $this->__('Username'); ?>:</div>
                                <div class="col-md-9"><strong><?php echo $_customer->getName(); ?></strong></div>
                            </div>
							<?php if ($_customer->isInactiveContact()) { ?>
							<div class="row">
                                <div class="col-md-3"><?php echo $this->__('Status'); ?>:</div>
                                <div class="col-md-9"><strong>
                                        <?php
                                        //echo $_customer->getStatus();
                                        if ($_customer->isInactiveContact()) {
                                            echo $this->__('Inactive');
                                        } else {
                                            echo $this->__('Active');
                                        }
                                        ?>
                                    </strong></div>
                            </div> 
							<?php } ?>
                            <div class="row">
                                <div class="col-md-3"><?php if (!$_customer->isInactiveContact()) { echo $this->__('Email'); ?>:<?php } ?></div>
                                <div class="col-md-9"><strong><?php if (!$_customer->isInactiveContact()) { echo $_customer->getEmail(); } ?></strong></div>
                            </div>
                            <div class="row">
                                <div class="col-md-3"><?php if (!$_customer->isInactiveContact()) { echo $this->__('Role'); ?>:<?php } ?></div>
                                <div class="col-md-9"><strong><?php if (!$_customer->isInactiveContact()) { echo $_customer->getSchrackAclRole(); } ?></strong></div>
                            </div>
							<?php if (!$_customer->isInactiveContact()) { ?>
                            <div class="row">
                                <div class="col-md-3"><?php echo $this->__('Status'); ?>:</div>
                                <div class="col-md-9"><strong>
                                        <?php
                                        //echo $_customer->getStatus();
                                        if ($_customer->isInactiveContact()) {
                                            echo $this->__('Inactive');
                                        } else {
                                            echo $this->__('Active');
                                        }
                                        ?>
                                    </strong></div>
                            </div>  
							<?php } ?>
                        </div>
                    </div>
                    <?php
                    if ($i == 2)
                        break;
                endforeach;
                ?>
            </div>
        </div> 
    </div>
<?php endif ?>
<!-- app/design/frontend/schrack/schrackresponsive/template/customer/account/dashboard/persons.phtml (end) -->