<?php /* @var $this Mage_Wishlist_Block_Customer_Sidebar */ ?>
<?php if ($this->helper('wishlist')->isAllow()) : ?>
	<div class="block block-wishlist">
		<h2><span><?php echo $this->__('My Wishlist <small>(%d)</small>',
			$this->helper('wishlist')->getItemCount()) ?></span></h2>
		<div class="block-content">
			<p class="block-subtitle"><?php echo $this->__('Last Added Items') ?></p>
			<?php if ($this->hasWishlistItems()): ?>
				<ol class="mini-products-list" id="wishlist-sidebar">
					<?php foreach ($this->getWishlistItems() as $_item): ?>
						<li class="item">
							<?php
							$_product = $_item->getProduct();
							$_categories = $_item->getCategoryIds();
							$_category = Mage::getModel('catalog/category')->load($_categories[0]);
							$url = $this->getUrl(dirname($_category->getUrlPath()).'/'.basename($_category->getUrlPath(), '.html')).basename($_item->getProductUrl());

							?>
							<a href="<?php echo $url ?>" title="<?php echo $this->htmlEscape($_product->getName()) ?>" class="product-image"><img src="<?php echo $this->helper('catalog/image')->init($_product,
																																			  'thumbnail')->resize(32, 32); ?>" width="32" height="32" alt="<?php echo $this->htmlEscape($_product->getName()) ?>" /></a>
							<div class="product-details">
								<p class="product-name-qty-price"><a href="<?php echo $url ?>"><?php echo $this->htmlEscape($_product->getName()) ?></a><br />
									<?php echo $this->getPriceHtml($_product,
											false, '-wishlist') ?></p>
								<?php if (Mage::getSingleton('customer/session')->getCustomer()->isAllowed('customerOrder',
												'order')): ?>
									<?php if ($_product->isSaleable()): ?>
										<a href="<?php echo $this->getAddToCartItemUrl($_item) ?>" class="link-cart"><?php echo $this->__('Add to Cart') ?></a><br />
				<?php endif; ?>
			<?php endif; ?>
								<a href="<?php echo $this->getItemRemoveUrl($_item) ?>" title="<?php echo $this->__('Remove This Item') ?>" onclick="return confirm('<?php echo $this->__('Are you sure you would like to remove this item from the wishlist?') ?>');" class="btn-remove"><?php echo $this->__('Remove This Item') ?></a>
							</div>
						</li>
		<?php endforeach; ?>
				</ol>
				<script type="text/javascript">//<![CDATA[
				    decorateList('wishlist-sidebar');
				//]]></script>
				<div class="actions">
					<a href="<?php echo $this->helper('wishlist')->getListUrl() ?>"><?php echo $this->__('Go to Wishlist') ?></a>
				</div>
			<?php else: ?>
				<p class="empty"><?php echo $this->__('You have no items in your wishlist.') ?></p>
	<?php endif ?>
		</div>
	</div>
	<?php

 endif ?>
