<!-- default/template/customer/widget/addressname.phtml (start) -->

<?php
    /* @var $this Schracklive_SchrackCustomer_Block_Widget_Addressname */
    /**
    USAGE:

    <?php echo $this->getLayout()->createBlock('customer/widget_addressname')
       ->setObject($this->getAddress())
       ->toHtml() ?>
    */

	if ( $this->getRequest()->getActionName() == 'new' ) {
        $prefix = $firstname = $middlename = $lastname = '';
    } else {

        $customer = $this->getObject();

        if ( is_object($customer) && !$customer->getId() > 0 ) {
            $customer = Mage::getSingleton('customer/session')->getCustomer();
        }
        if ( !is_object($customer) ) {
            $customer = Mage::getSingleton('customer/session')->getCustomer();
        }

        $prefix = $customer->getPrefix();
        $firstname = $customer->getFirstname();
        $middlename = $customer->getMiddlename();
        $lastname = $customer->getLastname();
    }


?>
<table class="<?php echo $this->getContainerClassName()?>">
    <tr style="height: 10px;">
        <?php if ($this->showPrefix()): ?>
            <td>
                <label for="<?php echo $this->getFieldId('prefix')?>"<?php if ($this->isPrefixRequired()) echo ' class="required"' ?>>
                    <?php echo $this->__('Prefix') ?><?php if ($this->isPrefixRequired()) echo '<em> *</em>' ?>
                </label>
            </td>
        <?php endif; ?>
        <td>
            <label style="margin-bottom: 7px !important;" for="<?php echo $this->getFieldId('firstname')?>"><?php echo $this->__('First Name') ?></label>
        </td>
        <?php if ($this->showMiddlename()): ?>
            <td>
                <label for="<?php echo $this->getFieldId('middlename')?>"><?php echo $this->__('M.I.') ?></label>
            </td>
        <?php endif; ?>
        <td>
            <label for="<?php echo $this->getFieldId('lastname')?>" class="required"><?php echo $this->__('Last Name') ?><em> *</em>
            </label>
        </td>
        <?php if ($this->showSuffix()): ?>
        <td>
            <label for="<?php echo $this->getFieldId('suffix')?>"<?php if ($this->isSuffixRequired()) echo ' class="required"' ?>>
                <?php echo $this->__('Suffix') ?><?php if ($this->isSuffixRequired()) echo '<em> *</em>' ?>
            </label>
        </td>
        <?php endif; ?>
    </tr>
    <tr style="height: 53px;">
        <?php if ($this->showPrefix()): ?>
            <td>
                <?php if ($this->getPrefixOptions()===false): ?>
                    <input type="text" id="<?php echo $this->getFieldId('prefix')?>" name="<?php echo $this->getFieldName('prefix')?>" value="<?php echo $this->htmlEscape($this->getObject()->getPrefix()) ?>" title="<?php echo $this->__('Prefix') ?>" class="input-text<?php if ($this->isPrefixRequired()):?> required-entry<?php endif; ?>" <?php echo $this->getFieldParams() ?> />
                <?php else: ?>
                    <select id="<?php echo $this->getFieldId('prefix')?>" name="<?php echo $this->getFieldName('prefix')?>" title="<?php echo $this->__('Prefix') ?>"<?php if ($this->isPrefixRequired()):?> class="required-entry"<?php endif; ?> <?php echo $this->getFieldParams() ?>>
                    <?php foreach ($this->getPrefixOptions() as $_option): ?>
                        <option value="<?php echo $_option?>"<?php if ($this->getObject()->getPrefix()==$_option):?> selected="selected"<?php endif; ?>><?php echo $this->__($_option)?></option>
                    <?php endforeach ?>
                    </select>
                <?php endif; ?>
            </td>
        <?php endif; ?>
        <td>
            <input type="text" id="<?php echo $this->getFieldId('firstname')?>" name="<?php echo $this->getFieldName('firstname')?>" value="<?php echo $this->escapeHtml($firstname); ?>" title="<?php echo $this->__('First Name') ?>" class="input-text validation-passed" <?php echo $this->getFieldParams() ?> maxlength="30" />
        </td>
        <?php if ($this->showMiddlename()): ?>
            <td>
                <input type="text" id="<?php echo $this->getFieldId('middlename')?>" name="<?php echo $this->getFieldName('middlename')?>" value="<?php echo $this->escapeHtml($middlename); ?>" title="<?php echo $this->__('M.I.') ?>" class="input-text" <?php echo $this->getFieldParams() ?> />
            </td>
        <?php endif; ?>
        <td style="line-height: 0em !important;">
            <input type="text" style="margin-bottom: 11px; margin-top: 10px;" id="<?php echo $this->getFieldId('lastname')?>" name="<?php echo $this->getFieldName('lastname')?>" value="<?php echo $this->escapeHtml($lastname); ?>" title="<?php echo $this->__('Last Name') ?>" class="input-text required-entry" <?php echo $this->getFieldParams() ?> maxlength="30"/>
        </td>
        <?php if ($this->showSuffix()): ?>
            <td>
                <?php if ($this->getSuffixOptions()===false): ?>
                    <input type="text" id="<?php echo $this->getFieldId('suffix')?>" name="<?php echo $this->getFieldName('suffix')?>" value="<?php echo $this->htmlEscape($this->getObject()->getSuffix()) ?>" title="<?php echo $this->__('Suffix') ?>" class="input-text<?php if ($this->isSuffixRequired()):?> required-entry<?php endif; ?>" <?php echo $this->getFieldParams() ?> />
                <?php else: ?>
                    <select id="<?php echo $this->getFieldId('suffix')?>" name="<?php echo $this->getFieldName('suffix')?>" title="<?php echo $this->__('Suffix') ?>"<?php if ($this->isSuffixRequired()):?> class="required-entry"<?php endif; ?> <?php echo $this->getFieldParams() ?>>
                    <?php foreach ($this->getSuffixOptions() as $_option): ?>
                        <option value="<?php echo $_option?>"<?php if ($this->getObject()->getSuffix()==$_option):?> selected="selected"<?php endif; ?>><?php echo $this->__($_option)?></option>
                    <?php endforeach ?>
                    </select>
                <?php endif; ?>
            </td>
        <?php endif; ?>
    </tr>
</table>

<!-- default/template/customer/widget/addressname.phtml (end) -->