<!-- app/design/frontend/schrack/default/template/customer/widget/gender.phtml (start) -->
<label for="<?php echo $this->getFieldId('gender')?>"<?php if ($this->isRequired()) echo ' class="required"' ?>><?php echo $this->__('Gender') ?><?php if ($this->isRequired()) echo '<em> *</em>' ?></label>
<div class="input-box" style="width: 221px;">
    <select style="width: 150px !important; margin-top: 10px; margin-left: 4px;" id="<?php echo $this->getFieldId('gender')?>" name="<?php echo $this->getFieldName('gender')?>" title="<?php echo $this->__('Gender') ?>"<?php if ($this->isRequired()):?> class="validate-select"<?php endif; ?> <?php echo $this->getFieldParams() ?>>
        <?php $options = Mage::getResourceSingleton('customer/customer')->getAttribute('gender')->getSource()->getAllOptions();?>
        <?php $value = $this->getGender();?>
        <?php foreach ($options as $option):?>
            <!-- <?php echo "option['label'] = " . $option['label'] ?> -->
            <option value="<?php echo $option['value'] ?>"<?php if ($option['value'] == $value) echo ' selected="selected"' ?>><?php echo $this->__($option['label']); ?></option>
        <?php endforeach;?>
    </select>
</div>
<!-- app/design/frontend/schrack/default/template/customer/widget/gender.phtml (end) -->