<?php
/* @var $this Schracklive_SchrackCustomer_Block_Account_Dashboard_Hello */
?>
<div class="welcome-msg">
    <p class="hello"><strong><?php echo $this->__('Welcome, %s!', $this->htmlEscape($this->getCustomerFullName())) ?></strong></p>
    <p><?php echo $this->__('From your My Account Dashboard you have the ability to view a snapshot of your recent account activity and update your account information. Select a link below to view or edit information.') ?></p>
</div>
