<?php
/* @var this Mage_Checkout_Block_Onepage_Payment */
?>
<script type="text/javascript">
var payment = new Payment('co-payment-form', '<?php echo $this->getUrl('mobile/onepage/savePayment') ?>');
</script>
<form action="" id="co-payment-form">
    <?php echo $this->getChildHtml('methods') ?>
	<br />
	<b><?php echo $this->__('Purchase Order Number'); ?>:</b>&nbsp;<input type="text" id="payment-schrack-custom-order-number" name="payment[schrack_custom_order_number]" maxlength="20" size="20" />
</form>

<div class="clear"></div>
<div class="col2-alt-set button-set" style="padding-top:0;">
    <div class="col-1" style="padding-top:8px;">
        <a href="#" class="left" onclick="checkout.back(); return false;"><span><?php echo $this->__('&laquo Back') ?></span></a>
    </div>
    <div class="col-2">
        <div class="form-buttons">
            <span id="payment-buttons-container">
                <span id="payment-please-wait" style="display:none;" class="opc-please-wait">
                    <img src="<?php echo $this->getSkinUrl('images/opc-ajax-loader.gif') ?>" class="v-middle" alt="" /> &nbsp; <?php echo $this->__('Loading next step...') ?> &nbsp;
                </span><br />
                <button type="button" class="form-button right" onclick="payment.save();"><span><?php echo $this->__('Continue') ?></span></button>
            </span>
        </div>
    </div>
</div><div class="clear"></div>

<script type="text/javascript">
    function toggleToolTip(event){
        if($('payment-tool-tip')){
            $('payment-tool-tip').setStyle({
                top: (Event.pointerY(event)-400)+'px',
                left: (Event.pointerX(event)+100)+'px'
            })
            $('payment-tool-tip').toggle();
        }
        Event.stop(event);
    }
    if($('payment-tool-tip-close')){
        Event.observe($('payment-tool-tip-close'), 'click', toggleToolTip);
    }
    $$('.cvv-what-is-this').each(function(element){
        Event.observe(element, 'click', toggleToolTip);
    });
    payment.currentMethod = "<?php echo $this->getChild('methods')->getSelectedMethodCode() ?>";
</script>
