<?php
/* @var this Mage_Checkout_Block_Onepage_Shipping_Method */
?>
<form id="co-shipping-method-form" action="">
<div class="inner-box">
    <div class="default-box" style="padding:10px;" id="checkout-shipping-method-load">
        <?php echo $this->getChildHtml('available') ?>
    </div>
</div>
<script type="text/javascript">
    var shippingMethod = new ShippingMethod('co-shipping-method-form', "<?php echo $this->getUrl('mobile/onepage/saveShippingMethod') ?>");
</script>
<div id="onepage-checkout-shipping-method-additional-load">
<?php echo $this->getChildHtml('additional') ?>
</div>
</form>
<div class="col2-alt-set button-set" style="padding-top:0;">
    <div class="col-1" style="padding-top:8px;">
        <a href="#" class="left" onclick="checkout.back(); return false;"><span><?php echo $this->__('&laquo Back') ?></span></a>
    </div>
    <div class="col-2">
        <div class="form-buttons">
            <span id="shipping-method-buttons-container">
                <span id="shipping-method-please-wait" style="display:none;" class="opc-please-wait">
                    <img src="<?php echo $this->getSkinUrl('images/opc-ajax-loader.gif') ?>" class="v-middle" alt="" /> &nbsp; <?php echo $this->__('Loading next step...') ?> &nbsp;
                </span><br />
                <button type="button" class="form-button right" onclick="shippingMethod.save();"><span><?php echo $this->__('Continue') ?></span></button>
            </span>
        </div>
    </div>
</div><div class="clear"></div>
