<?php
/* @var $this Schracklive_SchrackCheckout_Block_Onepage_Shipping */
?>
<form id="co-shipping-form" action="">
    <p><?php echo $this->__('Select a shipping address from your address book.') ?></p>
    <p class="select300inner"><?php echo $this->getAddressesHtmlRadio('shipping') ?></p>
    <input type="hidden" name="shipping[same_as_billing]" value="0" />
</form>

<div class="col2-alt-set button-set">
    <div class="col-2">&nbsp;</div>
</div><div class="clear"></div>
<div class="col2-alt-set button-set" style="padding-top:0;">
    <div class="col-2">
        <div class="form-buttons">
            <span id="shipping-buttons-container">
                <span id="shipping-please-wait" style="display:none;" class="opc-please-wait">
                    <img src="<?php echo $this->getSkinUrl('images/opc-ajax-loader.gif') ?>" class="v-middle" alt="" /> &nbsp; <?php echo $this->__('Loading next step...') ?> &nbsp;
                </span><br />
                <button type="button" class="form-button right" onclick="shipping.save();"><span><?php echo $this->__('Continue') ?></span></button>
            </span>
        </div>
    </div>
</div><div class="clear"></div>
<script type="text/javascript">
//<!--
    var shipping = new Shipping('co-shipping-form', '<?php echo $this->getUrl('mobile/onepage/getAddress') ?>address/', '<?php echo $this->getUrl('mobile/onepage/saveShipping') ?>',
        '<?php echo $this->getUrl('mobile/onepage/shippingMethod') ?>');
    var shippingForm = new VarienForm('co-shipping-form');
//-->
</script>
