<!-- app/design/frontend/schrack/schrackresponsive/template/page/empty.phtml (start) -->
<?php
/**
 * Template for Mage_Page_Block_Html
 */
?>
<!DOCTYPE html>
<!--[if lt IE 7 ]> <html lang="<?php echo substr($this->getLang(), 0, 2);?>" id="top" class="no-js ie6"> <![endif]-->
<!--[if IE 7 ]>    <html lang="<?php echo substr($this->getLang(), 0, 2);?>" id="top" class="no-js ie7"> <![endif]-->
<!--[if IE 8 ]>    <html lang="<?php echo substr($this->getLang(), 0, 2);?>" id="top" class="no-js ie8"> <![endif]-->
<!--[if IE 9 ]>    <html lang="<?php echo substr($this->getLang(), 0, 2);?>" id="top" class="no-js ie9"> <![endif]-->
<!--[if (gt IE 9)|!(IE)]><!--> <html lang="<?php echo substr($this->getLang(), 0, 2);?>" id="top" class="no-js"> <!--<![endif]-->
<head>
<?php echo $this->getChildHtml('head') ?>
</head>
<body<?php echo $this->getBodyClass()?' class="'.$this->getBodyClass().'"':'' ?> id="tmpl-empty">
<div id="content" class="content row">
    <?php echo $this->getChildHtml('content') ?>
</div>
</body>
</html>
<!-- app/design/frontend/schrack/schrackresponsive/template/page/empty.phtml (end) -->