<!-- default/template/datanorm/form/index.phtml (start) -->
<?php
    /* @var $this Mage_Core_Block_Template */
    $ajaxLoaderGifPath = $this->getSkinUrl('schrackdesign/Public/Images/download_ajax_loader.gif');
?>

<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<?php if (!$isLoggedIn): ?>
	<p><a href="<?php echo $this->getUrl('customer/account/login') ?>" class="info-msg-link"><?php echo $this->__('Go to login?') ?></a></p>
<?php endif; ?>

<div class="listArea"></div>
<div class="headline a"><?php echo $this->__('Download CSV Price Lists'); ?></div>
<div class="gray-form">
    <div class="row">
        <div class="large-12 columns">
            <p><?php echo $this->__('Download CSV Price Lists Explanation'); ?></p>
        </div>
    </div>
    <div class="row">
        <div class="large-3 columns large-offset-9">
            <button id="getCVSPricelistButton" type="button" class="button-red small gray" title="<?php echo $this->__('Download Now!') ?>" class="button btn-checkout"><?php echo $this->__('Download Now!') ?></button>
        </div>
    </div>
</div>
<br>
<div class="headline a"><?php echo $this->__('Datanorm Download'); ?></div>
<div class="gray-form">
    <div class="row">
        <div class="large-12 columns">
            <p><?php echo $this->__('Datanorm Text'); ?></p>
            <div><a href="<?php echo Mage::getStoreConfig('schrack/typo3/typo3url') . '?id=' . Mage::getStoreConfig('schrack/datanorm/typo3_information_site_id'); ?>" target="_blank"><?php echo $this->__('Datanorm Information'); ?></a></div>
        </div>
    </div>
    <div id="download-flags-opener" class="opener closed"><?php echo $this->__('Options'); ?></div>
    <div id="download-flags-content">
        <div class="row">
            <div class="large-1 columns">
                <input id="idSelectImgURLs" class="checkbox" type="checkbox" name="addImages" value="1"/>
            </div>
            <div class="large-11 columns">
                <label for="idSelectImgURLs"><?php echo ' '.$this->__('Include Image URLs'); ?></label>
            </div>
        </div>
        <div class="row">
            <div class="large-12 columns">
                <p><?php echo $this->__('Datanorm Image Explanation Text'); ?></p>
            </div>
        </div>
        <div class="row">
            <div class="large-1 columns">
                <input id="idEncodeUTF8" class="checkbox" type="checkbox" name="encodeUTF8" value="1"/>
            </div>
            <div class="large-11 columns">
                <label for="idEncodeUTF8"><?php echo ' '.$this->__('Use UTF-8 Format'); ?></label>
            </div>
        </div>
        <div class="row">
            <div class="large-12 columns">
                <p><?php echo $this->__('Use UTF-8 Format Explanation'); ?></p>
            </div>
        </div>
        <div class="row">
            <div class="large-1 columns">
                <input id="idGroupArticlesBySchrackStructure" class="checkbox" type="checkbox" name="groupArticlesBySchrackStructure" value="1"/>
            </div>
            <div class="large-11 columns">
                <label for="idGroupArticlesBySchrackStructure"><?php echo ' '.$this->__('Use Alternative Grouping'); ?></label>
            </div>
        </div>
        <div class="row">
            <div class="large-12 columns">
                <p><?php echo $this->__('Use Alternative Grouping Explanation'); ?></p>
            </div>
        </div>
        <div class="row">
            <div class="large-1 columns">
                <input id="idUseEdsArticleNumbers" class="checkbox" type="checkbox" name="useEdsArticleNumbers" value="1"/>
            </div>
            <div class="large-11 columns">
                <label for="idUseEdsArticleNumbers"><?php echo ' '.$this->__('Use EDS Article Numbers'); ?></label>
            </div>
        </div>
        <div class="row">
            <div class="large-12 columns">
                <p><?php echo $this->__('Use EDS Article Numbers Explanation'); ?></p>
            </div>
        </div>
        <div class="row">
            <div class="large-1 columns">
                <input id="idWithoutLongText" class="checkbox" type="checkbox" name="withoutLongText" value="1"/>
            </div>
            <div class="large-11 columns">
                <label for="idWithoutLongText"><?php echo ' '.$this->__('Omit Longtexts'); ?></label>
            </div>
        </div>
        <div class="row">
            <div class="large-12 columns">
                <p><?php echo $this->__('Omit Longtexts Explanation'); ?></p>
            </div>
        </div>
        <?php if ($remain = false) :// Removed from frontend, but not deleted from source code! ?>
            <div class="row">
                <div class="large-1 columns">
                    <input id="idWithoutUVP" class="checkbox" type="checkbox" name="withoutUVP" value="1"/>
                </div>
                <div class="large-11 columns">
                    <label for="idWithoutLongText"><?php echo ' '.$this->__('Without Recommended Retail Price'); ?></label>
                </div>
            </div>
            <div class="row">
                <div class="large-12 columns">
                    <p><?php echo $this->__('Without Recommended Retail Price Explanation'); ?></p>
                </div>
            </div>
        <?php endif; ?>
    </div>
    <div class="row">
        <div class="large-3 columns large-offset-9">
            <button id="getDatanormArticledataButton" type="button" class="button-red small gray" title="<?php echo $this->__('Download Now!') ?>" class="button btn-checkout"><?php echo $this->__('Download Now!') ?></button>
        </div>
    </div>
</div>
<br>
<div class="headline a"><?php echo $this->__('XML Catalog Download'); ?></div>
<div class="gray-form">
    <div class="row">
        <div class="large-12 columns">
            <p><?php echo $this->__('XML Catalog Download Explanation'); ?></p>
        </div>
    </div>
    <div class="row">
        <div class="large-3 columns large-offset-9">
            <button id="getXMLCatalogueButton" type="button" class="button-red small gray" title="<?php echo $this->__('Download Now!') ?>" class="button btn-checkout" ><?php echo $this->__('Download Now!') ?></button>
        </div>
    </div>
</div>


<script type="text/javascript">
    //<![CDATA[
    jQuery(document).ready(function () {

        var getArticleDataFile = function(species) {
            // Removes head banner (error-) messages:
            jQuery('.errors').remove();

            // Show overlay loader for protect from interim actions from user, and for show action progress:
            setOverlayLoader('listArea', '<?php echo $ajaxLoaderGifPath; ?>');

            var ajaxUrl = '';
            var ajaxUrlWithProtocol = '';
            if (species == 'csv') {
                ajaxUrlWithProtocol = '<?php echo Mage::getUrl('datanorm/index/downloadCvs/'); ?>';
                // Removing protocol ('http:' / 'https'):
                ajaxUrl = ajaxUrlWithProtocol.replace('http:', '');
                ajaxUrl = ajaxUrl.replace('https:', '');
            }

            if (species == 'datanorm') {
                ajaxUrlWithProtocol = '<?php echo Mage::getUrl('datanorm/index/download/'); ?>';
                // Removing protocol ('http:' / 'https'):
                ajaxUrl = ajaxUrlWithProtocol.replace('http:', '');
                ajaxUrl = ajaxUrl.replace('https:', '');
            }

            if (species == 'xml') {
                ajaxUrlWithProtocol = '<?php echo Mage::getUrl('datanorm/index/downloadXml/'); ?>';
                // Removing protocol ('http:' / 'https'):
                ajaxUrl = ajaxUrlWithProtocol.replace('http:', '');
                ajaxUrl = ajaxUrl.replace('https:', '');
            }

            jQuery.ajax(ajaxUrl, {
                'type': 'POST',
                'dataType': "json",
                'data': {
                    'SelectImgURLs' : jQuery('#idSelectImgURLs').is(':checked'),
                    'EncodeUTF8' : jQuery('#idEncodeUTF8').is(':checked'),
                    'GroupArticlesBySchrackStructure' : jQuery('#idGroupArticlesBySchrackStructure').is(':checked'),
                    'UseEdsArticleNumbers' : jQuery('#idUseEdsArticleNumbers').is(':checked'),
                    'WithoutLongText' : jQuery('#idWithoutLongText').is(':checked'),
                    'WithoutUVP' : jQuery('#idWithoutUVP').is(':checked')
                },
                'success': function (responseData) {
                    //console.log(responseData);
                    if (jQuery.isEmptyObject(responseData) || responseData.downloadFilePath == '' || responseData.error) {
                        unsetOverlayLoader('listArea');
                        var errorMessages = ['<?php echo $this->__('Datanorm could not be fetched.'); ?>'];
                        appendMessageUl(errorMessages, 'errors', 'error-msg');
                    } else {
                        unsetOverlayLoader('listArea');
                        window.location.href = responseData.downloadFilePath;
                    }
                },
                error: function (e) {
                    unsetOverlayLoader('listArea');
                    var errorMessages = ['<?php echo $this->__('Datanorm could not be fetched.'); ?>'];
                    appendMessageUl(errorMessages, 'errors', 'error-msg');
                }
            });
        }

        // Elapse/collapse options:
        jQuery('#download-flags-opener').click(function (ev) {
            var t = jQuery(ev.target);
            if (t.hasClass('closed')) {
                jQuery('#download-flags-content').show();
                t.switchClass('closed', 'opened');
            } else {
                jQuery('#download-flags-content').hide();
                t.switchClass('opened', 'closed');
            }
        });

        // Button actions (download: csv, datanorm, xml):
        jQuery('#getCVSPricelistButton').on('click', function(){
            getArticleDataFile('csv');
        });
        jQuery('#getDatanormArticledataButton').on('click', function(){
            getArticleDataFile('datanorm');
        });
        jQuery('#getXMLCatalogueButton').on('click', function(){
            getArticleDataFile('xml');
        });

    });
    //]]>
</script>
<!-- default/template/datanorm/form/index.phtml (end) -->