<?php if ($this->getMessage()): ?>
	<div class="notification-global">
		<div><strong>Google Tag Manager Enhanced Ecommerce (UA) Tracking installed successfully!</strong></div>
		<div>You need to configure the extension. <a href="<?php echo Mage::helper("adminhtml")->getUrl("adminhtml/system_config/edit/section/ec") ?>">Configure</a> | <a target="_blank" href="http://www.anowave.com/marketplace/magento-extensions/magento-google-tag-manager-enhanced-ecommerce-ua-tracking/">Docs & Guide</a></div>
	</div>
<?php endif ?>