<?php if ($this->getMessage()): ?>
	<div class="notification-global">
		<div><strong>It seems you are using older version of GTM snippet.</strong></div>
		<div>Please use the new splitted approach to insert the GTM snippet otherwise tracking may not work. To fix, empty field <strong>Google Tag Manager Install Snippet</strong>, set <strong>Use GTM split snippet</strong> to <strong>Yes</strong> and then insert the &lt;head&gt; and &lt;body&gt; snippets respectively.<a href="<?php echo Mage::helper("adminhtml")->getUrl("adminhtml/system_config/edit/section/ec") ?>">Configure</a></div>
	</div>
<?php endif ?>