<!-- app/design/frontend/schrack/default/template/checkout/onepage/review/info.phtml (start) -->
<?php /* @var $this Mage_Checkout_Block_Onepage_Review_Info */
    $isProspect = false;

    $quote = $this->getQuote();

    if ($quote && is_object($quote)) {
        $quoteCustomerType = $quote->getSchrackCustomertype();
        if (in_array($quoteCustomerType, array('oldFullProspect', 'oldLightProspect', 'newProspect'))) {
           $isProspect = true;
        }
    }
?>
<div class="box-content">
<?php echo $this->getChildHtml('items_before'); ?>
<div id="checkout-review-table-wrapper">
    <table class="checkout-review-table" id="checkout-review-table">
        <thead>
            <tr>
                <th><?php echo $this->__('Product Name') ?></th>
                <th><?php echo $this->__('Backorder') ?></th>
                <th><?php echo $this->__('Qty') ?></th>
                <th><?php echo $this->__('QU') ?></th>
                <?php if ( Mage::helper('geoip')->maySeePrices() ): ?>
                    <th><?php echo $this->__('Price') ?></th>
                    <th><?php echo $this->__('Disc.%') ?></th>
                    <th><?php echo $this->__('Subtotal') ?></th>
                <?php endif;?>
            </tr>
        </thead>
        
        <tbody>
        <?php foreach($this->getItems() as $_item): ?>
            <?php echo $this->getItemHtml($_item)?>
        <?php endforeach ?>
        </tbody>
        
    </table>
</div>
<?php echo $this->getChildHtml('totals'); ?>
<?php
$geoipHelper = Mage::helper('geoip');
if ($geoipHelper->maySeePrices()):?>
    <p>
        <?php
            $shipmentMode = Mage::getSingleton('checkout/session')->getQuote()->getSchrackShipmentMode();
            $paymentTerms = Mage::getSingleton('checkout/session')->getQuote()->getSchrackPaymentTerms();
        ?>
        <?php if ($shipmentMode && strlen(trim($shipmentMode)) > 0) : ?>
            <strong><?php echo $this->__('Shipment Mode'); ?></strong>: <?php echo $this->__($shipmentMode); ?><br/>
        <?php endif;?>
        <?php if ($paymentTerms && strlen(trim($paymentTerms)) > 0) : ?>
            <strong><?php echo $this->__('Payment Terms'); ?></strong>: <?php echo $this->__($paymentTerms); ?>
        <?php endif;?>
    </p>
<?php endif;?>
</div>
<script type="text/javascript">
//<![CDATA[
    decorateTable('checkout-review-table');
    truncateOptions();
//]]>
</script>
<div id="checkout-review-submit">
    <div class="box-content">
		<?php echo $this->getChildHtml('agreements') ?>
        <?php if ($isProspect && Mage::getStoreConfig('schrack/new_self_registration/triggerNewsletterForProspects')): ?>
            <div>
                <input id="newsletter_checkbox" type="checkbox" value="newsletter" <?php if (Mage::getStoreConfig('schrack/new_self_registration/triggerNewsletterForProspectsDefaultSetting')) : ?> checked="checked" <?php endif; ?>>&nbsp;<?php echo $this->__('Agree Newsletter Checkbox Text'); ?>
            </div>
            <br>
        <?php endif; ?>
		<p class="f-left"><?php echo $this->__('Forgot an Item?') ?> <a href="<?php echo $this->getUrl('checkout/cart') ?>"><?php echo $this->__('Edit Your Cart') ?></a></p>
    </div>
    <div class="buttons-set" id="review-buttons-container">
	<?php echo $this->getChildHtml('button') ?>
        <span class="please-wait" id="review-please-wait" style="display:none;">
            <img src="<?php echo $this->getSkinUrl('images/opc-ajax-loader.gif') ?>" alt="<?php echo $this->__('Submitting order information...') ?>" title="<?php echo $this->__('Submitting order information...') ?>" class="v-middle" /> <?php echo $this->__('Submitting order information...') ?>
        </span>
    </div>
    <script type="text/javascript">
    //<![CDATA[
        jQuery(document).ready(function(){

            <?php if (Mage::getStoreConfig('schrack/new_self_registration/triggerNewsletterForProspectsDefaultSetting')) : ?>
                localStorage.newCheckoutNewsletter = 1;
            <?php else :?>
                localStorage.newCheckoutNewsletter = 0;
            <?php endif; ?>

            jQuery('#newsletter_checkbox').on('click', function() {
                if (jQuery('#newsletter_checkbox').prop('checked') == true) {
                    localStorage.newCheckoutNewsletter = 1;
                } else {
                    localStorage.newCheckoutNewsletter = 0;
                }
            });

        });

       review = new Review('<?php echo $this->getUrl('checkout/onepage/saveOrder', array('form_key' => Mage::getSingleton('core/session')->getFormKey())) ?>', '<?php echo $this->getUrl('checkout/onepage/success') ?>', $('checkout-agreements')); //Nagarro: Added for key parameter
    //]]>
    </script>
</div>
<!-- app/design/frontend/schrack/default/template/checkout/onepage/review/info.phtml (end) -->