<!-- app/design/frontend/schrack/schrackresponsive/template/checkout/onepage/email/noprices_customer.phtml (start) -->
<?php
$session = Mage::getSingleton('core/session');
$name = $session->getOnepageName();
$email = $session->getOnepageEmail();
$phone = $session->getOnepagePhone();
$homepage = $session->getOnepageHomepage();
?>                
<html>
    <body>

        <p>
            <?php echo $this->__('Dear Customer,')?>
        </p>
        <p>
            <?php echo $this->__('thank you for your enquiry. We are currently processing your request and you will shortly receive our proposal. Please find attached the requested products in CSV file format.')?>
        </p>
        <p>
            <?php echo $this->__('Sincerely,')?><br/>

            <?php echo $this->__('your online shop team')?>
        </p>
    </body>
</html>
<!-- app/design/frontend/schrack/schrackresponsive/template/checkout/onepage/email/noprices_customer.phtml (end) -->