<!-- app\design\frontend\schrack\schrackresponsive\template\customer\form\confirmation.phtml (start) -->
<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<div class="col-xs-12 forgotCont">
        <h1 class="headline b1"><?php echo $this->__('Send confirmation link') ?></h1>
    <div class="col-xs-12 col-sm-8 col-md-6 padLR0">
        <form action="" method="post" id="form-validate">
            <div class="formContianer">
                <div class="hdCont">
                        <p><?php echo $this->__('* Required Fields') ?></p>
                </div>
                <h2 class="padB5"><?php echo $this->__('Retrieve your confirmation link here') ?></h2>
                <p><?php echo $this->__('Please enter your email below and we\'ll send you confirmation link for it.') ?></p>
                <ul>
                    <li>
                        <h3><?php echo $this->__('Email Address') ?> <span class="red">*</span></h3>
                    </li>
                    <li>
                        <input type="text" name="email" id="email_address" placeholder="<?php echo $this->__('Email Address') ?>" title="<?php echo $this->__('Email Address') ?>" class="input-text required-entry validate-email form-control" value="<?php echo $this->htmlEscape($this->getEmail()) ?>" />
                    </li>
                </ul>
                <div class="row">
                    <div class="col-xs-6"><button class="bttn-md" type="submit" title="<?php echo $this->__('Submit') ?>" class="button"><?php echo $this->__('Submit') ?></button></div>
                    <div class="col-xs-6 text-right small"><a href="<?php echo $this->helper('customer')->getLoginUrl() ?>"><small>&laquo; </small><?php echo $this->__('Back to Login') ?></a></div>
                </div>
            </div>
        </form>
    </div>
</div>
<script type="text/javascript">
//<![CDATA[
    var dataForm = new VarienForm('form-validate', true);
//]]>
</script>
<!-- app\design\frontend\schrack\schrackresponsive\template\customer\form\confirmation.phtml (end) -->