<!-- app/design/frontend/schrack/default/template/customer/form/confirm.and.set.password.phtml (start) -->

<?php
    $_helper = $this->helper('schrackcustomer');
    $customer = $this->getCustomer();

    $showBecauseImNotAProspect = true;
    $customerType = $customer->getSchrackCustomerType(); // ProspectTypes: 'light-prospect' / 'full-prospect'
    // Prospect Light / Full
    if (in_array($customerType, array('light-prospect', 'full-prospect'))) {
        $showBecauseImNotAProspect = false;
    }
    $currentUrl = Mage::helper('core/url')->getCurrentUrl();
    $postUrl = $this->getPostUrl();
    if ( ! isset($postUrl) || ! $postUrl ) {
        $postUrl = 'customer/account/confirmAndSetPasswordPost';
    }
?>

<style>
    .initialHideToTopSymbol {
        display: none !important;
    }
    #password {
        font-size: 16px !important;
    }
    #confirmation {
         font-size: 16px !important;
    }
    @media (min-width: 60px) and (max-width: 320px) {
        #save_password_data_button {
            height: 30px !important;
        }
    }
    @media (min-width: 321px) and (max-width: 480px) {
        #save_password_data_button {
            height: 30px !important;
        }
    }
    @media (min-width: 481px) and (max-width: 767px) {
        #save_password_data_button {
            height: 30px !important;
        }
    }
</style>

<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<div class="row">
    <div class="col-xs-12">
        <h1>
            <?php echo $this->__('Change Password') ?>
        </h1>
        <div>
            <p class="required" id="required-info"><?php echo $this->__('* Required Fields') ?></p>
        </div>
        <form action="<?php echo $this->getUrl($postUrl) ?>" method="post" id="form-validate">
            <input type="hidden" name="customer_id" id="customer_id" value="<?php echo $this->getCustomerId() ?>" />
            <input type="hidden" name="security_key" id="security_key" value="<?php echo $this->getSecurityKey() ?>" />
            <div class="gray-form loginCont">
                <h3><?php echo $this->__('Password') ?></h3>
                <div class="formContianer">
                    <?php echo $this->getBlockHtml('formkey')?>                    
                    <ul class="form-list" id="passwordForm">
                        <li style="display: none;"><input type="checkbox" name="change_password" id="change_password" value="1" onclick="setPasswordForm(this.checked)" title="<?php echo $this->__('Change Password') ?>" checked="checked" class="checkbox floatL" />
                            <label for="change_password" style="display: inline;">&nbsp;<?php echo $this->__('Change Password') ?></label>
                        </li>
                        <li>
                            <div class="row">
                                <div class="col-xs-12 col-sm-4">
                                    <input type="password" placeholder="<?php echo $this->__('New Password') ?>*" title="<?php echo $this->__('New Password') ?>" class="input-text form-control required-entry" name="password" id="password" />  
                                </div>
                                <div class="col-xs-12 col-sm-4">                                        
                                    <input type="password" placeholder="<?php echo $this->__('Confirm New Password') ?>*" title="<?php echo $this->__('Confirm New Password') ?>" class="input-text form-control required-entry" name="confirmation" id="confirmation" />                                   
                                </div>
                            </div>
                        </li>
                    </ul>
                    
                </div>
            </div>
            <div class="row">
                <div class="col-xs-6">
                    <button id="save_password_data_button" class="bttn-md" title="<?php echo $this->__('Change Password') ?>"><?php echo $this->__('Change Password') ?></button>
                </div>
                <div class="col-xs-6 text-right">
                    <p class="back-link hidden-xs hidden-sm"><a href="<?php echo Mage::helper('schrackcore/url')->getUrlWithCurrentProtocol('customer/account'); ?>"><small>&laquo; </small><?php echo $this->__('Back') ?></a></p>
                    <p class="back-link hidden-md hidden-lg"><a href="<?php echo Mage::helper('schrackcore/url')->getUrlWithCurrentProtocol('account/account/index'); ?>" ><small>&laquo; </small><?php echo $this->__('Back') ?></a></p>
                </div>
            </div>
        </form>
    </div>
</div>
<script type="text/javascript">
//<![CDATA[

    var dataForm = new VarienForm('form-validate', true);

    function setPasswordForm(arg){
        if(arg){
            jQuery('#passwordForm').show();
        }else{
            jQuery('#passwordForm').hide();
        }
    }
    <?php if($this->getCustomer()->getChangePassword()): ?>
        setPasswordForm(true);
    <?php endif; ?>
	jQuery(document).ready(function() {	// Set tabindex to all element of forms

		jQuery('#change_password').focus();
		jQuery('#form-validate :input,select,button,a').each(function (fv) { if (this.type != "hidden") { jQuery(this).attr('tabindex', fv + 1); } });

        /* Back to Top */
        jQuery('body').append('<div id="toTop" class="btn btn-info print-hide-imp initialHideToTopSymbol"><span class="glyphicon glyphicon-chevron-up"></span> <?php echo $this->__('Back to Top'); ?></div>');
        jQuery(window).scroll(function () {
            if (jQuery(this).scrollTop() != 0) {
                jQuery('#toTop').fadeIn();
            } else {
                jQuery('#toTop').fadeOut();
            }
        });
        jQuery('#toTop').click(function(){
            jQuery("html, body").animate({ scrollTop: 0 }, 600);
            console.log('ScrollTop #85');
            return false;
        });
        jQuery('#toTop').removeClass('initialHideToTopSymbol');
        /* Back to Top */

	});
//]]>
</script>

<!-- app/design/frontend/schrack/default/template/customer/form/confirm.and.set.password.phtml (start) -->
