<!-- design\frontend\schrack\schrackresponsive\template\customer\form\forgotpassword.phtml (start) -->
<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<div class="col-xs-12 forgotCont">
    <h1 class="headline b1"><?php echo $this->__('Forgot Your Password?') ?></h1>
    <div class="col-xs-12 col-sm-8 col-md-6 padLR0">
        <form action="<?php echo $this->getUrl('*/*/forgotpasswordpost') ?>" method="post" id="form-validate">
            <div class="formContianer">
                <h2 class="padB5"><?php echo $this->__('Reset your password here') ?></h2>
                <p><?php echo $this->__('Please enter your email below and we\'ll send an email with a link to reset your password.') ?></p>
                <ul>
                    <li>
                        <input placeholder="<?php echo $this->__('Email Address') ?>*" type="text" name="email" alt="email" id="email_address" class="input-text required-entry validate-email form-control" value="<?php echo $this->htmlEscape($this->getEmailValue()) ?>" />
                    </li>
                </ul>
                <div class="row">
                    <div class="col-xs-6"><button class="bttn-md" type="submit" title="<?php echo $this->__('Submit') ?>" class="button"><?php echo $this->__('Submit') ?></button></div>
                    <div class="col-xs-6 text-right small"><a href="<?php echo $this->helper('customer')->getLoginUrl() ?>"><small>&laquo; </small><?php echo $this->__('Back to Login') ?></a></div>
                </div>
            </div>
        </form>
    </div>
</div>
<script type="text/javascript">
    //<![CDATA[
    var dataForm = new VarienForm('form-validate', true);
	jQuery(document).ready(function(){	// Set tabindex to all element of forms
		jQuery('#email_address').focus();
		jQuery('#form-validate :input,select,button,a').each(function (fv) { if (this.type != "hidden") { jQuery(this).attr('tabindex', fv + 1); } });
	});
    //]]>
</script>

<!-- design\frontend\schrack\schrackresponsive\template\customer\form\forgotpassword.phtml (end) -->