<!-- app/design/frontend/schrack/schrackresponsive/template/persistent/checkout/onepage/billing.phtml (start) -->
<?php
    // @var $this Schracklive_SchrackCheckout_Block_Onepage_Billing

    $customer = $this->getCustomer();
    if ($customer) {
        $customerType = $customer->getSchrackCustomerType(); // ProspectTypes: 'light-prospect' / 'full-prospect'
    }

    $prospectFull  = false;
    $prospectLight = false;

    if ($customerType == 'light-prospect') {
        $prospectLight = true;
    }

    if ($customerType == 'full-prospect') {
        $prospectFull = true;
    }

    $customerIsLoggedIn = $this->helper('customer')->isLoggedIn();

    $useBillingAddressForShipping = $this->isUseBillingAddressForShipping();
    if ($useBillingAddressForShipping == true) {
        $useBillingAddressForShippingValue = 'yes';
    } else {
        $useBillingAddressForShippingValue = 'no';
    }

    $localeCode = strtolower(Mage::getStoreConfig('schrack/general/country'));

/*
    if () {
        $this->getQuote()->etBillingAddress()->setSameAsBilling()
    }*/
?>

<style>
    #co-billing-form {
        height: 975px;
    }

    #billing_telephone_plus_symbol {
        float: left !important;
        width: 17px !important;
        margin-left: 10px !important;
        margin-top: 20px !important;
        font-weight: bold !important;
        font-size: 18px !important;
    }

    #billing_fax_plus_symbol{
        float: left !important;
        width: 17px !important;
        margin-left: 10px !important;
        margin-top: 20px !important;
        font-weight: bold !important;
        font-size: 18px !important;
    }


    #billing_telephone_company__plus_symbol{
        float: left !important;
        width: 17px !important;
        margin-left: 10px !important;
        margin-top: 20px !important;
        font-weight: bold !important;
        font-size: 18px !important;
    }

    .billingAdressContainer {
        background-color: #EEE;
        border: 2px solid #D6D6D6!important;
        margin-top: 10px;
        border-radius: 6px;
        height: 987px;
    }

    .checkoutBillingAddressRow{
        width: 100%;
        padding-left: 12px;
    }

    .customHeightDistance {
        height: 10px;;
    }

    .validation-advice {
        margin-top: -55px;
        margin-left: 70px;
    }

    #advice-validate-cpassword-billing\:confirm_password {
        margin-top:  0px !important;
    }

    #advice-validate-email-billing\:email {
        margin-top: 2px !important;
        margin-left: 2px !important;
    }

    .checkoutBillingEmailAddressField {
        color: black;
        width: 31%;
        float: left;
        margin-bottom: 20px;
        margin-top: 14px;
        margin-left: 25px;
        height: 82px;
    }

    .checkoutBillingGenderField {
        color: black;
        width: 31%;
        float: left;
        margin-bottom: 20px;
        margin-top: 14px;
        margin-left: 25px;
        height: 82px;
    }

    .checkoutBillingFirstnameField {
        color: black;
        width: 31%;
        float: left;
        margin-bottom: 20px;
        margin-top: 14px;
        margin-left: 25px;
        height: 82px;
    }

    .checkoutBillingLastnameField {
        color: black;
        width: 31%;
        float: left;
        margin-bottom: 20px;
        margin-top: 14px;
        margin-left: 25px;
        height: 82px;
    }

    .checkoutBillingCompanynameLastname {
        color: black;
        width: 31%;
        float: left;
        margin-bottom: 20px;
        margin-top: 14px;
        margin-left: 25px;
        height: 82px;
    }

    .checkoutBillingCompanynameCompany {
        color: black;
        width: 31%;
        float: left;
        margin-bottom: 20px;
        margin-top: 14px;
        margin-left: 25px;
        height: 82px;
    }

    .checkoutBillingCompanynameFirstname {
        color: black;
        width: 31%;
        float: left;
        margin-bottom: 20px;
        margin-top: 14px;
        margin-left: 25px;
        height: 82px;
    }

    .checkoutBillingCompanydataVATIdentificationNumber {
        color: black;
        width: 31%;
        float: left;
        margin-bottom: 20px;
        margin-top: 14px;
        margin-left: 25px;
        height: 82px;
    }

    .checkoutBillingCompanydataRegistrationNumber {
        color: black;
        width: 31%;
        float: left;
        margin-bottom: 20px;
        margin-top: 14px;
        margin-left: 25px;
        height: 82px;
    }

    .checkoutBillingCompanyWebsite {
        color: black;
        width: 31%;
        float: left;
        margin-bottom: 20px;
        margin-top: 14px;
        margin-left: 25px;
        height: 82px;
    }

    .checkoutBillingStreet1Field {
        color: black;
        width: 31%;
        float: left;
        margin-bottom: 20px;
        margin-top: 14px;
        margin-left: 25px;
        height: 82px;
        padding-top: 3px;
    }

    .checkoutBillingPostcodeField {
        color: black;
        width: 31%;
        float: left;
        margin-bottom: 20px;
        margin-top: 14px;
        margin-left: 25px;
        height: 82px;
    }

    .checkoutBillingCityField {
        color: black;
        width: 31%;
        float: left;
        margin-bottom: 20px;
        margin-top: 14px;
        margin-left: 25px;
        height: 82px;
    }

    .checkoutBillingStateField {
        display: none;
        color: black;
        width: 31%;
        float: left;
        margin-bottom: 20px;
        margin-top: 14px;
        margin-left: 25px;
        height: 82px;
    }

    .checkoutBillingCountryField {
        color: black;
        width: 31%;
        float: left;
        margin-bottom: 20px;
        margin-top: 14px;
        margin-left: 25px;
        height: 82px;
    }

    .checkoutBillingTelephoneField {
        color: black;
        width: 31%;
        float: left;
        margin-bottom: 20px;
        margin-top: 14px;
        margin-left: 25px;
        height: 78px;
    }

    .checkoutBillingFaxField {
        color: black;
        width: 31%;
        float: left;
        margin-bottom: 20px;
        margin-top: 14px;
        margin-left: 25px;
        height: 78px;
    }

    .checkoutBillingTelephoneCompanyField {
        color: black;
        width: 31%;
        float: left;
        margin-bottom: 20px;
        margin-top: 14px;
        margin-left: 25px;
        height: 78px;
    }

    .checkoutPasswordField {
        color: black;
        width: 31%;
        float: left;
        margin-bottom: 20px;
        margin-top: 14px;
        margin-left: 25px;
        height: 78px;
    }

    .register_customer_password_field {
        border: 1px solid #d6d6d6;
        color: black;
        width: 31%;
        float: left;
        margin-right: 25px;
        margin-bottom: 20px;
        margin-top: 14px;
        margin-left: 25px;
        height: 137px;
        display: none;
    }

    #checkout_saveBillingButton {
        padding-left: 20px;
        margin-top: 69px;
        margin-left: 76%;
        width: 21%;
    }

    #billing\:email {
        width: 85% !important;
    }

    #billing\:gender {
        width: 85% !important;
        height: 27px;
    }

    #billing\:person-firstname {
        width: 85% !important;
    }

    #billing\:person-lastname {
        width: 85% !important;
    }

    #billing\:lastname {
        width: 85% !important;
        margin-top: 19px;
    }

    #billing\:company {
        width: 85% !important;
        margin-top: 19px;
    }

    #billing\:firstname {
        width: 85% !important;
        margin-top: 19px;
    }

    #billing\:companyuid {
        width: 85% !important;
        margin-top: 19px;
    }

    #billing\:companyregistrationnumber {
        width: 85% !important;
        margin-top: 19px;
    }

    #billing\:homepage {
        width: 85% !important;
        margin-top: 19px;
    }

    #billing\:street1 {
        width: 85% !important;
        margin-top: 19px;
    }

    #billing\:postcode {
        width: 85% !important;
        margin-top: 19px;
    }

    #billing\:city {
        width: 85% !important;
        margin-top: 19px;
    }

    #billing\:country_id {
        width: 85% !important;
    }

    #billing\:telephone {
        width: 80% !important;
        margin-top: 19px;
    }

    #billing\:fax {
        width: 80% !important;
        margin-top: 19px;
    }

    #billing\:telephone_company {
        width: 80% !important;
        margin-top: 19px;
    }

    #billing\:password {
        width: 85% !important;
        margin-top: 19px;
    }

    #billing\:password_confirmation {
        width: 85% !important;
        margin-top: 19px;
    }

    .plusIcon {
        width: 4%;
        float: left;
        padding-top: 4px;
        font-weight: bold !important;
        font-size: 18px !important;
        margin-left: 10px !important;
    }

    .checkoutBillingAddressPhoneField {
        color: black;
        width: 31%;
        float: left;
        margin-bottom: 20px;
        margin-top: 14px;
        margin-left: 25px;
        height: 78px;
    }

    #billing_phone_address_contact {
        width: 91%;
        border: 1px solid #A9A9A9;
        padding-left: 5px;
        height: 28px;
        margin-left: 3px;
    }

    @media (min-width: 1px) and (max-width: 641px) {
        #checkout_saveBillingButton {
            margin-left: 51% !important;
            width: 120px !important;
        }
        #co-billing-form {
            height: 2037px;
        }
        .billingAdressContainer {
            height: 2037px;
        }
        .checkoutBillingAddressRow {
            padding-left: 6%;
        }
        .checkoutBillingEmailAddressField {
            width: 90%;
        }
        .checkoutBillingGenderField {
            width: 90%;
        }
        .checkoutBillingFirstnameField {
            width: 90%;
            margin-left: 6%;
        }
        .checkoutBillingLastnameField {
            width: 90%;
        }
        .checkoutBillingCompanynameLastname {
            width: 90%;
            height: 36px;
        }
        .checkoutBillingCompanynameCompany {
            width: 90%;
            margin-left: 6%;
        }
        .checkoutBillingCompanynameFirstname {
            width: 90%;
        }
        .checkoutBillingCompanydataVATIdentificationNumber {
            width: 90%;
        }
        .checkoutBillingCompanydataRegistrationNumber {
            width: 90%;
        }
        .checkoutBillingCompanyWebsite {
            width: 90%;
        }
        .checkoutBillingStreet1Field {
            width: 90%;
        }
        .checkoutBillingPostcodeField {
            width: 90%;
        }
        .checkoutBillingCityField {
            width: 90%;
        }
        .checkoutBillingCountryField {
            width: 90%;
        }
        .checkoutBillingTelephoneField {
            width: 90%;
        }
        .checkoutBillingFaxField {
            width: 90%;
        }
        .checkoutBillingTelephoneCompanyField {
            width: 90%;
        }
        .checkoutPasswordField {
            width: 90%;
        }
        .checkoutBillingAddressPhoneField {
            width: 90%;
        }
    }

    @media (min-width: 642px) and (max-width: 1133px) {
        .checkoutBillingAddressRow {
            padding-left: 6%;
        }
        .checkoutBillingEmailAddressField {
            width: 39%;
        }
        .checkoutBillingGenderField {
            width: 39%;
        }
        .checkoutBillingFirstnameField {
            width: 39%;
            margin-left: 6%;
        }
        .checkoutBillingLastnameField {
            width: 39%;
        }
        .checkoutBillingCompanynameLastname {
            width: 39%;
        }
        .checkoutBillingCompanynameCompany {
            width: 39%;
            margin-left: 6%;
        }
        .checkoutBillingCompanynameFirstname {
            width: 39%;
        }
        .checkoutBillingCompanydataVATIdentificationNumber {
            width: 39%;
        }
        .checkoutBillingCompanydataRegistrationNumber {
            width: 39%;
            margin-left: 6%;
        }
        .checkoutBillingCompanyWebsite {
            width: 39%;
        }
        .checkoutBillingStreet1Field {
            width: 39%;
        }
        .checkoutBillingPostcodeField {
            width: 39%;
            margin-left: 6%;
        }
        .checkoutBillingCountryField {
            width: 39%;
        }
        .checkoutBillingTelephoneField {
            width: 39%;
        }
        .checkoutBillingFaxField {
            width: 39%;
            margin-left: 6%;
        }
        .checkoutBillingTelephoneCompanyField {
            width: 39%;
        }
        .checkoutPasswordField {
            width: 39%;
        }
        .checkoutTelephoneFaxHeadlineText {
            /* font-size: 0.9em; */
            width: 120%;
        }
        #advice-required-entry-billing\:city {
            width: 100%;
        }
        #advice-validate-select-billing\:gender {
            width: 100%;
            font-size: 0.9em;
        }
        #billing\:email {
            width: 100% !important;
        }
        #billing\:gender {
            width: 100% !important;
        }
        #billing\:person-firstname {
            width: 100% !important;
        }
        #billing\:person-lastname {
            width: 100% !important;
        }
        #billing\:lastname {
            width: 100% !important;
        }
        #billing\:company {
            width: 100% !important;
        }
        #billing\:firstname {
            width: 100% !important;
        }
        #billing\:companyuid {
            width: 100% !important;
        }
        #billing\:companyregistrationnumber {
            width: 100% !important;
        }
        #billing\:homepage {
            width: 100% !important;
        }
        #billing\:street1 {
            width: 100% !important;
        }
        #billing\:postcode {
            width: 100% !important;
        }
        #billing\:city {
            width: 100% !important;
        }
        #billing\:country_id {
            width: 100% !important;
        }
        #billing\:telephone {
            width: 86% !important;
        }
        #billing\:fax {
            width: 86% !important;
        }
        #billing\:telephone_company {
            width: 86% !important;
        }
        .checkoutBillingAddressPhoneField {
            width: 39%;
            margin-left: 6%;
        }
        #billing_phone_address_contact {
            margin-left: 8px;
            width: 86% !important;
        }
    }

    @media (min-width: 992px) and (max-width: 1132px) {
        #co-billing-form {
            height: 1553px;
        }
        .billingAdressContainer {
            height: 1566px;
        }
    }

    @media (min-width: 642px) and (max-width: 991px) {
        #co-billing-form {
            height: 1650px;
        }
        .billingAdressContainer {
            height: 1663px;
        }
    }

    @media (min-width: 1px) and (max-width: 641px) {
        #co-billing-form {
            height: 2298px;
        }
        .billingAdressContainer {
            height: 2298px;
        }
    }
</style>

<form id="co-billing-form" action="" style="display: none">
    <?php echo $this->getBlockHtml('formkey'); ?>
    <input type="hidden" id="useBillingAddressForShipping" value="<?php echo $useBillingAddressForShippingValue ;?>" />
    <div>
        <?php if ($this->customerHasAddresses()): ?>
            <div class="wide">
                <?php if ($this->getCustomer()->isContact() || $this->getCustomer()->isProspect()) : ?>
                    <address>
                        <?php echo $this->getCustomer()->getPrimaryBillingAddress()->format('html') ?>
                    </address>
                <?php else: ?>
                    <div class="input-box">
                        <label for="billing-address-select">
                            <?php echo $this->__('Select a billing address from your address book or enter a new address.') ?>
                        </label>
                        <?php echo $this->getAddressesHtmlSelect('billing') ?>
                    </div>
                <?php endif; ?>
            </div>
        <?php endif; ?>
        <div id="fieldAreaBilling"></div>
        <div id="billing-new-address-form"<?php if (true): ?> style="display: none;"<?php endif; ?>>
            <div class="billingAdressContainer">
                <div>
                    <?php if(!$this->isCustomerLoggedIn()): ?>
                        <div class="checkoutBillingAddressRow">
                            <div class="checkoutBillingEmailAddressField">
                                <div><em style="color: red;"> *</em> <?php echo $this->__('Email Address') ?>&nbsp;&nbsp;</div>
                                <div>
                                    <label for="billing:email" class="required"></label>
                                    <div class="input-box">
                                        <input type="text" name="billing[email]" id="billing:email" value="" title="<?php echo $this->__('Email Address') ?>" class="input-text validate-email required-entry" />
                                    </div>
                                    <div id="resultingErrorMessageEMAIL" style="position: absolute; font-size: 1em; color: #D1222B; margin-top: -44px; margin-left: 0px; width: 410px; "></div>
                                </div>
                            </div>
                            <div style="clear: both;"></div>
                        </div>
                        <div class="checkoutBillingAddressRow">
                            <div class="checkoutBillingGenderField">
                                <div><em style="color: red;"> *</em> <?php echo $this->__('Gender') ?>&nbsp;&nbsp;</div>
                                <div>
                                    <label for="billing:gender" class="required"></label>
                                    <div class="input-box">
                                        <select name="billing[gender]" id="billing:gender" title="<?php echo $this->__('Gender') ?>" class="validate-select">
                                            <option value=""></option>
                                            <option value="1"><?php echo $this->__('Male'); ?></option>
                                            <option value="2"><?php echo $this->__('Female'); ?></option>
                                        </select>
                                    </div>
                                </div>
                            </div>
                            <div class="checkoutBillingFirstnameField">
                                <div id="personFirstnameLegendBilling"><em style="color: red;"> *</em> <?php echo $this->__('First Name') ?>&nbsp;&nbsp;</div>
                                <div>
                                    <label for="billing:person-firstname" class="required"></label>
                                    <div class="input-box">
                                        <input type="text" title="<?php echo $this->__('First Name') ?>" name="billing[person-firstname]" id="billing:person-firstname" value="" class="input-text required-entry" maxlength="30" />
                                    </div>
                                </div>
                            </div>
                            <div class="checkoutBillingLastnameField">
                                <div><em style="color: red;"> *</em> <?php echo $this->__('Last Name') ?>&nbsp;&nbsp;</div>
                                <div>
                                    <label for="billing:person-lastname" class="required"></label>
                                    <div class="input-box">
                                        <input type="text" title="<?php echo $this->__('Last Name') ?>" name="billing[person-lastname]" id="billing:person-lastname" value="" class="input-text required-entry" maxlength="30" />
                                    </div>
                                </div>
                            </div>
                            <div style="clear: both;"></div>
                        </div>
                    <?php endif; ?>
                    <input type="hidden" id="billing:customertype" name="billing[customertype]" value="" class="customertype input-text">

                        <div class="checkoutBillingAddressRow">
                            <div class="checkoutBillingCompanynameLastname">
                                <div><em style="color: red;"> *</em> <?php echo $this->__('Company') ?>&nbsp;&nbsp;</div>
                                <div>
                                    <div class="required"></div>
                                    <div class="input-box">
                                        <input type="text" id="billing:lastname" name="billing[lastname]" value="" title="<?php echo $this->__('Company') ?>" class="input-text required-entry" maxlength="30" />
                                    </div>
                                </div>
                            </div>
                            <div class="checkoutBillingCompanynameCompany">
                                <div>&nbsp;</div>
                                <div>
                                    <div class="input-box">
                                        <input type="text" id="billing:company" name="billing[company]" value="" title="<?php echo $this->__('Company') ?>" class="input-text" maxlength="30" />
                                    </div>
                                </div>
                            </div>
                            <div class="checkoutBillingCompanynameFirstname">
                                <div class="billing_firstname"><?php echo $this->__('ContactPerson') ?></div>
                                <div>
                                    <div class="input-box">
                                        <input type="text" id="billing:firstname" name="billing[firstname]" value="" title="<?php echo $this->__('ContactPerson') ?>" class="input-text" maxlength="30" />
                                    </div>
                                </div>
                            </div>
                            <div style="clear: both;"></div>
                        </div>

                        <div class="checkoutBillingAddressRow">
                            <div id="companyDataFieldset">
                                <?php // Condition for backend setting (Use local vat yes/no) ?>
                                <?php if(Mage::getStoreConfig('schrack/new_self_registration/triggerLocalVat')) : ?>
                                    <div id="vat_identification_number_local_selector">
                                        <input type="radio" name="vat_special_billing" value="vat_normal" checked="checked" /> <?php echo $this->__('VAT Normal') ?><br>
                                        <input type="radio" name="vat_special_billing" value="vat_local" /> <?php echo $this->__('VAT Local') ?>
                                    </div>
                                <?php endif; ?>

                                <div id="vat_identification_number-field" class="checkoutBillingCompanydataVATIdentificationNumber">
                                    <?php if (Mage::getStoreConfig('schrack/vatcheck/required')) : ?>
                                        <div for="billing:companyuid" style="color: #000;" class="required"><em style="color: red;"> *</em>
                                     <?php else: ?>
                                        <div for="vat_identification_number">
                                     <?php endif; ?>
                                            <?php echo $this->__('VAT Identification Number') ?>
                                            <div class="input-box">
                                                <input type="text" name="billing[companyuid][]" id="billing:companyuid" value="" title="" class="input-text<?php if (Mage::getStoreConfig('schrack/vatcheck/required')) echo ' required-entry'; ?>" />
                                            </div>
                                            <div id="resultingErrorMessageVATBilling" style="position: absolute; font-size: 1em; color: #D1222B; margin-top: -83px; margin-left: 75px; width: 410px; background: #EEEEEE;"></div>
                                        </div>
                                </div>
                                <div id="company-registration-number-field" class="checkoutBillingCompanydataRegistrationNumber">
                                    <?php if (Mage::getStoreConfig('schrack/vatcheck/comregrequired')) : ?>
                                        <?php if (!Mage::getStoreConfig('schrack/vatcheck/required')) : ?>
                                            <!-- <div class="customHeightDistance"></div> -->
                                        <?php endif ?>
                                        <div for="billing:companyregistrationnumber" style="color: #000;" class="required"><em style="color: red;"> *</em>
                                     <?php else: ?>
                                        <?php if (!Mage::getStoreConfig('schrack/vatcheck/required')) : ?>
                                            <!-- <div class="customHeightDistance"></div> -->
                                        <?php endif ?>
                                            <div class="company_registration_number_label">
                                     <?php endif ?>
                                                <?php echo $this->__('Company Registration Number') ?>
                                            </div>
                                            <div class="input-box">
                                                <input type="text" name="billing[companyregistrationnumber][]" id="billing:companyregistrationnumber" maxlength="14" value="" title="<?php echo $this->__('Company Registration Number') ?>" class="input-text<?php if (Mage::getStoreConfig('schrack/vatcheck/comregrequired')) echo ' required-entry'; ?>" />
                                            </div>
                                        </div>
                                        <?php if (!Mage::getStoreConfig('schrack/new_self_registration/triggerLocalVat')) : ?>
                                            <!-- v<div class="customHeightDistance"></div> -->
                                        <?php endif ?>
                                    </div>

                                    <div id="website-field" class="checkoutBillingCompanyWebsite">
                                        <div class="homepage" style="color: #000000 !important;"><?php echo $this->__('Website') ?></div>
                                        <div class="input-box">
                                            <input type="text" name="billing[homepage][]" id="billing:homepage" value="" title="<?php echo $this->__('Website') ?>" class="textInput input-text" />
                                        </div>
                                    </div>
                                    <div style="clear: both;"></div>
                                </div>
                            </div>


                    <div class="checkoutBillingAddressRow">
                        <div class="checkoutBillingStreet1Field">
                            <div><em style="color: red;"> *</em> <?php echo $this->__('Street Address') ?>&nbsp;&nbsp;</div>
                            <div>
                                <div for="billing:street1" class="required"></div>
                                <div class="input-box">
                                    <input type="text" title="<?php echo $this->__('Street Address') ?>" name="billing[street][]" id="billing:street1" value="" class="input-text required-entry" maxlength="30" />
                                </div>
                            </div>
                            <?php for ($_i=2, $_n=$this->helper('customer/address')->getStreetLines(); $_i<=$_n; $_i++): ?>
                                <div>
                                    <div for="billing:street<?php echo $_i?>" class="required"></div>
                                    <div class="input-box">
                                        <input type="text" style="width: 85% !important; margin-top: 19px;" title="<?php echo $this->__('Street Address '.$_i) ?>" name="billing[street][]" id="billing:street<?php echo $_i?>" value="" class="input-text" maxlength="30" />
                                    </div>>
                                </div>
                            <?php endfor ?>
                        </div>

                        <div class="checkoutBillingPostcodeField">
                            <div id="postcodeLegendBilling"><span style="color: red;"> *</span> <?php echo $this->__('Zip') ?>&nbsp;&nbsp;</div>
                            <div>
                                <div for="billing:postcode" class="required"></div>
                                <div class="input-box">
                                    <input type="text" title="<?php echo $this->__('Zip') ?>" name="billing[postcode]" id="billing:postcode" value="" class="input-text validate-zip-international required-entry" maxlength="8" />
                                </div>
                            </div>
                        </div>

                        <div class="checkoutBillingCityField">
                            <div><em style="color: red;"> *</em> <?php echo $this->__('City') ?>&nbsp;&nbsp;</div>
                            <div>
                                <div for="billing:city" class="required"></div>
                                <div class="input-box">
                                    <input type="text" title="<?php echo $this->__('City') ?>" name="billing[city]" value="" class="input-text required-entry" id="billing:city" maxlength="30" />
                                </div>
                            </div>
                        </div>

                        <div class="checkoutBillingStateField">
                            <div><em style="color: red;"> *</em> <?php echo $this->__('State/Province') ?>&nbsp;&nbsp;</div>
                            <div>
                                <div for="billing:region_id" class="required"></div>
                                <div class="input-box">
                                    <!-- <select style="width: 85% !important;" id="billing:region_id" name="billing[region_id]" title="<?php echo $this->__('State/Province') ?>" class="validate-select" style="display:none;" defaultValue="<?php echo $this->getAddress()->getRegionId() ?>">
                                        <option value=""><?php //echo $this->__('Please select region, state or province') ?></option>
                                    </select> -->
                                    <script type="text/javascript">
                                        //<![CDATA[
                                        //$('billing:region_id').setAttribute('defaultValue',  "<?php //echo $this->getAddress()->getRegionId() ?>");
                                        //]]>
                                    </script>
                                    <input type="text" id="billing:region" name="billing[region]" value="<?php //echo $this->htmlEscape($this->getAddress()->getRegion()) ?>"  title="<?php echo $this->__('State/Province') ?>" class="input-text" style="display:none;" />
                                </div>
                            </div>
                        </div>
                        <div style="clear: both;"></div>
                    </div>

                    <div class="checkoutBillingAddressRow">
                        <div class="checkoutBillingCountryField">
                            <div><em style="color: red;"> *</em> <?php echo $this->__('Country') ?>&nbsp;&nbsp;</div>
                            <div>
                                <div for="billing:country_id" class="required"></div>
                                <div id="country-select-dynamic" class="input-box">
                                    <?php if(!Mage::getStoreConfig('schrack/vatcheck/contry_selectable')): ?>
                                        <input type="hidden" id="billing:country_id" name="billing[country_id]" value="<?php echo Mage::helper('core')->getDefaultCountry(); ?>">
                                        <input type="text" value=" <?php echo Mage::app()->getLocale()->getCountryTranslation(Mage::helper('core')->getDefaultCountry()) ?>" style="width: 85% !important; margin-top: 19px; background: #d3d3d3" readonly="readonly">
                                    <?php else : ?>
                                        <?php echo $this->getCountryHtmlSelect('billing') ?>
                                    <?php endif ?>
                                </div>
                            </div>
                        </div>
                        <div class="checkoutBillingAddressPhoneField">
                            <div><?php echo $this->__('PhoneAddressContact') ?>&nbsp;&nbsp;</div>
                            <div>
                                <div for="billing:schrack_address_phone"></div>
                                <div class="input-box" style="width: 85% !important; margin-top: 16px;">
                                    <div class="plusIcon">+</div>
                                    <input type="tel" name="billing[phone_address_contact]" id="billing_phone_address_contact" value="" maxlength="30" />
                                </div>
                            </div>
                        </div>
                        <div style="clear: both;"></div>
                    </div>

                    <div class="checkoutBillingAddressRow">
                        <div class="checkoutBillingTelephoneField">
                            <div><em style="color: red;"> *</em> <?php echo $this->__('Telephone') ?>&nbsp;&nbsp;</div>
                            <div>
                                <div for="billing:telephone" class="required"></div>
                                <div class="input-box">
                                    <div id="billing_telephone_plus_symbol">+</div>
                                    <input type="tel" name="billing[telephone]" id="billing:telephone" value="<?php echo $this->htmlEscape($this->getAddress()->getTelephone()) ?>" title="<?php echo $this->__('Telephone') ?>" class="input-text required-entry checkoutBillingTelephone" />
                                </div>
                            </div>
                        </div>
                        <div class="checkoutBillingFaxField">
                            <div class="checkoutTelephoneFaxHeadlineText"> <?php echo $this->__('Fax') ?>&nbsp;&nbsp;</div>
                            <div>
                                <div for="billing:fax"></div>
                                <div class="input-box">
                                    <div id="billing_fax_plus_symbol">+</div>
                                    <input type="tel" name="billing[fax]" value="<?php echo $this->htmlEscape($this->getAddress()->getFax()) ?>" title="<?php echo $this->__('Fax') ?>" class="input-text checkoutBillingTelephoneFax" id="billing:fax" />
                                </div>
                            </div>
                        </div>
                        <div class="checkoutBillingTelephoneCompanyField">
                            <div><?php echo $this->__('Telephone Company') ?>&nbsp;&nbsp;</div>
                            <div>
                                <div for="billing:telephone_company"></div>
                                <div class="input-box">
                                    <div id="billing_telephone_company__plus_symbol">+</div>
                                    <input type="tel" name="billing[telephone_company]" id="billing:telephone_company" value="" title="<?php echo $this->__('Telephone Company') ?>" class="input-text checkoutBillingTelephoneCompany" />
                                </div>
                            </div>
                        </div>
                        <div style="clear: both;"></div>
                    </div>

                    <div id="registerPasswordFields" class="checkoutBillingAddressRow">
                        <div class="checkoutPasswordField">
                            <div><em style="color: red;"> *</em> <?php echo $this->__('Password') ?>&nbsp;&nbsp;</div>
                            <div>
                                <div for="billing:password" class="required"></div>
                                <div class="input-box">
                                    <input type="password" name="billing[password]" id="billing:password" title="<?php echo $this->__('Password') ?>" class="input-text required-entry password-check" />
                                    <div id="billing_password_error_message" style="color: #d1222b;"></div>
                                </div>
                            </div>
                        </div>
                        <div class="checkoutPasswordField">
                            <div><em style="color: red;"> *</em> <?php echo $this->__('Confirm Password') ?>&nbsp;&nbsp;</div>
                            <div>
                                <div for="billing:password_confirmation" class="required"></div>
                                <div class="input-box">
                                    <input type="password" name="billing[password_confirmation]" id="billing:password_confirmation" title="<?php echo $this->__('Confirm Password') ?>" class="input-text required-entry password-equal-check" />
                                    <div id="billing_password_confirmation_error_message" style="color: #d1222b;"></div>
                                </div>
                            </div>
                        </div>
                    </div>

                    <?php if(!$this->isCustomerLoggedIn()): ?>
                        <?php $_taxvat = $this->getLayout()->createBlock('customer/widget_taxvat') /* @var $_taxvat Mage_Customer_Block_Widget_Taxvat */ ?>
                        <?php if ($_taxvat->isEnabled()): ?>
                        <div style="border: 1px solid #d6d6d6; color: black; width: 350px; float: left; margin-right: 25px; margin-bottom: 20px; margin-top: 14px; margin-left: 25px; height: 82px;">
                            <div>
                                <?php echo $_taxvat->setTaxvat($this->getQuote()->getCustomerTaxvat())->setFieldIdFormat('billing:%s')->setFieldNameFormat('billing[%s]')->toHtml() ?>
                            </div>
                        </div>
                        <?php endif ?>

                    <?php endif; ?>
                    <?php if ($this->isCustomerLoggedIn() && $this->customerHasAddresses()):?>
                        <div style="clear: both;"></div>
                        <?php if (false):?>
                            <div style="border: 1px solid #d6d6d6; color: black; width: 361px; float: left; margin-right: 25px; margin-bottom: 20px; margin-top: 14px; margin-left: 25px; height: 51px;">
                                <div>
                                    <div class="customHeightDistance"></div>
                                    <input type="checkbox" name="billing[save_in_address_book]" value="1" title="<?php echo $this->__('Save in address book') ?>" id="billing:save_in_address_book" onchange="shipping.setSameAsBilling(false);"<?php if ($this->getAddress()->getSaveInAddressBook()):?> checked="checked"<?php endif;?> class="checkbox" /><label for="billing:save_in_address_book"><?php echo $this->__('Save in address book') ?></label>
                                </div>
                            </div>
                        <?php endif; ?>
                    <?php else:?>
                        <div class="no-display"><input type="hidden" name="billing[save_in_address_book]" value="1" /></div>
                    <?php endif; ?>
                    <div style="float: left; margin-left: 25px; margin-top: 25px !important;">
                        <p class="required" style="color: #000; font-weight: bold;"><?php echo $this->__('* Required Fields') ?></p>
                    </div>

                <div class="buttons-set" id="billing-buttons-container">
                    <button id="checkout_saveBillingButton" type="button" title="<?php echo $this->__('Continue') ?>" class="bttn-lg checkout_saveBillingButton">
                        <span id="billing-please-wait" class="please-wait"
                              style="display: none; float: left; padding-left: 20px; text-align: left; background:url('<?php echo $this->getSkinUrl('images/opc-ajax-loader.gif') ?>') left center no-repeat;">
                        &nbsp;
                        </span>
                        <span id="checkout_saveBillingButtonContinue"><?php echo $this->__('Continue') ?></span>
                    </button>
                </div>
            </div>
         </div>
        <?php if ($this->canShip()): ?>
            <div class="customHeightDistance"></div>
            <div id="alternate-delivery-address-choser" style="display: none;">
                <div class="control">
                    <input type="radio" name="billing[use_for_shipping]" id="billing:use_for_shipping_yes" value="1" title="<?php echo  $this->__('Ship to this address') ?>" class="usebilling_address_for_shipping_yes radio" /><label for="billing:use_for_shipping_yes"><?php echo  $this->__('Ship to this address') ?></label>
                </div>
                <div class="control">
                    <input type="radio" name="billing[use_for_shipping]" id="billing:use_for_shipping_no" value="0"  title="<?php echo $this->__('Ship to different address') ?>" class="usebilling_address_for_shipping_no radio" /><label for="billing:use_for_shipping_no"><?php echo $this->__('Ship to different address') ?></label>
                </div>
            </div>
        <?php endif; ?>
        <?php if (!$this->canShip()): ?>
            <input type="hidden" name="billing[use_for_shipping]" value="1" />
        <?php endif; ?>
    </div>
</form>

<script type="text/javascript">
//<![CDATA[

    let guest_inpost = localStorage.newCheckoutShippingMethod;

    if(guest_inpost == "inpost") {
        jQuery('#opc-billing').hide();
        //jQuery('#inpostGuestContinueButton').hide();
    }

    var billing = new Billing('co-billing-form', '<?php echo $this->getUrl('checkout/onepage/getAddress') ?>address/', '<?php echo $this->getUrl('checkout/onepage/saveBilling') ?>');
    var billingForm = new VarienForm('co-billing-form');

    //billingForm.setElementsRelation('billing:country_id', 'billing:region', '<?php echo $this->getUrl('directory/json/childRegion') ?>', '<?php echo $this->__('Select State/Province...') ?>');
    jQuery('billing-address-select') && billing.newAddress(!jQuery('billing-address-select').value);

    //var billingRegionUpdater = new RegionUpdater('billing:country_id', 'billing:region', 'billing:region_id', countryRegions, undefined, 'billing:postcode');

jQuery(document).ready(function() {
    jQuery('#checkSelectionButton').on('click', function() {
        jQuery('#opc-billing').show();
    });

    var localeCode = '<?php echo $localeCode; ?>';

    jQuery('#billing\\:telephone').on('paste', function() {
        return false;
    });

    jQuery('#billing\\:fax').on('paste', function() {
        return false;
    });

    jQuery('#billing\\:telephone_company').on('paste', function() {
        return false;
    });

    jQuery('#billing\\:telephone').on('keyup', function() {
        removeForbiddenPhoneFieldCharacters('billing\\:telephone');
    });

    jQuery('#billing\\:fax').on('keyup', function() {
        removeForbiddenPhoneFieldCharacters('billing\\:fax');
    });

    jQuery('#billing\\:telephone_company').on('keyup', function() {
        removeForbiddenPhoneFieldCharacters('billing\\:telephone_company');
    });

    function checkPassword () {
        if ( localStorage.newCheckoutProcessCurrentRole == 'guest' )
            return true;
        var pw = jQuery('#billing\\:password').val();
        if ( pw.length < 8 )
            return passwordCheckFailed();
        if ( ! pw.match(/[a-z]/i) )
            return passwordCheckFailed();
        if ( ! pw.match(/[0-9]/) )
            return passwordCheckFailed();
        return true;
    }

    function checkPasswordConfirmation () {
        if ( localStorage.newCheckoutProcessCurrentRole == 'guest' )
            return true;
        var pw = jQuery('#billing\\:password').val();
        var pwc = jQuery('#billing\\:password_confirmation').val();
        if ( pw != pwc ) {
            jQuery('#billing_password_confirmation_error_message').text('<?php echo $this->__("Please make sure your passwords match."); ?>');
            jQuery('#billing\\:password_confirmation').css('border', '2px solid #d1222b');
            return false;
        }
        return true;
    }

    function passwordCheckFailed () {
        jQuery('#billing_password_error_message').text('<?php echo $this->__("The new password must have at least 8 characters and must contain at least one digit and one letter."); ?>');
        jQuery('#billing\\:password').css('border', '2px solid #d1222b');
        return false;
    }

    var setOverlayLoaderBilling = function() {
        // Set overlay for
        jQuery('#fieldAreaBilling').css({  "position": "absolute",
            "height": "100%",
            "width": "100%",
            "background": "url(<?php echo $this->getSkinUrl('schrackdesign/Public/Images/download_ajax_loader.gif'); ?>) no-repeat center center",
            "top": "-15px",
            "left": "0",
            "opacity": "0.4",
            "z-index": "99"});
    }

    var checkUIDBilling = function () {
        var ad_street   = jQuery('#billing\\:street1').val();
        var ad_postcode = jQuery('#billing\\:postcode').val();
        var ad_city     = jQuery('#billing\\:city').val();
        var ad_country  = jQuery('#billing\\:country_id').val();

        var needsValidation = true;
        if (ad_street == "" && ad_postcode == "" && ad_city == "") {
            needsValidation = false;
        }

        setOverlayLoaderBilling();
        var checkData = {
            'vat_identification_number' : jQuery('#billing\\:companyuid').val(),
            'email' : jQuery('#billing\\:email').val(),
            'name1' : jQuery('#billing\\:lastname').val(),
            'name2' : jQuery('#billing\\:company').val(),
            'name3' : jQuery('#billing\\:firstname').val(),
            'firstname' : jQuery('#billing\\:person-firstname').val(),
            'lastname' : jQuery('#billing\\:person-lastname').val(),
            'schrack_telephone' : jQuery('#billing\\:telephone').val(),
            'user_selected_country' : jQuery('#billing\\:country_id').val()
        };
        if (jQuery('input[name="vat_special_billing"]') && jQuery('input[name="vat_special_billing"]:checked').val() == 'vat_local') {
            // Don't check VAT intensively (just execute normal success actions)!
            jQuery('#fieldAreaBilling').removeAttr('style');
            jQuery('#billing\\:companyuid').removeClass('validation-failed');
            if (needsValidation == true) {
                deferredAddressValidation('billing',
                    ad_street,
                    ad_postcode,
                    ad_city,
                    ad_country,
                    'billing_1'
                );
            } else {
                billing.save();
            }
        } else {
            jQuery.ajax({
                url: '<?php echo Mage::getUrl('customer/account/checkUid'); ?>',
                type: 'post',
                dataType: 'json',
                data: checkData,
                success: function(data) {
                    if (data.errormsg) {
                        jQuery('#resultingErrorMessageVATBilling').text(data.errormsg);
                        jQuery('#resultingErrorMessageVATBilling').show();
                        jQuery('#billing\\:companyuid').addClass('validation-failed');
                    } else {
                        jQuery('#billing\\:companyuid').removeClass('validation-failed');
                        if (needsValidation == true) {
                            deferredAddressValidation('billing',
                                ad_street,
                                ad_postcode,
                                ad_city,
                                ad_country,
                                'billing_2'
                            );
                        }  else {
                            billing.save();
                        }
                    }
                },
                error: function (data) {
                    // console.log('error');
                },
                complete: function () {
                    jQuery('#fieldAreaBilling').removeAttr('style');
                    //console.log('complete');
                }
            });
        }
    }


    var checkLocalVATBilling = function () {
    // Special route for option of local VAT:
    // Check, if partial HTML-Snippet with radio-buttons existing:
        if (jQuery('input[name="vat_special_billing"]')) {
            if (jQuery('input[name="vat_special_billing"]:checked').val() == 'vat_local') {
                // Only check number of characters (= 8) and type of chars (must be integer):
                if (localeCode == 'sk') {
                    var reg = new RegExp('^[0-9]{10}$');
                    var errorMessage = '<?php echo $this->__('Please Enter 10 Numbers'); ?>';
                } else {
                    var reg = new RegExp('^[0-9]{8}$');
                    var errorMessage = '<?php echo $this->__('Please Enter 8 Numbers'); ?>';
                }
                if (!reg.test(jQuery('#billing\\:companyuid').val())) {
                    if (jQuery('#billing\\:companyuid').val() != '') {
                        // Show error and do nothing
                        jQuery('#resultingErrorMessageVATBilling').text('');
                        jQuery('#resultingErrorMessageVATBilling').css({'margin-left' : '0px'});
                        jQuery('#resultingErrorMessageVATBilling').text(errorMessage);
                        jQuery('#resultingErrorMessageVATBilling').show();
                        jQuery('#billing\\:companyuid').addClass('validation-failed');
                        return false;
                    }
                } else {
                    // Now check form for other issues:
                    jQuery('#billing\\:companyuid').removeClass('validation-failed');
                    jQuery('#resultingErrorMessageVATBilling').text('');
                    jQuery('#resultingErrorMessageVATBilling').css({'margin-left' : '75px'});
                    jQuery('#resultingErrorMessageVATBilling').hide();
                    localStorage.newCheckoutLocalVAT = 1;
                    return true;
                }
            } else {
                localStorage.newCheckoutLocalVAT = 0;
                return true;
            }
        } else {
            localStorage.newCheckoutLocalVAT = 0;
            return true;
        }
    }


    var checkEmailDoubletteBilling = function () {
        var ad_street   = jQuery('#billing\\:street1').val();
        var ad_postcode = jQuery('#billing\\:postcode').val();
        var ad_city     = jQuery('#billing\\:city').val();
        var ad_country  = jQuery('#billing\\:country_id').val();

        var needsValidation = true;
        if (ad_street == "" && ad_postcode == "" && ad_city == "") {
            needsValidation = false;
        }

        var checkData = {
            'email' : jQuery('#billing\\:email').val(),
            'validate' : true
        };
        if (jQuery('#billing\\:email').length == 0) {
            if (needsValidation == true) {
                deferredAddressValidation('billing',
                    ad_street,
                    ad_postcode,
                    ad_city,
                    ad_country,
                    'billing_3'
                );
            } else {
                billing.save();
            }
        }
        if (jQuery('#billing\\:email').val() != '') {
            jQuery.ajax({
                url: '<?php echo Mage::getUrl('customer/account/checkCommonEmail'); ?>',
                type: 'post',
                dataType: 'json',
                data: checkData,
                success: function(data) {
                    if (data.errormsg) {
                        jQuery('#advice-required-entry-billing\\:email').css({'opacity' : '0', 'display' : 'none'});
                        jQuery('#resultingErrorMessageEMAIL').text(data.errormsg);
                        jQuery('#resultingErrorMessageEMAIL').show();
                        jQuery('#billing\\:email').addClass('validation-failed');
                    } else {
                        jQuery('#billing\\:email').removeClass('validation-failed');
                        <?php if (Mage::getStoreConfig('schrack/vatcheck/enabled')): ?>
                        if (jQuery('#billing\\:companyuid').val() != '') {
                            checkUIDBilling();
                        } else {
                            console.log('save1');
                            if (needsValidation == true) {
                                deferredAddressValidation('billing',
                                    ad_street,
                                    ad_postcode,
                                    ad_city,
                                    ad_country,
                                    'billing_4'
                                );
                            } else {
                                billing.save();
                            }
                        }
                        <?php else : ?>
                            console.log('save2');
                            if (needsValidation == true) {
                                deferredAddressValidation('billing',
                                    ad_street,
                                    ad_postcode,
                                    ad_city,
                                    ad_country,
                                    'billing_5'
                                );
                            } else {
                                billing.save();
                            }
                        <?php endif; ?>
                    }
                },
                error: function (data) {
                    console.log('error');
                },
                complete: function () {
                    jQuery('#fieldAreaBilling').removeAttr('style');
                    // console.log('complete');
                }
            });
        } else {
            jQuery('#fieldAreaBilling').removeAttr('style');
            if (needsValidation == true) {
                deferredAddressValidation('billing',
                    ad_street,
                    ad_postcode,
                    ad_city,
                    ad_country,
                    'billing_6'
                );
            } else {
                billing.save();
            }
        }
    }

    //jQuery('#postcodeLegendBilling').text(jQuery('#postcodeLegendBilling').text().replace('* *','<em style="color: red;">* </em>'));

    jQuery('.checkout_saveBillingButton').on('click', function() {
        if ( ! checkPassword() || ! checkPasswordConfirmation() ) {
            return false;
        }
        if(localStorage.newCheckoutProcessCurrentRole == 'prospect-user' && localStorage.newCheckoutShippingMethod == 'inpost') {
            console.log("billing phtml -> prospect-user & inpost");
            //localStorage.newCheckoutProcessCurrentStep == 'opc-payment';

            //jQuery('#checkout-step-payment').show();
        }

        jQuery('#checkout_saveBillingButtonContinue').hide();
        if (jQuery('#billing\\:postcode').val() != '') {
            jQuery('#billing\\:postcode').removeClass('required-entry');
            jQuery('#advice-required-entry-billing\\:postcode').hide();

            var validateBillingPostcode = jQuery('#billing\\:postcode').val();
            var postcodeRegexes = <?php echo Mage::helper('geoip')->getZipCodeRegexes()?>;
            var countryID = '<?php echo Mage::getStoreConfig('schrack/general/country'); ?>';
            var regexPostcode = '';

            if (regexPostcode[countryID]) {
                regexPostcode = new RegExp(postcodeRegexes[countryID]);
            } else {
                regexPostcode = /\w+/;
            }

            if (regexPostcode.match(validateBillingPostcode) == false && countryID != 'at') {
                jQuery('#billing\\:postcode').addClass('validation-failed');
                jQuery( '<div class="validation-advice" id="validate-must-be-zip-billing:postcode" ><?php echo $this->__('Please enter a valid zip code.')?></div>' ).insertAfter( "#billing\\:postcode" );
                jQuery('#billing\\:street1').removeClass('validation-failed');
                jQuery('#advice-required-entry-billing\\:street1').hide();
                jQuery('#billing\\:city').removeClass('validation-failed');
                jQuery('#advice-required-entry-billing\\:city').hide();
                jQuery('#billing\\:lastname').removeClass('validation-failed');
                jQuery('#advice-required-entry-billing\\:lastname').hide();
                jQuery('#billing\\:email').removeClass('validation-failed');
                jQuery('#advice-required-entry-billing\\:email').hide();
                jQuery('#billing\\:gender').removeClass('validation-failed');
                jQuery('#advice-validate-select-billing\\:gender').hide();
                jQuery('#billing\\:person-firstname').removeClass('validation-failed');
                jQuery('#advice-required-entry-billing\\:person-firstname').hide();
                jQuery('#billing\\:person-lastname').removeClass('validation-failed');
                jQuery('#advice-required-entry-billing\\:person-lastname').hide();
                jQuery('#billing\\:telephone').removeClass('validation-failed');
                jQuery('#advice-required-entry-billing\\:telephone').hide();
                return;
            } else {
                jQuery('#validate-must-be-zip-billing\\:postcode').hide();
            }
        } else{
            jQuery('#validate-must-be-zip-billing\\:postcode').hide();
            jQuery('#billing\\:postcode').addClass('required-entry');
            jQuery('#advice-required-entry-billing\\:postcode').show();
        }

        jQuery('#resultingErrorMessageEMAIL').text('');

        jQuery('.customertype').val(localStorage.newCheckoutProspectRole);
        localStorage.newCheckoutProcessLastUpdateTime = Math.floor(Date.now() / 1000);

        localStorage.newCheckoutProcessEmail                     = jQuery('#billing\\:email').val();
        localStorage.newCheckoutProcessPassword                  = jQuery('#billing\\:password').val();
        localStorage.newCheckoutProcessGender                    = jQuery('#billing\\:gender').val();
        localStorage.newCheckoutProcessPersonFirstname           = jQuery('#billing\\:person-firstname').val();
        localStorage.newCheckoutProcessPersonLastname            = jQuery('#billing\\:person-lastname').val();
        localStorage.newCheckoutProcessName1                     = jQuery('#billing\\:lastname').val();
        localStorage.newCheckoutProcessName2                     = jQuery('#billing\\:company').val();
        localStorage.newCheckoutProcessName3                     = jQuery('#billing\\:firstname').val();
        localStorage.newCheckoutProcessVATIdentificationNumber   = jQuery('#billing\\:companyuid').val();
        localStorage.newCheckoutProcessCompanyRegistrationNumber = jQuery('#billing\\:companyregistrationnumber').val();
        localStorage.newCheckoutHomepage                         = jQuery('#billing\\:homepage').val();
        localStorage.newCheckoutProcessStreet1                   = jQuery('#billing\\:street1').val();
        localStorage.newCheckoutProcessPostcode                  = jQuery('#billing\\:postcode').val();
        localStorage.newCheckoutProcessCity                      = jQuery('#billing\\:city').val();
        //localStorage.newCheckoutProcessRegionId                  = jQuery('#billing\\:region_id').val();
        localStorage.newCheckoutProcessCountryId                 = jQuery('#billing\\:country_id').val();
        localStorage.newCheckoutProcessTelephone                 = jQuery('#billing\\:telephone').val();
        localStorage.newCheckoutProcessTelephoneCompany          = jQuery('#billing\\:telephone_company').val();
        localStorage.newCheckoutProcessFax                       = jQuery('#billing\\:fax').val();

        if(localStorage.newCheckoutProcessCurrentRole == 'guest' && localStorage.newCheckoutShippingMethod == 'inpost' || localStorage.newCheckoutProcessCurrentRole == 'prospect-user' && localStorage.newCheckoutShippingMethod == 'inpost') {
            console.log("billing phtml -> inpost & ", localStorage.newCheckoutProcessCurrentRole);
            localStorage.newCheckoutProcessCurrentStep == 'opc-payment';
        }

        if (localStorage.newCheckoutProcessCurrentRole == 'guest' || localStorage.newCheckoutProcessSpecialAction == 'full-register-prospect-application') {
            // Added: auto filling the contact fields:
            if (jQuery('#billing\\:firstname').val() == "") {
                var firstname_copy = jQuery('#billing\\:person-firstname').val();
                var lastname_copy  = jQuery('#billing\\:person-lastname').val();
                var complete_name_copy = lastname_copy + ' ' + firstname_copy;
                if (complete_name_copy.length > 30) {
                    complete_name_copy = complete_name_copy.substring(0, 30);
                }
                jQuery('#billing\\:firstname').val(complete_name_copy);
            }

            // Autofill phone_address_contact-field, if empty on submit
            if (jQuery('#billing_phone_address_contact').val() == "") {
                var tel_copy = jQuery('#billing\\:telephone').val();
                jQuery('#billing_phone_address_contact').val(tel_copy);
            }

            function checkPhonenumberMinCountryData(elementId, required) {
                var pattRegexCountry = /^\+{0,1}([1-9]\d*)[0-9]{4,17}(-\d+)?$/;
                var result           = false;
                var htmlElementValue = jQuery('#' + elementId).val();
                htmlElementValue     = htmlElementValue.replace(/\s/g,''); // Remove all whitespaces

                if (htmlElementValue) {
                    if(htmlElementValue.match(pattRegexCountry)) {
                        result = true;
                    }
                }

                if (result == false) {
                    jQuery('#' + elementId).removeClass();
                    jQuery('#' + elementId).val('');
                    if (required == true) {
                        jQuery('#' + elementId).addClass('input-text required required-entry validation-failed');
                    } else {
                        jQuery('#' + elementId).addClass('input-text validation-failed');
                    }

                } else {
                    jQuery('#' + elementId).removeClass();
                    if (required == true) {
                        jQuery('#' + elementId).addClass('input-text required required-entry validation-passed');
                    } else {
                        jQuery('#' + elementId).addClass('input-text validation-passed');
                    }
                }

                jQuery('#' + elementId).css({'color' : 'black'});

                return result;
            }

            if (jQuery('#billing\\:telephone').length) {
                checkPhonenumberMinCountryData('billing\\:telephone', true);
            }
            if (jQuery('#billing\\:fax').length) {
                checkPhonenumberMinCountryData('billing\\:fax', false);
            }
            if (jQuery('#billing\\:telephone_company').length) {
                checkPhonenumberMinCountryData('billing\\:telephone_company', false);
            }
        }

<?php if (Mage::getStoreConfig('schrack/vatcheck/enabled')): ?>
        var ad_street   = jQuery('#billing\\:street1').val();
        var ad_postcode = jQuery('#billing\\:postcode').val();
        var ad_city     = jQuery('#billing\\:city').val();
        var ad_country  = jQuery('#billing\\:country_id').val();

        var needsValidation = true;
        if (ad_street == "" && ad_postcode == "" && ad_city == "") {
            needsValidation = false;
        }

        if (localStorage.newCheckoutProcessCurrentRole == 'guest' || localStorage.newCheckoutProcessSpecialAction == 'full-register-prospect-application') {
            jQuery('#resultingErrorMessageVATBilling').text('');
            if (jQuery('#billing\\:companyuid').val() != '') {
                jQuery('#billing\\:companyuid').removeClass('validation-failed');

                jQuery('#advice-required-entry-billing\\:companyuid').css({'opacity' : '0', 'display' : 'none'});
                if (jQuery('#billing\\:email').val() != '') {
                    jQuery('#billing\\:email').removeClass('validation-failed');
                    jQuery('#advice-required-entry-billing\\:email').css({'opacity' : '0', 'display' : 'none'});
                }
                if (jQuery('#billing\\:gender').val() != '') {
                    jQuery('#billing\\:gender').removeClass('validation-failed');
                    jQuery('#advice-required-entry-billing\\:gender').css({'opacity' : '0', 'display' : 'none'});
                    jQuery('#advice-validate-select-billing\\:gender').css({'opacity' : '0', 'display' : 'none'});
                }
                if (jQuery('#billing\\:person-firstname').val() != '') {
                    jQuery('#billing\\:person-firstname').removeClass('validation-failed');
                    jQuery('#advice-required-entry-billing\\:person-firstname').css({'opacity' : '0', 'display' : 'none'});
                }
                if (jQuery('#billing\\:person-lastname').val() != '') {
                    jQuery('#billing\\:person-lastname').removeClass('validation-failed');
                    jQuery('#advice-required-entry-billing\\:person-lastname').css({'opacity' : '0', 'display' : 'none'});
                }
                if (jQuery('#billing\\:lastname').val() != '') {
                    jQuery('#billing\\:lastname').removeClass('validation-failed');
                    jQuery('#advice-required-entry-billing\\:lastname').css({'opacity' : '0', 'display' : 'none'});
                }
                if (jQuery('#billing\\:companyregistrationnumber').val() != '') {
                    jQuery('#billing\\:companyregistrationnumber').removeClass('validation-failed');
                    jQuery('#advice-required-entry-billing\\:companyregistrationnumber').css({'opacity' : '0', 'display' : 'none'});
                }
                if (jQuery('#billing\\:street1').val() != '') {
                    jQuery('#billing\\:street1').removeClass('validation-failed');
                    jQuery('#advice-required-entry-billing\\:street1').css({'opacity' : '0', 'display' : 'none'});
                }
                if (jQuery('#billing\\:postcode').val() != '') {
                    jQuery('#billing\\:postcode').removeClass('validation-failed');
                    jQuery('#advice-required-entry-billing\\:postcode').css({'opacity' : '0', 'display' : 'none'});
                }
                if (jQuery('#billing\\:city').val() != '') {
                    jQuery('#billing\\:city').removeClass('validation-failed');
                    jQuery('#advice-required-entry-billing\\:city').css({'opacity' : '0', 'display' : 'none'});
                }
                /*
                if (jQuery('#billing\\:region_id').val() != '') {
                    jQuery('#billing\\:region_id').removeClass('validation-failed');
                    jQuery('#advice-required-entry-billing\\:region_id').remove();
                }
                */
                if (jQuery('#billing\\:country_id').val() != '') {
                    jQuery('#billing\\:country_id').removeClass('validation-failed');
                    jQuery('#advice-required-entry-billing\\:country_id').css({'opacity' : '0', 'display' : 'none'});
                }
                if (jQuery('#billing\\:telephone').val() != '') {
                    jQuery('#billing\\:telephone').removeClass('validation-failed');
                    jQuery('#advice-required-entry-billing\\:telephone').css({'opacity' : '0', 'display' : 'none'});
                }

                if (checkLocalVATBilling()) {
                    if (jsdebug == 1) console.log('case #101');
                    setOverlayLoaderBilling();
                    checkEmailDoubletteBilling();
                }
                if (jsdebug == 1) console.log('case #102');

                // Check the email field on warnings after some time of processing:
                setTimeout(function() {
                    if (!jQuery('#billing\\:email').hasClass('validation-failed')) {
                        if (jsdebug == 1) console.log('case #01');
                        if (checkLocalVATBilling()) {
                            if (jsdebug == 1) console.log('case #02');
                            setOverlayLoaderBilling();
                            checkUIDBilling()
                        } else {
                            if (jsdebug == 1) console.log('case #03');
                        }
                    }
                }, 1000);
                if (jsdebug == 1) console.log('case #103');
            } else {
                if (jQuery('#billing\\:email').val() != '') {
                    if (jsdebug == 1) console.log('case #04');
                    if (checkLocalVATBilling()) {
                        if (jsdebug == 1) console.log('case #05');
                        setOverlayLoaderBilling();
                        checkEmailDoubletteBilling();
                    }
                } else {
                    if (jsdebug == 1) console.log('case #06');
                    if (checkLocalVATBilling()) {
                        if (jsdebug == 1) console.log('case #07');
                        if (needsValidation == true) {
                            deferredAddressValidation('billing',
                                ad_street,
                                ad_postcode,
                                ad_city,
                                ad_country,
                                'billing_7'
                            );
                        } else {
                            billing.save();
                        }
                    } else {
                        if (jsdebug == 1) console.log('case #08');
                    }
                }
            }
        } else {
            if (jQuery('#billing\\:email').val() != '') {
                if (jsdebug == 1) console.log('case #09');
                if (checkLocalVATBilling()) {
                    if (jsdebug == 1) console.log('case #10');
                    setOverlayLoaderBilling();
                    checkEmailDoubletteBilling();
                } else {
                    if (jsdebug == 1) console.log('case #11');
                }
            } else {
                if (jsdebug == 1) console.log('case #12');
                if (checkLocalVATBilling()) {
                    if (jsdebug == 1) console.log('case #13');
                    if (needsValidation == true) {
                        deferredAddressValidation('billing',
                            ad_street,
                            ad_postcode,
                            ad_city,
                            ad_country,
                            'billing_8'
                        );
                    } else {
                        billing.save();
                    }
                } else {
                    if (jsdebug == 1) console.log('case #14');
                }
            }
        }
<?php else: ?>
        if (jQuery('#billing\\:email').val() != '') {
            if (jsdebug == 1) console.log('case #15');
            if (checkLocalVATBilling()) {
                if (jsdebug == 1) console.log('case #16');
                setOverlayLoaderBilling();
                checkEmailDoubletteBilling();
            } else {
                if (jsdebug == 1) console.log('case #17');
            }
        } else {
            if (jsdebug == 1) console.log('case #18');
            if (checkLocalVATBilling()) {
                if (jsdebug == 1) console.log('case #19');
                if (needsValidation == true) {
                    deferredAddressValidation('billing',
                        ad_street,
                        ad_postcode,
                        ad_city,
                        ad_country,
                        'billing_9'
                    );
                } else {
                    billing.save();
                }
            } else {
                if (jsdebug == 1) console.log('case #20');
            }
        };
<?php endif; ?>

        jQuery('#change-back-to-edit-shipping').hide();
        jQuery('#change-back-to-edit-shipping-method').hide();
        jQuery('#change-back-to-edit-payment-method').hide();
    });
    // guest = non-registering-user
    if (localStorage.newCheckoutProcessCurrentRole != 'prospect-user' && localStorage.newCheckoutProcessCurrentRole != 'guest') {
        jQuery('#alternate-delivery-address-choser').show();
        jQuery('#change-back-to-edit-shipping').show();
        jQuery('.checkout-back-link-container').show();
    } else {
        jQuery('#alternate-delivery-address-choser').hide();
        jQuery('#change-back-to-edit-shipping').hide();
        jQuery('.checkout-back-link-container').hide();
    }

    localStorage.newCheckoutProspectRole = 'none';

<?php if ($customerIsLoggedIn) : ?>
    localStorage.newCheckoutProcessCurrentRole = 'login-user';
    localStorage.newCheckoutProcessCurrentStep = 'opc-billing';
    localStorage.newCheckoutRunningProcess = 'processCheckoutAsLoggedInUser';
    localStorage.customerNotLoggedIn = "0";
    <?php if ($prospectLight || $prospectFull) : ?>
        localStorage.newCheckoutProcessCurrentRole = 'prospect-user';
    <?php endif; ?>
    <?php if ($prospectLight) : ?>
        localStorage.newCheckoutProspectRole = 'prospect-light';
    <?php endif; ?>
    <?php if ($prospectFull) : ?>
        localStorage.newCheckoutProspectRole = 'prospect-full';
    <?php endif; ?>
<?php else : ?>
    localStorage.newCheckoutRunningProcess = 'processCheckoutAsNonLoggedInUser';
    // guest = non-registering-user
    //localStorage.newCheckoutProcessCurrentRole = 'guest';
    localStorage.customerNotLoggedIn = "1";
    jQuery('#fieldsetPostcodeLegendShipping').css({'margin-left' : '32px'});
<?php endif; ?>

    if (localStorage.newCheckoutProspectRole == 'prospect-light' ||
        localStorage.newCheckoutProcessSpecialAction == 'full-register-prospect-application') {
        localStorage.newCheckoutProcessSpecialAction = 'full-register-prospect-application';
    } else {
        localStorage.newCheckoutProcessSpecialAction = 'none';
    }

    if (localStorage.newCheckoutProspectRole == 'prospect-light' ||
        localStorage.newCheckoutProspectRole == 'prospect-full' ||
        localStorage.newCheckoutProspectRole == 'guest') {
            jQuery('#useBillingAddressForShipping').val('yes');
    }

    if (jQuery('#useBillingAddressForShipping').val() == 'yes' ) {
        jQuery('.usebilling_address_for_shipping_yes').prop('checked', true);
    } else {
        jQuery('.usebilling_address_for_shipping_no').prop('checked', true);
    }

    // Prevent enter illegal character(s) by CHANGE or PASTE :
    jQuery('#billing\\:email').bind('keydown change paste',function(e) {
        setTimeout(function(){
                jQuery('#billing\\:email').val(jQuery('#billing\\:email').val().replace(/["';\[\]<>\x00-\x09\x0B\x0C\x0E-\x1F\xE2\x7F\n\r]/g, ""));
            }, 50
        );
    });

    // Prevent enter illegal character(s) by CHANGE or PASTE :
    jQuery('#billing\\:person-firstname').bind('keydown change paste',function(e) {
        setTimeout(function(){
                jQuery('#billing\\:person-firstname').val(jQuery('#billing\\:person-firstname').val().replace(/["';\[\]<>\x00-\x09\x0B\x0C\x0E-\x1F\xE2\x7F\n\r]/g, ""));
            }, 50
        );
    });

    // Prevent enter illegal character(s) by CHANGE or PASTE :
    jQuery('#billing\\:person-lastname').bind('keydown change paste',function(e) {
        setTimeout(function(){
                jQuery('#billing\\:person-lastname').val(jQuery('#billing\\:person-lastname').val().replace(/["';\[\]<>\x00-\x09\x0B\x0C\x0E-\x1F\xE2\x7F\n\r]/g, ""));
            }, 50
        );
    });

    // Prevent enter illegal character(s) by CHANGE or PASTE :
    jQuery('#billing\\:lastname').bind('keydown change paste',function(e) {
        setTimeout(function(){
                jQuery('#billing\\:lastname').val(jQuery('#billing\\:lastname').val().replace(/["';\[\]<>\x00-\x09\x0B\x0C\x0E-\x1F\xE2\x7F\n\r]/g, ""));
            }, 50
        );
    });

    // Prevent enter illegal character(s) by CHANGE or PASTE :
    jQuery('#billing\\:company').bind('keydown change paste',function(e) {
        setTimeout(function(){
                jQuery('#billing\\:company').val(jQuery('#billing\\:company').val().replace(/["';\[\]<>\x00-\x09\x0B\x0C\x0E-\x1F\xE2\x7F\n\r]/g, ""));
            }, 50
        );
    });

    // Prevent enter illegal character(s) by CHANGE or PASTE :
    jQuery('#billing\\:firstname').bind('keydown change paste',function(e) {
        setTimeout(function(){
                jQuery('#billing\\:firstname').val(jQuery('#billing\\:firstname').val().replace(/["';\[\]<>\x00-\x09\x0B\x0C\x0E-\x1F\xE2\x7F\n\r]/g, ""));
            }, 50
        );
    });

    // Prevent enter illegal character(s) by CHANGE or PASTE :
    jQuery('#billing\\:companyuid').bind('keydown change paste',function(e) {
        setTimeout(function(){
                jQuery('#billing\\:companyuid').val(jQuery('#billing\\:companyuid').val().replace(/["';\[\]<>\x00-\x09\x0B\x0C\x0E-\x1F\xE2\x7F\n\r]/g, ""));
                jQuery('#billing\\:companyuid').val(jQuery('#billing\\:companyuid').val().replace(/ /g, ""));
            }, 50
        );
    });

    // Prevent enter illegal character(s) by CHANGE or PASTE :
    jQuery('#billing\\:companyregistrationnumber').bind('keydown change paste',function(e) {
        setTimeout(function(){
                jQuery('#billing\\:companyregistrationnumber').val(jQuery('#billing\\:companyregistrationnumber').val().replace(/["';\[\]<>\x00-\x09\x0B\x0C\x0E-\x1F\xE2\x7F\n\r]/g, ""));
            }, 50
        );
    });

    // Prevent enter illegal character(s) by CHANGE or PASTE :
    jQuery('#billing\\:homepage').bind('keydown change paste',function(e) {
        setTimeout(function(){
                jQuery('#billing\\:homepage').val(jQuery('#billing\\:homepage').val().replace(/["';\[\]<>\x00-\x09\x0B\x0C\x0E-\x1F\xE2\x7F\n\r]/g, ""));
            }, 50
        );
    });

    // Prevent enter illegal character(s) by CHANGE or PASTE :
    jQuery('#billing\\:street1').bind('keydown change paste',function(e) {
        setTimeout(function(){
                jQuery('#billing\\:street1').val(jQuery('#billing\\:street1').val().replace(/["';\[\]<>\x00-\x09\x0B\x0C\x0E-\x1F\xE2\x7F\n\r]/g, ""));
            }, 50
        );
    });

    // Prevent enter illegal character(s) by CHANGE or PASTE :
    jQuery('#billing\\:postcode').bind('keydown change paste',function(e) {
        setTimeout(function(){
                jQuery('#billing\\:postcode').val(jQuery('#billing\\:postcode').val().replace(/["';\[\]<>\x00-\x09\x0B\x0C\x0E-\x1F\xE2\x7F\n\r]/g, ""));
            }, 50
        );
    });

    // Prevent enter illegal character(s) by CHANGE or PASTE :
    jQuery('#billing\\:city').bind('keydown change paste',function(e) {
        setTimeout(function(){
                jQuery('#billing\\:city').val(jQuery('#billing\\:city').val().replace(/["';\[\]<>\x00-\x09\x0B\x0C\x0E-\x1F\xE2\x7F\n\r]/g, ""));
            }, 50
        );
    });

    // ###

    jQuery('#billing\\:password').on('click focus', function() {
        jQuery('#billing\\:password').css('border', '1px solid #A9A9A9');
        jQuery('#billing_password_error_message').text('');
    });
    jQuery('#billing\\:password_confirmation').on('click focus', function() {
        jQuery('#billing\\:password_confirmation').css('border', '1px solid #A9A9A9');
        jQuery('#billing_password_confirmation_error_message').text('');
    });

    jQuery('#billing_phone_address_contact').on('keyup', function() {
        removeForbiddenPhoneFieldCharacters('billing_phone_address_contact');
    });
});

//]]>
</script>
<!-- app/design/frontend/schrack/schrackresponsive/template/persistent/checkout/onepage/billing.phtml (end) -->
