<!-- app/design/frontend/schrack/schrackresponsive/template/catalog/category/subcats.phtml (start) -->
<style>
    .product_name_text_box{
        margin-top: 22px !important;
    }
    .product_image_box {
        display: block;
        height: 63px !important;
    }
    @media (min-width: 321px) and (max-width: 400px) {
        .product_image_box {
            height: 72px !important;
        }
        .product_name_text_box{
            margin-top: 35px !important;
        }
    }
    @media (min-width: 401px) and (max-width: 500px) {
        .product_image_box {
            height: 121px !important;
        }
        .product_name_text_box{
            margin-top: 9px !important;
        }
    }
    @media (min-width: 501px) and (max-width: 600px) {
        .product_name_text_box{
            margin-top: 8px !important;
        }
        .product_image_box {
            height: 156px !important;
        }
    }
    @media (min-width: 601px) and (max-width: 700px) {
        .product_name_text_box{
            margin-top: 22px !important;
        }
        .product_image_box {
            height: 152px !important;
        }
    }
    @media (min-width: 701px) and (max-width: 767px) {
        .product_name_text_box{
            margin-top: 69px !important;
        }
        .product_image_box {
            height: 115px !important;
        }
    }
    @media (min-width: 768px) and (max-width: 991px) {
        .product_name_text_box{
            margin-top: 49px !important;
        }
        .product_image_box {
            height: 115px !important;
        }
    }
    @media (min-width: 992px) and (max-width: 1023px) {
        .product_name_text_box{
            margin-top: 105px !important;
        }
    }
    @media (min-width: 1024px) and (max-width: 1024px) {
        .product_name_text_box{
            margin-top: 49px !important;
        }
        .product_image_box {
            height: 115px !important;
        }
    }
    @media (min-width: 1025px) and (max-width: 1099px) {
        .product_name_text_box{
            margin-top: 95px !important;
        }
        .product_image_box {
            height: 67px !important;
        }
    }
    @media (min-width: 1100px) and (max-width: 1199px) {
        .product_name_text_box{
            margin-top: 134px !important;
        }
        .product_image_box {
            height: 67px !important;
        }
    }
    @media (min-width: 1200px) and (max-width: 4000px) {
        .product_name_text_box{
            margin-top: 95px !important;
        }
        .product_image_box {
            height: 67px !important;
        }
    }
</style>

<?php $_childCats = Mage::registry('categoryCollectionSolr');  //$this->getCurrentChildCategories();?>
<div class="subcategories-container show-for-print">
    <div class="row">
        <?php if (count($_childCats) > 0) : ?>
            <?php $i = 0; ?>
            <?php foreach ($_childCats as $_childCat) : ?>
            <?php
                $imgUrl   = Schracklive_SchrackCatalog_Helper_Image::getImageUrl($_childCat['image'],Schracklive_SchrackCatalog_Helper_Image::PRODUCT_CATEGORY_PAGE);
                $imgUrl   = str_replace('.png', '.jpg', $imgUrl);
                $_imgHtml = '<img style="width: 100%; height: auto; margin-top: 12px !important;" data-src="' . $imgUrl . '" src="' . $imgUrl . '" alt="' . $this->htmlEscape($_childCat['name']) . '" class="lazy" />';
                $category = Mage::getModel('catalog/category');
                $category->load($_childCat['id']);
                //$currentTrackingCategoryId = $category->getId4googleTagManager();
                $currentCategoryName = $this->htmlEscape($_childCat['name']);
            ?>
                <?php if($_childCat['count'] > 0) : ?>
                    <div class="col-md-4 col-sm-4 col-xs-6">
                        <div class="prdouct-box">
                            <div class="product_image_box">
                            <?php
                                $subCatLink = Mage::helper('schrackcore/url')->getUrlWithCurrentProtocol('').$_childCat['path'];
                            ?>
                        <?php if (strlen($_childCat['image'])):?>
                                <a class="categoryFieldLink"
                                   href="<?php echo $subCatLink; ?>"
                                   data-href="<?php echo $subCatLink; ?>"
                                   data-id="<?php echo $_childCat['id']; ?>"
                                   data-tracking-category="<?php echo $currentCategoryName; ?>">
                                   <?php echo $_imgHtml;?>
                                </a>
                            <?php endif;?>
                            </div>
                            <div class="product-name product_name_text_box">
                                <a class="link-arrow categoryFieldLink"
                                   href="<?php echo $subCatLink; ?>"
                                   data-href="<?php echo $subCatLink; ?>"
                                   data-id="<?php echo $_childCat['id']; ?>"
                                   data-tracking-category="<?php echo $currentCategoryName; ?>">
                                   <?php echo $_childCat['name'];?> (<?php echo $_childCat['count'];?>)
                                 </a>
                            </div>
                        </div>
                    </div>
                <?php else : ?>
                    <div class="col-md-4 col-sm-4 col-xs-6">
                        <div class="prdouct-box">
                            <div class="product-image">
                        <?php if ( strlen($_childCat['image']) ) : ?>
                            <a href="<?php echo Mage::helper('schrackcore/url')->getUrlWithCurrentProtocol('').$_childCat['path']; ?>">
                                <?php echo $_imgHtml;?>
                            </a>
                        <?php endif;?>
                            </div>
                            <div class="product-name">
                                <a class="link-arrow"
                                   href="<?php echo Mage::helper('schrackcore/url')->getUrlWithCurrentProtocol('').$_childCat['path']; ?>">
                                    <?php echo $_childCat['name'];?> (<?php echo $_childCat['count'];?>)
                                </a>
                            </div>
                        </div>
                    </div>
                <?php endif; ?>
            <?php ++$i; endforeach; ?>
        <?php else : ?>
            <div class="col-md-4 col-sm-4 col-xs-6">
                <div class="prdouct-box">
                    <div class="product-name">
                        <div class="progress">
                            <div class="progress-bar progress-bar-gray progress-bar-striped active" role="progressbar" aria-valuenow="40" aria-valuemin="0" aria-valuemax="100" style="width:100%"></div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-md-4 col-sm-4 col-xs-6">
                <div class="prdouct-box">
                    <div class="product-name">
                        <div class="progress">
                            <div class="progress-bar progress-bar-gray progress-bar-striped active" role="progressbar" aria-valuenow="40" aria-valuemin="0" aria-valuemax="100" style="width:100%"></div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-md-4 col-sm-4 col-xs-6">
                <div class="prdouct-box">
                    <div class="product-name">
                        <div class="progress">
                            <div class="progress-bar progress-bar-gray progress-bar-striped active" role="progressbar" aria-valuenow="40" aria-valuemin="0" aria-valuemax="100" style="width:100%"></div>
                        </div>
                    </div>
                </div>
            </div>
        <?php endif; ?>
    </div>
</div>



<script type="text/javascript">
    //<![CDATA[

    jQuery(document).ready(function() {

        jQuery('.categoryFieldLink').on('click', function(evt) {
            evt.preventDefault();

            var categoryHref = jQuery(this).attr('data-href');
            var categoryId = jQuery(this).attr('data-id');
            var categoryNameTracking = jQuery(this).attr('data-tracking-category');

            if (dataLayer && categoryNameTracking) {
                dataLayer.push({
                    'event' : 'allNavigation',
                    'eventAction' : 'Category Tile Navigation',
                    'eventLabel' : categoryNameTracking
                });
            }

            getSubCategory(categoryHref, categoryId);
            return false;
        });

    });
    //]]>
</script>
<!-- app/design/frontend/schrack/schrackresponsive/template/catalog/category/subcats.phtml (end) -->
