<!-- app/design/frontend/schrack/default/template/checkout/onepage/payment/methods.phtml (start) -->
<?php
    /**
     * One page checkout payment methods
     */
    /* @var $this Mage_Checkout_Block_Onepage_Payment_Methods */

    $session  = Mage::getSingleton('customer/session');
    $customer = $session->getCustomer();
    $swcid    = $customer->getSchrackWwsCustomerId();
    $prospect = false;

    // Prospect check #1:
    if (stristr($swcid, 'PROS') || stristr($swcid, 'PROSLI')) {
        $prospect = true;
    }

    if ($customer) {
        $customerType = $customer->getSchrackCustomerType(); // ProspectTypes: 'light-prospect' / 'full-prospect'
    }

    $prospectFull  = false;
    $prospectLight = false;

    // Prospect check #2:
    if ($customerType == 'light-prospect') {
        $prospectLight = true;
    }
    // Prospect check #3:
    if ($customerType == 'full-prospect') {
        $prospectFull = true;
    }

    if ($prospect == false) {
        if ($prospectLight || $prospectFull) {
            $prospect = true;
        }
        // Prospect check #4:
        if ($customer->getGroupId() == Mage::getStoreConfig('schrack/shop/prospect_group')) {
            $prospect = true;
        }
    }

    if (!is_int($swcid)) {
        $swcid = (int) $swcid;
    }

    $isFullyRegisteredCustomer = false;
    if ($swcid > 0) {
        $isFullyRegisteredCustomer = true;
    }

    if ($prospect) {
        $isFullyRegisteredCustomer = false;
    }

    $firstMethod = null;

    // Find out matching default payment method.
    // Shipping / Pickup ??
    $deliveryMode          = $this->getQuote()->getShippingAddress()->getShippingMethod();
    $defaultPaymentMethod  = '';
    $selectedPaymentMethod = '';

    if (!$this->helper('customer')->isLoggedIn() || $isFullyRegisteredCustomer == false) {
        if (Mage::getStoreConfig('schrack/new_self_registration/checkmo_payment_available') == 1) {
            $availablePaymentMethods = array('paypal_standard', 'payunitycw_mastercard', 'payunitycw_visa', 'checkmo', 'free');
        } else {
            $availablePaymentMethods = array('paypal_standard', 'payunitycw_mastercard', 'payunitycw_visa', 'free');
        }
    } else {
        foreach ($this->getMethods() as $paymentMethod) {
            $availablePaymentMethods[] = $paymentMethod->getCode();
        }
    }

    // Abholung:
    if (stristr($deliveryMode, 'schrackpickup')) {
        $defaultPaymentMethod = $customer->getSchrackDefaultPaymentPickup();
    }
    // Versand:
    if (stristr($deliveryMode, 'schrackdelivery')) {
        $defaultPaymentMethod = $customer->getSchrackDefaultPaymentShipping();
    }

    if ($this->getSelectedMethodCode()) {
        if (is_array($availablePaymentMethods) && in_array($this->getSelectedMethodCode(), $availablePaymentMethods)) {
            $selectedPaymentMethod = $this->getSelectedMethodCode();
        } else {
            if (is_array($availablePaymentMethods) && in_array($defaultPaymentMethod, $availablePaymentMethods)) {
                $selectedPaymentMethod = $defaultPaymentMethod;
            }
        }
    } else {
        $selectedPaymentMethod = $defaultPaymentMethod;
    }

    $disableCreditCardPayment = false;
    $disablePayPalPayment     = true;
?>

<?php echo $this->getChildHtml('payment_before'); ?>
<dl class="sp-methods" id="checkout-payment-method-load">
<input type="hidden" id="defaultPayment" value="<?php echo $selectedPaymentMethod; ?>">
<?php foreach ($this->getMethods() as $_method): $_code = $_method->getCode() ?>
    <?php // Mastercard & Visa deactivated temporarely (except N.Kasper ==> 800199) ?>
    <?php if ($_code == 'pupay_cc') continue; ?>
    <?php
        // Override criteria (nothing accepted, except listed here):
        if (!$this->helper('customer')->isLoggedIn() || $isFullyRegisteredCustomer == false) {
            if (Mage::getStoreConfig('schrack/new_self_registration/checkmo_payment_available') == 1) {
                $allowedPaymentMethodsForNonFullyRegisteredCustomers = array('paypal_standard', 'payunitycw_mastercard', 'payunitycw_visa', 'checkmo', 'free');
            } else {
                $allowedPaymentMethodsForNonFullyRegisteredCustomers = array('paypal_standard', 'payunitycw_mastercard', 'payunitycw_visa', 'free');
            }

            if (!in_array($_code, $allowedPaymentMethodsForNonFullyRegisteredCustomers) ) continue;
        }
        $localeCode = strtolower(Mage::getStoreConfig('schrack/general/country'));

        // Get information about articles, which could have cutting-costs (only cable main article), and disable Credit-card payment:
        $quoteItems = $this->getQuote()->getAllItems();
        if (is_array($quoteItems) && !empty($quoteItems)) {
            foreach ($quoteItems as $item) {
                if ($product = $item->getProduct()) {
                    if ($product->hasSubProducts() ) {
                        $disableCreditCardPayment = true;
                    }
                }
            }
        }

        // Disable credit card payment:
        if ($disableCreditCardPayment == true) {
            if ($_code == 'payunitycw_mastercard') continue;
            if ($_code == 'payunitycw_visa') continue;
        }

        if ($disablePayPalPayment == true) {
            if ($_code == 'paypal_standard') continue;
        }

        // Examples (orginally used for implementing the working process):
        // if ($_code == 'payunitycw_mastercard' && !in_array(intval($swcid), array(800199, 777777))) continue;
        // if ($_code == 'payunitycw_visa' && !in_array(intval($swcid), array(800199, 777777))) continue;
    ?>
        <dt>
        <?php if ( $firstMethod == null ) { $firstMethod = $_code; } ?>
            <?php if( sizeof($this->getMethods()) > 1 ) : ?>
                <input id="p_method_<?php echo $_code ?>" value="<?php echo $_code ?>" type="radio" name="payment[method]" title="<?php echo $this->htmlEscape($_method->getTitle()) ?>" onclick="payment.switchMethod('<?php echo $_code ?>')"<?php if($selectedPaymentMethod == $_code ): ?> checked="checked"<?php endif; ?> class="radio" />
            <?php else: ?>
                <span class="no-display"><input id="p_method_<?php echo $_code ?>" value="<?php echo $_code ?>" type="radio" name="payment[method]" checked="checked" class="radio" /></span>
            <?php endif; ?>
            <label for="p_method_<?php echo $_code ?>"><?php echo $_method->getTitle() ?> <?php echo $this->getMethodLabelAfterHtml($_method) ?></label>
            </dt>
            <?php if ($html = $this->getPaymentMethodFormHtml($_method)): ?>
            <dd>
                <?php echo $html; ?>
            </dd>
        <?php endif; ?>
<?php endforeach; ?>
</dl>
<script type="text/javascript">
//<![CDATA[
<?php echo $this->getChildChildHtml('scripts'); ?>
jQuery(document).ready(function() {

    (function() {
        payment.init();

        if (jQuery('#defaultPayment').val() == '') {
            jQuery('#p_method_<?php echo $firstMethod; ?>').prop('checked', true);
        }
        var pmcon = $('payment-schrack-custom-order-number');
        if (pmcon && typeof(pmcon) !== 'undefined') {
            pmcon.disabled = false;
        }
    }());

    jQuery('a[href*=paypal]').prop('href', '#');
});
//]]>
</script>
