<!-- app/design/frontend/schrack/schrackresponsive/template/checkout/cart/rightcartnav.phtml (start) -->
<?php
    $partslistIds = array();
    $partslistDescriptions = array();
    $partslistHelper = Mage::helper('schrackwishlist/partslist'); // Get partlist object
    $_quickaddHelper = Mage::helper('schrackcheckout/quickadd');
    $affectedId = '';
    if ($this->getRequest()->getParam('id')) {
        $affectedId = $this->getRequest()->getParam('id');
    } else {
        if ($_quickaddHelper->getModuleName() === 'wishlist' && $_quickaddHelper->getControllerName() === 'partslist') {
            $partslist = $partslistHelper->getActiveOrFirstPartslist();
            $affectedId = $partslist->getId();
        }
    }
    $_quote = Mage::registry('quote_tricky');
    if (isset($_quote)) {
        $_isPickup = $_quote->getIsPickup();
    } else {
        $_isPickup = false;
    }

    $showSubtotalAndGotoCheckout = true;

    $_session = Mage::getSingleton('customer/session');
    $customer = $_session->getCustomer();
    $sessionCustomerId = $customer->getId();
    $aclRoleId = Mage::getModel('customer/customer')->load($sessionCustomerId)->getSchrackAclRoleId();
    $aclHelper = Mage::helper('schrack/acl');
    if ( !$aclHelper->mayCheckout() ) {
        $showSubtotalAndGotoCheckout = false;
    }
    // Override blocking of checkout, because a special case of projectant is indeed able to see checkout and also order:

    $aclrole = '';
    $showSpecialPriceInformation = false;
    if ($_session->isLoggedIn()) {
        $aclrole = $customer->getSchrackAclRole();
        if($aclrole == 'list_price_customer') {
            $showSubtotalAndGotoCheckout = true;
            $showSpecialPriceInformation = true;
        }
        $storeCountry = strtoupper(Mage::getStoreConfig('schrack/general/country'));
        $sessionCustomer = Mage::getSingleton('customer/session')->getCustomer();
        if ($sessionCustomer && $sessionCustomer->getSchrackCustomerType() == 'light-prospect'
            || $sessionCustomer->getSchrackCustomerType() == 'full-prospect') {
            $showCartOfferButton = false;
        } else {
            $showCartOfferButton = true;
        }
        if($storeCountry == "CH"){
            $showCartOfferButton = false;
        }
    }

    $_currency = Mage::getStoreConfig('currency/options/default');

    $_priceHelper = Mage::helper('schrackcatalog/price');
    $_maySeePrices = Mage::helper('geoip')->maySeePrices();
?>

<style>
    html, body {
        max-width: 100% !important;
        overflow-x: hidden !important;
    }
    #price_waiting_ajax_loader_gif {
        width: 20px;
        height: 20px;
        margin-left: 10px;
    }

    .initialHideToTopSymbol {
        display: none !important;
    }
    /* TODO Media-Queries: */
    .other-actions {
        width: 100% !important;
    }

    .hidden_other_actions_button {
        display: none !important;
    }
    .price_on_request {
        margin-right: -88px !important;
    }
    #supersale_link_button {
        color: #fff;
        background: #00589D;
    }

    @media (min-width: 1px) and (max-width: 320px) {
        .to_checkout_button_dimension_correction {
            height: 31px !important;
            width: 185px !important;
        }
        .to_checkout_button_dimension_correction_small {
            float: right !important;
            height: 30px !important;
        }
        .minimized_rightcartnav {
            position: fixed !important;
            top: 0 !important;
            z-index: 1000000 !important;
            width: 102% !important;
            left: 0 !important;
            padding-top: 32px !important;
            padding-bottom: 0 !important;
            padding-left: 0 !important;
            padding-right: 0;
        }
        .cartSubTotal {
            margin-left: -3px !important;
        }
        .cart_subtotal_text_small {
            font-size: 1em !important;
            margin-bottom: 0 !important;
            margin-left: 15px !important;
        }
        .surcharges_additionl_text_small {
            font-size: 0.7em !important;
            margin-left: 15px !important;
            width: 43% !important;
        }
        .line_break_distance_margin_small {
            margin-bottom: 0 !important;
            padding-bottom: 0 !important;
            margin-left: 0 !important;
            width: 103%;

        }
        .minimized_checkout_button {
            width: 50% !important;
            height: 26px !important;
            color: #fff !important;
            background: #d1222b !important;
            font-size: 0.8em !important;
            text-align: center !important;
            font-family: inherit !important;
            border-top: 0 !important;
            border-right: 0 !important;
            border-bottom: 0 !important;
            border-left: 1px solid white !important;
        }
        .minimized_other_actions_button {
            width: 50% !important;
            height: 26px !important;
            color: #fff !important;
            background: #d1222b !important;
            font-size: 0.8em !important;
            text-align: center !important;
            font-family: inherit !important;
            float: left  !important;
            border-top: 0 !important;
            border-left: 0 !important;
            border-bottom: 0 !important;
            border-right: 1px solid white !important;
        }
        .red_button_actions_container {
            width: 103%;
        }
    }

    @media (min-width: 321px) and (max-width: 360px) {
        .to_checkout_button_dimension_correction {
            height: 31px !important;
            width: 185px !important;
        }
        .to_checkout_button_dimension_correction_small {
            float: right !important;
            height: 30px !important;
        }
        .minimized_rightcartnav {
            position: fixed !important;
            top: 0 !important;
            z-index: 1000000 !important;
            left: 0 !important;
            padding-top: 32px !important;
            padding-bottom: 0 !important;
            padding-left: 0 !important;
            padding-right: 0 !important;
            width: 100% !important;
        }
        .cart_subtotal_text_small {
            font-size: 1em !important;
            margin-bottom: 0 !important;
            margin-left: 15px !important;
        }
        .surcharges_additionl_text_small {
            font-size: 0.7em !important;
            margin-left: 15px !important;
            width: 43% !important;
        }
        .line_break_distance_margin_small {
            margin-bottom: 0 !important;
            padding-bottom: 0 !important;
            margin-left: 0 !important;
        }
        .minimized_checkout_button {
            width: 50% !important;
            height: 26px !important;
            color: #fff !important;
            background: #d1222b !important;
            font-size: 0.8em !important;
            text-align: center !important;
            font-family: inherit !important;
            border-top: 0 !important;
            border-right: 0 !important;
            border-bottom: 0 !important;
            border-left: 1px solid white !important;
        }
        .minimized_other_actions_button {
            width: 50% !important;
            height: 26px !important;
            color: #fff !important;
            background: #d1222b !important;
            font-size: 0.8em !important;
            text-align: center !important;
            font-family: inherit !important;
            float: left  !important;
            border-top: 0 !important;
            border-left: 0 !important;
            border-bottom: 0 !important;
            border-right: 1px solid white !important;
        }
        .cartSubTotal {
            min-width: 94.6% !important;
            max-width: 100% !important;
        }
        .cartSubTotalWrapper {
            padding-left: 26px !important;
            width: 99% !important;
            padding-right: 27px !important;
        }
    }

    @media (min-width: 361px) and (max-width: 410px) {
        .to_checkout_button_dimension_correction {
            height: 31px !important;
            width: 185px !important;
        }
        .to_checkout_button_dimension_correction_small {
            float: right !important;
            height: 30px !important;
        }
        .minimized_rightcartnav {
            position: fixed !important;
            top: 0 !important;
            z-index: 1000000 !important;
            width: 100% !important;
            left: 0 !important;
            padding-top: 32px !important;
            padding-bottom: 0 !important;
            padding-left: 0 !important;
            padding-right: 0 !important;
            margin-left: 0px !important;
        }
        .cart_subtotal_text_small {
            font-size: 1em !important;
            margin-bottom: 0 !important;
            margin-left: 15px !important;
        }
        .surcharges_additionl_text_small {
            font-size: 0.7em !important;
            margin-left: 15px !important;
            width: 43% !important;
        }
        .line_break_distance_margin_small {
            margin-bottom: 0 !important;
            padding-bottom: 0 !important;
            margin-left: 0 !important;
        }
        .minimized_checkout_button {
            width: 50% !important;
            height: 26px !important;
            color: #fff !important;
            background: #d1222b !important;
            font-size: 0.8em !important;
            text-align: center !important;
            font-family: inherit !important;
            border-top: 0 !important;
            border-right: 0 !important;
            border-bottom: 0 !important;
            border-left: 1px solid white !important;
        }
        .minimized_other_actions_button {
            width: 50% !important;
            height: 26px !important;
            color: #fff !important;
            background: #d1222b !important;
            font-size: 0.8em !important;
            text-align: center !important;
            font-family: inherit !important;
            float: left  !important;
            border-top: 0 !important;
            border-left: 0 !important;
            border-bottom: 0 !important;
            border-right: 1px solid white !important;
        }
        .cartSubTotal {
            width: 100% !important;
            margin-left: 7px;
        }
        .minimized_rightcartnav {
            margin-left: 0px !important;
        }
        .cartItemsWrapper{
            margin-left: -1px !important;
            width: 101.5% !important;
        }
    }

    @media (min-width: 411px) and (max-width: 460px) {
        .cartSubTotalWrapper {
            padding-left: 27px !important;
        }
        .to_checkout_button_dimension_correction {
            height: 35px !important;
            width: 185px !important;
        }
        .to_checkout_button_dimension_correction_small {
            float: right !important;
            height: 30px !important;
        }
        .minimized_rightcartnav {
            position: fixed !important;
            top: 0 !important;
            z-index: 1000000 !important;
            width: 100% !important;
            left: 0 !important;
            padding-top: 32px !important;
            padding-bottom: 0 !important;
            padding-left: 0 !important;
            padding-right: 0 !important;
        }
        .cart_subtotal_text_small {
            font-size: 1em !important;
            margin-bottom: 0 !important;
            margin-left: 15px !important;
        }
        .surcharges_additionl_text_small {
            font-size: 0.7em !important;
            margin-left: 15px !important;
            width: 43% !important;
        }
        .line_break_distance_margin_small {
            margin-bottom: 0 !important;
            padding-bottom: 0 !important;
            margin-left: 0 !important;
        }
        .minimized_checkout_button {
            width: 50% !important;
            height: 26px !important;
            color: #fff !important;
            background: #d1222b !important;
            font-size: 0.8em !important;
            text-align: center !important;
            font-family: inherit !important;
            border-top: 0 !important;
            border-right: 0 !important;
            border-bottom: 0 !important;
            border-left: 1px solid white !important;
        }
        .minimized_other_actions_button {
            width: 50% !important;
            height: 26px !important;
            color: #fff !important;
            background: #d1222b !important;
            font-size: 0.8em !important;
            text-align: center !important;
            font-family: inherit !important;
            float: left  !important;
            border-top: 0 !important;
            border-left: 0 !important;
            border-bottom: 0 !important;
            border-right: 1px solid white !important;
        }
        .cartSubTotal {
            width: 97.5%;
        }
        .cartItemsWrapper{
            margin-left: 12px !important;
            width: 97% !important;
        }
    }

    @media (min-width: 461px) and (max-width: 480px) {
        .to_checkout_button_dimension_correction {
            height: 35px !important;
            width: 185px !important;
        }
        .to_checkout_button_dimension_correction_small {
            float: right !important;
            height: 30px !important;
        }
        .minimized_rightcartnav {
            position: fixed !important;
            top: 0 !important;
            z-index: 1000000 !important;
            width: 100% !important;
            left: 0 !important;
            padding-top: 32px !important;
            padding-bottom: 0 !important;
            padding-left: 0 !important;
            padding-right: 0 !important;
        }
        .cart_subtotal_text_small {
            font-size: 1em !important;
            margin-bottom: 0 !important;
            margin-left: 15px !important;
        }
        .surcharges_additionl_text_small {
            font-size: 0.7em !important;
            margin-left: 15px !important;
            width: 43% !important;
        }
        .line_break_distance_margin_small {
            margin-bottom: 0 !important;
            padding-bottom: 0 !important;
            margin-left: 0 !important;
        }
        .minimized_checkout_button {
            width: 50% !important;
            height: 26px !important;
            color: #fff !important;
            background: #d1222b !important;
            font-size: 0.8em !important;
            text-align: center !important;
            font-family: inherit !important;
            border-top: 0 !important;
            border-right: 0 !important;
            border-bottom: 0 !important;
            border-left: 1px solid white !important;
        }
        .minimized_other_actions_button {
            width: 50% !important;
            height: 26px !important;
            color: #fff !important;
            background: #d1222b !important;
            font-size: 0.8em !important;
            text-align: center !important;
            font-family: inherit !important;
            float: left  !important;
            border-top: 0 !important;
            border-left: 0 !important;
            border-bottom: 0 !important;
            border-right: 1px solid white !important;
        }
    }

    @media (min-width: 481px) and (max-width: 560px) {
        .to_checkout_button_dimension_correction {
            height: 35px !important;
            width: 185px !important;
        }
        .to_checkout_button_dimension_correction_small {
            float: right !important;
            height: 30px !important;
        }
        .minimized_rightcartnav {
            position: fixed !important;
            top: 0 !important;
            z-index: 1000000 !important;
            width: 100% !important;
            left: 0 !important;
            padding-top: 32px !important;
            padding-bottom: 0 !important;
            padding-left: 0 !important;
            padding-right: 0 !important;
        }
        .cart_subtotal_text_small {
            font-size: 1em !important;
            margin-bottom: 0 !important;
            margin-left: 15px !important;
        }
        .surcharges_additionl_text_small {
            font-size: 0.7em !important;
            margin-left: 15px !important;
            width: 43% !important;
        }
        .line_break_distance_margin_small {
            margin-bottom: 0 !important;
            padding-bottom: 0 !important;
            margin-left: 0 !important;
        }
        .minimized_checkout_button {
            width: 50% !important;
            height: 26px !important;
            color: #fff !important;
            background: #d1222b !important;
            font-size: 0.8em !important;
            text-align: center !important;
            font-family: inherit !important;
            border-top: 0 !important;
            border-right: 0 !important;
            border-bottom: 0 !important;
            border-left: 1px solid white !important;
        }
        .minimized_other_actions_button {
            width: 50% !important;
            height: 26px !important;
            color: #fff !important;
            background: #d1222b !important;
            font-size: 0.8em !important;
            text-align: center !important;
            font-family: inherit !important;
            float: left  !important;
            border-top: 0 !important;
            border-left: 0 !important;
            border-bottom: 0 !important;
            border-right: 1px solid white !important;
        }
    }

    @media (min-width: 561px) and (max-width: 639px) {
        .to_checkout_button_dimension_correction {
            height: 35px !important;
            width: 185px !important;
        }
        .to_checkout_button_dimension_correction_small {
            float: right !important;
            height: 30px !important;
        }
        .minimized_rightcartnav {
            position: fixed !important;
            top: 0 !important;
            z-index: 1000000 !important;
            width: 101% !important;
            left: -8px !important;
            padding-top: 32px !important;
            padding-bottom: 0 !important;
            padding-left: 0 !important;
            padding-right: 0 !important;
        }
        .cart_subtotal_text_small {
            font-size: 1em !important;
            margin-bottom: 0 !important;
            margin-left: 15px !important;
        }
        .surcharges_additionl_text_small {
            font-size: 0.7em !important;
            margin-left: 15px !important;
            width: 43% !important;
        }
        .line_break_distance_margin_small {
            margin-bottom: 0 !important;
            padding-bottom: 0 !important;
            margin-left: 0 !important;
        }
        .minimized_checkout_button {
            width: 50% !important;
            height: 26px !important;
            color: #fff !important;
            background: #d1222b !important;
            font-size: 0.8em !important;
            text-align: center !important;
            font-family: inherit !important;
            border-top: 0 !important;
            border-right: 0 !important;
            border-bottom: 0 !important;
            border-left: 1px solid white !important;
        }
        .minimized_other_actions_button {
            width: 50% !important;
            height: 26px !important;
            color: #fff !important;
            background: #d1222b !important;
            font-size: 0.8em !important;
            text-align: center !important;
            font-family: inherit !important;
            float: left  !important;
            border-top: 0 !important;
            border-left: 0 !important;
            border-bottom: 0 !important;
            border-right: 1px solid white !important;
        }
        .cartSubTotal {
            min-width: 97%;
            max-width: 101%;
            width: 98%;
            margin-left: 7px;
        }
    }

    @media (min-width: 640px) and (max-width: 767px) {
        .to_checkout_button_dimension_correction {
            height: 35px !important;
            width: 185px !important;
        }
        .to_checkout_button_dimension_correction_small {
            float: right !important;
            height: 30px !important;
        }
        .minimized_rightcartnav {
            position: fixed !important;
            top: 0 !important;
            z-index: 1000000 !important;
            width: 100% !important;
            left: 0 !important;
            padding-top: 32px !important;
            padding-bottom: 0 !important;
            padding-left: 0 !important;
            padding-right: 0 !important;
        }
        .cartSubTotalWrapper {
            width: 100% !important;
            margin-right: 0 !important;
        }
        .cart_subtotal_text_small {
            font-size: 1em !important;
            margin-bottom: 0 !important;
            margin-left: 15px !important;
        }
        .surcharges_additionl_text_small {
            font-size: 0.7em !important;
            margin-left: 15px !important;
            width: 43% !important;
        }
        .cartItemsWrapper {
            width: 98% !important;
        }
        .line_break_distance_margin_small {
            margin-bottom: 0 !important;
            padding-bottom: 0 !important;
            margin-left: 0 !important;
        }
        /*
        .minimized_checkout_button {
            height: 30px !important;
        }
        .minimized_other_actions_button {
            margin-left: 10px;
            height: 30px !important;
        }
        */
        .minimized_checkout_button {
            width: 50% !important;
            height: 26px !important;
            color: #fff !important;
            background: #d1222b !important;
            font-size: 0.8em !important;
            text-align: center !important;
            font-family: inherit !important;
            border-top: 0 !important;
            border-right: 0 !important;
            border-bottom: 0 !important;
            border-left: 1px solid white !important;
        }
        .minimized_other_actions_button {
            width: 50% !important;
            height: 26px !important;
            color: #fff !important;
            background: #d1222b !important;
            font-size: 0.8em !important;
            text-align: center !important;
            font-family: inherit !important;
            float: left  !important;
            border-top: 0 !important;
            border-left: 0 !important;
            border-bottom: 0 !important;
            border-right: 1px solid white !important;
        }
    }

    @media (min-width: 768px) and (max-width: 768px) {
        .to_checkout_button_dimension_correction {
            height: 35px !important;
            width: 185px !important;
        }
    }

    @media (min-width: 769px) and (max-width: 992px) {
        .to_checkout_button_dimension_correction {
            height: 35px !important;
            width: 185px !important;
        }
    }

    @media (min-width: 1025px) and (max-width: 1279px) {
        .to_checkout_button_dimension_correction {
            height: 35px !important;
            width: 185px !important;
    }

    @media (min-width: 1280px) and (max-width: 1370px) {
        .to_checkout_button_dimension_correction {
            height: 39px !important;
        }
    }

    @media (min-width: 1371px) and (max-width: 1919px) {
        .to_checkout_button_dimension_correction {
            height: 39px !important;
        }
    }

    @media (min-width: 1920px) and (max-width: 4000px) {
        .to_checkout_button_dimension_correction {
            height: 39px !important;
        }
    }
</style>

<script type="text/javascript">//<![CDATA[
    var partslistCartSku = new ListRequestManager.List('<?php echo $partslistHelper->getBaseUrl() ?>', false);
    var partslistFECartSku = new ListRequestManager.Frontend(partslistCartSku, ListRequestManager.Product);
	//]]>
</script>

<?php if ($showSubtotalAndGotoCheckout) : ?>
    <div id="crtRtAction" class="col-xs-12 col-sm-5 col-md-4 pull-right cartSubTotalWrapper">
        <div class="cartSubTotal">
            <div class="hd cart_subtotal_text_big"><?php echo $this->__('Cart Subtotal'); ?></div>
            <div class="priceBx clearfix line_break_distance_margin_big">
                <?php if ($_maySeePrices) : ?>
                    <div class="left surcharges_additionl_text_big"><?php echo $this->__('Incl. surcharge') . ' ' . $this->__('excl. fees & VAT'); ?></div>
                    <div class="right">
                            <?php echo $_currency; ?> <span class="price" id="product-grand-total">
                                                          <img id="price_waiting_ajax_loader_gif" class="ajaxSpinnerOverlay" src="<?php echo $this->getSkinUrl('schrackdesign/Public/Images/download_ajax_loader.gif'); ?>" title="<?php echo $this->__('Processing...'); ?>" />
                                                      </span>
                        <?php echo $this->getChildHtml('totals'); ?>
                    </div>
                <?php else : ?>
                    <div class="left surcharges_additionl_text_big"></div>
                    <div class="right">
                        <span class="price_on_request">
                            <?php echo $this->__('Price') . '&nbsp;' . $this->__('on request'); ?>
                        </span>
                    </div>
                <?php endif; ?>
            </div>

            <div id="online_bonus_block">
                <?php if ($showSpecialPriceInformation) : ?>
                    <div>
                        <p><?php echo $this->__('Your Visible Prices Are Not The Invoiced Prices'); ?></p>
                    </div>
                <?php else : ?>
                    <?php
                        if (Mage::getSingleton('customer/session')->isLoggedIn()) :
                            $bonusUrl = Mage::getStoreConfig('schrack/general/onlinebonus_url');
                            $onlinebonusActive = true;
                            $onlineBonusStart  = strtotime(Mage::getStoreConfig('schrack/general/onlinebonus_datestart'));
                            $onlineBonusStop   = strtotime(Mage::getStoreConfig('schrack/general/onlinebonus_datestop'));
                            $nowDateTime       = strtotime(date('Y-m-d H:i:s'));
                            if ($onlineBonusStart) {
                                if ($onlineBonusStart <= $nowDateTime && $nowDateTime <= $onlineBonusStop) {
                                    $onlinebonusActive = true;
                                } else {
                                    $onlinebonusActive = false;
                                }
                            }
                            $bonusMinValue = Mage::getStoreConfig('schrack/general/onlinebonus_minvalue');
                            //$diffValue = $bonusMinValue - Mage::getSingleton('checkout/session')->getQuote()->getTotal();
                            $diffValue = $bonusMinValue - Mage::getSingleton('checkout/session')->getQuote()->getSubtotal();
                    ?>
                    <input type="hidden" name="bonusUrlHdn" id="bonusUrlHdn" value="<?php echo $bonusUrl; ?>" />
                    <input type="hidden" name="bonusMinValue" id="bonusMinValue" value="<?php echo $bonusMinValue; ?>" />
                    <input type="hidden" name="cartSubTotalHdn" id="cartSubTotalHdn" value="<?php echo Mage::getSingleton('checkout/session')->getQuote()->getSubtotal(); ?>" />
                        <?php if ($_maySeePrices) : ?>
                            <div class="onlineBonus" <?php if ($onlinebonusActive == true && isset($bonusUrl) && isset($bonusMinValue) && intval($bonusMinValue) > 0 && $diffValue > 0){  ?> style="display:block" <?php } else { ?> style="display:none" <?php } ?>>
                                <p id="onlineBonusText">
                                    <?php echo $this->__('You are still missing %s to reach your online bonus.', (Mage::getStoreConfig('currency/options/default') . ' ' . $this->helper('checkout')->formatPrice($diffValue))); ?>
                                </p>
                                <?php //if ($bonusUrl) { ?>
                                    <p id="onlineBonusAnchor" <?php if ($onlinebonusActive == true && $bonusUrl) { ?> style="display:block" <?php } else { ?> style="display:none" <?php } ?>>
                                        <a href="<?php echo $bonusUrl ?>"><?php echo $this->__('Online Bonus') ?></a>
                                    </p>
                                <?php //} ?>
                            </div>
                        <?php endif; ?>
                    <?php endif; ?>
                <?php endif; ?>
             </div>

            <div class="clearfix red_button_actions_container">
                <button id="other_actions_button" type="button" class="hidden_other_actions_button"><?php echo $this->__('Other Actions') ?></button>
                <?php if (Mage::helper('sapoci')->isSapociCheckout()):?>
                    <button type="submit" name="sap_oci_checkout" title="<?php echo $this->__('SAP OCI Checkout') ?>" class="bttn-md"><?php echo $this->__('SAP OCI Checkout') ?></button>
                <?php else:?>
                    <button id="proceed_to_checkout_button" type="button" class="bttn-md to_checkout_button_dimension_correction" name="proceed_to_checkout">
                        <?php echo $this->__('Proceed to Checkout')/* "zur Kasse gehen" */ ?>
                    </button>
                <?php endif; ?>
                <?php if(Mage::helper('ids')->isIdsSession()) : ?>
                    <div style="display: none">
                        <?php echo Mage::helper('ids')->getIdsForm(); ?>
                    </div>
                    <br>
                    <br>
                    <div>
                        <button style="margin-top: 10px;" id="ids_cart_transfer_cart" type="button" class="bttn-md"><?php echo $this->__('Export IDS Cart'); ?></button>
                    </div>
                <?php endif; ?>
            </div>
        </div>
        <div class="row">
            <div id="other_actions_container" class="otherActions col-xs-12 col-sm-9 col-md-7 hidden-xs">
            <div class="heading3"><?php echo $this->__('Other Actions') ?></div>
                <ul>
                    <?php if (Mage::getStoreConfig('schrack/sales/supersaleurl') && Mage::getStoreConfig('schrack/sales/supersaleurl') != '') : ?>
                        <li>
                            <a id="supersale_link_button" href="<?php echo Mage::getStoreConfig('schrack/sales/supersaleurl'); ?>">
                                <span style="margin-right: 4px;">%</span>
                                <span><?php echo $this->__('Super Sale') ?></span>
                            </a>
                        </li>
                    <?php endif; ?>
                    <li class="hidden-sm">
                        <a href="javascript:void(0);" onclick="jQuery('.btn-quickAdd').click();">
                            <img src="<?php echo $this->getSkinUrl('schrackdesign/Public/Images/rwd/uploadIcon.png'); ?>" />
                            <span><?php echo $this->__('Upload CSV') ?></span>
                        </a>
                    </li>
                    <li>
                        <?php if ($_quickaddHelper->getModuleName() === 'wishlist' && $_quickaddHelper->getControllerName() === 'partslist') : ?>
                            <a id="downloadButton1" href="javascript:void(0);">
                                <img src="<?php echo $this->getSkinUrl('schrackdesign/Public/Images/rwd/downloadIconGray.png'); ?>" />
                                <span><?php echo $this->__('Download CSV') ?></span>
                            </a>
                        <?php else: ?>
                            <a id="downloadButton2" href="javascript:void(0);">
                                <img src="<?php echo $this->getSkinUrl('schrackdesign/Public/Images/rwd/downloadIconGray.png'); ?>" />
                                <span><?php echo $this->__('Download CSV') ?></span>
                            </a>
                        <?php endif; ?>
                    </li>
					<li>
						<div class="product-name posRel">
                        <a class="dropdown partslist-drop all-products" href="javascript:void(0);"  data-toggle="dropdown" id="all-products-cart">
                           
							<span class="glyphicon glyphicon-pushpin <?php if($sessionCustomerId) { echo  "blueTxt";  } else { echo  "lightGray"; } ?>" title="Add to partlist"></span>
                                <span>
                                    <?php echo $this->
                                    __('Add All Product to Partslist')?>
                                </span>
							
                        </a>
						
						<ul aria-labelledby="all-products-cart" class="dropdown-list dropdown-menu allproductaddtocart-switch <?php if(!$sessionCustomerId) { echo  "withoutLgn";  } ?>" <?php if(!$sessionCustomerId) { ?> style="height: auto;" <?php } ?> role="menu">
						<?php if($sessionCustomerId) { ?>
							<li class="add-to-new-partslist no-auto-activate" onClick="partslistFECartSku.addCheckedItemsToNewList('<?php echo $this->__('New partslist') ?>', 'rowId', 'sku', 'qty', '<?php echo Mage::getSingleton('core/session')->getFormKey(); ?>', false, 'cart');"><span class="glyphicon glyphicon-plus-sign plusIcon"></span>&nbsp;<?php echo $this->__("Add to new partslist"); ?></li>
						<?php if ($partslistHelper->getPartslistCount() > 0): ?>
						<?php $activePl = $partslistHelper->getActiveOrFirstPartslist(); ?>
							<li onClick="addSKUToPartlistAjaxCall('<?php echo $activePl->getId(); ?>', 1, this, 'Standard', 'cart');" selected="selected" title="<?php echo $activePl->getDescription() ?>"><?php echo $this->__('Add to %s', $activePl->getDescription()) ?></li>
						<?php else: ?>
							<?php $activePl = null; ?>
						<?php endif; ?>

                        <?php
                            foreach ($partslistHelper->getPartslists() as $pl) {
                                $partslistIds[]          = $pl->getId();
                                $partslistDescriptions[] = $pl->getDescription();
                            }
                        ?>
						<?php foreach ($partslistIds as $index => $partslistId) : ?>
							<?php if ($activePl === null || (int) $partslistId !== (int) $activePl->getId()) : ?>
								<li onClick="addSKUToPartlistAjaxCall('<?php echo $partslistId; ?>', 1, this, 'Standard', 'cart');" title="<?php echo $partslistDescriptions[$index]; ?>"><?php echo $this->__('Add to %s', $partslistDescriptions[$index]) ?></li>
							<?php endif; ?>
						<?php endforeach; ?>
						<?php } else { 
						$cartUrlReferrer = Mage::getUrl('customer/account/login', array('referer' => base64_encode(Mage::getUrl('checkout/cart'))));
						?>
						<li title="<?php echo $this->__('Please login first!'); ?>">
							<a href='<?php echo $cartUrlReferrer; ?>' title='<?php echo $this->__('Login'); ?>'><?php echo $this->__('Please login first!'); ?></a>
						</li>
						<?php } ?>
						</ul>
						</div>
                            
                    </li>
                    <?php if (Mage::getSingleton('customer/session')->isLoggedIn()) : ?>
                        <li>
                            <a href="<?php echo Mage::getUrl('checkout/cart/shareshoppingcart/'); ?>"><img src="<?php echo $this->getSkinUrl('schrackdesign/Public/Images/rwd/shareIcon.png'); ?>" /> 
                                <span><?php echo $this->__('Share Shopping List') ?></span>
                            </a>
                        </li>
                        <?php if ($showCartOfferButton == true): ?>
                            <li>
                                <a href="<?php echo Mage::getUrl('checkout/cart/makeoffer/'); ?>">
                                    <img src="<?php echo $this->getSkinUrl('schrackdesign/Public/Images/rwd/makeOfferIcon.png'); ?>" />
                                    <span><?php echo $this->__('Make an Offer') ?></span>
                                </a>
                            </li>
                        <?php endif; ?>
                    <?php endif; ?>

                    <?php if (Mage::getStoreConfig('schrack/media_zip_download/enable_download')) : ?>
                        <li>
							<a id="download-media-files-button" data-toggle="modal" data-target="#selectmediagpopup" href="javascript:void(0);">
                                <img src="<?php echo $this->getSkinUrl('schrackdesign/Public/Images/rwd/labelprintingIcon.png'); ?>" /> 
                                <span><?php echo $this->__('Lable Printing') ?></span>
                            </a>
                        </li>
                    <?php endif; ?>
                    <?php if(!Mage::helper('ids')->isWKSAction()) : ?>
                        <li>
                            <a id="emptyShoppingCart" href="javascript:void(0);" onclick="javascript:setCartEmpty('<?php echo Mage::helper('schrackcore/url')->getUrlWithCurrentProtocol('sd/AjaxDispatcher/setGetData'); ?>');">
                                <img src="<?php echo $this->getSkinUrl('schrackdesign/Public/Images/rwd/cartIconGray.png'); ?>" />
                                <span><?php echo $this->__('Empty Cart') ?></span>
                            </a>
                        </li>
                    <?php endif; ?>
                </ul>
            </div>
        </div>
    </div>
    <style>
        button:focus { outline: none; }
    </style>
<?php endif; ?>

<?php
    // Deactivate old SAP OCI logic, because of v1.0.1 -> 2.1.3 UPGRADE :
    // $_sapociHelper = false;
    $_sapociHelper = Mage::helper('sapoci');
    if ($_sapociHelper && $_sapociHelper->isSapociCheckout()) :
?>
    <form id="sapoci-form" name="sapoci" action="<?php echo $_sapociHelper->getActionUrl();?>" method="post"<?php if ($_sapociHelper->getTarget()):?> target="<?php echo $_sapociHelper->getTarget();?>"<?php endif?>>
        <?php foreach($_sapociHelper->cartItems() as $key => $value):?>
            <input name="<?php echo $key ?>" value="<?php echo $value ?>" type="hidden" />
        <?php endforeach; ?>
    </form>
<?php endif;?>


<script type="text/javascript">//<![CDATA[

    jQuery(document).ready(function() {

<?php
    $_sapociHelper = Mage::helper('sapoci');
    if ($_sapociHelper && $_sapociHelper->isSapociCheckout()) :
?>
        jQuery("button[name='sap_oci_checkout']").on('click', function(){
            jQuery('#sapoci-form').submit();
            return false;
        });
<?php endif;?>


        jQuery('body').append('<div id="toTop" class="btn btn-info print-hide-imp initialHideToTopSymbol"><span class="glyphicon glyphicon-chevron-up"></span> <?php echo $this->__('Back to Top'); ?></div>');

        var cartSidebar                 = jQuery("#crtRtAction");
        var sidebarOffset               = cartSidebar.offset();
        var offsetTop                   = sidebarOffset.top;
        var staticLeftItemsContainer    = 0;
        var staticRightActionsContainer = 0;
        var dynamicScrollDistance       = 0;

        var fixedSetting1               = 30;
        var topPadding                  = 15;
        var fixedSetting3               = 0; // Vorher war's mal = 140 - keine Ahnung warum ??
        var offsetTopPlusPadding        = offsetTop + topPadding;
        var offsetTopMinusStaticValue   = offsetTop - fixedSetting3;

        var viewportWidth = Math.max(document.documentElement.clientWidth, window.innerWidth || 0);
        var allowDynamicTotalAmountBlockAlignment = true;

        jQuery(window).scroll(function () {
            /* Back to Top */
            if (jQuery(this).scrollTop() != 0) {
                jQuery('#toTop').show();
                jQuery('#toTop').fadeOut(3000);
            } else {
                jQuery('#toTop').fadeOut();
            }
            /* Back to Top */

            if (viewportWidth >= 60 && viewportWidth < 768) {
                allowDynamicTotalAmountBlockAlignment = false;
            } else {
                allowDynamicTotalAmountBlockAlignment = true;
            }

            if (jQuery(this).scrollTop() > offsetTop) {
                staticLeftItemsContainer = jQuery('#crtLtItems').outerHeight();
                staticRightActionsContainer = jQuery('#crtRtAction').outerHeight();
                dynamicScrollDistance = jQuery(this).scrollTop() - offsetTopPlusPadding;

                if ((dynamicScrollDistance + staticRightActionsContainer - fixedSetting1) < staticLeftItemsContainer) {
                    if (allowDynamicTotalAmountBlockAlignment == true) {
                        cartSidebar.stop().animate({
                            marginTop: dynamicScrollDistance
                        });
                    }
                }
            } else {
                if (allowDynamicTotalAmountBlockAlignment == true) {
                    cartSidebar.stop().animate({
                        marginTop: 0
                    });
                }
            }

            // Change style of rightcartnav and fix the position to top:
            if (jQuery(this).scrollTop() > offsetTopMinusStaticValue && allowDynamicTotalAmountBlockAlignment == false) {
                // Minimize rightcartnav:
                jQuery('#online_bonus_block').hide();
                jQuery('.cartSubTotal').addClass('minimized_rightcartnav');

                jQuery('.cart_subtotal_text_big').addClass('cart_subtotal_text_small');
                jQuery('.surcharges_additionl_text_big').addClass('surcharges_additionl_text_small');
                jQuery('.line_break_distance_margin_big').addClass('line_break_distance_margin_small');
                jQuery('.to_checkout_button_dimension_correction').addClass('to_checkout_button_dimension_correction_small');
                jQuery('#proceed_to_checkout_button').removeClass('bttn-md');
                jQuery('#proceed_to_checkout_button').addClass('minimized_checkout_button');
                jQuery('#other_actions_button').removeClass('hidden_other_actions_button');
                jQuery('#other_actions_button').addClass('minimized_other_actions_button');
            } else {
                // Maximize rightcartnav:
                jQuery('.cartSubTotal').removeClass('minimized_rightcartnav');

                jQuery('.cart_subtotal_text_big').removeClass('cart_subtotal_text_small');
                jQuery('.surcharges_additionl_text_big').removeClass('surcharges_additionl_text_small');
                jQuery('.line_break_distance_margin_big').removeClass('line_break_distance_margin_small');
                jQuery('.to_checkout_button_dimension_correction').removeClass('to_checkout_button_dimension_correction_small');
                jQuery('#proceed_to_checkout_button').removeClass('minimized_checkout_button');
                jQuery('#proceed_to_checkout_button').addClass('bttn-md');
                jQuery('#other_actions_button').removeClass('minimized_other_actions_button');
                jQuery('#other_actions_button').addClass('hidden_other_actions_button');
                jQuery('#online_bonus_block').show();
            }
        });

        jQuery('#toTop').click(function(){
            jQuery("html, body").animate({ scrollTop: 0 }, 600);
            console.log('ScrollTop #71');
            return false;
        });

        jQuery('#other_actions_button').click(function(evt){
            evt.preventDefault();
            var position = jQuery('#footer-container').offset().top;
            jQuery("body, html").animate({scrollTop: (position - 430)});
        });

        jQuery('#toTop').removeClass('initialHideToTopSymbol');

        jQuery("#IdsForm").on('submit', function(event){
            localStorage.setItem('IDS_Transfer_Done', 'true');
            var ajaxUrl = '<?php echo Mage::helper('schrackcore/url')->getUrlWithCurrentProtocol('sd/AjaxDispatcher/setGetData'); ?>';
            setCartEmptyConfirmed(ajaxUrl);

            /*
            event.preventDefault();
            var idsUrl = jQuery("#IdsForm").attr('action');
            // Serialize data
            var formData = jQuery(this).serialize();

            // After truncating cart, send form to IDS Software
            jQuery.post(idsUrl, formData).complete(function() {
                console.log("Success IDS : Transfer Complete");
                console.log("Success IDS Transfer : Empty Cart");
            });
            */
        });

        jQuery('#ids_cart_transfer_cart').on('click', function(event) {
            event.preventDefault();
            jQuery('#IdsForm').submit();
        });

        jQuery('.otherActions ul li a span').on('click', function () {
            if (dataLayer && jQuery(this).text()) {
                dataLayer.push({
                    'event' : 'allNavigation',
                    'eventAction' : 'Cart Other Actions Navigation',
                    'eventLabel' : jQuery(this).text()
                });
            }
        });

    });

//]]></script>
<!-- app/design/frontend/schrack/schrackresponsive/template/checkout/cart/rightcartnav.phtml (end) -->
