<!-- app/design/frontend/schrack/schrackresponsive/template/persistent/customer/form/login.phtml (start) -->
<?php
    // Customer login form template ->> This is the lightbox Popup!
    // @var $this Mage_Customer_Block_Form_Login

    $selfRegistrationAvailable = false; // Default fallback
    $selfRegistrationOptions = Mage::getStoreConfig('schrack/new_self_registration/new_self_registration_options');
    if ($selfRegistrationOptions == 'self_registration_not_available') {
        $selfRegistrationAvailable = false;
    } else {
        if($selfRegistrationOptions == 'self_registration_with_typo' || $selfRegistrationOptions == 'new_self_registration_form' || $selfRegistrationOptions == 'old_self_registration_available') {
            $selfRegistrationAvailable = true;
        }
    }

    $showAdditionalLightSelfRegisterButton = true;
    $selfRegistrationWithTypoForm = false;
    if ($selfRegistrationOptions == 'self_registration_with_typo') {
        // Typo form is only used as fallback:
        $selfRegistrationWithTypoForm = true;
        $showAdditionalLightSelfRegisterButton = false;
    }

    if ($selfRegistrationOptions == 'new_light_self_registration_form') {
        $selfRegistrationWithTypoForm = false;
        $selfRegistrationAvailable = true;
    }

    $referer = $this->getRequest()->getParam('referer');
    if ( $referer ) {
        $loginPostUrl = $this->getUrl('customer/account/loginPost',array('referer' => $referer));
    } else {
        $loginPostUrl = $this->getUrl('customer/account/loginPost');
    }
?>

<style>
#sezameLoginContainer {
    display: none;
    float: right;
}

.form-control {
    font-size: 16px !important;
}

@media (min-width: 60px) and (max-width: 320px) {
    #commonUserLoginButoon {
        height: 30px !important;
    }
    .forget_password_button_customized {
        width: 135px !important;
        padding: 3px !important;
        font-size: 0.7em !important;
        height: 22px !important;
        float: right !important;
        margin-right: 14px !important;
    }
    .forget_password_button_customized:after {
        height: 22px !important;
    }
}

@media (min-width: 321px) and (max-width: 480px) {
    #commonUserLoginButoon {
        height: 30px !important;
    }
    .forget_password_button_customized {
        width: 153px !important;
        padding: 4px !important;
        font-size: 0.8em !important;
        height: 24px !important;
        float: right !important;
        margin-right: 14px !important;
    }
    .forget_password_button_customized:after {
        height: 24px !important;
    }

}

@media (min-width: 481px) and (max-width: 767px) {
    #commonUserLoginButoon {
        height: 30px !important;
    }
    .forget_password_button_customized {
        width: 157px !important;
        padding: 4px !important;
        font-size: 0.8em !important;
        height: 24px !important;
        float: right !important;
        margin-right: 14px !important;
    }
    .forget_password_button_customized:after {
        height: 24px !important;
    }

}
@media (min-width: 768px) and (max-width: 1024px) {
    .forget_password_button_customized {
        width: 145px !important;
        padding: 2px !important;
        font-size: 0.9em !important;
        height: 24px !important;
        float: right !important;
        margin-right: 14px !important;
    }
    .forget_password_button_customized:after {
        height: 24px !important;
    }
}

@media (min-width: 1025px) and (max-width: 4000px) {
    .forget_password_button_customized {
        width: 200px !important;
        height: 25px !important;
        font-size: 1em !important;
        padding: 4px !important;
        float: right !important;
        margin-right: 14px !important;
    }

    .forget_password_button_customized:after {
        height: 25px !important;
    }
}

</style>

<?php echo $this->getMessagesBlock()->toHtml() ?>
<div class="mainContent">
<div class="clearfix loginCont">
        <div class="col-xs-12">
                <h1><img src="<?php echo $this->getSkinUrl('schrackdesign/Public/Images/rwd/loginIcon.png'); ?>" alt=""/> <?php echo $this->__('Login'); ?></h1>
        </div>
        
        <div class="col-xs-12 col-sm-6 col-md-5 leftSection">
            <form action="<?php echo $loginPostUrl ?>" method="post" id="login-form" name="login-form">
                <?php echo $this->getBlockHtml('formkey'); ?>
                <input type="hidden" name="redirectUrl" value=""/>
                <div class="hdCont">
                        <h2 class="marginB5"><?php echo $this->__('Registered Customers'); ?></h2>
                        <p><?php echo $this->__('If you have an account with us, please log in.'); ?></p>
                </div>
                <div class="formContianer">
                        <ul>
                                <li><input type="text" name="login[username]" value="<?php echo $this->htmlEscape($this->getUsername()) ?>" id="email" title="<?php echo $this->__('Email Address') ?>" class="input-text required-entry form-control" placeholder="<?php echo $this->__('Email Address') ?>*" tabindex="1"></li>
                                <li><input type="password" name="login[password]" id="pass" title="<?php echo $this->__('Password') ?>" class="input-text required-entry validate-password form-control" placeholder="<?php echo $this->__('Password') ?>*"  tabindex="2"></li>
                                <li>
                                        <div class="row">
                                                <div class="col-xs-6 col-sm-6 col-md-6 padR0">
                                                    <label class="darkGray bold">
                                                        <input type="checkbox" name="rememberme" id="rememberme" title="<?php echo $this->__('Keep Me Logged In') ?>" <?php if (Mage::getStoreConfigFlag('customer/rememberme/checked')) echo 'checked="checked"'; ?>  tabindex="4"> <?php echo $this->__('Keep Me Logged In'); ?>
                                                        <input type="hidden" name="remembermeValue" id="remembermeValue" value="<?php if (Mage::getStoreConfigFlag('customer/rememberme/checked')) echo '1'; ?>" />
                                                    </label>
                                                </div>
                                                <div class="col-xs-6 col-sm-6 txtRgt padL0">
                                                    <a href="<?php echo Mage::getUrl('customer/account/forgotpassword') ?>"
                                                       class="internal-link blue forget_password_button_customized"
                                                       tabindex="5"><?php echo $this->__('Forgot Your Password?'); ?></a>
                                                 </div>
                                        </div>
                                     <?php echo $this->getChildHtml('form.additional.info'); ?>
                                     <?php echo $this->getChildHtml('persistent.remember.me'); ?>
                                </li>
                                <li>
                                    <button type="submit" class="bttn-md" id="commonUserLoginButoon" title="<?php echo $this->__('Login') ?>" name="send" tabindex="3"><?php echo $this->__('Login') ?></button>
                                    <div id="sezameLoginContainer"></div>
                                </li>
                                <?php echo $this->getChildHtml('persistent.remember.me.tooltip'); ?>
                        </ul>
                </div>
            </form>
        </div>
        <?php
        if ($selfRegistrationAvailable == true ):
            $registerUrl = Mage::getUrl('customer/account/create');
            //------------------------------------------------------------------
            $hidden_checkout_input = '';
            if (Mage::helper('checkout')->isContextCheckout()):
                $hidden_checkout_input = '<input name="context" type="hidden" value="checkout" />';
            endif;
            //------------------------------------------------------------------
            echo
            '<div class="col-xs-12 col-sm-6 rightSection pull-right">' .
                '<div class="hdCont">' .
                    '<h2 class="marginB5">' .
                        $this->__('New Customers') .
                    '</h2>' .
                    '<p>' .
                        $this->__("If it's your first time at Schrack:") .
                    '</p>' .
                '</div>' .
                '<div class="bttnArea clearfix">' .
                    '<a href="' .  $registerUrl . '" class="internal-link blue" tabindex="6">' .
                        $this->__('Create Account') .
                    '</a>' .
                '</div>' .
                '<p>' .
                    $this->__('login.popup.registration-hint-only') .
                '</p>' .
                $hidden_checkout_input .
            '</div>';
        endif;
        ?>
</div>
    <script type="text/javascript">
    //<![CDATA[
        var dataForm = new VarienForm('login-form', true);
        jQuery(document).ready(function(){

            jQuery('#rememberme').on('click', function() {
                if ( jQuery('#rememberme').prop('checked')) {
                    jQuery('#remembermeValue').val(1);
                } else  {
                    jQuery('#remembermeValue').val(0);
                }
             });

             jQuery('#commonUserLoginButoon').on('click', function() {
                 localStorage.actAsACustomer = 0;
                 localStorage.actAsACustomerRealEmail = '';
                 localStorage.customerLoggedInEmail = '';

                 // Reset mega menu, forces new fetch:
                 localStorage.removeItem('refreshMegaMenuForceTimeLastChangeDropdownMenu');
                 localStorage.removeItem('megamenuContentResponsive');
                 localStorage.removeItem('refreshMegaMenuForceTimeLastChange');
                 localStorage.removeItem('refreshMegaMenuForceTimeCurrent');

                 if (dataLayer && jQuery(this).text()) {
                     dataLayer.push({
                         'event' : 'allNavigation',
                         'eventAction' : 'Customer Login Navigation',
                         'eventLabel' : jQuery(this).text()
                     });
                 }

             })

        });
    //]]>
    </script>
</div>
<!-- app/design/frontend/schrack/schrackresponsive/template/persistent/customer/form/login.phtml (end) -->
