<?php
/* @var $this Schracklive_SchrackWishlist_Block_Endcustomerpartslist_View */
?>
<?php
$_infoHelper = Mage::helper('schrackcatalog/info');
$_productHelper = Mage::helper('schrackcatalog/product');
$_customer = Mage::getSingleton('customer/session')->getCustomer();
$_stockHelper = Mage::helper('schrackcataloginventory/stock');
$_partslistHelper = $this->helper('schrackwishlist/partslist');
$_partslist = $this->getPartslist();
$_priceHelper = Mage::helper('schrackcatalog/price');
$_ecplHelper = Mage::helper('schrackwishlist/endcustomerpartslist');

/* @var $_infoHelper Schracklive_SchrackCatalog_Helper_Info */
/* @var $_productHelper Schracklive_SchrackCatalog_Helper_Product */
?>

<div class="row partslist">
    <div class="large-10 columns large-offset-1">
        <?php if ($_partslist): ?>
            <?php if ($_partslist->hasPartslistItems()): ?>
                <form id="wishlist-view-form"
                      action="<?php echo $this->getUrl('*/*/update', array('id' => $_partslist->getId())) ?>" method="post">
                <?php echo $this->getBlockHtml('formkey') ?>
                <div class="table">
                <?php
                $_partslistItems = $this->getPartslistItems($_partslist);
                $products = array();
                foreach ($_partslistItems as $item) {
                    $products[] = $item->getProduct();
                }
                $_infoHelper->preloadProductsInfo($products, $_customer);
                ?>
                <?php
                $i = 0;
                foreach ($_partslistItems as $item): /* start foreach for products loop */
                    ?>
                    <?php
                    $_product = $item->getProduct();
                    $_categories = $_product->getCategoryIds();
                    if (isset($_categories[0])) {
                        $_category = Mage::getModel('catalog/category')->load($_categories[0]);
                        $_url = $this->getUrl(dirname($_category->getUrlPath()) . '/' . basename($_category->getUrlPath(), '.html') . '/' . basename($_product->getProductUrl(false)));
                    } else {
                        $_url = '';
                    }
                    ?>
                    <div class="row-fine body hide-on-print refresh-after-ajax">
                        <div class="large-fine-3 columns-fine image-col">
                            <?php $_product_image = $this->helper('catalog/image')->init($_product, 'small_image')->constrainOnly(true)->resize(66, 66); ?>
                            <a href="#" target="_blank"
                               title="<?php echo $this->htmlEscape($this->getImageLabel($_product, 'small_image')) ?>"
                               class="product-image"><img src="<?php echo $_product_image ?>"
                                                          width="<?php echo $_product_image->getWidth() ?>"
                                                          height="<?php echo $_product_image->getHeight() ?>"
                                                          alt="<?php echo $this->htmlEscape($this->getImageLabel($_product, 'small_image')) ?>"/></a>
                        </div>
                        <div class="large-fine-7 columns-fine">
                            <div class="row">
                                <div class="large-12 columns text-col">
                                    <h2 class="product-name"><a href="#" onClick="openReferredCatalog('<?php echo trim($item->getReferrerUrl())?>', '<?php echo $this->getCatalogName($item)?>');"
                                                                title="<?php echo $this->htmlEscape($_product->getName()) ?>"><?php echo $this->htmlEscape($_product->getName()) ?></a>
                                    </h2>
                                </div>
                            </div>
                            <div class="row">
                                <div class="large-12 columns text-col" style="position: relative; height: 25px;">
                                    <div class="bottom-align-container-0" style="position: absolute; bottom: 12px;">
                                        <?php if ($_product->getSku()): ?>
                                            <span id="sku-<?php echo $_product->getId() ?>" class="catalog-nr"><?php echo $this->htmlEscape($_product->getSku()); ?></span>
                                        <?php endif; ?>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="large-fine-5 columns-fine buttons-col" style="padding-top: 20px; padding-bottom: 10px;">
                            <?php if ($_product->isSaleable()): ?>
                                        <div class="addtocart">
                                            <label class="unit"><?php echo $_product->getSchrackQtyunit() ?></label>
                                            <input type="text" id="qty-<?php echo $_product->getId() ?>"
                                                   class="qty"
                                                   name="qty[<?php echo $item->getId() ?>]" maxlength="12"
                                                   value="<?php echo Mage::helper('schrackcore/string')->numberFormat($item->getQty()); ?>"
                                                   title="<?php echo $this->__('Qty') ?>"
                                                   onChange="saveQty(<?php echo $item->getId() ?>);"/>
                                            <script type="text/javascript">//<![CDATA[

                                                jQuery('input#qty-<?php echo $_product->getId() ?>').keyup(function(ev) {
                                                    if (ev.keyCode == 13) {
                                                        ev.preventDefault();
                                                        saveQty(<?php echo $_product->getId() ?>);
                                                        return false;
                                                    }
                                                });
                                            //]]>
                                            </script>
                                        </div>
                            <?php endif; ?>
                        </div>
                        <div class="large-fine-4 columns-fine product-link" style="padding-top: 30px; padding-bottom: 10px;" xx="artikeldetails-link">
                                <a class="show-product-detail" id="show-product-detail-<?php echo $_product->getSku()?>" onClick="refreshProductDetail('<?php echo $_product->getSku()?>')"><?php echo $this->__('Show product details')?></a>
                            <a class="hide-product-detail" id="hide-product-detail-<?php echo $_product->getSku()?>" onClick="hideProductDetail('<?php echo $_product->getSku()?>')"><?php echo $this->__('Hide product details')?></a>
                        </div>
                        <div class="large-fine-4 columns-fine product-link" style="padding-top: 30px; padding-bottom: 10px;" xx="im katalog ansehen">
                            <a href="#" onClick="openReferredCatalog('<?php echo trim($item->getReferrerUrl())?>', '<?php echo $this->getCatalogName($item)?>');"
                                title="<?php echo $this->htmlEscape($_product->getName()) ?>"><?php echo $this->__('View in catalog') ?></a>
                        </div>
                        <div class="large-fine-2 columns-fine remove-link">

                                <div onClick="removeProduct(<?php echo $_product->getId()?>);" class="remove" title="<?php echo $this->__('Remove item')?>"></div>

                        </div>
                    </div>
                    <div class="row">
                        <div class="large-12 columns product-detail" id="productdetail-<?php echo $_product->getSku()?>"></div>
                    </div>

                    <?php ++$i;endforeach; ?>
                </div>
                <div class="row buttons hide-on-print">
                    <div class="large-7 columns"><div class="truncate" onClick="truncatePartslist();"><?php if ($_partslist->hasPartslistItems()): ?><a href="javascript:void(truncatePartslist());"><?php echo $this->__('Truncate')?><?php endif;?></a></div></div>
                    <div class="large-1 columns">
                        <div class="bookmark"><?php if ($_partslist->hasPartslistItems()): ?><a href="javascript:void(setBookmark());"><?php echo $this->__('Bookmark')?><?php endif;?></a></div>
                    </div>
                    <div class="large-1 columns">
                        <div class="print"><?php if ($_partslist->hasPartslistItems()): ?><a href="javascript:void(printPartslist());"><?php echo $this->__('Print')?></a><?php endif?></div>
                    </div>
                    <div class="large-1 columns">
                        <div class="share"><?php if ($_partslist->hasPartslistItems()): ?><a href="javascript:void(showShareForm(shareFormCoordsForViewForm().x, shareFormCoordsForViewForm().y));"><?php echo $this->__('Share')?></a><<?php endif;?>/div>
                    </div>
                    <div class="large-2 columns show-request-offer-form"><div class="request-offer" onClick="showRequestOfferForm()"><?php echo $this->__('Request offer')?></div></div>
                </div>
                </form>
            <?php else:?>
                <?php echo $this->__('There are no items on your partslist yet. You can add items by opening a catalog and clicking on the link there.')?>
            <?php endif; ?>
        <?php endif; ?>
    </div>
    <div class="large-1 columns"></div>
</div>
<script type="text/javascript">//<![CDATA[

    function printPartslist() {
        var url = '<?php echo $this->getUrl('wishlist/endcustomerpartslist/print')?>';
        window.open(url);
    }
    function removeProduct(productId) {
        gaAddToCart(jQuery('#sku-'+productId).text(), 'remove');
        var url = '<?php echo $this->getUrl('wishlist/endcustomerpartslist/remove')?>/product/' + productId;
        jQuery.ajax(url,
            {
                'success': function(data) {
                    var datax = JSON.parse(data);
                    jQuery('#view').html(datax.html);
                    refreshPartslistItemsCount(false);
                }
            }
        );
    }

    <?php if ( $_partslist && $_partslist->hasPartslistItems() ): ?>
        function saveQty(itemId) {
            var data = {};
            data['qty[' + itemId + ']'] = jQuery('input[name="qty[' + itemId + ']"]').val();
            data['id'] = <?php echo $_partslist->getId()?>;
            jQuery.ajax('<?php echo $this->getUrl('wishlist/endcustomerpartslist/update')?>', {
                'type': 'POST',
                'data' : data
            });
        }
    <?php endif;?>
    function confirmEmptyPartslist() {
        return confirm('<?php echo $this->__('Are you sure you want to empty this partslist?') ?>');
    }
    function truncatePartslist() {
        if ( confirmEmptyPartslist() ) {
            jQuery('#wishlist-view-form .catalog-nr').each(function() {
                gaAddToCart(jQuery(this).text(), 'remove');
            });
            var url = '<?php echo $this->getUrl('wishlist/endcustomerpartslist/truncate')?>';
            jQuery.ajax(url,
                {
                    'success': function (data) {
                        var datax = JSON.parse(data);
                        jQuery('#view').html(datax.html);
                        refreshPartslistItemsCount(false);
                    }
                }
            );
        }
    }

    function savePartslist() {
        var url = '<?php echo $this->getUrl('wishlist/endcustomerpartslist/save')?>';
        jQuery.ajax(url,
            {
                'success': function(data) {
                    var datax = JSON.parse(data);
                    jQuery('#view').html(datax.html);
                }
            }
        );
    }

    function setBookmark() {
        var url = '<?php echo $_ecplHelper->getPartslistUrl()?>';
        if (window.sidebar && window.sidebar.addPanel) { // Mozilla Firefox Bookmark
            window.sidebar.addPanel(document.title, url, '');
        } else if(window.external && ('AddFavorite' in window.external)) { // IE Favorite
            window.external.AddFavorite(url, document.title);
        } else if(window.opera && window.print) { // Opera Hotlist
            this.title=document.title;
            return true;
        } else { // webkit - safari/chrome
            jQuery('#set-bookmark').dialog({
                width: 300,
                modal: true,
                buttons: {
                    "Ok": function () {
                        jQuery(this).dialog("close");
                    }
                }
            });
            jQuery('#set-bookmark').dialog('open');
        }
    }
//]]>
</script>


<div id="set-bookmark" style="display: none;">
    <p>
        <?php echo $this->__('Copy <a href="%s">this link</a>, or press CTRL + D to bookmark this page.', $_ecplHelper->getPartslistUrl())?>
    </p>
</div>