<!-- app/design/frontend/schrack/schrackresponsive/template/wishlist/partslist/active-partlist.phtml (start) -->
<?php
    $partslistHelper = Mage::helper('schrackwishlist/partslist'); // Get partlist object
    $partslists = $this->getPartslists()->toArray();
    $aclroleClass = '';
    if (Mage::getSingleton('customer/session')->isLoggedIn()) {
        $customer = Mage::getSingleton('customer/session')->getCustomer();
        $aclrole = $customer->getSchrackAclRole();
        if($aclrole == 'staff' || $aclrole == 'projectant'){
            $aclroleClass = 'hide';
        }
    }
    try{
    $active_flag = true;
    $active = Mage::getModel('schrackwishlist/partslist')->loadActiveListByCustomer(Mage::getSingleton('customer/session')->getCustomer()->getId());
    }
    catch(Exception $e){
        $active_flag = false;
    }
    $activeId = $active->getId();
    //if($active_flag && !empty($activeId)) {
    $activeName = $active->getDescription();
    $deleteUrl = $this->getUrl('wishlist/partslist/delete', array('id'=>$activeId, 'forward' => '#active-tab'));
    $emptyUrl = $this->getUrl('wishlist/partslist/truncate', array('id'=>$activeId));
    $editUrl = $this->getUrl('wishlist/partslist/edit', array('id'=>$activeId));
?>

<style>
<?php if ( intval(Mage::getStoreConfig('carriers/schrackpickup/active')) != 1 ) : ?>
    .cartInfoHide {
        display: none !important;
    }
    .info_button_pickup_info {
        display: none !important;
    }
    .row_pickup_info {
        display: none !important;
    }
<?php endif; ?>
    .tracking_info_icon {
        z-index: 1000;
    }
    .triggerDescriptionPartslistItemPositionRowTextInput {
        font-size: 16px !important;
    }
    .partslistActionFieldExtra {
        width: 38% !important;
        float: left;
    }
    .partslistActionField {
        width: 30% !important;
        float: left;
    }
    .topDistancePartslistActionField {
        margin-top: 7px !important;
    }
    .ajaxSpinnerOverlay {
        opacity: 0.4;
        z-index: 99999;
        width: 60%;
        margin-left: 25%;
        margin-top: 7%;
    }


    @media (min-width: 60px) and (max-width: 320px) {
        .quantity_input_from_user {
            font-size: 16px !important;
        }
        .fake_dropdown_select_partslist {
            font-size: 16px !important;
        }
        #bulkAddCartActivePartlist {
            width: 120px !important;
            font-size: 10px !important;
            padding-top: 9px !important;
            padding-left: 1px !important;
        }
    }


    @media (min-width: 321px) and (max-width: 480px) {
        .quantity_input_from_user {
            font-size: 16px !important;
        }
        .fake_dropdown_select_partslist {
            font-size: 16px !important;
        }
        #bulkAddCartActivePartlist {
            width: 120px !important;
            font-size: 10px !important;
            padding-top: 9px !important;
            padding-left: 1px !important;
        }

    }


    @media (min-width: 481px) and (max-width: 767px) {
        .quantity_input_from_user {
            font-size: 16px !important;
        }
        .fake_dropdown_select_partslist {
            font-size: 16px !important;
        }
        #bulkAddCartActivePartlist {
            width: 120px !important;
            font-size: 10px !important;
            padding-top: 9px !important;
            padding-left: 1px !important;
        }
    }
</style>

<script type="text/javascript">//<![CDATA[
    var partslistActiveSku = new ListRequestManager.List('<?php echo $partslistHelper->getBaseUrl() ?>', false);
    var partslistFEActiveSku = new ListRequestManager.Frontend(partslistActiveSku, ListRequestManager.Product);
	//]]>
</script>
<input type="hidden" name="noactiverecords" id="noactiverecords" value="<?php if($active_flag && !empty($activeId)) { echo "1"; } else { echo "0"; } ?>" />

<div id="activePartlistContainer" <?php if($active_flag && !empty($activeId)) { ?> style="display:block" <?php } else { ?> style="display:none" <?php } ?>>
<input id="sku-list" type="hidden"/>
<div class="actionBx">
    <div class="row">
        <div class="col-xs-6 col-sm-9 top-links">
            <div class="row">
                <div class="col-xs-12 col-sm-4">
                    <div class="dropdown partslist-drop partslist-switch">
                        <button class="btn dropdown-toggle form-control" data-toggle="dropdown" id="menu1" type="button">
                            <span class="textOverFlw fake_dropdown_select_partslist"><?php echo $activeName;?></span>
                        </button>
                        <ul aria-labelledby="menu1" class="dropdown-menu dropDwnListGeneric" role="menu">
                            <?php
                                foreach($partslists['items'] as $list) {
                                    if($list['partslist_id'] != $activeId) {
                            ?>
                            <li role="presentation"
                                data-brand=""
                                data-click=""
                                data-event=""
                                data-id=""
                                class="partslistTableRow"
                            >
                                <a data-id="<?php echo $list['partslist_id'];?>"
                                   data-url="<?php echo $this->getUrl('wishlist/partslist/view/', array('id'=>$list['partslist_id']));?>"
                                   href="#"
                                   role="menuitem"
                                   tabindex="-1"
                                   class="fake_dropdown_select_partslist"
                                >
                                     <?php echo $list['description'];?>
                                </a>
                            </li>
                            <?php
                                    }
                                }
                            ?>
                        </ul>
                    </div>
                </div>
                <div class="col-xs-12 col-sm-8 hidden-xs norLinks">
                    <div class="row">
                        <div class="lnkBx partslistActionFieldExtra">
                            <a data-id="<?php echo $activeId;?>" class="gtm-partlist-quick-add" data-target="#quick-add" data-toggle="modal" href="#" onclick="return false;">
                                <span class="quickaddIcon">
                                </span>
                                <?php echo $this->
                                __('Quick-Add');?>
                            </a>
                        </div>
                        <div class="lnkBx partslistActionField">
                            <a data-id="<?php echo $activeId;?>" class="gtm-partlist-rename" data-target="#active-rename" data-toggle="modal" href="#" onclick="return false;">
                                <span class="renameIcon">
                                </span>
                                <?php echo $this->
                                __('Rename');?>
                            </a>
                        </div>
                        <br>
                        <div class="lnkBx partslistActionFieldExtra topDistancePartslistActionField">
                            <a  data-id="<?php echo $activeId;?>" class="gtm-partlist-clear" href="#" onclick="if (confirmEmptyPartslist()) setLocationAndTrackList('<?php echo $emptyUrl;?>');return false;">
                                <span class="clearIcon">
                                </span>
                                <?php echo $this->
                                __('Clear');?>
                            </a>
                        </div>
                        <div class="lnkBx partslistActionField topDistancePartslistActionField">
                            <a data-id="<?php echo $activeId;?>" class="gtm-partlist-delete" href="#" onclick="if (confirmDeletePartslist()) setLocation('<?php echo $deleteUrl;?>');return false;">
                                <span class="deleteIcon">
                                </span>
                                <?php echo $this->
                                __('Delete');?>
                            </a>
                        </div>
                        <div class="lnkBx partslistActionField topDistancePartslistActionField">
                            <a data-id="<?php echo $activeId;?>" class="gtm-partlist-notes" data-target="#active-rename" data-toggle="modal" href="#" onclick="return false;">
                                <span class="noteIcon">
                                </span>
                                <?php echo $this->
                                __('Notes');?>
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-xs-6 col-sm-3">
            <?php if(!is_null($partslistHelper->getPartslist())):?>
            <input type="hidden" id="active_wishlist_empty_status" value="">
            <a data-id="<?php echo $activeId;?>" class="bulkAddCartActivePartlist bttn-sm gtm-partlist-addtocart <?php echo $aclroleClass; ?>" id="bulkAddCartActivePartlist" bulk-add-to-cart-url="" href="#" onclick="return false;">
                <img src="<?php echo $this->getSkinUrl('schrackdesign/Public/Images/rwd/cartIconWht.png');?>"/>
                <?php echo $this->__('Add to cart');?>
            </a>
        <?php endif;?>
        </div>
        <div class="col-xs-12 hidden-sm hidden-md hidden-lg norLinks">
            <div class="row">
                <div class="lnkBx paddingL10 partslistActionFieldExtra">
                    <a data-id="<?php echo $activeId;?>" onclick="jQuery('#quick-add').modal(); return false;" class="gtm-partlist-quick-add"  href="#">
                        <span class="quickaddIcon">
                        </span>
                        <?php echo $this->
                        __('Quick-Add');?>
                    </a>
                </div>
                <div class="lnkBx partslistActionField">
                    <a data-id="<?php echo $activeId;?>" onclick="jQuery('#active-rename').modal(); return false;" class="gtm-partlist-rename" href="#">
                        <span class="renameIcon">
                        </span>
                        <?php echo $this->
                        __('Rename');?>
                    </a>
                </div>
                <br>
                <div class="lnkBx paddingL10 partslistActionFieldExtra topDistancePartslistActionField">
                    <a data-id="<?php echo $activeId;?>" class="gtm-partlist-clear" href="#" onclick="if (confirmEmptyPartslist()) setLocationAndTrackList('<?php echo $emptyUrl;?>');return false;">
                        <span class="clearIcon">
                        </span>
                        <?php echo $this->
                        __('Clear');?>
                    </a>
                </div>
                <div class="lnkBx partslistActionField topDistancePartslistActionField">
                    <a data-id="<?php echo $activeId;?>" class="gtm-partlist-delete active-partlist-delete" href="#" onclick="return false;" data-url="'<?php echo $deleteUrl;?>'">
                        <span class="deleteIcon">
                        </span>
                        <?php echo $this->
                        __('Delete');?>
                    </a>
                </div>
                <div class="lnkBx partslistActionField topDistancePartslistActionField">
                    <a data-id="<?php echo $activeId;?>" onclick="jQuery('#active-rename').modal(); return false;"  class="gtm-partlist-notes" href="#">
                        <span class="noteIcon">
                        </span>
                        <?php echo $this->
                        __('Notes');?>
                    </a>
                </div>
            </div>
        </div>
    </div>
	<?php if($active->getComment()) { ?>
		<div class="row" id="partlistCommentContainer"><div class="col-xs-12 col-sm-12 normalTxt" style="margin-top: 2px;"><strong><?php echo $this->__('Note');?>:</strong> <?php echo $active->getComment(); ?></div></div>
	<?php } ?>
</div>
<script type="text/javascript">
    jQuery('.partslist-switch ul li a').click(function(){
        jQuery('.partslist-switch button').html(jQuery(this).html());
        window.location.href=jQuery(this).attr('data-url');
    });
</script>
<div class="row">
    <form action="<?php echo $this->getUrl('wishlist/partslist/update', array('id'=>$activeId));?>" id="active-partlist" method="POST">
        <input name="form_key" type="hidden" value="<?php echo Mage::getSingleton('core/session')->getFormKey()?>"/>
        <div id="active-partslist-container" class="col-xs-12 col-sm-9 col-md-9 active-container">
		    <span id="noItemInActivePartlistDesktop" class="normalTxt" style="display: none;"><?php echo $this->__('There are no products in this partslist');?></span>
            <img id="placeholderAjaxSpinner" class="ajaxSpinnerOverlay" src="<?php echo $this->getSkinUrl('schrackdesign/Public/Images/download_ajax_loader.gif'); ?>" />
        </div>
    </form>
    <div class="col-xs-12 col-sm-3 col-md-3">
        <div class="row">
            <div class="otherActions col-xs-12">
                <h2 class="hidden-xs"><?php echo $this->__('Other Actions');?></h2>
                <ul>
                    <li class="hidden-sm hidden-xs">
                        <a data-target="#upload-csv" data-toggle="modal" href="#" onclick="return false;">
                            <img src="<?php echo $this->getSkinUrl('schrackdesign/Public/Images/rwd/uploadIcon.png');?>">
                                <span>
                                    <?php echo $this->
                                    __('Upload CSV')?>
                                </span>
                            </img>
                        </a>
                    </li>
                    <li>
                        <a class="download_button_partslist_csv" href="<?php echo $this->getUrl('wishlist/partslist/downloadCsv/');?>" target="_blank">
                            <img src="<?php echo $this->getSkinUrl('schrackdesign/Public/Images/rwd/downloadIconGray.png');?>">
                                <span>
                                    <?php echo $this->
                                    __('Download CSV')?>
                                </span>
                            </img>
                        </a>
                    </li>
                    <li>
                        <a class="labelprint gtm-partlist-labelprint" data-id="<?php echo $activeId;?>" href="#" onclick="return false;">
                            <img src="<?php echo $this->getSkinUrl('schrackdesign/Public/Images/rwd/labelprintingIcon.png');?>">
                                <span>
                                    <?php echo $this->
                                    __('Label Printing')?>
                                </span>
                            </img>
                        </a>
                    </li>
                    <li class="hidden-xs">
                        <a class="active-submit" data-id="<?php echo $activeId?>" href="#" onclick="return false;">
                            <img src="<?php echo $this->getSkinUrl('schrackdesign/Public/Images/rwd/downloadIconGray.png');?>">
                                <span>
                                    <?php echo $this->
                                    __('Save')?>
                                </span>
                            </img>
                        </a>
                    </li>
                    <li>
                        <a class="dropdown partslist-drop all-products" href="#" onclick="return false;">
                            <span class="glyphicon glyphicon-pushpin lightBlue" title="Add to partlist"></span>
                                <span data-toggle="dropdown" id="all-products">
                                    <?php echo $this->
                                    __('Add All Product to Partslist')?>
                                </span>
                                <ul aria-labelledby="all-products" class="dropdown-menu dropDwnListGeneric" role="menu">
								<li class="add-to-new-partslist no-auto-activate bgAnchor" onClick="partslistFEActiveSku.addCheckedItemsToNewList('<?php echo $this->__('New partslist') ?>', 'rowId', 'sku', 'qty', '<?php echo Mage::getSingleton('core/session')->getFormKey(); ?>');"><span class="glyphicon glyphicon-plus-sign plusIcon"></span>&nbsp;<?php echo $this->__("Add to new partslist"); ?></li>
                                </ul>
                        </a>
                    </li>
                    <li  class="hidden-xs">
                        <a class="share-active" data-id="<?php echo $activeId;?>" data-target="#share-modal" data-toggle="modal" href="#" onclick="return false;">
                            <img src="<?php echo $this->getSkinUrl('schrackdesign/Public/Images/rwd/shareIcon.png');?>">
                                <span>
                                    <?php echo $this->
                                    __('Share Partslist')?>
                                </span>
                            </img>
                        </a>
                    </li>
                    <li  class="hidden-sm hidden-md hidden-lg hidden-xl">
                        <a class="share-active" data-id="<?php echo $activeId;?>" onclick="jQuery('#share-modal').modal(); return false;" href="#">
                            <img src="<?php echo $this->getSkinUrl('schrackdesign/Public/Images/rwd/shareIcon.png');?>">
                                <span>
                                    <?php echo $this->
                                    __('Share Partslist')?>
                                </span>
                            </img>
                        </a>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</div>

<script type="text/javascript">
    function setLocationAndTrack(deleteurl, sku) {
        if (dataLayer) {
            dataLayer.push({
                'event' : 'partlistModification',
                'eventAction' : 'Remove',
                'eventLabel' : '-',
                'partlistModificationSource' : 'Partlist',
                'productSku' : sku
            });
        }
        setLocation(deleteurl);
    }

    function setLocationAndTrackList(deleteurl) {
        skuListLength = skuList.length;
        for (var i = 0; i < skuListLength; i++) {
            if (dataLayer) {
                dataLayer.push({
                    'event' : 'partlistModification',
                    'eventAction' : 'Remove',
                    'eventLabel' : '-',
                    'partlistModificationSource' : 'Partlist',
                    'productSku' : skuList[i]
                });
            }
        }
        setLocation(deleteurl);
    }

    function trackPartlistAddClick(thisElement) {
        var addType = thisElement.parent().parent().attr('class');
        var singleAdd = addType.indexOf('singleProductAddPartlistTracking');

        if (singleAdd > 0) {
            var singleProductSku = thisElement.parent().parent().attr('product-id');
            if (dataLayer) {
                dataLayer.push({
                    'event' : 'partlistModification',
                    'eventAction' : 'Add',
                    'eventLabel' : '-',
                    'partlistModificationSource' : 'Partlist',
                    'productSku' : singleProductSku
                });
            }
        } else {
            skuListLength = skuList.length;
            for (var i = 0; i < skuListLength; i++) {
                if (dataLayer) {
                    dataLayer.push({
                        'event' : 'partlistModification',
                        'eventAction' : 'Add',
                        'eventLabel' : '-',
                        'partlistModificationSource' : 'Partlist',
                        'productSku' : skuList[i]
                    });
                }
            }
        }
    }

    jQuery('.active-partlist-product-delete').on('click', function() {
        console.log('Naunu');
    });

    var skuList = [];

    jQuery(document).ready(function() {

        // We have 2 forms, with 2 ok-buttons to submit new-partslist-form, with same id in footer (remove number one in cart):
        // Wait one second, and remove the first element, after it is loaded by AJAX:
        setTimeout( function() {
            if (jQuery('.save_new_partslist').length > 1) {
                jQuery('.save_new_partslist')[0].remove();
            }
        }, 2000);
     
        jQuery('.share-active').click(function(){
          jQuery('#partlistshare-id').val(jQuery(this).attr('data-id'));
        });
        jQuery('#rename').click(function(){
            var url = '<?php echo $editUrl;?>' + 'description/' + jQuery('#partslist-name').val() + '/comment/' + jQuery('#partslist-comment').val();
            jQuery.ajax(url).done(function(data){
                var res = JSON.parse(data);
                if(res.ok == true) {
                    jQuery('.rename-alert').html('<?php echo $this->__('Partslist saved')?>').fadeIn('slow').show().delay(1000).fadeIn(function(){
                        jQuery('#active-rename').modal('hide');
                        jQuery('.rename-alert').hide();
                        jQuery('.dropdown.partslist-drop.partslist-switch button').html(jQuery('#partslist-name').val());
                    });
                }
            })
        });

        jQuery('.labelprint').click(function(){
        var ajaxUrlLabelPrint = '<?php echo Mage::getUrl('catalog/download/getDownloadMediaDialog',array('_secure'=>true));?>';
        var source = 'partslist.view.phtml';
        localStorage.mediaDownloadSource = 'partslist.view.phtml';
        localStorage.partslistID = '<?php echo $activeId; ?>';
            jQuery.ajax(ajaxUrlLabelPrint,  {
                'type': 'POST', 
                'async': false, 
                'data': {
                    'source': source, 
                    'affectedItems': skuList
                }, 
                'success': function (data) {
                    var datax = JSON.parse(data);
                    if (datax.html) {
                        jQuery('#print-label').html(datax.html);
                        jQuery('#print-label').modal();
                    }
                }
            });
        });
            
        jQuery('.active-submit').click(function(){
            jQuery('#active-partlist').submit();
        });

        jQuery('.download_button_partslist_csv').on('click', function () {
            if (dataLayer) {
                dataLayer.push({
                    'event' : 'userDownloads',
                    'eventCategory' : 'File Download',
                    'eventAction' : 'Document Download',
                    'eventLabel' : 'partslist (csv)'
                });
            }
        });

    });

</script>
</div>

<p  id="noActivePartlistContainer" <?php if($active_flag && !empty($activeId)) { ?> style="display:none" <?php } ?>>
    <?php echo $this->__('You have no active Partslist'); ?>
</p>

<script type="text/javascript">
    function confirmDeletePartslist() {
            return confirm('<?php echo $this->__('Are you sure you want to delete this partslist?')?>');
        }
    function confirmEmptyPartslist() {
            return confirm('<?php echo $this->__('Are you sure you want to empty this partslist?')?>');
        }
</script>
<!-- app/design/frontend/schrack/schrackresponsive/template/wishlist/partslist/active-partlist.phtml (end) -->
