<?php
$mediaFileData = $this->getMediaFileData();
// Remove big data:
if (isset($mediaFileData['katalogseiten'])) {
    unset($mediaFileData['katalogseiten']);
}
// Remove big data:
if (isset($mediaFileData['produktkataloge'])) {
    unset($mediaFileData['produktkataloge']);
}
$preselectedFiletypes = $this->getPreselectedFiletypes();
$boolBarcodeAvailable = false;

// Sorting array alphabetically (low to high) by key -> media categories:
ksort($mediaFileData);

if (isset($mediaFileData['barcode_labels'])) {
    $format = Mage::getStoreConfig('schrack/media_zip_download/define_labelformat');
    $boolBarcodeAvailable = true;

    $barcodeLabels = array();
    $barcodeLabels = $mediaFileData['barcode_labels'];
    unset($mediaFileData['barcode_labels']);
    $mediaFileData['barcode_labels'] = $barcodeLabels;
}
?>
<div class="modal-dialog" role="document">
    <div class="modal-content">
        <div id="ajax-loader" style="display: none;">
            <img src="<?php echo $this->getSkinUrl('schrackdesign/Public/Images/download_ajax_loader.gif'); ?>" class="zip-download-animation"/>
        </div>
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <h4 class="modal-title"><?php echo $this->__('Product Media Download'); ?></h4>
        </div>
        <div class="loginCont">   
            <div class="quickadd row no-table-heights">
                <div class="col-xs-12">
                    <div class="row add-product no-table-heights">
                        <div class="col-xs-12">
                            <div id="messageField"></div>
                        </div>
                    </div>
                    <div>
                        <?php
                        foreach ($mediaFileData as $filetype => $mediaData):
                            $numberOfMediaFiles = count($mediaData);
                            $sizeTotalPerFiletype = 0;
                            $sizeTotalPerFiletypeDescription = '';

                            foreach ($mediaData as $ItemNumber => $itemFileData) {
                                if ($filetype == 'barcode_labels') {
                                    $sizeTotalPerFiletype += 70000; // Estimated filesize per label
                                } else {
                                    $sizeTotalPerFiletype += $itemFileData[2];
                                }
                            }

                            $result = array();
                            $units = array("B", "KB", "MB", "GB", "TB");
                            $c = 0;
                            $b = (float) $sizeTotalPerFiletype;
                            foreach ($units as $k => $u) {
                                if (($b / pow(1024, $k)) >= 1) {
                                    $result['bytes'] = $b / pow(1024, $k);
                                    $result['units'] = $u;
                                    $c++;
                                }
                            }

                            $sizeTotalPerFiletypeDescription = round($result['bytes'], 2) . ' ' . $result['units'];
                            ?>
                            <?php if ($filetype == 'barcode_labels') : ?>
                                
                                <div class="marginT15">
                                    <h4 class="modal-title"><?php echo $this->__('Label Download'); ?></h4>
                                </div>
                                
                            <?php endif; ?>

                            <div><input type="checkbox" class="<?php echo 'fileTypeClass-' . $filetype; ?>" <?php if (in_array($filetype, $preselectedFiletypes)) echo 'checked="checked"'; ?> >
                                <?php echo ucfirst($this->__($filetype)) . '  (' . $numberOfMediaFiles . ')' . ', ' . $sizeTotalPerFiletypeDescription; ?>
                            </div>

                        <?php endforeach; ?>
                        <?php if ($boolBarcodeAvailable) : ?>
                            
							<div class="row">
								<div class="col-xs-3 padR0 marginT10" style="float: left !important; width: 100% !important;"><?php echo $this->__('Choose label format'); ?>:</div>
								<div class="col-xs-9" style="float: left !important; width: 100% !important;">
									<select id="label-format-selection" class="form-control">
										<option value="3420" <?php if ($format == 3420) echo 'selected="selected"' ?>>Avery 3420 (1,69 x 7,00<?php echo $this->__('cm'); ?>; 3x17)</option>
										<option value="3421" <?php if ($format == 3421) echo 'selected="selected"' ?>>Avery 3421 (2,54 x 7,00<?php echo $this->__('cm'); ?>; 3x11)</option>
										<option value="3425" <?php if ($format == 3425) echo 'selected="selected"' ?>>Avery 3425 (5,70 x 10,50<?php echo $this->__('cm'); ?>; 2x5)</option>
										<option value="3658" <?php if ($format == 3658) echo 'selected="selected"' ?>>Avery 3658 (3,38 x 6,46<?php echo $this->__('cm'); ?>; 3x8)</option>
										<option value="3669" <?php if ($format == 3669) echo 'selected="selected"' ?>>Avery 3669 (5,08 x 7,00<?php echo $this->__('cm'); ?>; 3x5)</option>
										<option value="4776" <?php if ($format == 4776) echo 'selected="selected"' ?>>Avery 4776 (4,20 x 9,91<?php echo $this->__('cm'); ?>; 2x6)</option>
                                        <option value="9999" <?php if ($format == 4776) echo 'selected="selected"' ?>>Schrack Store (10,5 x 7,42<?php echo $this->__('cm'); ?>; 2x8)</option>
									</select>
								</div>
							</div>
                            <div>
                                <input type="checkbox" id="checkbox_add_label_quantity" name="checkbox_add_label_quantity" class="barcode_labels-quantity-yesno"><span id="checkbox_add_label_quantity-text">&nbsp;<?php echo $this->__('Print Labels With Quantity'); ?></span>
                            </div>
                        <?php endif; ?>
                    </div>
                    <div class="msg right">
                        <p class="info-box">
                            <span class="info right"></span>
                            <?php echo $this->__('Schrack Technik media download offers you the opportunity to download all available product information by one click. Choose between fotos, datasheets, catalogue page or more and get all downloads for products in your shopping cart, parts list or offers.'); ?>
                        </p>
                    </div>

                    <?php if (!$this->isRestricted()) : ?>
                        <div class="table row add-product no-table-heights">
                            <div class="col-xs-12">
                                <button type="button" id="downloadMediaFiles" title="<?php echo $this->__('Download Media'); ?>" class="bttn-md">
                                    <?php echo $this->__('Download Media'); ?>
                                </button>
                            </div>
                        </div>
                    <?php endif; ?>
                    <div class="row add-product no-table-heights">
                        <div class="col-xs-12 col-sm-6">
                        </div>
                    </div>
                    <div id="error" style="color: red;"></div>
                </div>
            </div>
        </div>
    </div>
</div>
<script type="text/javascript">

    jQuery(document).ready(function () {

        jQuery('#downloadMediaFiles').on('click', function () {

            //jQuery("#ajax-loader").show();
			setOverlayLoader();
            jQuery('#downloadMediaFiles').hide();

            var selectedFileTypes = [];
            var printLabelWithQuantity = 'no';

            jQuery("input[type='checkbox']:checked").each(
                    function () {
                        if (!this.getAttribute('class').indexOf('fileTypeClass-')) {
                            selectedFileTypes.push(this.getAttribute('class').replace('fileTypeClass-', ''));
                        }
                        if (!this.getAttribute('class').indexOf('barcode_labels-quantity-yesno')) {
                            printLabelWithQuantity = 'yes';
                        }
                    }
            );

            if (selectedFileTypes.length > 0) {
                var filedownloadURL = "<?php echo Mage::helper('schrackcore/url')->getUrlWithCurrentProtocol('catalog/download/getDownloadMediaZip'); ?>";
                var partslistID = '';
                if (localStorage.partslistID) {
                    partslistID = localStorage.partslistID;
                }
                var docId = '';
                if ( localStorage.documentId )
                    docId = localStorage.documentId;
                filedownloadURL = filedownloadURL.replace("?___SID=U", "");
                filedownloadURL = filedownloadURL.replace("?___SID=S", "");
                jQuery.ajax(filedownloadURL, {
                    'type': 'POST',
                    'async': true,
                    'data': {
                        'source': localStorage.mediaDownloadSource,
                        'partslistID': partslistID,
                        'documentID': docId,
                        'allMediaFileData': '<?php echo base64_encode(json_encode($mediaFileData)); ?>',
                        'mediaFileSelection': JSON.stringify(selectedFileTypes),
                        'labelFormat': jQuery('#label-format-selection').val(),
                        'printLabelWithQuantity': printLabelWithQuantity
                    },
                    'success': function (data) {
                        //jQuery("#ajax-loader").hide();
						unsetOverlayLoader();
                        if (data == '' || data.indexOf("error") >= 0) {
                            //console.log('fehler');
                            jQuery('#downloadMediaFiles').show();
                           // jQuery("#ajax-loader").hide();
						   unsetOverlayLoader();
                            jQuery("#messageField").addClass('alert-danger');
                            jQuery("#messageField").text('<?php echo $this->__('At the moment media download is not available. Please try it again later.'); ?>');
                            jQuery("#messageField").show();
                            jQuery("#messageField").fadeOut(10000);
                        } else {
							jQuery('#selectmediagpopup').modal('hide');
							jQuery('#print-label').modal('hide');
                            var downloadPath = '';
                            downloadPath = "<?php echo Mage::helper('schrackcore/url')->getUrlWithCurrentProtocol('catalog/download/startDownloadMediaZip'); ?>" + 'filename/' + data + '/';
                            downloadPath = downloadPath.replace('?___SID=U', '');
                            downloadPath = downloadPath.replace('?___SID=S', '');
                            if (dataLayer) {
                                dataLayer.push({
                                    'event' : 'userDownloads',
                                    'eventCategory' : 'File Download',
                                    'eventAction' : 'Media Mass Download',
                                    'eventLabel' : localStorage.mediaDownloadSourceDetail
                                });
                            }

                            if (jQuery('.fileTypeClass-barcode_labels').prop('checked')) {
                                if (dataLayer) {
                                    dataLayer.push({
                                        'event' : 'userDownloads',
                                        'eventCategory' : 'File Download',
                                        'eventAction' : 'Label Print',
                                        'eventLabel' : localStorage.mediaDownloadSourceDetail
                                    });
                                }
                            }

                            window.location.href = downloadPath;
                        }
                    }
                });
            } else {
                //jQuery("#ajax-loader").hide();
				unsetOverlayLoader();
                jQuery('#downloadMediaFiles').show();
                jQuery("#messageField").addClass('alert-danger');
                jQuery("#messageField").text('<?php echo $this->__('No Item Selected'); ?>');
                jQuery("#messageField").show();
                jQuery("#messageField").fadeOut(5000);
            }
        });

        jQuery('#closePopup').on('click', function () {
            jQuery('#selectmediagpopup').dialog('close');
        });

        jQuery('.fileTypeClass-barcode_labels').on('change', function () {
            var labelPrintStatus = jQuery('.fileTypeClass-barcode_labels').prop('checked');

            if (labelPrintStatus) {
                jQuery('#label-format-selection').prop('disabled', false);
                jQuery('#label-format-selection').css('background-color', '#fff');
                jQuery('#checkbox_add_label_quantity').prop('disabled', false);
            } else {
                jQuery('#label-format-selection').prop('disabled', true);
                jQuery('#label-format-selection').css('background-color', '##D8D8D8');
                jQuery('#checkbox_add_label_quantity').prop('checked', false);
                jQuery('#checkbox_add_label_quantity').prop('disabled', true);
            }
        });
    });

</script>