<div class="success-form" id="success-form">
    <div class="header-success">
        <?php echo $this->__('Request sent')?>
    </div>
    <div class="success" style="line-height: 120%">
        <?php echo $this->__('wishlist.endcustomerpartslist.request_form.handling_request')?>
    </div>
    <div class="share"><a href="javascript:void(showShareForm(shareFormCoordsForSuccessForm().x, shareFormCoordsForSuccessForm().y));"><?php echo $this->__('Share')?></a></div>
</div>
