<!-- default/template/customer/account/documents/newdocuments.phtml (start) -->
<?php
$_customer = $this->getCustomer();
$customerType = $_customer->getSchrackCustomerType(); // ProspectTypes: 'light-prospect' / 'full-prospect'
$_schrackWwsCustomerId = null;
$_customerAccountName = null;
$_warehouseName = null;
$_maySeePrices = false;
if ($_customer) {
    $_customerAccount = $_customer->getAccount();    
    $_schrackWwsCustomerId = $_customer->getSchrackWwsCustomerId();
    if ($_customerAccount)
        $_customerAccountName = $_customerAccount->getName();
    $_pickup = $_customer->getSchrackPickup();
    if ($_pickup) {
        $_warehouse = $this->helper('schrackshipping/pickup')->getWarehouse($_pickup);
        if ($_warehouse)
            $_warehouseName = $_warehouse->getName();
    }
    $_maySeePrices = $_customer->isAllowed('price', 'view');
}
?>
<div class="row">
    <div class="large-12 columns"><div class="headline a"><?php echo $this->__('My Account Overview')?></div></div>
</div>
<div class="table row info-box main">
    <div class="large-9 columns welcome">
        <div class="headline c2"><?php echo $this->__('Welcome, %s!', $this->getCustomerFullName())?></div>
        <p><?php echo $this->__("From your My Account Dashboard you have the ability to view a snapshot of your recent account activity and update your account information. Select a link below to view or edit information.")?></p>
    </div>
    <div class="body large-3 columns align-right icon-account-overview-main"><div class="middle-align-container">            
    </div></div>
</div>
<?php if (isset($_customerAccountName) && strlen($_customerAccountName)):?>
<div class="row">
    <div class="large-12 columns standout">
        <?php if (!in_array($customerType, array('light-prospect'))) echo $this->htmlEscape($_customerAccountName) . ', ' ?><?php if (!in_array($customerType, array('light-prospect', 'full-prospect'))) echo $this->__('Customer ID') . ': ' . $_schrackWwsCustomerId . ', ' ?><?php echo $_warehouseName ?></div>
</div>
<?php endif; ?>
<?php if ( $_maySeePrices ) : ?>
    <form action="<?php echo $this->getUrl('*/*/*') ?>" method="get" id="documents_form">
        <?php echo $this->getChildHtml('documents_latestorders') ?>
        <?php echo $this->getChildHtml('documents_latestoffers') ?>
    </form>
    <div id="ordernowpopup" class="product-warning" title="<?php echo $this->__('Accept offer'); /*###*/ ?>"></div>
<?php endif; ?>

<script type="text/javascript">//<![CDATA[
    jQuery(function() {
<?php $_locale = explode('_', Mage::app()->getLocale()->getLocaleCode()); ?>
        jQuery(".date-picker").datepicker(jQuery.datepicker.regional['<?php echo $_locale[0]; ?>']);
    });

    var orderNow = function(orderNumber) {
        jQuery.ajax("<?php echo Mage::helper('schrackcore/url')->getUrlWithCurrentProtocol('customer/account/orderNow'); ?>",{
            'success' : function ( data ) {
                var datax = JSON.parse(data);
                if ( datax.html ) {
                    jQuery('#ordernowpopup').html(datax.html);
                    jQuery('#ordernowpopup').dialog({
                        'modal': true,
                        'width': '450px'
                    });
                }
            },
            'type' : 'POST',
            'data' : { 'orderNo' : orderNumber }
        });
        return false;
    };

//]]></script>

<div class="sizing-default"></div>
<!-- default/template/customer/account/documents/newdocuments.phtml (end) -->