<?php
$_sessionParams = Mage::getSingleton('customer/session')->getData('documentParams');
?>

<div style="height: 47px;">
    <ul id="notice-message-container-overview" class="messages" style="display: none;"">
    <li class="notice-msg">
        <ul>
            <li id="notice-message-overview"></li>
        </ul>
    </li>
    </ul>
</div>

<div class="row">
    <div class="large-12 columns"><div class="headline a"><?php echo $this->__('My Offers') ?></div></div>
</div>

<?php echo $this->getChildHtml('documents_results') ?>

<div id="ordernowpopup" class="product-warning" title="<?php echo $this->__('Accept offer'); /*###*/ ?>"></div>

<script type="text/javascript">//<![CDATA[

    jQuery(document).ready(function(){
        jQuery('#textsearch').keypress(function(e) {
        if(e.which == 13) {
            jQuery('#documents_form').submit();
        }
      });
    });
    jQuery(function() {
        <?php $_locale = explode('_', Mage::app()->getLocale()->getLocaleCode()); ?>
        jQuery(".date-picker").datepicker(jQuery.datepicker.regional['<?php echo $_locale[0]; ?>']);
    });

    var orderNow = function(orderNumber) {
        jQuery.ajax("<?php echo Mage::helper('schrackcore/url')->getUrlWithCurrentProtocol('customer/account/orderNow'); ?>",{
            'success' : function ( data ) {
                var datax = JSON.parse(data);
                if ( datax.html ) {
                    jQuery('#ordernowpopup').html(datax.html);
                    jQuery('#ordernowpopup').dialog({
                        'modal': true,
                        'width': '450px'
                    });
                }
            },
            'type' : 'POST',
            'data' : { 'orderNo' : orderNumber }
        });
        return false;
    };

//]]></script>