<h1><?php echo $this->__('Download Power Loss CSV')?> </h1>
<button type="button" class="button-red small" title="<?php echo $this->__('Download Now!') ?>" class="button btn-checkout" onclick="document.location.href='<?php echo Mage::getUrl("catalog/product/downloadPowerLossCsv/",array('doDownload' => '1')); ?>'" ><?php echo $this->__('Download Now!') ?></button>
<STYLE type="text/css">
    div#resetmagento .indent{padding-left: 0px;}
    div#resetmagento p.header1{margin-bottom: 0; margin-top: 35px; padding-left: 0px; text-align: left; font: 22px 'Arial'; line-height: 24px;}
    div#resetmagento p.formular{margin-top: 35px; color: #00589d;font: bold 25px 'Arial'; line-height: 25px;text-align: left;}
    div#resetmagento p.header2{margin-top: 35px; color: #00589d; margin-bottom: 0; font: bold 22px 'Arial'; line-height: 17px;text-align: left;}
    div#resetmagento .table1{font: 16px "Arial";margin-left: 29px;margin-top: 23px;width: 250px;}
    div#resetmagento .table2{width: 221px;font: 16px 'Arial';margin-top: 4px;}
    div#resetmagento .table3{width: 530px;margin-top: 15px;font: 16px 'Arial';}
    div#resetmagento .cellx{height: 20px; margin: 0; padding: 0; vertical-align: bottom;}
    div#resetmagento .cell015{height: 20px; margin: 0; padding: 0; vertical-align: bottom; width: 15px}
    div#resetmagento .cell023{height: 20px; margin: 0; padding: 0; vertical-align: bottom; width: 23px}
    div#resetmagento .cell120{height: 20px; margin: 0; padding: 0; vertical-align: bottom; width: 120px}
    div#resetmagento .cell192{height: 20px; margin: 0; padding: 0; vertical-align: bottom; width: 192px}
    div#resetmagento .cell338{height: 20px; margin: 0; padding: 0; vertical-align: bottom; width: 338px}
    div#resetmagento .cellpr{margin-bottom: 0; margin-top: 0; padding-right: 5px; text-align: right; white-space: nowrap; font: 16px 'Arial'; line-height: 19px;}
    div#resetmagento .cellpl{margin-bottom: 0; margin-top: 0; padding-right: 5px; text-align: left; white-space: nowrap; font: 16px 'Arial'; line-height: 19px;}
    div#resetmagento .cellplpl{margin-bottom: 0; margin-top: 0; padding-left: 8px; padding-right: 5px; text-align: left; white-space: nowrap; font: 16px 'Arial'; line-height: 19px;}
    div#resetmagento p.textdist{margin-bottom: 0; margin-top: 20px; text-align: left; font: 16px 'Arial'; line-height: 19px;}
    div#resetmagento p.text{margin-bottom: 0; margin-top: 4px; text-align: left; font: 16px 'Arial'; line-height: 19px;}
</STYLE>
<div id="resetmagento">
<?php echo $this->__('Power Loss Formula: Q = k x A x &Delta;T'); ?>
</div>