<!-- app\design\frontend\schrack\schrackresponsive\template\catalogsearch\form.mini.phtml (start) -->
<?php
//$search_url = Mage::helper('schrackcatalogsearch')->getResultUrl();
    $catalogSearchHelper =  $this->helper('catalogsearch');
    $_quickaddHelper = Mage::helper('schrackcheckout/quickadd');
    $affectedId = "";
?>

<style>
    html, body {
        max-width: 100% !important;
        overflow-x: hidden !important;
    }
    .hideImportant {
        display: none !important;
    }
    .overlay {
        background-color: #000;
        bottom: 0;
        display: none;
        left: 0;
        opacity: 0.5;
        filter: alpha(opacity = 50); /* IE7 & 8 */
        position: fixed;
        right: 0;
        top: 0;
        z-index: 1002;
    }
    #showActAsACustomerEmailField {
        display: none;
        width: auto;
        z-index: 111;
    }
    #showActAsACustomerEmail {
        color: #e32c2c !important;
        font-weight: bold !important;
        padding: 5px !important;
        cursor: default !important;
    }
    #srchiconclickshop {
        background: #00589d !important;
        color: #fff !important;
    }
    #megaMenuCaptionTxt {
        color: #00589d !important;
    }
    @media screen and (orientation: landscape) {
        .scannerPopup {
            width: 45% !important;
            height: auto !important;
        }
    }
    @media screen and (orientation: portrait) {
        .scannerPopup {
            width: 65% !important;
            height: auto !important;
        }
    }

    .modal {
        text-align: center;
    }

    .modal::before {
        content: "";
        display: inline-block;
        height: 100%;
        margin-right: -4px;
        vertical-align: top;
    }

    .modal-dialog {
        display: inline-block;
        text-align: left;
        vertical-align: top;
    }

    .hamburgerMenuAlternate {
        width: 36px !important;
        z-index: 101 !important;
        margin-left: 0 !important;
        display: none !important;
        background: #f5f5f5;
    }

    #quick_add_button_alternate_container {
        display: none;
    }

    #quick_add_button_alternate {
        width: 100% !important;
        height: 47px !important;
        font-family: robotoregular,Helvetica,Arial,Sans-Serif !important;
        font-size: 18px !important;
        color: #00589D !important;
        text-align: left !important;
        padding-left: 25px !important;
    }

    #quick_add_button_alternate_arrow {
        color: #00589D !important;
        margin-right: 23px !important;
        margin-top: -10px !important;
        float: right !important;
        font-size: 30px !important;
        font-weight: bold !important;
    }

    #quick_add_container_alternate{
        display: none;
    }

    #scanpopup_scandit_alternate {
        display: none;
        z-index: 100000000000 !important;
        border: 1px solid grey !important;
        width: 80% !important;
        top: 14px !important;
        position: absolute !important;
        background: #fff !important;
        padding-top: 10px;
        padding-left: 20px !important;
        border-radius: 7px;
        box-sizing: border-box;
    }

    .scanpopup_scandit_alternate {
        height: 429px !important;
    }

    .scanpopup_scandit_alternate_message_open {
        height: 529px !important;
    }

    #close_quickadd_popup_alternate {
        float: right !important;
        margin-top: -7px !important;
        margin-right: 10px !important;
        margin-bottom: 10px !important;
    }

    #scanner_popup_alternate {
        width: 94% !important;
    }

    .scanner_popup_alternate {
        height: 298px !important;
    }

    .scanner_popup_alternate_message_open {
        height: 400px !important;
    }

    #scandit-barcode-picker-alternate {
        height: 284px !important;
    }

    #modal-label-headline-alternate {
        margin-bottom: 10px;
    }

    .search-wrapper {
        margin-bottom: 0 !important;
    }

    /* Mobile Mega Menu Redesign 2019 */
    @media (min-width: 1px) and (max-width: 320px) {
        #search {
            font-size: 16px !important;
        }
        .container {
            padding-right: 0 !important;
            padding-left: 8px !important;
        }
        .minimized_rightcartnav {
            padding-right: 10px !important;
        }
        .otherActions {
            margin-left: -5px;
        }
        .quick_add_button_alternate_container {
            width: 104% !important;
            margin-left: -14px !important;
        }
        .quick_add_button_alternate_containerIos {
            width: 104% !important;
            margin-left: -14px !important;
        }
        .hamburgerMenuAlternate {
            display: block !important;
            margin-top: -3px !important;
            padding-bottom: 0 !important;
        }
        .hamburgerMenuAlternateIos {
            display: block !important;
            margin-top: -3px !important;
            padding-bottom: 0 !important;
            margin-right: -15px !important;
            margin-left: -5px !important;
        }
        .hamburgerMenuAlternateButtonIos {
        }
        .searchWrapperIphone5 {
            width: 122% !important;
            padding-left: 0 !important;
            padding-right: 0 !important;
            margin-left: -14px !important;
            margin-right: 0 !important;
        }
        .hamburgerMenuAlternateIphone5 {
            display: block !important;
            margin-top: -3px !important;
            padding-bottom: 0 !important;
            margin-right: -15px !important;
            margin-left: -2px !important;
        }
        #megaMenuCaptionTxt {
            font-size: 10px !important;
        }
        .searchWrapper {
            width: 100% !important;
            padding-left: 0 !important;
            padding-right: 0 !important;
            margin-left: -8px !important;
        }
        #search_mini_form {
            height: 40px !important;
        }
        .searchbox_container {
            margin-left: 9px !important;
            height: 40px !important;
            width: 68% !important;
        }
        .searchbox_containerIos {
            margin-left: 9px !important;
            height: 40px !important;
            width: 68% !important;
        }
        .search_bar_box {
            width: 103% !important;
        }
        .search_bar_boxIos {
            width: 103% !important;
        }
        .search_bar_boxIphone5 {
            width: 105% !important;
        }
        #crtLtItems {
            padding-left: 8px !important;
        }
        .id_scan_button_orig {
            display: none !important;
        }
        .id_scan_button_copy {
            display: block !important;
            float: right !important;
            margin-right: 46px !important;
            padding: 0 !important;
            background: transparent !important;
        }
        .scan_magnifier_barcode {
            width: 40px !important;
            height: 40px !important;
            margin-left: 12px !important
        }
        .scan_magnifier_barcodeIos {
            width: 40px !important;
            height: 40px !important;
            margin-left: 8px !important;
            margin-top: 1px;
        }
        #quick_add_button {
            display: none !important;
        }
        #srchiconclickshop {
            background: #fff !important;
        }
        #srchiconclickshop_glyph {
            color: #00589d !important;
        }
        #search_mini_form{
            width: 100% !important;
        }
        #scan_magnifier_barcode_and_cart {
            height: 40px !important;
        }
        #id_scan_button_quickadd_copy {
            display: block !important;
            float: right !important;
            margin-right: 37px !important;
            padding: 0 !important;
            background: transparent !important;
            width: 40px !important;
            vertical-align: middle !important;
            text-align: center !important;
            border: none !important;
            margin-top: -10px !important;
        }
        #quick_add_container_alternate {
            padding-left: 22px !important;
            max-width: 100% !important;
            overflow-x: hidden !important;
        }
        #scanpopup_scandit_alternate {
            margin-left: 18px !important;
        }
        #search_autocomplete {
            width: 99.6% !important;
            z-index: ;
        }
    }

    @media (min-width: 321px) and (max-width: 360px) {
        #search {
            font-size: 16px !important;
        }
        .container {
            padding-right: 0 !important;
        }
        .quick_add_button_alternate_container {
            width: 103.5% !important;
            margin-left: -14px !important;
        }
        .quick_add_button_alternate_containerIos {
            width: 103.5% !important;
            margin-left: -14px !important;
        }
        #quick_add_button_alternate {
            padding-top: 11px !important;
        }
        #quick_add_button_alternate_arrow_trigger {
            padding-top: 8px !important;
        }
        .hamburgerMenuAlternate {
            display: block !important;
            margin-top: -3px !important;
            padding-bottom: 0 !important;
        }
        .hamburgerMenuAlternateIos {
            display: block !important;
            margin-top: -3px !important;
            padding-bottom: 0 !important;
            margin-right: -15px !important;
            margin-left: -5px !important;
        }
        .hamburgerMenuAlternateButtonIos {
        }
        #megaMenuCaptionTxt {
            font-size: 10px !important;
        }
        .searchWrapper {
            /* width: 100% !important; */
            padding-left: 0 !important;
            padding-right: 0 !important;
            margin-left: -14px !important;
            height: 72px !important;
        }
        #search_mini_form {
            height: 40px !important;
        }
        .searchbox_container {
            margin-left: 9px !important;
            height: 40px !important;
            width: 73% !important;
        }
        .searchbox_containerIos {
            margin-left: 9px !important;
            height: 40px !important;
            width: 73% !important;
        }
        .search_bar_box {
             width: 100% !important;
             margin-left: -3px !important;
         }
        .search_bar_boxIos {
            width: 100% !important;
            margin-left: -3px !important;
        }
        .id_scan_button_orig {
            display: none !important;
        }
        .id_scan_button_copy {
            display: block !important;
            float: right !important;
            margin-right: 46px !important;
            padding: 0 !important;
            background: transparent !important;
        }
        .scan_magnifier_barcode {
            width: 40px !important;
            height: 40px !important;
            margin-left: 6px;
        }
        .scan_magnifier_barcodeIos {
            width: 40px !important;
            height: 40px !important;
            margin-left: 6px;
        }
        #quick_add_button {
            display: none !important;
        }
        #srchiconclickshop {
            background: #fff !important;
        }
        #srchiconclickshop_glyph {
            color: #00589d !important;
        }
        #search_mini_form{
            width: 100% !important;
        }
        #scan_magnifier_barcode_and_cart {
            height: 40px !important;
        }
        #id_scan_button_quickadd_copy {
            display: block !important;
            float: right !important;
            margin-right: 37px !important;
            padding: 0 !important;
            background: transparent !important;
            width: 40px !important;
            vertical-align: middle !important;
            text-align: center !important;
            border: none !important;
            margin-top: -10px !important;
        }
        #quick_add_container_alternate {
            padding-left: 10px !important;
            max-width: 100% !important;
            overflow-x: hidden !important;
        }
        #scanpopup_scandit_alternate {
            margin-left: 25px !important;
        }
        #search_autocomplete {
            width: 99.6% !important;
        }
    }

    @media (min-width: 361px) and (max-width: 410px) {
        #search {
            font-size: 16px !important;
        }
        .container {
            padding-right: 0 !important;
        }
        .quick_add_button_alternate_container {
            width: 111% !important;
            margin-left: -14px !important;
            margin-right: -14px;
        }
        .quick_add_button_alternate_containerIos {
            width: 104% !important;
            margin-left: -14px !important;
            margin-right: -14px;
        }
        #quick_add_button_alternate {
            padding-top: 11px !important;
        }
        #quick_add_button_alternate_arrow_trigger {
            padding-top: 8px !important;
        }
        .hamburgerMenuAlternate {
            display: block !important;
            margin-top: -3px !important;
            padding-bottom: 0 !important;
        }
        .hamburgerMenuAlternateIos {
            display: block !important;
            margin-top: -3px !important;
            padding-bottom: 0 !important;
            margin-right: -15px !important;
            margin-left: -5px !important;
        }
        .hamburgerMenuAlternateButtonIos {
        }
        #megaMenuCaptionTxt {
            font-size: 10px !important;
        }
        .searchWrapper {
            width: 112% !important;
            padding-left: 0 !important;
            padding-right: 0 !important;
            margin-left: -14px !important;
            margin-right: 0 !important;
        }
        #search_mini_form {
            height: 40px !important;
        }
        .searchbox_container {
            margin-left: 5px !important;
            height: 40px !important;
            width: 73% !important;
        }
        .searchbox_containerIos {
            margin-left: 5px !important;
            height: 40px !important;
            width: 73% !important;
        }
        .search_bar_box {
            width: 100% !important;
        }
        .search_bar_boxIos {
            width: 93% !important;
            margin-left: 6px !important;
        }
        .id_scan_button_orig {
            display: none !important;
        }
        .id_scan_button_copy {
            display: block !important;
            float: right !important;
            margin-right: 66px !important;
            padding: 0 !important;
            background: transparent !important;
        }
        .scan_magnifier_barcode {
            width: 40px !important;
            height: 40px !important;
            margin-left: 14px !important;
        }
        .scan_magnifier_barcodeIos {
            width: 40px !important;
            height: 40px !important;
            margin-left: -6px !important;
        }
        #quick_add_button {
            display: none !important;
        }
        #srchiconclickshop {
            background: #fff !important;
        }
        #srchiconclickshop_glyph {
            color: #00589d !important;
        }
        #search_mini_form{
            width: 100% !important;
        }
        #scan_magnifier_barcode_and_cart {
            height: 40px !important;
        }
        #id_scan_button_quickadd_copy {
            display: block !important;
            float: right !important;
            margin-right: 37px !important;
            padding: 0 !important;
            background: transparent !important;
            width: 40px !important;
            vertical-align: middle !important;
            text-align: center !important;
            border: none !important;
            margin-top: -10px !important;
        }
        #quick_add_container_alternate {
            padding-left: 10px !important;
            max-width: 100% !important;
            overflow-x: hidden !important;
        }
        #editAreaAlternate {
            margin-left: -8px !important;
        }
        #scanpopup_scandit_alternate {
            margin-left: 25px !important;
        }
        #search_autocomplete {
            width: 99.6% !important;
        }
    }

    @media (min-width: 411px) and (max-width: 460px) {
        #search {
            font-size: 16px !important;
        }
        .container {
            padding-right: 0 !important;
        }
        .quick_add_button_alternate_container {
            width: 103.5% !important;
            margin-left: -14px !important;
            margin-right: -14px;
        }
        .quick_add_button_alternate_containerIos {
            width: 103.5% !important;
            margin-left: -14px !important;
            margin-right: -14px;
        }
        #quick_add_button_alternate {
            padding-top: 11px !important;
        }
        #quick_add_button_alternate_arrow_trigger {
            padding-top: 8px !important;
        }
        .hamburgerMenuAlternate {
            display: block !important;
            margin-top: -3px !important;
            padding-bottom: 0 !important;
            margin-left: 3px !important;
        }
        .hamburgerMenuAlternateIos {
            display: block !important;
            margin-top: -3px !important;
            padding-bottom: 0 !important;
            margin-right: -8px !important;
            margin-left: -5px !important;
        }
        .hamburgerMenuAlternateButtonIos {
        }
        #megaMenuCaptionTxt {
            font-size: 10px !important;
        }
        .searchWrapper {
            width: 104% !important;
            padding-left: 0 !important;
            padding-right: 0 !important;
            margin-left: -13px !important;
        }
        #search_mini_form {
            height: 40px !important;
        }
        .searchbox_container {
            margin-left: 7px !important;
            height: 40px !important;
            width: 73% !important;
        }
        .searchbox_containerIos {
            margin-left: 7px !important;
            height: 40px !important;
            width: 73% !important;
        }
        .search_bar_box {
            width: 101% !important;
        }
        .search_bar_boxIos {
            width: 102% !important;
            margin-left: -3px;
        }
        .id_scan_button_orig {
            display: none !important;
        }
        .id_scan_button_copy {
            display: block !important;
            float: right !important;
            margin-right: 54px !important;
            padding: 0 !important;
            background: transparent !important;
        }
        .scan_magnifier_barcode {
            width: 40px !important;
            height: 40px !important;
            margin-left: 6px !important;
        }
        .scan_magnifier_barcodeIos {
            width: 40px !important;
            height: 40px !important;
            margin-left: 6px !important;
        }
        #quick_add_button {
            display: none !important;
        }
        #srchiconclickshop {
            background: #fff !important;
        }
        #srchiconclickshop_glyph {
            color: #00589d !important;
        }
        #search_mini_form{
            width: 100% !important;
        }
        #scan_magnifier_barcode_and_cart {
            height: 40px !important;
        }
        #id_scan_button_quickadd_copy {
            display: block !important;
            float: right !important;
            margin-right: 37px !important;
            padding: 0 !important;
            background: transparent !important;
            width: 40px !important;
            vertical-align: middle !important;
            text-align: center !important;
            border: none !important;
            margin-top: -10px !important;
        }
        #quick_add_container_alternate {
            padding-left: 10px !important;
            max-width: 100% !important;
            overflow-x: hidden !important;
        }
        #editAreaAlternate {
            margin-left: -8px !important;
        }
        #scanpopup_scandit_alternate {
            margin-left: 25px !important;
        }
        #search_autocomplete {
            width: 99.6% !important;
        }
    }

    @media (min-width: 461px) and (max-width: 480px) {
        #search {
            font-size: 16px !important;
        }
        .container {
            padding-right: 0 !important;
        }
        .quick_add_button_alternate_container {
            width: 103% !important;
            margin-left: -14px !important;
            margin-right: -14px;
        }
        .quick_add_button_alternate_containerIos {
            width: 111% !important;
            margin-left: -14px !important;
            margin-right: -14px;
        }
        #quick_add_button_alternate {
            padding-top: 11px !important;
        }
        #quick_add_button_alternate_arrow_trigger {
            padding-top: 8px !important;
        }
        .hamburgerMenuAlternate {
            display: block !important;
            margin-top: -3px !important;
            padding-bottom: 0 !important;
        }
        .hamburgerMenuAlternateIos {
            display: block !important;
            margin-top: -3px !important;
            padding-bottom: 0 !important;
        }
        .hamburgerMenuAlternateButtonIos {
        }
        #megaMenuCaptionTxt {
            font-size: 10px !important;
        }
        .searchWrapper {
            width: 100% !important;
            padding-left: 0 !important;
            padding-right: 0 !important;
            margin-left: -14px !important;
        }
        #search_mini_form {
            height: 40px !important;
        }
        .searchbox_container {
            margin-left: 5px !important;
            height: 40px !important;
            width: 73% !important;
        }
        .searchbox_containerIos {
            margin-left: 5px !important;
            height: 40px !important;
            width: 73% !important;
        }
        .search_bar_box {
            width: 100% !important;
        }
        .search_bar_boxIos {
            width: 100% !important;
        }
        .id_scan_button_orig {
            display: none !important;
        }
        .id_scan_button_copy {
            display: block !important;
            float: right !important;
            margin-right: 54px !important;
            padding: 0 !important;
            background: transparent !important;
        }
        .scan_magnifier_barcode {
            width: 40px !important;
            height: 40px !important;
        }
        .scan_magnifier_barcodeIos {
            width: 40px !important;
            height: 40px !important;
        }
        #quick_add_button {
            display: none !important;
        }
        #srchiconclickshop {
            background: #fff !important;
        }
        #srchiconclickshop_glyph {
            color: #00589d !important;
        }
        #search_mini_form{
            width: 100% !important;
        }
        #scan_magnifier_barcode_and_cart {
            height: 40px !important;
        }
        #id_scan_button_quickadd_copy {
            display: block !important;
            float: right !important;
            margin-right: 37px !important;
            padding: 0 !important;
            background: transparent !important;
            width: 40px !important;
            vertical-align: middle !important;
            text-align: center !important;
            border: none !important;
            margin-top: -10px !important;
        }
        #quick_add_container_alternate {
            padding-left: 10px !important;
            max-width: 100% !important;
            overflow-x: hidden !important;
        }
        #editAreaAlternate {
            margin-left: -8px !important;
        }
        #scanpopup_scandit_alternate {
            margin-left: 25px !important;
        }
        #search_autocomplete {
            width: 99.6% !important;
        }
    }

    @media (min-width: 481px) and (max-width: 560px) {
        #search {
            font-size: 16px !important;
        }
        .container {
            padding-right: 0 !important;
        }
        .quick_add_button_alternate_container {
            width: 103% !important;
            margin-left: -14px !important;
            margin-right: -14px;
        }
        .quick_add_button_alternate_containerIos {
            width: 111% !important;
            margin-left: -14px !important;
            margin-right: -14px;
        }
        #quick_add_button_alternate {
            padding-top: 11px !important;
        }
        #quick_add_button_alternate_arrow_trigger {
            padding-top: 8px !important;
        }
        .hamburgerMenuAlternate {
            display: block !important;
            margin-top: -3px !important;
            padding-bottom: 0 !important;
        }
        .hamburgerMenuAlternateIos {
            display: block !important;
            margin-top: -3px !important;
            padding-bottom: 0 !important;
        }
        .hamburgerMenuAlternateButtonIos {
        }
        #megaMenuCaptionTxt {
            font-size: 10px !important;
        }
        .searchWrapper {
            width: 100% !important;
            padding-left: 0 !important;
            padding-right: 0 !important;
            margin-left: -14px !important;
        }
        #search_mini_form {
            height: 40px !important;
        }
        .searchbox_container {
            margin-left: 5px !important;
            height: 40px !important;
            width: 73% !important;
        }
        .searchbox_containerIos {
            margin-left: 5px !important;
            height: 40px !important;
            width: 73% !important;
        }
        .search_bar_box {
            width: 100% !important;
        }
        .search_bar_boxIos {
            width: 100% !important;
        }
        .id_scan_button_orig {
            display: none !important;
        }
        .id_scan_button_copy {
            display: block !important;
            float: right !important;
            margin-right: 54px !important;
            padding: 0 !important;
            background: transparent !important;
        }
        .scan_magnifier_barcode {
            width: 40px !important;
            height: 40px !important;
        }
        .scan_magnifier_barcodeIos {
            width: 40px !important;
            height: 40px !important;
        }
        #quick_add_button {
            display: none !important;
        }
        #srchiconclickshop {
            background: #fff !important;
        }
        #srchiconclickshop_glyph {
            color: #00589d !important;
        }
        #search_mini_form{
            width: 100% !important;
        }
        #scan_magnifier_barcode_and_cart {
            height: 40px !important;
        }
        #id_scan_button_quickadd_copy {
            display: block !important;
            float: right !important;
            margin-right: 37px !important;
            padding: 0 !important;
            background: transparent !important;
            width: 40px !important;
            vertical-align: middle !important;
            text-align: center !important;
            border: none !important;
            margin-top: -10px !important;
        }
        #quick_add_container_alternate {
            padding-left: 10px !important;
            max-width: 100% !important;
            overflow-x: hidden !important;
        }
        #editAreaAlternate {
            margin-left: -8px !important;
        }
        #scanpopup_scandit_alternate {
            margin-left: 25px !important;
        }
        #search_autocomplete {
            width: 99.6% !important;
        }
    }

    @media (min-width: 561px) and (max-width: 639px) {
        #search {
            font-size: 16px !important;
        }
        .container {
            padding-right: 0 !important;
        }
        .quick_add_button_alternate_container {
            width: 103% !important;
            margin-left: -14px !important;
            margin-right: -14px;
        }
        .quick_add_button_alternate_containerIos {
            width: 103% !important;
            margin-left: -14px !important;
            margin-right: -14px;
        }
        #quick_add_button_alternate {
            padding-top: 11px !important;
        }
        #quick_add_button_alternate_arrow_trigger {
            padding-top: 8px !important;
        }
        .hamburgerMenuAlternate {
            display: block !important;
            margin-top: -3px !important;
            padding-bottom: 0 !important;
        }
        .hamburgerMenuAlternateIos {
            display: block !important;
            margin-top: -3px !important;
            padding-bottom: 0 !important;
        }
        .hamburgerMenuAlternateButtonIos {
        }
        .hamburgerMenuAlternateIphone5 {
            display: block !important;
            margin-top: -3px !important;
            padding-bottom: 0 !important;
            margin-left: -7px !important;
            margin-right: -8px !important;
        }
        .searchWrapperIphone5 {
            width: 103% !important;
            padding-left: 0 !important;
            padding-right: 0 !important;
            margin-left: -14px !important;
        }
        #megaMenuCaptionTxt {
            font-size: 10px !important;
        }
        .searchWrapper {
            width: 103% !important;
            padding-left: 0 !important;
            padding-right: 0 !important;
            margin-left: -14px !important;
        }
        #search_mini_form {
            height: 40px !important;
        }
        .searchbox_container {
            margin-left: 5px !important;
            height: 40px !important;
            width: 73% !important;
        }
        .searchbox_containerIos {
            margin-left: 5px !important;
            height: 40px !important;
            width: 73% !important;
        }
        .search_bar_box {
            width: 114% !important;
        }
        .search_bar_boxIos {
            width: 114% !important;
        }
        .search_bar_boxIphone5 {
            width: 123% !important;
        }
        .id_scan_button_orig {
            display: none !important;
        }
        .id_scan_button_copy {
            display: block !important;
            float: right !important;
            margin-right: 40px !important;
            padding: 0 !important;
            background: transparent !important;
        }
        .scan_magnifier_barcode {
            width: 40px !important;
            height: 40px !important;
        }
        .scan_magnifier_barcodeIos {
            width: 40px !important;
            height: 40px !important;
        }
        #quick_add_button {
            display: none !important;
        }
        #srchiconclickshop {
            background: #fff !important;
        }
        #srchiconclickshop_glyph {
            color: #00589d !important;
        }
        #search_mini_form{
            width: 100% !important;
        }
        #scan_magnifier_barcode_and_cart {
            height: 40px !important;
        }
        #id_scan_button_quickadd_copy {
            display: block !important;
            float: right !important;
            margin-right: 37px !important;
            padding: 0 !important;
            background: transparent !important;
            width: 40px !important;
            vertical-align: middle !important;
            text-align: center !important;
            border: none !important;
            margin-top: -10px !important;
        }
        #quick_add_container_alternate {
            padding-left: 10px !important;
            max-width: 100% !important;
            overflow-x: hidden !important;
        }
        #editAreaAlternate {
            margin-left: -8px !important;
        }
        #scanpopup_scandit_alternate {
            margin-left: 25px !important;
        }
        #search_autocomplete {
            width: 99.6% !important;
        }
    }

    @media (min-width: 640px) and (max-width: 767px) {
        #search {
            font-size: 16px !important;
        }
        .container {
            padding-right: 0 !important;
        }
        .quick_add_button_alternate_container {
            width: 102% !important;
            margin-left: -14px !important;
        }
        .quick_add_button_alternate_containerIos {
            width: 102% !important;
            margin-left: -14px !important;
        }
        #quick_add_button_alternate {
            padding-top: 12px !important;
        }
        #quick_add_button_alternate_arrow_trigger {
            padding-top: 8px !important;
        }
        #proceed_to_checkout_button {
            height: 30px;
            width: 185px;
        }
        .hamburgerMenuAlternate {
            display: block !important;
            margin-top: -3px !important;
            padding-bottom: 0 !important;
        }
        .hamburgerMenuAlternateIos {
            display: block !important;
            margin-top: -3px !important;
            padding-bottom: 0 !important;
            margin-left: -2px !important;
        }
        .hamburgerMenuAlternateButtonIos {
        }
        #megaMenuCaptionTxt {
            font-size: 10px !important;
        }
        .searchWrapper {
            width: 102% !important;
            padding-left: 0 !important;
            padding-right: 0 !important;
            margin-left: -14px !important;
        }
        #search_mini_form {
            height: 40px !important;
        }
        .searchbox_container {
            margin-left: 9px !important;
            height: 40px !important;
            width: 82% !important;
        }
        .searchbox_containerIos {
            margin-left: 9px !important;
            height: 40px !important;
            width: 82% !important;
        }
        .search_bar_box {
            width: 103.7% !important;
            margin-left: -5px !important;
        }
        .search_bar_boxIos {
            width: 102.5% !important;
            margin-left: -11px !important;
        }
        .id_scan_button_orig {
            display: none !important;
        }
        #id-scan-button {
            margin-right: 40px !important;
        }
        .id_scan_button_copy {
            display: block !important;
            float: right !important;
            margin-right: 49px !important;
            padding: 0 !important;
            background: transparent !important;
        }
        .scan_magnifier_barcode {
            width: 40px !important;
            height: 40px !important;
        }
        .scan_magnifier_barcodeIos {
            width: 40px !important;
            height: 40px !important;
        }
        #quick_add_button {
            display: none !important;
        }
        #srchiconclickshop {
            background: #fff !important;
        }
        #srchiconclickshop_glyph {
            color: #00589d !important;
        }
        #search_mini_form{
            width: 100% !important;
        }
        #scan_magnifier_barcode_and_cart {
            height: 40px !important;
        }
        #id_scan_button_quickadd_copy {
            display: block !important;
            float: right !important;
            margin-right: 37px !important;
            padding: 0 !important;
            background: transparent !important;
            width: 40px !important;
            vertical-align: middle !important;
            text-align: center !important;
            border: none !important;
            margin-top: -10px !important;
        }
        #quick_add_container_alternate {
            padding-left: 31px !important;
            max-width: 100% !important;
            overflow-x: hidden !important;
        }
        #scanpopup_scandit_alternate {
            margin-left: 60px !important;
        }
        #search_autocomplete {
            width: 99.6% !important;
        }
    }

    @media (min-width: 768px) and (max-width: 768px) {
        #search {
            font-size: 16px !important;
        }
        .container {
            padding-right: 0 !important;
        }
        .quick_add_button_alternate_container {
            width: 104.6% !important;
            margin-left: -26px !important;
        }
        .quick_add_button_alternate_containerIos {
            width: 97.4% !important;
            margin-left: -1px !important;
        }
        #quick_add_button_alternate {
            height: 100% !important;
            padding-top: 14px !important;
            padding-bottom: 2px !important;
            padding-left: 57px !important;
        }
        #quick_add_button_alternate_arrow_trigger {
            padding-top: 6px !important;
        }
        .hamburgerMenuAlternate {
            display: block !important;
            margin-top: -3px !important;
            padding-bottom: 0 !important;
            margin-right: 8px !important;
            margin-left: 3px !important;
        }
        .hamburgerMenuAlternateIos {
            display: block !important;
            margin-top: 6px !important;
            padding-bottom: 0 !important;
            margin-right: -23px !important;
            margin-left: 0 !important
        }
        .hamburgerMenuAlternateButtonIos {
            display: block !important;
            margin-top: -3px !important;
            padding-bottom: 0 !important;
            margin-right: 15px !important;
            margin-left: -1px !important;
        }
        #megaMenuCaptionTxt {
            font-size: 10px !important;
            text-align: center;
            margin-left: 0px !important;
        }
        .searchWrapper {
            width: 97.9% !important;
            padding-left: 0 !important;
            padding-right: 0 !important;
            margin-left: -3px !important;
            height: 94px !important;
            padding-top: 20px !important;
        }
        #search_mini_form {
            height: 40px !important;
        }
        .searchbox_container {
            margin-left: 6px !important;
            height: 40px !important;
            width: 71% !important;
        }
        .searchbox_containerIos {
            margin-left: 6px !important;
            height: 40px !important;
            width: 71.6% !important;
        }
        .search_bar_box {
            width: 109% !important;
        }
        .search_bar_boxIos {
            width: 114% !important;
        }
        .id_scan_button_orig {
            display: none !important;
        }
        .id_scan_button_copy {
            display: block !important;
            float: right !important;
            margin-right: 55px !important;
            padding: 0 !important;
            background: transparent !important;
        }
        .scan_magnifier_barcode {
            width: 53px !important;
            height: 53px !important;
        }
        .scan_magnifier_barcodeIos {
            width: 53px !important;
            height: 53px !important;
        }
        #quick_add_button {
            display: none !important;
        }
        #srchiconclickshop {
            background: #fff !important;
        }
        #srchiconclickshop_glyph {
            color: #00589d !important;
        }
        #search_mini_form{
            width: 100% !important;
        }
        #scan_magnifier_barcode_and_cart {
            height: 40px !important;
        }
        #id_scan_button_quickadd_copy {
            display: block !important;
            float: right !important;
            margin-right: 54px !important;
            padding: 0 !important;
            background: transparent !important;
            width: 40px !important;
            vertical-align: middle !important;
            text-align: center !important;
            border: none !important;
            margin-top: -10px !important;
        }
        #quick_add_container_alternate {
            padding-left: 10px !important;
            max-width: 100% !important;
            overflow-x: hidden !important;
        }
        #editAreaAlternate {
            margin-left: 14px !important;
        }
        #scanpopup_scandit_alternate {
            margin-left: 48px !important;
        }
        #search_autocomplete {
            width: 99.6% !important;
        }
    }

    @media (min-width: 769px) and (max-width: 992px) {
        #search {
            font-size: 16px !important;
        }
        .container {
            padding-right: 0 !important;
        }
        .quick_add_button_alternate_container {
            margin-left: -1px !important;
            margin-right: -46px !important;
            width: 100% !important;
        }
        .quick_add_button_alternate_containerIos {
            margin-left: -1px !important;
            margin-right: -46px !important;
            width: 100% !important;
        }
        #quick_add_button_alternate {
            height: 100% !important;
            padding-top: 13px !important;
            padding-bottom: 2px !important;
        }
        #quick_add_button_alternate_arrow_trigger {
            padding-top: 8px !important;
        }
        .hamburgerMenuAlternate {
            display: block !important;
            margin-top: -3px !important;
            padding-bottom: 0 !important;
            margin-right: 6px !important;
        }
        .hamburgerMenuAlternateIos {
            display: block !important;
            margin-top: -3px !important;
            padding-bottom: 0 !important;
            margin-right: 6px !important;
            margin-left: -5px !important;
        }
        .hamburgerMenuAlternateButtonIos {
            margin-left: -3px !important;
        }
        #megaMenuCaptionTxt {
            font-size: 10px !important;
        }
        .searchWrapper {
            width: 100.32% !important;
            padding-left: 0 !important;
            padding-right: 0 !important;
            padding-top: 18px !important;
            padding-bottom: 18px !important;
            margin-left: -2px;
        }
        #search_mini_form {
            height: 40px !important;
        }
        .searchbox_container {
            margin-left: 9px !important;
            height: 40px !important;
            width: 73% !important;
        }
        .searchbox_containerIos {
            margin-left: -11px !important;
            height: 40px !important;
            width: 73% !important;
        }
        .search_bar_box {
            width: 110% !important;
        }
        .search_bar_boxIos {
            width: 115.5% !important;
        }
        .id_scan_button_orig {
            display: none !important;
        }
        .id_scan_button_copy {
            display: block !important;
            float: right !important;
            margin-right: 52px !important;
            padding: 0 !important;
            background: transparent !important;
        }
        .scan_magnifier_barcode {
            width: 53px !important;
            height: 53px !important;
        }
        .scan_magnifier_barcodeIos {
            width: 53px !important;
            height: 53px !important;
        }
        #quick_add_button {
            display: none !important;
        }
        #srchiconclickshop {
            background: #fff !important;
        }
        #srchiconclickshop_glyph {
            color: #00589d !important;
        }
        #search_mini_form{
            width: 100% !important;
        }
        #scan_magnifier_barcode_and_cart {
            height: 40px !important;
        }
        #id_scan_button_quickadd_copy {
            display: block !important;
            float: right !important;
            margin-right: 50px !important;
            padding: 0 !important;
            background: transparent !important;
            width: 40px !important;
            vertical-align: middle !important;
            text-align: center !important;
            border: none !important;
            margin-top: -10px !important;
        }
        #quick_add_container_alternate {
            padding-left: 10px !important;
            max-width: 100% !important;
            overflow-x: hidden !important;
        }
        #scanpopup_scandit_alternate {
            margin-left: 32px !important;
        }
        #product_quickadd_form {
            margin-left: 36px !important;
        }
        #search_autocomplete {
            width: 99.6% !important;
        }
    }


    @media (min-width: 993px) and (max-width: 4000px) {
        #search {
            font-size: 16px !important;
        }
        .hamburgerMenuAlternate {
            display: none !important;
        }
        .hamburgerMenuAlternateIos {
            display: none !important;
        }
        .id_scan_button_copy {
            display: none !important;
        }
    }

</style>
<input type="hidden" id="hide_show_alternate" value="down">
<input type="hidden" id="form_mini_phtml_uncached_timestamp" value="<?php echo date('Y-m-d H:i:s'); ?>">
<div class="searchContiner clearfix hide-on-print searchWrapper">
    <div id="showActAsACustomerEmailField">
        <span id="showActAsACustomerEmail"></span>
    </div>
    <div id="hamburgerMenuAlternate" class="sandwichMenuQuadrant print-hide hamburgerMenuAlternate">
        <button id="hamburgerMenuAlternateButton" type="button">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span id="megaMenuCaptionTxt">Menu</span>
        </button>
    </div>
    <div id="searchbox_container" class="tx-solr-searchbox searchbox_container">
        <form class="search-wrapper clearfix"
              id="search_mini_form"
              action="<?php echo $catalogSearchHelper->getResultUrl() ?>"
              method="get">
            <div id="search_bar_box" class="input-group search_bar_box">
                <span id="id-scan-button"
                      style="display:none;"
                      class="input-group-addon id_scan_button_orig"
                      onclick="openPopupAndScan('scanpopup_scandit',scanResultHandler)">
                    <span class="glyphicon glyphicon-barcode"></span>
                </span>
                <div class="input-group-btn hidden-lg hidden-md hidden-xs hidden-sm">
                    <!--  hidden-lg hidden-md hidden-xs hidden-sm -->
                    <button type="button"
                            id="allSrchCat"
                            class="btn btn-secondary dropdown-toggle hidden-lg hidden-md hidden-xs hidden-sm"
                            data-toggle="dropdown"
                            aria-haspopup="true"
                            aria-expanded="false"> <?php echo $this->__('All Categories'); ?>
                    </button>
                    <ul class="dropdown-menu" id="searchDropdownBox" name="cat"></ul>
                </div>
                <input id="search" type="text" name="<?php echo $this->helper('catalogsearch')->getQueryParamName() ?>" value="<?php //echo $this->helper('catalogsearch')->getEscapedQueryText() ?>" class="form-control" autocomplete='off' />
                <input type="hidden" name="cat" id="selSrchHidden" value="" />
                <span  id="srchiconclickshop" class="input-group-addon">
                    <span id="srchiconclickshop_glyph" class="glyphicon glyphicon-search"></span>
                </span>
                <div id="search_autocomplete" class="search-autocomplete searchAutocompleteBx" style="display: none;"></div>

                <script type="text/javascript">
                    //<![CDATA[
                    searchDefaultText = Translator.translate('Search in:') +' '+ Translator.translate('All Categories');

                    //default text after load
                    if (jQuery('#search').val() == ''){
                        jQuery('#search').val(searchDefaultText);
                    }
                    //on focus behaviour
                    jQuery('#search').on('focus', function() {
                        if (jQuery(this).val() == searchDefaultText) {
                            jQuery(this).val('');//clear text field
                        }
                    });
                    //on blur behaviour
                    jQuery("#search").on('blur', function() {
                        if (jQuery(this).val() == "") {
                            jQuery(this).val(searchDefaultText);//restore default texts
                        }
                    });

                    jQuery('#search').keyup(function(){
                        var query = jQuery('#search').val();
                        var cat = jQuery('#selSrchHidden').val();
                        if(query.length > 2){
                            jQuery.ajax('<?php echo Mage::getStoreConfig('schrack/typo3/typo3url') ?>'+'?eID=schrack_suggest&q='+encodeURIComponent(query)+'&cat='+encodeURIComponent(cat), {
                                'dataType': 'json',
                                'type': 'GET',
                                'success': function (data) {
                                    var parsedData = data;
                                    renderAutoSuggest(parsedData, '<?php echo $catalogSearchHelper->getResultUrl() ?>', query);
                                },
                                'error': function (data) {
                                    var parsedData = data;
                                }
                            });
                        } else {
                            jQuery('#search_autocomplete').css('display', 'none');
                            jQuery(".grayout").hide();
                            jQuery('.searchContiner .input-group').css('z-index', 'auto');
                        }
                    });
                    jQuery('#search').on('paste', function(){
                        setTimeout(function(){
                            var query = jQuery('#search').val();
                            var cat = jQuery('#selSrchHidden').val();
                            if(query.length > 2){
                                jQuery.ajax('<?php echo Mage::getStoreConfig('schrack/typo3/typo3url') ?>'+'?eID=schrack_suggest&q='+encodeURIComponent(query)+'&cat='+encodeURIComponent(cat), {
                                    'dataType': 'json',
                                    'type': 'GET',
                                    crossDomain: true,
                                    'success': function (data) {
                                        var parsedData = data;
                                        renderAutoSuggest(parsedData, '<?php echo $catalogSearchHelper->getResultUrl() ?>', query);
                                    },
                                    'error': function (data) {
                                        var parsedData = data;
                                    }
                                });
                            } else {
                                jQuery('#search_autocomplete').css('display', 'none');
                                jQuery(".grayout").hide();
                                jQuery('.searchContiner .input-group').css('z-index', 'auto');
                            }
                        }, 50);
                    });
                    //]]>
                </script>
            </div>
        </form>
    </div>
    <span id="id-scan-button"
          style="display:none;"
          class="input-group-addon id_scan_button_copy">
        <img id="scan_magnifier_barcode"
             src="<?php echo $this->getSkinUrl('schrackdesign/Public/Images/rwd/scan_magnifier_barcode.png') ?>"
             class="scan_magnifier_barcode"
             alt="" />
    </span>
    <button id="quick_add_button"
            type="button"
            class="btn btn-quickAdd"
            data-toggle="modal"
            data-target="#quickaddpopup">
        <?php echo $this->__('Quick Add'); ?> +
    </button>
</div>

<div id="messagebar_form_mini_smartphone"></div>

<div id="quick_add_button_alternate_container" class="quick_add_button_alternate_container">
    <div id="quick_add_button_alternate" class="btn-quickAdd">
        <?php echo $this->__('Quick Add'); ?>
        <span id="quick_add_button_alternate_arrow">
            <i id="quick_add_button_alternate_arrow_trigger" class="fa fa-angle-down" aria-hidden="true"></i>
        </span>
    </div>
    <div style="clear: both !important;"></div>
    <div id="quick_add_container_alternate">
        <div>
            <div>
                <div class="loginCont">
                    <div class="quickadd row">
                        <div class="col-xs-12">
                            <!-- <div id="quickadd_message"></div> -->
                            <div id="editAreaAlternate" class="row add-product">
                                <form action="<?php echo Mage::helper('schrackcore/url')->getUrlWithCurrentProtocol('checkout/cart/quickadd') ?>" method="post" id="product_quickadd_form">
                                    <input type="hidden" name="target" value="cart" />
                                    <input type="hidden" name="id" value="<?php echo $affectedId; ?>" />
                                    <input type="hidden" name="quickadd-drum" id="quickadd-drum" value="" />
                                    <div class="col-xs-12">
                                        <h3><?php echo $this->__('Quickadd') ?></h3>
                                    </div>
                                    <!-- div id="quickadd-sku-div" class="col-xs-12 col-sm-5" style="padding-left:0" -->
                                    <div id="wait_loader">
                                        <img id="wait_loader_inline_gif" style="margin-top: 31px; margin-right: -3px; width: 20px; height: 20px; float: right; display: none;" src="<?php echo $this->getSkinUrl('schrackdesign/Public/Images/download_ajax_loader.gif'); ?>">
                                    </div>
                                    <div id="quickadd-sku-div" class="col-xs-12 col-sm-6">
                                        <input type="hidden" name="url" value="<?php echo $_quickaddHelper->getResultUrl(); ?>" id="url"/>
                                        <input type="text" name="<?php echo $_quickaddHelper->getQueryParamName(); ?>" id="quickadd_sku" maxlength="13" placeholder="<?php echo $this->__('Article Number'); ?>" title="<?php echo $this->__('Article Number'); ?>" class="form-control quickadd-sku required-entry" autocomplete="off" autofocus />
                                        <div id="quickadd_autocomplete" class="quickadd-autocomplete"></div>
                                    </div>
                                    <div id="sku_found_okay"><i class="fa fa-check" aria-hidden="true"></i></div>
                                    <div id="quickadd-qty-div" class="col-xs-12 col-sm-6">
                                        <input type="number" name="qty" onkeypress="return isNumberKey(event)" id="quickadd_qty" maxlength="12" placeholder="<?php echo $this->__('Qty'); ?>" title="<?php echo $this->__('Qty'); ?>" class="form-control quickadd-qty" autocomplete="off" />
                                    </div>
                                    <div style="clear: both;"></div>
                                    <div style="height: 20px; width: 100%;">
                                        <span id="ean_equivalent"></span>
                                    </div>
                                    <div style="height: 30px; width: 100%;">
                                        <span id="product_longtext"></span>
                                    </div>
                                    <div class="col-xs-12 col-sm-12">
                                        <?php if ($_quickaddHelper->getModuleName() === 'wishlist'
                                                  && $_quickaddHelper->getControllerName() === 'partslist') : ?>
                                            <button type="button" id="quickadd_addproduct_button"
                                                    data-id=""
                                                    data-name=""
                                                    data-type="quickadd"
                                                    title="<?php echo $this->__('Add to Cart'); ?>"
                                                    class="bttn-md">
                                                <?php echo $this->__('Add to Cart'); ?>
                                            </button>
                                            <!-- @todo patch for now; no partslist functionality required on this -->
                                            <?php echo $this->__('Add to partslist'); ?>
                                        </button> -->
                                        <?php else: ?>
                                            <button type="button" id="quickadd_addproduct_button"
                                                    data-id=""
                                                    data-name=""
                                                    data-type="quickadd"
                                                    title="<?php echo $this->__('Add to Cart'); ?>"
                                                    class="bttn-md">
                                                <?php echo $this->__('Add to Cart'); ?>
                                            </button>
                                        <?php endif; ?>
                                        <span id="id_scan_button_quickadd_copy"
                                              class="form-control">
                                            <img id="scan_magnifier_barcode_and_cart"
                                                 <?php
                                                    $path  = 'schrackdesign/Public/Images/';
                                                    $path .= 'rwd/scan_magnifier_barcode_and_cart.png';
                                                 ?>
                                                 src="<?php echo $this->getSkinUrl($path) ?>" />
                                        </span>
                                    </div>
                                </form>
                                <input type="hidden" id="memo" value="0">
                            </div>

                            <div class="row">
                                <div class="col-xs-12 col-sm-12" id="quickadd-barcode-group-alternate" style="margin-top:10px; text-align: center; display:none">
                                    <div class="scanner" id="quickadd-barcode-picker-alternate" style="display: inline-block;">
                                    </div>
                                </div>
                            </div>

                            <div id="csvAreaAlternate" class="row csv hidden-xs hidden-sm">
                                <div class="col-xs-12"><hr></div>
                                <form method="post"
                                    onsubmit="submitFormAndTrackGaEvent(this.form, 'cart', 'quick_add_upload', 'csv')"
                                    action="<?php echo Mage::helper('schrackcore/url')->getUrlWithCurrentProtocol('checkout/cart/addCsv'); ?>"
                                    enctype="multipart/form-data" id="cart-addcsv-form">
                                    <div class="col-xs-12">
                                        <h3><?php echo $this->__('Upload CSV') ?>
                                            <a href="<?php echo Mage::getStoreConfig('schrack/typo3/typo3url') . Mage::getStoreConfig('schrack/typo3/uploadcsvtext_url'); ?>">[?]
                                            </a>
                                        </h3>
                                    </div>
                                    <div class="upload col-xs-12">
                                        <input type="file"
                                        title="<?php echo $this->__('CSV File'); ?>"
                                        name="csv"
                                        id="quickadd-csv-upload-button"
                                        accept=".csv" />
                                    </div>
                                    <div class="add_product col-xs-6"><div class="right-align-container">
                                            <button type="button" id="quickadd-button" title="<?php echo $this->__('Add Products') ?>" class="bttn-md quickadd_button_grey"><?php echo $this->__('Add Products') ?></button>
                                            <input id="verifyUploadFile" type="hidden" value="">
                                        </div></div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<!-- scan modal scandit start -->
<div class="modal fade" id="scanpopup_scandit" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog scannerPopup" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button data-dismiss="modal"
                          aria-label="Close"
                                  id="close_scanner_popup_right_upper_corner"
                               class="close"
                                type="button">
                  <span aria-hidden="true">&times;</span>
                </button>
                <h4 class="modal-title" id="myModalLabel2"><?php echo $this->__('Scan') ?></h4>
            </div>
            <div class="modal-body">
                <div id="scandit-barcode-picker" class="scanner"></div>
                <div id="scandit-barcode-result" class="result-text"></div>
            </div>
            <div class="modal-footer">
                <button data-dismiss="modal"
                                type="button"
                                  id="close_scanner_popup_right_lower_corner"
                               class="btn btn-secondary"><?php echo $this->__('Close'); ?>
                </button>
            </div>
        </div>
    </div>
</div>
<!-- scan modal scandit end -->

<!-- scan non-modal scandit start -->
<div id="scanpopup_scandit_alternate" tabindex="-1" class="scanpopup_scandit_alternate">
    <div id="scanner_popup_alternate" class="scannerPopup scanner_popup_alternate">
        <div>
            <div>
                <button type="button" class="close close_quickadd_popup_alternate" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                <h4 id="modal-label-headline-alternate" class="modal-title"><?php echo $this->__('Quick Add') ?></h4>
            </div>
            <hr style="margin-top: 0;">
            <div id="quickadd_message"></div>
            <div>
                <div id="scandit-barcode-picker-alternate" class="scanner"></div>
                <div id="scandit-barcode-result-alternate" class="result-text"></div>
            </div>
        </div>
    </div>
    <hr style="margin-top: 59px;">
    <div>
        <button id="close_quickadd_popup_alternate" type="button" class="btn btn-secondary close_quickadd_popup_alternate"><?php echo $this->__('Close'); ?></button>
    </div>
</div>
<!-- scan non-modal scandit end -->

<!-- script src="<?php echo Mage::getBaseUrl(); ?>skin/frontend/schrack/default/schrackdesign/Public/Javascript/scanner-glue.js"></script -->
<script type="text/javascript">
//<![CDATA[

jQuery( document ).ready(function() {

    jQuery('#scanpopup_scandit').on('hidden.bs.modal',stopScan);
    if ( mayScan() ) {
        initScan("<?php echo Mage::getBaseUrl(); ?>", null, "scandit-barcode-picker", "<?php echo $this->getSkinUrl('schrackdesign/Public/Images/download_ajax_loader.gif'); ?>","<?php echo $this->__('Scan bar code or QR code'); ?>");
        jQuery("#id-scan-button").show();
    }

    if (localStorage.quickAddEditMode == 'on') {
        localStorage.openedQuickAddPanel = 1;
        localStorage.quickAddEditMode = '';
        localStorage.flagForHeader = 1;
        setTimeout(function(){ jQuery('#quick_add_button_alternate').click(); }, 1000);
    }

    jQuery('#id_scan_button_quickadd_copy').on('click', function() {
        switchToScanModeAlternate();
    });

    var iOSPhone = /iPhone|iPad/.test(navigator.userAgent) && !window.MSStream;
    if (iOSPhone == true ) {
        jQuery('#hamburgerMenuAlternate').removeClass('hamburgerMenuAlternate');
        jQuery('#hamburgerMenuAlternate').addClass('hamburgerMenuAlternateIos');
        jQuery('#hamburgerMenuAlternateButton').addClass('hamburgerMenuAlternateButtonIos');
        jQuery('#searchbox_container').removeClass('searchbox_container');
        jQuery('#searchbox_container').addClass('searchbox_containerIos');
        jQuery('#search_bar_box').removeClass('search_bar_box');
        jQuery('#search_bar_box').addClass('search_bar_boxIos');
        jQuery('#scan_magnifier_barcode').removeClass('scan_magnifier_barcode');
        jQuery('#scan_magnifier_barcode').addClass('scan_magnifier_barcodeIos');
        jQuery('#quick_add_button_alternate_container').removeClass('quick_add_button_alternate_container');
        jQuery('#quick_add_button_alternate_container').addClass('quick_add_button_alternate_containerIos');
    }

});


function quickaddScanResultHandlerAlternate (scanResult) {
    scanResult.barcodes.reduce(function(string, barcode) {
        var product = '';
        var cnt = '';
        var data = barcode.data;
        var p = data.indexOf("?a=");
        if ( p > -1 ) {
            product = data.substring(p + 3, p + 13);
        } else if ( (p = data.indexOf("?ah=")) > -1 || (p = data.indexOf("?al=")) > -1 ) {
            product = data.substring(p + 4, p + 14);
        } else {
            // 0123456789012345678901234567890
            // XC01010101:12
            // p = 10
            p = data.indexOf(":");
            if ( p == -1 ) {
                p = data.indexOf(";");
            }
            if ( p > -1 ) {
                cnt = parseInt(data.substring(p + 1),10);
                product = data.substring(0,p);
            } else {
                product = data;
            }
        }
        //     0123456789012345678901234567890
        // EAN: 9004840618464
        if ( product.length == 10 || (product.length == 13 &&  ! isNaN(parseInt(product,13))) ) {
            jQuery('#quickadd_sku').val(product);
            if ( ! isNaN(cnt) && cnt > 0 ) {
                jQuery('#quickadd_qty').val(cnt);
            }
            var res = string + ScanditSDK.Barcode.Symbology.toHumanizedName(barcode.symbology) + ": " + data + "<br>";
            console.log(res);
            availabilityCheck4quickadd(false);
            pauseScan();
            setTimeout(resumeScan,2000); // freeze and sleep for 2 seconds
        } else {
            var msg = null;
            if ( data.indexOf('schrack') > -1 && data.indexOf('?k=') > -1 ) {
                msg = "<?php echo $this->__('Please don\'t scan categories in quick add. For category scan use the scan in the search bar.'); ?>";
            } else {
                msg = "<?php echo $this->__('Please make sure you have scanned a Schrack Code.'); ?>";
            }
            jQuery('#scanner_popup_alternate').removeClass('scanner_popup_alternate');
            jQuery('#scanner_popup_alternate').addClass('scanner_popup_alternate_message_open');
            jQuery('#scanpopup_scandit_alternate').removeClass('scanpopup_scandit_alternate');
            jQuery('#scanpopup_scandit_alternate').addClass('scanpopup_scandit_alternate_message_open');
            jQuery('#quickadd_message').html('<ul class="messages"><li class="error-msg"><span class="glyphicon glyphicon-exclamation-sign"></span> <span>' + msg + '</span></li></ul>');
        }
    }, "");
}

var csvAreaVisibleAlternate = null;
var xIsAddedAlternate = false;

function switchToScanModeAlternate () {
    if( jQuery('.overlay').length == 0 ){
        jQuery('body').append('<div class="overlay"></div>');
    }
    jQuery('.overlay').show();
    jQuery('#scanpopup_scandit_alternate').show();
    jQuery('#quickadd-barcode-group-alternate').show();
    csvAreaVisibleAlternate = jQuery('#csvAreaAlternate').is(":visible");
    if (csvAreaVisibleAlternate) {
        jQuery('#csvAreaAlternate').hide();
    }
    showAndStartScan(quickaddScanResultHandlerAlternate);
    if (xIsAddedAlternate == false) {
        jQuery('<div id="ScanModeXAlternate" style="position: absolute; right: 2%; top: 2%; z-index: 1000000 !important; color:#FFFFFF; cursor:default; font-size: large" onclick="switchToEditModeAlternate()">X</div>').insertAfter('#scandit-barcode-picker-alternate .scandit .scandit .scandit-logo');
        xIsAddedAlternate = true;
    }
}

function switchToEditModeAlternate () {
    stopScan();
    jQuery('#scanpopup_scandit_alternate').hide();
    jQuery('.overlay').remove();
    jQuery('#quickadd-barcode-group-alternate').hide();
    jQuery('#ScanModeXAlternate').remove();
    xIsAddedAlternate = false;
    if (csvAreaVisibleAlternate) {
        jQuery('#csvAreaAlternate').show();
    }
    // Reload cart on close scanner popup:
    location.reload();
}

function scanResultHandler ( scanResult ) {
    document.getElementById("scandit-barcode-result").innerHTML = scanResult.barcodes.reduce(function(string, barcode) {
        var baseUrl = "<?php echo Mage::getBaseUrl(); ?>";
        var data = barcode.data;
        var targetUrl = baseUrl + "catalogsearch/result/?q=";
        // support opening URL only if it's a Schrack URL
        var schrackUrlRegex = /(https?:\/\/[^\s]+(schrack|schrackcdn)[\.\-][^\s]+\/[^\s]*)/g;
        if ( schrackUrlRegex.test(data) ) {
            var p = data.indexOf('http');
            if ( p > 0 ) {
                data = data.substr(p,data.length - p);
            }
            // when it's an a= short url, cut out sku and paste it into search, anyhow, if it's from another country
            p = data.indexOf("?a=");
            if (p > -1) {
                sku = data.substring(p + 3, p + 13);;
                // http://www.schrack.at.local/shop/sd/productdownloads?a=XC01010101
                if ( data.substring(p - 16,p) == 'productdownloads' ) {
                    targetUrl = baseUrl + "sd/sd/?a=" + sku + "&focusDownloads=1";
                } else {
                    targetUrl += sku;
                }
            } else { // check country and shop path
                // URL does not work in IE 11, but anyhow, the whole barcode stuff does not...
                var dataUrlObj = new URL(data);
                var baseUrlObj = new URL(baseUrl);
                // is from different country and is not our image server?
                if (    dataUrlObj.hostname != baseUrlObj.hostname
                     && dataUrlObj.hostname != 'image.schrack.com'
                     && dataUrlObj.hostname != 'image.schrackcdn.com' ) {
                    // change hostname
                    dataUrlObj.hostname = baseUrlObj.hostname;
                    dataUrlObj.protocol = baseUrlObj.protocol;
                    var dataUrlObjPathElems = dataUrlObj.pathname.split('/');
                    // is in shop path
                    if ( dataUrlObjPathElems[1].match("shop|trgovina|sklep|comenzi|prodavnica|eshop") ) {
                        // change to current one
                        dataUrlObjPathElems[1] = baseUrlObj.pathname.split('/')[1];
                        dataUrlObj.pathname = dataUrlObjPathElems.join('/');
                    }
                    data = dataUrlObj.toString();
                }
                targetUrl = data;
            }
        } else {
            // handle SKUs with count like "XC01010101:300"
            var p = data.indexOf(":");
            if ( p == -1 ) {
                p = data.indexOf(";");
            }
            if ( p > -1 ) {
                data = data.substring(0,p);
            }
            targetUrl += data;
        }

            var res = string + ScanditSDK.Barcode.Symbology.toHumanizedName(barcode.symbology) + ": " + data + "<br>";
            console.log(res);
            stopScan();
            window.open(targetUrl,"_self");
            return res;
        }, "");
    }

    var currentURL = window.location.href;
    if(currentURL.match(/checkout\/cart/)) {
        if (jQuery(window).width() <= 992) {
            jQuery('#quick_add_button_alternate_container').show();
        }
    }

    if (jQuery(window).width() <= 992) {
        jQuery('#quickaddpopup').remove();
    } else {
        jQuery('#quick_add_container_alternate').remove();
    }

    var mayIScan = mayScan();
    mayIScan = true; // TODO : Test

    if (mayIScan) {
        jQuery("#id_scan_button_quickadd_copy").show();
    }

    jQuery('#quick_add_button_alternate').on('click', function() {
        if(jQuery('#hide_show_alternate').val() == 'down') {
            jQuery('#quick_add_container_alternate').show();
            jQuery('#hide_show_alternate').val('up');
            jQuery('#quick_add_button_alternate_arrow_trigger').removeClass('fa-angle-down');
            jQuery('#quick_add_button_alternate_arrow_trigger').addClass('fa-angle-up');
            removeMessages();
            pushScannerOriginElement('scandit-barcode-picker-alternate');
            localStorage.openedQuickAddPanel = 1;
        } else {
            jQuery('#quick_add_container_alternate').hide();
            jQuery('#hide_show_alternate').val('down');
            jQuery('#quick_add_button_alternate_arrow_trigger').removeClass('fa-angle-up');
            jQuery('#quick_add_button_alternate_arrow_trigger').addClass('fa-angle-down');
            switchToEditModeAlternate();
            popScannerOriginElement();
            localStorage.openedQuickAddPanel = 0;
            // Reload cart on close scanner popup:
            location.reload();
        }
    });

    jQuery('.close_quickadd_popup_alternate').on('click', function () {
        jQuery('#scanpopup_scandit_alternate').hide();
        jQuery('.overlay').remove();
        // Reload cart on close scanner popup:
        location.reload();
    });



    jQuery('.id_scan_button_copy').on('click', function() {
        if (localStorage.openedQuickAddPanel == 1) {
            jQuery('#quick_add_button_alternate').click();
            localStorage.openedQuickAddPanel = 0;
        }
        openPopupAndScan('scanpopup_scandit',scanResultHandler);
    });

    if (isIphone5() == true) {
        jQuery('.id_scan_button_copy').remove();
        jQuery('#id_scan_button_quickadd_copy').remove();
        jQuery('.searchContiner').removeClass('searchWrapper');
        jQuery('.searchContiner').addClass('searchWrapperIphone5');
        jQuery('#search_bar_box').addClass('search_bar_boxIphone5');
        jQuery('#hamburgerMenuAlternate').removeClass('hamburgerMenuAlternateIos');
        jQuery('#hamburgerMenuAlternate').addClass('hamburgerMenuAlternateIphone5');
    }

    jQuery('#close_scanner_popup_right_upper_corner').on('click', function() {
        location.reload();
    });

    jQuery('#close_scanner_popup_right_lower_corner').on('click', function() {
        location.reload();
    });

//]]>
</script>

<!-- app\design\frontend\schrack\schrackresponsive\template\catalogsearch\form.mini.phtml (end) -->
