<!-- app/design/frontend/schrack/schrackresponsive/template/mocalc/step07.phtml (start) -->
<?php
    $data = $this->getMoData();
    $step = Mage::registry(Schracklive_MoCalc_Helper_Data::REGISTRY_STEP_KEY);

    $accs = $this->getPossibleBaseAccessories('actuation');
    $current = $data['base_accessories']['actuation']['part_no'];
?>

    <table style="width: 700px">
        <tr>
            <td style="width:3%"></td>
            <td style="width:12%"></td>
            <td style="width:75%"></td>
            <td style="width:10%"></td>
        </tr>
        <?php foreach ( $accs as $acc ) : ?>
            <tr>
                <td>
                    <input type="radio" id="<?php echo $acc['part_number'] ?>" name="input" value="<?php echo $acc['part_number'] ?>" <?php echo $current == $acc['part_number'] ? 'checked' : '' ?>/>
                </td>
                <td class="partnumber">
                    <?php echo $acc['part_number'] ?>
                </td>
                <td>
                    <?php echo $acc['description']; ?>
                </td>
                <td class="price">
                    <?php echo $acc['price']; ?>
                </td>
            </tr>
        <?php endforeach; ?>
    </table>

<script type="text/javascript">
    //<![CDATA[
    jQuery(document).ready(function() {
        jQuery('#step-header-chapter').text("<?php echo $this->__('Basic accessory') ?>: ");
        jQuery('#step-header-page').text("<?php echo $this->__('Drive') ?>");
    });
    //]]>
</script>
<!-- app/design/frontend/schrack/schrackresponsive/template/mocalc/step07.phtml (end) -->
