<!-- app/design/frontend/schrack/schrackresponsive/template/mocalc/step11.phtml (start) -->
<?php
    $data = $this->getMoData();
    $step = Mage::registry(Schracklive_MoCalc_Helper_Data::REGISTRY_STEP_KEY);
?>

<style>
    .finish {
        width: 100%;
        height: 100%;
        display: flex;
        justify-content: center;
        align-items: center;
        font-size: 36px;
        font-weight: bold;
    }
</style>

<div class="finish"><?php echo "Finished" ?>! :-)</div>

<script type="text/javascript">
    //<![CDATA[
    jQuery(document).ready(function() {
        jQuery('#step-header-chapter').text("<?php echo $this->__('Finished') ?>");
        jQuery('#step-header-page').text("");
        jQuery('#update_button').css('visibility','hidden');
        jQuery('#next_button').css('visibility','hidden');
        jQuery('#discount_button').css('visibility','hidden');
    });
    //]]>
</script>
<!-- app/design/frontend/schrack/schrackresponsive/template/mocalc/step11.phtml (end) -->
