<!-- app/design/frontend/schrack/schrackresponsive/template/mocalc/step11.phtml (start) -->
<?php
    $data = $this->getMoData();
    $step = Mage::registry(Schracklive_MoCalc_Helper_Data::REGISTRY_STEP_KEY);
?>

<label for="discount"><?php echo $this->__('Discount') ?> (%):</label>
<input type="number" id="discount" name="input" min="0" max="99" value="<?php echo $data['discount']; ?>"/>

<script type="text/javascript">
    //<![CDATA[
    jQuery(document).ready(function() {
        jQuery('#step-header-chapter').text("<?php echo $this->__('Discount') ?>");
        jQuery('#step-header-page').text("");
        jQuery('#discount_button').css('visibility','hidden');
    });
    //]]>
</script>
<!-- app/design/frontend/schrack/schrackresponsive/template/mocalc/step11.phtml (end) -->
