<!-- app/design/frontend/schrack/schrackresponsive/template/customer/account/documents/snippet/detailssearchDesktop.phtml (start) -->
<?php
    $ordersList = json_decode(json_encode(Mage::registry('ordersList')),TRUE);
    $counter = 0;
?>
<?php
if(count($ordersList) > 0) :
    foreach ($ordersList as $order) :
?>
        <tr class="<?php echo (++$counter%2==0) ? "even": "odd" ?>">
            <td><?php echo $order['nameProject']; ?></td>
            <td><a class="order-number number_tracking_information" href="<?php echo $order['detailUrl']; ?>"><?php echo $order['documentNumber']; ?></a></td>
            <td><a class="order-number" href="<?php echo $order['detailUrlOrder']; ?>"><?php echo $order['isLa1'] ? '' : $order['orderNumber']; ?></a></td>
            <td><?php echo $order['creationDate']; ?></td>
            <td><?php echo $order['documentType']; ?></td>
            <td><?php echo $order['status']; ?></td>
            <td><?php echo $order['actions']; ?></td>
        </tr>
    <?php endforeach; ?>
<?php endif; ?>


<script type="text/javascript">
    //<![CDATA[

    jQuery(document).ready(function() {

        // We have 2 forms, with 2 ok-buttons to submit new-partslist-form, with same id in footer (remove number one in cart):
        // Wait one second, and remove the first element, after it is loaded by AJAX:
        setTimeout( function() {
            if (jQuery('.save_new_partslist').length > 1) {
                jQuery('.save_new_partslist')[0].remove();
            }
        }, 2000);

    });

    //]]>
</script>
<!-- app/design/frontend/schrack/schrackresponsive/template/customer/account/documents/snippet/detailssearchDesktop.phtml (end) -->