<!-- app/design/frontend/schrack/schrackresponsive/template/customer/account/documents/snippet/invoicesDesktop.phtml (start) -->
<?php
$invoices = json_decode(json_encode(Mage::registry('invoices')),TRUE);
$counter = 0;
?>

<?php
if(count($invoices) > 0) :
    foreach ($invoices as $invoice) :
?>
        <tr class="<?php echo (++$counter%2==0) ? "even": "odd" ?>">
            <td><?php echo $invoice['nameProject']; ?></td>
            <td><a class="order-number number_tracking_information" href="<?php echo $invoice['detailUrl']; ?>"><?php echo $invoice['documentNumber']; ?></a></td>
            <td><?php echo $invoice['orderNumber']; ?></td>
            <td><?php echo $invoice['creationDate']; ?></td>
            <td><?php echo $invoice['status']; ?></td>
            <td><?php echo $invoice['actions']; ?></td>
        </tr>
    <?php endforeach; ?>
<?php endif; ?>

<script type="text/javascript">
//<![CDATA[

    jQuery(document).ready(function() {

        // We have 2 forms, with 2 ok-buttons to submit new-partslist-form, with same id in footer (remove number one in cart):
        // Wait one second, and remove the first element, after it is loaded by AJAX:
        setTimeout( function() {
            if (jQuery('.save_new_partslist').length > 1) {
                jQuery('.save_new_partslist')[0].remove();
            }
        }, 2000);

        jQuery('.print_button_overview_csv').on('click', function () {
            var documentDownloadUrl = jQuery(this).attr('href');
            var documentType = 'no document type found';

            if (documentDownloadUrl.indexOf("offer") >= 0) documentType = 'offer (csv)';
            if (documentDownloadUrl.indexOf("order") >= 0) documentType = 'order (csv)';
            if (documentDownloadUrl.indexOf("invoice") >= 0) documentType = 'invoice (csv)';
            if (documentDownloadUrl.indexOf("shipment") >= 0) documentType = 'shipment (csv)';
            if (documentDownloadUrl.indexOf("invoice") >= 0) documentType = 'invoice (csv)';
            if (documentDownloadUrl.indexOf("creditmemo") >= 0) documentType = 'creditmemo (csv)';

            if (dataLayer) {
                dataLayer.push({
                    'event' : 'userDownloads',
                    'eventCategory' : 'File Download',
                    'eventAction' : 'Document Download',
                    'eventLabel' : documentType
                });
            }

            window.location.href = documentDownloadUrl;
            return false;
        });

    });

//]]>
</script>
<!-- app/design/frontend/schrack/schrackresponsive/template/customer/account/documents/snippet/invoicesDesktop.phtml (end) -->