<!-- app/design/frontend/schrack/schrackresponsive/template/customer/account/documents/snippet/shipmentsDesktop.phtml (start) -->
<?php
    $shipmentOrders = json_decode(json_encode(Mage::registry('shipmentOrders')),TRUE);
    $counter = 0;
?>

<?php
    if(count($shipmentOrders) > 0) :
        foreach ($shipmentOrders as $order) :
?>
            <tr class="<?php echo (++$counter%2==0) ? "even": "odd" ?>">
                <td><?php echo $order['nameProject']; ?></td>
                <td><a class="order-number number_tracking_information" href="<?php echo $order['detailUrl']; ?>"><?php echo $order['documentNumber']; ?></a></td>
                <td><?php echo $order['creationDate']; ?></td>
                <td><?php echo $order['status']; ?></td>
                <td><?php echo $order['trace']; ?></td>
                <td><?php echo $order['actions']; ?></td>
            </tr>
        <?php endforeach; ?>
    <?php endif; ?>

<script type="text/javascript">
//<![CDATA[

    jQuery(document).ready(function() {

        // We have 2 forms, with 2 ok-buttons to submit new-partslist-form, with same id in footer (remove number one in cart):
        // Wait one second, and remove the first element, after it is loaded by AJAX:
        setTimeout( function() {
            if (jQuery('.save_new_partslist').length > 1) {
                jQuery('.save_new_partslist')[0].remove();
            }
        }, 2000);

        jQuery('.print_button_overview_csv').on('click', function () {
            var documentDownloadUrl = jQuery(this).attr('href');
            var documentType = 'no document type found';

            if (documentDownloadUrl.indexOf("offer") >= 0) documentType = 'offer (csv)';
            if (documentDownloadUrl.indexOf("order") >= 0) documentType = 'order (csv)';
            if (documentDownloadUrl.indexOf("invoice") >= 0) documentType = 'invoice (csv)';
            if (documentDownloadUrl.indexOf("shipment") >= 0) documentType = 'shipment (csv)';
            if (documentDownloadUrl.indexOf("invoice") >= 0) documentType = 'invoice (csv)';
            if (documentDownloadUrl.indexOf("creditmemo") >= 0) documentType = 'creditmemo (csv)';

            if (dataLayer) {
                dataLayer.push({
                    'event' : 'userDownloads',
                    'eventCategory' : 'File Download',
                    'eventAction' : 'Document Download',
                    'eventLabel' : documentType
                });
            }

            window.location.href = documentDownloadUrl;
            return false;
        });

    });

//]]>
</script>
<!-- app/design/frontend/schrack/schrackresponsive/template/customer/account/documents/snippet/shipmentsDesktop.phtml (end) -->