<?php
 /* @var $this Mage_Checkout_Block_Onepage_Billing */
?>
<form id="co-billing-form" action="">
    <p class="select300inner"><?php echo $this->getCustomer()->getPrimaryBillingAddress()->format('oneline') ?></p>
    <input type="hidden" name="billing[use_for_shipping]" value="0" />
</form>
<div class="col2-alt-set button-set">
    <div class="col-2">
        <div class="form-buttons">
            <span id="billing-buttons-container" >
                <span id="billing-please-wait" style="display:none;" class="opc-please-wait">
                    <img src="<?php echo $this->getSkinUrl('images/opc-ajax-loader.gif') ?>" class="v-middle" alt="" /> &nbsp; <?php echo $this->__('Loading next step...') ?> &nbsp;
                </span><br />
                <button type="button" class="form-button right" onclick="billing.save();"><span><?php echo $this->__('Continue') ?></span></button>
            </span>
        </div>
    </div>
</div><div class="clear"></div>

<script type="text/javascript">
<!--
    var billing = new Billing('co-billing-form', '<?php echo $this->getUrl('mobile/onepage/getAddress') ?>address/', '<?php echo $this->getUrl('mobile/onepage/saveBilling') ?>');
    var billingForm = new VarienForm('co-billing-form');
//-->
</script>
